ios14 migration
xbmc/Official-Kodi-Remote-iOS pull request #101
Opened 2020-12-19 16:08 UTC by wutschel

Basic rework to migrate Kodi Remote App to IOS 14, building with XCode 12.2/.3. Summary of changes:
- Updated target properties to fulfill IOS14 requirements (local network access, registering bonjour services)
- Migrate to NSJSONSerialization (fixes main problems with crashes in several uses cases)
- Several clean ups (fixed runtime and compile time warnings, replaced deprecated function calls) 
- Fixes / fine tuning for several views and items for iPad and iPhone

ToDo:
- Search, Collection View and Sorting-By does not work (rework started on another branch)
- UIWebView must be replaced to allow upload to AppStore (only can offer a full removal for now)

2020-12-19 21:22 UTC, fuzzard commented
Thanks for the PR. Give us a few days to get a review going. Myself and @kambala-decapitator aren't overly familiar with the existing codebase, so just trying to get caught up and get all the logistics going

2020-12-20 14:44 UTC, kambala-decapitator requested changes
I don't really understand the point of adding suffixes: `+[UIImage imageNamed:]` doesn't require passing suffix to load an image

2020-12-20 14:44 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                                       [UIImage imageNamed:@"monkeys_38.png"],
what about a loop instead?

2020-12-20 14:46 UTC, kambala-decapitator requested changes
why not squash c698932f5ea3a583bb119a77c14a806f98b68488 into parent?

2020-12-20 14:46 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                                       [UIImage imageNamed:@"monkeys_38.png"],
Hi, I added the png suffix because it was convenient for understanding and searching the code. Functionally it is not relevant.

2020-12-20 14:50 UTC, kambala-decapitator requested changes
is `blank.png` a dedicated image (that exists) or just a stub name? If the latter, why not simply use `nil`?

2020-12-20 14:50 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                                       [UIImage imageNamed:@"monkeys_38.png"],
> I added the png suffix because it was convenient for understanding and searching the code

ok, then it's fine 👍

2020-12-20 14:51 UTC, wutschel commented
> is `blank.png` a dedicated image (that exists) or just a stub name? If the latter, why not simply use `nil`?

It is a dedicated image.

2020-12-20 14:56 UTC, kambala-decapitator requested changes

2020-12-20 14:56 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    self.navigationItem.title = [NSString stringWithFormat:NSLocalizedString(@"More (%ld)", nil), (count - MAX_NORMAL_BUTTONS)];
doesn't compiler complain to cast to `long` when building for a 32-bit arch? (analogous to `NSUInteger` and `%lu` below)

2020-12-20 14:56 UTC, kambala-decapitator commented on XBMC Remote/iPad/StackScrollViewController.m
> +    int orientation= (int)[[UIApplication sharedApplication] statusBarOrientation];
might be easier using proper type instead

2020-12-20 14:59 UTC, kambala-decapitator commented
FYI I'm checking commits one by one.

You might also want to check https://github.com/kambala-decapitator/Official-Kodi-Remote-iOS/commits/xcode11, there might be some changes you don't have ;)

2020-12-20 15:00 UTC, wutschel commented
> FYI I'm checking commits one by one.
> 
> You might also want to check https://github.com/kambala-decapitator/Official-Kodi-Remote-iOS/commits/xcode11, there might be some changes you don't have ;)

Good point. Will take look at this and see, if I covered this or not.

2020-12-20 15:07 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    self.navigationItem.title = [NSString stringWithFormat:NSLocalizedString(@"More (%ld)", nil), (count - MAX_NORMAL_BUTTONS)];
To my understanding only 64 Bit Apps are supported since a while. So, the case should be fine.

2020-12-20 15:27 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    self.navigationItem.title = [NSString stringWithFormat:NSLocalizedString(@"More (%ld)", nil), (count - MAX_NORMAL_BUTTONS)];
Minimum supported iOS deployment target in Xcode 12 is iOS 9, the latest 32-bit device is iPhone 5 which runs iOS 10 ;)
Also, I don't see deployment target raise in the diff, so it should be still iOS 8.

2020-12-20 15:47 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    self.navigationItem.title = [NSString stringWithFormat:NSLocalizedString(@"More (%ld)", nil), (count - MAX_NORMAL_BUTTONS)];
Ok, you won. :) Shall we still keep this change then? Before the code was throwing warnings for 64 Bit.

2020-12-20 15:53 UTC, wutschel commented on XBMC Remote/iPad/StackScrollViewController.m
> +    int orientation= (int)[[UIApplication sharedApplication] statusBarOrientation];
True. Please see https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/101/commits/5a18a40b42712a17b90bf98338bf92c834c14bfc

2020-12-20 16:40 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    self.navigationItem.title = [NSString stringWithFormat:NSLocalizedString(@"More (%ld)", nil), (count - MAX_NORMAL_BUTTONS)];
Simply cast the value to `long` and it'll be fine

2020-12-20 18:09 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    self.navigationItem.title = [NSString stringWithFormat:NSLocalizedString(@"More (%ld)", nil), (count - MAX_NORMAL_BUTTONS)];
Done with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/101/commits/c181ef38b03df5055aec11b81a6959db1a11f5db

2020-12-22 17:10 UTC, wutschel commented
In the meanwhile I updated my local changes based on the feedback from this PR, squashed several commits and also found a better solution for a fixed crash (instead of removing the faulty code). Will you continue to review the commits from this PR or shall I raise a new one with the updated commits?

2020-12-22 17:20 UTC, kambala-decapitator commented
@wutschel I've reviewed only first 4 commits so far. If those aren't touched by your new changes or there're changes that we had already discussed, then you can simply force push the branch.

2020-12-23 08:01 UTC, wutschel commented
I prefer to not overwrite the history of the public branch. When I reworked commits based on your feedback I can update them locally and later push this updated branch and raise a PR for it. Alternatively I can also raise PRs with a subset of already accepted changes to get the code changes merged stepwise. This way we can better separate the cleanup commits from the real ios14/xcode migration changes and iPad/iPhone fixes.

2020-12-24 15:59 UTC, kambala-decapitator commented
Would you be fine if we do like this?

1. add changes based on feedback on top of the current branch
2. when all is ready, open new PR with commits squashed appropriately to have a clean history

2020-12-24 16:03 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    NSString *query = [searchString stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLFragmentAllowedCharacterSet]];
is it really correct to use `URLFragmentAllowedCharacterSet` (in the whole commit)? URL Fragment is an "anchor" after `#`. Maybe you'd want path / query instead?

2020-12-24 16:06 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
The previous deletion commit says that it crashes only on iOS 14. Was the new fix tested on all previous iOS versions? Maybe it's better to have 2 code paths based on iOS version?

2020-12-24 16:11 UTC, kambala-decapitator requested changes

2020-12-24 16:11 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    NSError *error = nil;
`nil` is assigned implicitly in ARC mode

2020-12-24 16:11 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
>  #ifdef __OBJC_GC__
this can be dropped

2020-12-24 16:14 UTC, kambala-decapitator requested changes

2020-12-24 16:14 UTC, kambala-decapitator commented on Kodi Remote.xcodeproj/project.pbxproj
> -		0F747771151E5E8600EF78AD /* JSONKit.m in Sources */ = {isa = PBXBuildFile; fileRef = 0F74776E151E5E8600EF78AD /* JSONKit.m */; settings = {COMPILER_FLAGS = "-fno-objc-arc"; }; };
deleting JSONKit should be a part of previous (respective) commit

2020-12-24 16:16 UTC, kambala-decapitator commented on XBMC Remote/HostViewController.m
> +    [descriptionUI setBackgroundColor:[UIColor whiteColor]];
would it make sense to use "system white" on iOS 14 that flips to black in Night Mode?

2020-12-24 16:18 UTC, kambala-decapitator requested changes

2020-12-24 16:18 UTC, kambala-decapitator commented on XBMC Remote/Kodi Remote-Info.plist
> +	<string>Kodi Remote App uses local network to find and communicate to Kodi instances in the network.</string>
user-visible text should be added to `InfoPlist.strings` instead

2020-12-24 16:23 UTC, kambala-decapitator requested changes

2020-12-24 16:23 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    [items removeObjectAtIndex:14];
there should be a better way than using magic numbers

2020-12-24 16:23 UTC, kambala-decapitator commented on XBMC Remote/iPad/MenuViewController.m
> +        iconName = @"connection_off.png";
this and below should be a part of 992d59526d2825e9f288d907569f268e19b9a1b3

2020-12-24 16:26 UTC, kambala-decapitator requested changes

2020-12-24 16:26 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    if (IS_IPHONE_X) {
looks like even larger devices like 11 Pro Max aren't covered

2020-12-24 16:27 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> -    [powerButton setImage:[UIImage imageNamed: @"icon_power_up"] forState:UIControlStateNormal];
squash with 992d59526d2825e9f288d907569f268e19b9a1b3

2020-12-24 16:28 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +//    [self.view insertSubview:self.nowPlayingController.ProgressSlider aboveSubview:rootView];
please delete instead of commenting

2020-12-24 16:30 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
>      powerButton = [[UIButton alloc] initWithFrame:CGRectMake(620, 966, 42, 33)]; //225
copy-paste error on lines below this one?

2020-12-25 08:25 UTC, wutschel commented
> Would you be fine if we do like this?
> 
> 1. add changes based on feedback on top of the current branch
> 2. when all is ready, open new PR with commits squashed appropriately to have a clean history

This is exactly what I had in mind.

2020-12-25 08:32 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
When searching in the web I found hints this is observed for older iOS versions as: https://stackoverflow.com/questions/56664368/ios-13-custom-uisearchbar-searchfield-crash
The code segment is called each time when selecting an album. In the current released app this works, even for iOS14. So I assume this is somehow related to xcode.

2020-12-25 08:34 UTC, wutschel commented on Kodi Remote.xcodeproj/project.pbxproj
> -		0F747771151E5E8600EF78AD /* JSONKit.m in Sources */ = {isa = PBXBuildFile; fileRef = 0F74776E151E5E8600EF78AD /* JSONKit.m */; settings = {COMPILER_FLAGS = "-fno-objc-arc"; }; };
Agreed. I will find a way to sort this out for the final -- squashed -- PR.

2020-12-25 08:35 UTC, wutschel commented on XBMC Remote/iPad/MenuViewController.m
> +        iconName = @"connection_off.png";
Yes, already did this locally.

2020-12-25 08:36 UTC, wutschel commented on XBMC Remote/ViewControllerIPad.m
> -    [powerButton setImage:[UIImage imageNamed: @"icon_power_up"] forState:UIControlStateNormal];
Yes, already did this locally.

2020-12-25 08:57 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
> So I assume this is somehow related to Xcode.

to iOS SDK actually ;)

2020-12-25 10:01 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
So we keep the code change like it is?

2020-12-25 10:05 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    NSError *error = nil;
If I remove the assignment to nil, the app crashes at start.

2020-12-25 10:08 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
>  #ifdef __OBJC_GC__
I am removing JSONKit.h/.m. When keeping this line the code will not compile anymore.

2020-12-25 10:26 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    NSString *query = [searchString stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLFragmentAllowedCharacterSet]];
That´s why reviews are a good thing. I corrected the character sets in https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/101/commits/68565c8d04d8a0f15487e1b0a68d7d9b1c814c23

2020-12-25 10:32 UTC, wutschel commented on XBMC Remote/ViewControllerIPad.m
> +//    [self.view insertSubview:self.nowPlayingController.ProgressSlider aboveSubview:rootView];
Changed with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/101/commits/f357229233e077e932c23bdf45eefcaef358b09d

2020-12-25 10:35 UTC, wutschel commented on XBMC Remote/ViewControllerIPad.m
>      powerButton = [[UIButton alloc] initWithFrame:CGRectMake(620, 966, 42, 33)]; //225
No. This is intentionally and needed to keep the xbmc info centered in the toolbar.

2020-12-25 11:01 UTC, wutschel commented on XBMC Remote/HostViewController.m
> +    [descriptionUI setBackgroundColor:[UIColor whiteColor]];
For now I would keep this as white -- doesn´t look too bad in Night Mode. But the App as whole could need a color rework for Night Mode. For example all list view are still using white instead of SystemGray6. Possibly something to work on in future.
Independent of the color I found  I missed to set the background for tcpPortUI. Added this in https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/101/commits/955798d91aa7e0328b718252a74a50900fc1da8e

2020-12-25 11:56 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    if (IS_IPHONE_X) {
The macros which were introduced seem to only check for the exact boundary height of 3 types of iPhones (6, 6plus and X). I am not really sure, if we now -- with more phones and even higher resolutions -- need to change this for the other places as well...

For the above case I now thought to introduce a macro which checks if we at least have the boundary height of the iPhone X. This will result in moving the NowPlaying elements for other large devices as well. Let me know what you think of this approach.

AppDelegate.h:
#define IS_AT_LEAST_IPHONE_X_HEIGHT     ([[UIScreen mainScreen]bounds].size.height >= 812)

NowPlaying.m:
if (IS_AT_LEAST_IPHONE_X_HEIGHT) { ...

2020-12-25 12:38 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    [items removeObjectAtIndex:14];
I have no good idea how to solve this w/o too much changes. The toolbar items (actionable buttons) are created in a xib which is common for iPhone and iPad. To allow automated spacing/scaling to different widths there are flexible spaces added between these buttons. For iPad we only want to keep all actionable buttons (except the last which is not needed on iPad) at their fixed positions and only the rightmost flexible space left. I would rather add an exhaustive comment for this.

2020-12-26 11:14 UTC, wutschel commented on XBMC Remote/Kodi Remote-Info.plist
> +	<string>Kodi Remote App uses local network to find and communicate to Kodi instances in the network.</string>
I tried declaring NSLocalNetworkUsageDescription in InfoPlist.strings (NSLocalNetworkUsageDescription = "my text";), but then the defined text does not show up anymore. Instead a default text comes up.

2020-12-26 11:31 UTC, wutschel commented on XBMC Remote/Kodi Remote-Info.plist
> +	<string>Kodi Remote App uses local network to find and communicate to Kodi instances in the network.</string>
Had a problem with this initially as I was not defining the string for all languages. I can provide the text for English and German, for the other languages I would keep the English version. Is this ok?

2020-12-26 11:47 UTC, wutschel commented on XBMC Remote/Kodi Remote-Info.plist
> +	<string>Kodi Remote App uses local network to find and communicate to Kodi instances in the network.</string>
Done with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/101/commits/376ec12191dbf05d957536e993efe9b810b0bd67

2020-12-26 11:49 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
The best would've been replacing deprecated `UISearchDisplayController` with `UISearchController`, but that's probably too much work.

Other options to avoid relying on private implementation:

- just make a deep search for text field inside subviews
- use `UIAppearance` to configure properties of textfield inside search bar (might not fit here)
- utilize `searchTextField` property on iOS 13 and later

2020-12-26 11:51 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    NSError *error = nil;
true, because this file is compiled in MRC mode: https://github.com/xbmc/Official-Kodi-Remote-iOS/blob/master/Kodi%20Remote.xcodeproj/project.pbxproj#L509

I suggest to convert all files to ARC if possible.

2020-12-26 11:52 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
>  #ifdef __OBJC_GC__
I'm talking about `#ifdef __OBJC_GC__` block :)

2020-12-26 11:54 UTC, kambala-decapitator commented on XBMC Remote/HostViewController.m
> +    [descriptionUI setBackgroundColor:[UIColor whiteColor]];
ok, let's keep as is then.

Maybe assign the same color to array of controls to have less copy-paste? E.g. `for` or `makeObjectsPerformSelector`.

2020-12-26 11:56 UTC, kambala-decapitator commented on XBMC Remote/Kodi Remote-Info.plist
> +	<string>Kodi Remote App uses local network to find and communicate to Kodi instances in the network.</string>
I'd rather put English text to all languages (I can provide Russian translation btw) and place some fake text in `Info.plist`

2020-12-26 11:57 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    [items removeObjectAtIndex:14];
you could assign every button to a property and use `removeObject:` instead of index

2020-12-26 12:01 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    if (IS_IPHONE_X) {
I agree. But better use the following code:

```objc
CGRectGetHeight(UIScreen.mainScreen.fixedCoordinateSpace.bounds) >= 812
```

also make sure to handle iPad (if needed), as this condition would be true for standard iPad in portrait mode and all or most of the bigger iPads.

2020-12-26 12:03 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
Yes, I started to rework the whole thing to use UISearchController. This basically works, but I am struggling with the layout for iPad and adding the Sort/CollectionView buttons.
Yes, searchTextField is an option for iOS13+.

For now I would keep it as it is to not open up a bigger construction site. My main question is: How do we move with the overall state of the Search when built with current iOS SDK. Currently the search will crash as soon as you enter a character in the search field. I did not find a way to fix this w/o moving to UISearchController.

2020-12-26 12:13 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
To make it clear: does it crash with https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/354b6a8cdf0c445317a39b46860caf9018ed14db or not?

2020-12-26 12:14 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    if (IS_IPHONE_X) {
For iPads there is a dedicated method to define the NowPlaying layout. I added your suggestion with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/101/commits/16bbe801f697e600c9c67af3d97f68ba38e78f13

2020-12-26 12:19 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
Sorry for the confusion.
1. Without https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/354b6a8cdf0c445317a39b46860caf9018ed14db it crashes just by entering the album detail view.
2. With https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/354b6a8cdf0c445317a39b46860caf9018ed14db this crash is fixed.
3.  But: With or without https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/354b6a8cdf0c445317a39b46860caf9018ed14db the App still crashes when using the search bar (crash on entering first character).

2020-12-26 12:29 UTC, wutschel commented on XBMC Remote/HostViewController.m
> +    [descriptionUI setBackgroundColor:[UIColor whiteColor]];
If you don´t mind, I will keep it as it is then. I still have enough to work on the other suggestions. :)

2020-12-26 12:40 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
>  #ifdef __OBJC_GC__
This is not related to the implemented changes. Can´t we keep it in for now and handle this independent of this PR? Let us not add all generally needed cleanups into this single PR. :)

2020-12-26 12:41 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
thanks, then 3 is the most important, of course. I'll have a look.

2020-12-26 12:42 UTC, kambala-decapitator commented on XBMC Remote/HostViewController.m
> +    [descriptionUI setBackgroundColor:[UIColor whiteColor]];
sure, that's fine :)

2020-12-26 12:45 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +#define THUMB_SIZE_POS width:60 height:60 padding:0
that's a really terrible define :) Please use a separate function instead.

2020-12-26 12:45 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
Great. In addition,
4. When clicking the Sort or CollectionView the search bar will be activated. You cannot change sorting or view.

2020-12-26 12:51 UTC, kambala-decapitator requested changes

2020-12-26 12:51 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> + //       hideLine = YES;
1. please delete instead of commenting
2. "Do always use ClipsToBounds for toolbar" - but with this change you're NOT using ClipsToBounds ;)

2020-12-26 12:51 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +//        frame.size.height += bottomPadding;
please delete instead of commenting

2020-12-26 12:54 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                             fanartURL = [NSString stringWithFormat:@"http://%@%@", serverURL, [fanartPath stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLHostAllowedCharacterSe
1. squash with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/101/commits/9a41a205246de53f66680017384a6e2348cd5866
2. character set seems incorrect

2020-12-26 13:00 UTC, kambala-decapitator commented on XBMC Remote/HostViewController.m
> +                [[[NSURLSession sharedSession] dataTaskWithRequest:request] resume];
1. completion handler not passed - you simply ignore response. If you want more granular control (similar to what was before), consider using own session and set a delegate.
2. `fillMacAddressInfo` is now unused, but that looks incorrect
3. You can pass URL to `dataTaskWithURL:` directly, no need to construct `NSURLRequest`.

2020-12-26 13:09 UTC, kambala-decapitator requested changes

2020-12-26 13:09 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +    int bottom_scroll = (height_content - height_bounds)>0 ? height_content - height_bounds : 0;
1. please surround `>` with spaces
2. this piece of code repeats a few times, could you refactor?

2020-12-26 13:09 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +             [clearlogoButton setTitle:[[item objectForKey:@"showtitle"] length] == 0 ? [item objectForKey:@"label"] :[item objectForKey:@"showtitle"] forState:UIControlStateNormal];
only leading spacing changed? I'd drop this.

2020-12-26 13:09 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +    }
could be simplified to `arrow_continue_down.hidden = height_content <= height_bounds-height_navbar;`

2020-12-26 13:09 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +    else if (arrow_continue_down.hidden==YES && at_bottom==NO){
please avoid comparing to `YES` and `NO`, use `!` when needed

2020-12-26 13:09 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +    arrow_continue_down.frame = frame;
can be dropped

2020-12-26 13:13 UTC, kambala-decapitator commented on XBMC Remote/RightMenuViewController.m
> +        AVCapturePhotoSettings *settings = [AVCapturePhotoSettings photoSettings];
camera code in these 2 files looks identical. Could you refactor it since you're touching it already?

also, `AVCaptureDevice` is available unconditionally for a long time.

2020-12-26 13:15 UTC, kambala-decapitator requested changes

2020-12-26 13:15 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                    [[UIApplication sharedApplication] openURL:[NSURL URLWithString:stringURL] options:@{} completionHandler:^(BOOL success) {}];
set `completionHandler` to `nil` instead

2020-12-26 13:15 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +                    [[UIApplication sharedApplication] openURL:[NSURL URLWithString:stringURL] options:@{} completionHandler:^(BOOL success) {}];
set `completionHandler` to `nil` instead

2020-12-26 13:16 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                                     ProgressSlider.hidden = FALSE;
use `NO`

2020-12-26 13:20 UTC, kambala-decapitator commented on XBMC Remote/Kodi Remote-Info.plist
> -	<string>Kodi Remote App uses local network to find and communicate to Kodi instances in the network.</string>
please leave the key (I think it's required to be present) and use some fake string for value (e.g. also the key)

2020-12-26 13:21 UTC, kambala-decapitator commented
FYI I've reviewed all the available commits

2020-12-26 13:26 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> + //       hideLine = YES;
:) Yes, fixed the comment in my local squashed version. Code removed with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/101/commits/6bcc6d68cd58e49d482b3dfce46ef9d347400e6e

2020-12-26 13:26 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +//        frame.size.height += bottomPadding;
Done with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/101/commits/6bcc6d68cd58e49d482b3dfce46ef9d347400e6e

2020-12-26 13:37 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
FYI doesn't crash on iOS 12

2020-12-26 14:00 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                             fanartURL = [NSString stringWithFormat:@"http://%@%@", serverURL, [fanartPath stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLHostAllowedCharacterSe
I do not see any URLHostAllowedCharacterSet in my code anymore, for the code you refer to  URLPathAllowedCharacterSet is used.

2020-12-26 14:06 UTC, wutschel commented on XBMC Remote/HostViewController.m
> +                [[[NSURLSession sharedSession] dataTaskWithRequest:request] resume];
I will just remove this change. It´s obviously not mature.

2020-12-26 14:19 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
> With or without 354b6a8 the App still crashes when using the search bar (crash on entering first character).

looks like the only solution is to switch to the new class.

As a quick fix, I simply suggest to disable the search controller. This removes search bar:

```
❯ git --no-pager diff 'XBMC Remote/DetailViewController.m'  
diff --git a/XBMC Remote/DetailViewController.m b/XBMC Remote/DetailViewController.m
index 3808267..5119f5b 100644
--- a/XBMC Remote/DetailViewController.m	
+++ b/XBMC Remote/DetailViewController.m	
@@ -3513,6 +3513,10 @@ - (void)handleSwipeFromRight:(id)sender {
 
 #pragma mark - View Configuration
 
+- (UISearchDisplayController *)searchDisplayController {
+    return NSProcessInfo.processInfo.operatingSystemVersion.majorVersion >= 13 ? nil : [super searchDisplayController];
+}
+
 -(UIStatusBarStyle)preferredStatusBarStyle{
     return UIStatusBarStyleLightContent;
 }
```

2020-12-26 14:24 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
> 4. When clicking the Sort or CollectionView the search bar will be activated. You cannot change sorting or view.

don't fully understand this point, but I guess the above change also "fixes" it

2020-12-26 14:45 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> +    int bottom_scroll = (height_content - height_bounds)>0 ? height_content - height_bounds : 0;
1. Done locally, will be part of next PR.
2. Would like to keep the code as it is easy to read and debug. If I compress this it becomes harder to read.

2020-12-26 14:46 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> +             [clearlogoButton setTitle:[[item objectForKey:@"showtitle"] length] == 0 ? [item objectForKey:@"label"] :[item objectForKey:@"showtitle"] forState:UIControlStateNormal];
Done in local version, will be part of next PR.

2020-12-26 14:46 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> +    }
Done in local version, will be part of next PR.

2020-12-26 14:46 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> +    else if (arrow_continue_down.hidden==YES && at_bottom==NO){
Done in local version, will be part of next PR.

2020-12-26 14:46 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> +    arrow_continue_down.frame = frame;
Done in local version, will be part of next PR.

2020-12-26 15:07 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                    [[UIApplication sharedApplication] openURL:[NSURL URLWithString:stringURL] options:@{} completionHandler:^(BOOL success) {}];
Just "completionHandler:nil" ?

2020-12-26 15:11 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +                                     ProgressSlider.hidden = FALSE;
Done on local branch, will be part of new PR.

2020-12-26 15:14 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                    [[UIApplication sharedApplication] openURL:[NSURL URLWithString:stringURL] options:@{} completionHandler:^(BOOL success) {}];
yes

2020-12-26 15:20 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                    [[UIApplication sharedApplication] openURL:[NSURL URLWithString:stringURL] options:@{} completionHandler:^(BOOL success) {}];
Done on local branch, will be part of next PR.

2020-12-26 15:20 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> +                    [[UIApplication sharedApplication] openURL:[NSURL URLWithString:stringURL] options:@{} completionHandler:^(BOOL success) {}];
Done on local branch, will be part of next PR.

2020-12-26 15:56 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +#define THUMB_SIZE_POS width:60 height:60 padding:0
I have seen worse :)

The following method does the same magic. Fine for you?

-(UIImage *)resizeToolbarThumb: (UIImage *)img {
    UIImage *image = nil;
    image = [self resizeImage:img width:34 height:34 padding:0];
    return image;
}

2020-12-26 16:11 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
With your change the App shows a black bar on top of the album list. The behaviour is still not correct. You think it is possible to find a workaround / fix for the searchbar without a full migration to UISearchController?

2020-12-26 16:19 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +#define THUMB_SIZE_POS width:60 height:60 padding:0
yes, just not sure why you prefer to use a variable as well as not assign the value to it directly :)

2020-12-26 16:25 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
I think black bar is way better than broken functionality.

Unfortunately, there's no proper fix. It might be possible to swizzle private method(s) that crash or try catching the exception of interest in `UIApplication` subclass, but I wouldn't go down this way.

2020-12-26 16:26 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +#define THUMB_SIZE_POS width:60 height:60 padding:0
Well, the first version wasn´t fitting into 1 line. Will reduce this to 

return [self resizeImage:img width:34 height:34 padding:0];

:)

2020-12-26 16:29 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +        AVCapturePhotoSettings *settings = [AVCapturePhotoSettings photoSettings];
Let us do this in a next step. I would like to get the PR accepted first. A lot of work open.

2020-12-26 17:32 UTC, wutschel commented on XBMC Remote/Kodi Remote-Info.plist
> -	<string>Kodi Remote App uses local network to find and communicate to Kodi instances in the network.</string>
I did a few tests now. The localized text overwrites the string defined "Kodi Remote-Info.plist". To have a text tailored for Kodi it is easiest to define the string in there. Translations can be added later to the localized versions of  InfoPlist.strings.

So, I will keep the key and string inside "Kodi Remote-Info.plist" and will add the localized text for English and German for now. You are of course welcome to add the Russian translation.

2020-12-26 18:16 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    [items removeObjectAtIndex:14];
For now I added a detailed comment.

2020-12-26 18:23 UTC, wutschel commented
Raised PR https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/102 now. It holds the rework we discussed in this PR. We can close this PR.

2020-12-26 18:29 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                                          UITextField *searchTextField = [self.searchDisplayController.searchBar valueForKey:@"searchField"];
Agree, nevertheless I will try to find a way to avoid the black bar. Would also be great, if you could take a look at my initial migration to UISearchController which I started here: https://github.com/wutschel/Official-Kodi-Remote-iOS/tree/UISearchController-migration 
I will rebase this when the other changes got merged. Otherwise I have too many open changes hanging in the air.

2020-12-27 00:45 UTC, closed without merging