Bugfix: Fix top padding
xbmc/Official-Kodi-Remote-iOS pull request #1010
Opened 2024-03-23 18:47 UTC by wutschel

## Description

Fixes a regression caused by https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/889.

Generally it is correct to use `UIApplication.sharedApplication.keyWindow.safeAreaInsets.top` in `getTopPadding`. This resolves issues with moving and wrongly positioned tables in iPhone main menu and custom button view. For the HostManagementViewController we use `UIApplication.sharedApplication.statusBarFrame.size.height ` to read the size of the status bar.

## Summary for release notes

Bugfix: Fix vertical origin of main menu and custom button view

2024-03-24 08:18 UTC, wutschel commented
Conflicts with #1004. Please prioritize #1004, I will then rebase this one.

2024-03-26 06:07 UTC, wutschel commented
Converted back to draft as I obviously should relook the approach. It seems I need two different padding values: one when showing a navbar (= status bar height + nabber height) and another when not (= safe area height). For this I need to revisit the code where the different ways are required as some view have a navbar and some have not.

2024-04-02 18:17 UTC, wutschel commented
I am sure you will stumble over this one:

`deltaY = 44 + UIApplication.sharedApplication.statusBarFrame.size.height;`

The `44` is the NavigationBar's height which is 0 during init time. I am not sure why moving the `messagesView` layout to `viewDidLoad` does result in invisible messages, For now let us please keep it like this, I anyway have an issue open to rework the whole SettingsValuesVC which is the nastiest piece of code left from the past.

2024-04-02 19:13 UTC, kambala-decapitator commented
it's very simple: in viewDidLoad views don't have their final size. The best place to perform layout is viewDidLayoutSubviews

2024-04-02 19:44 UTC, wutschel commented
> viewDidLayoutSubviews

Works. I am sure this is still done wrong in many places ... So much work to do ...

2024-04-03 07:27 UTC, kambala-decapitator requested changes

2024-04-03 07:27 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    CGFloat topPadding = UIApplication.sharedApplication.statusBarFrame.size.height + navCtrl.navigationBar.frame.size.height;
it should be sufficient to use just `CGRectGetMaxY(navCtrl.navigationBar.frame)`

2024-04-03 07:27 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
> +    messagesView = [[MessagesView alloc] initWithFrame:CGRectMake(0, 0, frame.size.width, deltaY + DEFAULT_MSG_HEIGHT) deltaY:deltaY deltaX:0];
viewDidLayoutSubviews is called multiple times, so better create view in viewDidLoad and only adjust frame here

2024-04-03 08:58 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    CGFloat topPadding = UIApplication.sharedApplication.statusBarFrame.size.height + navCtrl.navigationBar.frame.size.height;
For the case of NowPlaying this does not return the correct value -- even after moving this to `viewDidLayoutSubviews`.

2024-04-03 09:24 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
> +    messagesView = [[MessagesView alloc] initWithFrame:CGRectMake(0, 0, frame.size.width, deltaY + DEFAULT_MSG_HEIGHT) deltaY:deltaY deltaX:0];
Sadly it is not that simple. `MessagesView` needs `deltaY` and `deltaX` when created.

2024-04-03 13:14 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
> +    messagesView = [[MessagesView alloc] initWithFrame:CGRectMake(0, 0, frame.size.width, deltaY + DEFAULT_MSG_HEIGHT) deltaY:deltaY deltaX:0];
don't see any reason why you can't adjust frame of the internal `viewMessage` when the delta values become available

2024-04-03 13:33 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
> +    messagesView = [[MessagesView alloc] initWithFrame:CGRectMake(0, 0, frame.size.width, deltaY + DEFAULT_MSG_HEIGHT) deltaY:deltaY deltaX:0];
I will look into this.

2024-04-03 18:14 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
> +    messagesView = [[MessagesView alloc] initWithFrame:CGRectMake(0, 0, frame.size.width, deltaY + DEFAULT_MSG_HEIGHT) deltaY:deltaY deltaX:0];
I spent more time on this and came up with some rework of `MessagesView`. There were more internal ivars which also need to be updated. Finally, I introduced a new method to update the frame and internal variables, and keep another method to create the view. The view creation can be called with `CGFrameZero`, the layout can be updated later. Hope this is what you had in mind.

2024-04-03 18:25 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
> +    messagesView = [[MessagesView alloc] initWithFrame:CGRectMake(0, 0, frame.size.width, deltaY + DEFAULT_MSG_HEIGHT) deltaY:deltaY deltaX:0];
yes, you did it right, well done!

and it seems now that you no longer need to pass the delta values to the initializer as well as call the update method from it

2024-04-03 19:39 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
> +    messagesView = [[MessagesView alloc] initWithFrame:CGRectMake(0, 0, frame.size.width, deltaY + DEFAULT_MSG_HEIGHT) deltaY:deltaY deltaX:0];
Well, the initializer with delta values is still used for all other occurances when `MessagesView` is created. I can of course change this to a 2-line call for each, 1st `initWithFrame` and 2nd `updateWithFrame:deltaY:deltaX`. But somehow the all at once solution is also nice.

2024-04-03 19:41 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
> +    messagesView = [[MessagesView alloc] initWithFrame:CGRectMake(0, 0, frame.size.width, deltaY + DEFAULT_MSG_HEIGHT) deltaY:deltaY deltaX:0];
I mean, now that you set correct delta values in viewDidLayoutSubviews, you don't need them at init time

2024-04-03 19:53 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
> +    messagesView = [[MessagesView alloc] initWithFrame:CGRectMake(0, 0, frame.size.width, deltaY + DEFAULT_MSG_HEIGHT) deltaY:deltaY deltaX:0];
I am confused. Yes, I do not need to set `deltaX` and `deltaY` at init as they are updated later, but only in the case of SettingsValueViewControllers. In other controllers there is only one init call with all parameters. So I cannot just remove the delta-parameters from `initWithFrame:deltaY:deltaX`.

See e.g. RightMenuViewController: 
`messagesView = [[MessagesView alloc] initWithFrame:CGRectMake(0, 0, frame.size.width, DEFAULT_MSG_HEIGHT + deltaY) deltaY:deltaY deltaX:deltaX];`

2024-04-03 20:06 UTC, kambala-decapitator approved these changes

2024-04-03 20:26 UTC, wutschel commented
Squashed and ready to go.

2024-04-04 15:52 UTC, merged