Remove UIWebView for AppStore upload
xbmc/Official-Kodi-Remote-iOS pull request #103
Opened 2020-12-30 02:09 UTC by wutschel

To my knowledge UIWebView must be removed to get acceptance from the AppStore. This PR is removing all references to UIWebView. 

- For some uses cases (e.g. Wikipedia search) the system browser is called.
- For movie trailers this PR implements a Play-button which allows to call the system browser.
- I also removed the PlayFileViewController.

If later there is a migration to WKWebView available, these changes can be rolled back.

2020-12-30 12:06 UTC, wutschel commented
As suggested by @kambala-decapitator it should be possible to use `SFSafariViewController` to provide a better user experience. I did a quick check with the Wikipedia-search and it works, also supporting to go back to the Kodi Remote App when pressing "Done" in the browser.

2020-12-30 12:30 UTC, kambala-decapitator commented
btw `UIWebView` is still allowed, although not recommended: https://developer.apple.com/news/?id=edwud51q

2020-12-31 07:37 UTC, fuzzard commented
With that last bit of info about the deprecation date being pushed, we can probably put this on hold and work through a proper replacement if it's not going to block us in a store submission.

Just a heads up, we are still working through the details around app access/submission, so won't be any imminent update to app store as yet

2020-12-31 08:45 UTC, wutschel commented
I agree. If there is no urgency to make this change, we can park it right here.

2021-01-05 11:38 UTC, kambala-decapitator requested changes
This is still a nice cleanup PR that removes deprecated functionality.

We can postpone this if:
1. `UIWebView` still works flawlessly on modern iOS
2. it's more convenient to watch trailers in an embedded webview rather that `SFSafariViewController`

2021-01-05 11:38 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.h
> +//    NSString *embedVideo;
please remove

2021-01-05 11:38 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +//    [trailerView loadHTMLString:embedVideo baseURL:nil];
please remove

2021-01-05 11:38 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +    [[UIApplication sharedApplication] openURL:_url options:@{} completionHandler:nil];
- don't name local variables with leading underscore
- just pass the URL directly to the method, no need for a variable

2021-01-05 11:38 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> + /*
please remove

2021-01-05 11:38 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +*/
please remove

2021-01-05 11:38 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +//                    [trailerView loadHTMLString:embedVideo baseURL:[NSURL URLWithString:@"http:"]];
please remove

2021-01-05 11:38 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +                    /*
please remove

2021-01-05 11:38 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> + //                   [trailerView loadHTMLString:blackPage baseURL:nil];
please remove

2021-01-05 11:38 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> + //                   [playTrailerButton setFrame:CGRectMake(0, 0, trailerView.frame.size.width, trailerView.frame.size.height)];
please remove

2021-01-05 11:38 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +//                    [trailerView addSubview:playTrailerButton];
please remove

2021-01-05 11:38 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> + */
please remove

2021-01-05 12:32 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.h
> +//    NSString *embedVideo;
The whole trailer related code is still not final -- maybe I shouldn´t have added this to the PR. Please don´t waste time to review this yet. In case we must continue to work on this (if `UIWebView` must be removed) I will update this properly.

Btw, `UIWebView` still works on my Xs target and the simulators.

2021-01-08 09:46 UTC, wutschel commented
- Rebased against master
- Remove code instead of commenting
- Use SFSafariViewController
- Re-implement trailer view (tested against Kodi19 with few movie´s metadata)

2021-01-10 17:09 UTC, kambala-decapitator requested changes

2021-01-10 17:09 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +}
this code is duplicated, please refactor (e.g. put in `Utilities`)

2021-01-10 17:09 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +    svc.delegate = (id)self;
don't cast to `id`

2021-01-24 10:43 UTC, kambala-decapitator commented
we can add this to next update if you wish, doesn't seem urgent

2021-01-24 12:36 UTC, wutschel commented
> we can add this to next update if you wish, doesn't seem urgent

As long as there is no urgency I wanted to leave this like it is.

2021-03-15 17:53 UTC, wutschel commented
Rebased to master, just to keep this up-to-date.

2021-03-28 10:02 UTC, kambala-decapitator commented
please remind: is this ready?

also please rebase.

2021-03-28 10:08 UTC, wutschel commented
> please remind: is this ready?

My main point is: Do we really *want* to take this in? Or do we rather want to migrate to `WKWebView`? For now it does not seem to be urgent, as `UIWebView` is still accepted by Apple.

> also please rebase.

Yes, will do.

2021-03-28 10:13 UTC, kambala-decapitator commented
getting rid of `UIWebView` is preferred. Besides, webview is not a central feature of the remote.

> it's more convenient to watch trailers in an embedded webview rather that SFSafariViewController

if you find this statement true, then let's aim to replace with `WKWebView`.

2021-03-28 13:49 UTC, wutschel commented
> getting rid of `UIWebView` is preferred. Besides, webview is not a central feature of the remote.

True, so let us get rid of then. 

> if you find this statement true, then let's aim to replace with `WKWebView`.

Personally I even prefer the SafariViewController.

Rebased and tested.

2021-03-30 18:52 UTC, merged