Reworking searchbar and related buttons
xbmc/Official-Kodi-Remote-iOS pull request #104
Opened 2020-12-30 02:38 UTC by wutschel

With the current iOS SDK the App´s search implementation based on `SearchDisplayController` does not work anymore. Reported for iOS 13+ the App crashes when trying to enter a search string. This PR can be a starting point to migrate to `SearchController` and to apply some tiny changes to the UI layout which also bring back the sort and library view feature.

Summary:
- Replacing `SearchDisplayController` with `SearchController`
- Move buttons for sorting and library view change to the Toolbar
- A bit of optimization for the searchbar colors and the iPad button/text layout

The Good:
- Search works for iPhone (only tested for Music content though)
- The buttons also work and now make them independent of the SearchBar. This way we could just switch off search for a next AppStore upload, but still have sort and library view change features.

The Bad:
- I am a bit lost in how to configure the SearchBar properly. Some issues:
  - On iPad the SearchBar can be activated and filtered results are presented, but it is not possible to select an item from the resulting list.
  - On iPad the SearchBar detaches from the active window and is always displayed far left.
  - On iPhone the SearchBar detaches and stays at the same position when going back to main menu.
  - "Detaching" can be fixed when using `definesPresentationContext = NO;`, but at cost of having the SearchBar vertically jumping when activated.

The Minor:
- The new button location in the Toolbar required at least the "button_sort..." images to be updated. They need a higher brightness, otherwise they are merely visible. 
- The library view buttons ("button_view...") do not really match the design of the other buttons, but they are well readable. Nevertheless I will try to look into finding a better fitting icon set.

2021-01-05 11:59 UTC, kambala-decapitator requested changes

2021-01-05 11:59 UTC, kambala-decapitator commented on Kodi Remote.xcodeproj/project.pbxproj
> +		C788DDCE259F6D76006C90F1 /* button_view_list_toolbar@3x.png in Resources */ = {isa = PBXBuildFile; fileRef = C788DDCA259F6D76006C90F1 /* button_view_list_toolbar@3x.png */; };
please start using asset catalog to manage images

2021-01-05 12:16 UTC, kambala-decapitator requested changes

2021-01-05 12:16 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        return ([self.filteredListContent count]>0);
please return an integer explicitly

2021-01-05 12:16 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +//AB                             [bar layoutSubviews];
such stuff should be removed in the end

2021-01-05 12:16 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    }
I'd prefer to have this implemented via `-[NSArray filteredArrayUsingPredicate:]` where predicate's format is something like `@"label CONTAINS[cd] %@", searchText` (please check docs for proper keyword)

2021-01-05 12:16 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +//AB-end
you could simply move it to a properly named function

2021-01-05 12:16 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        for (view in buttonsView.subviews) {
```suggestion
        for (UILabel *view in buttonsView.subviews) {
```

2021-01-05 12:16 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    CGFloat x2 = (x1 - 7*button1.frame.size.width)/8;
what is 7 and 8?

2021-01-05 13:55 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    CGFloat x2 = (x1 - 7*button1.frame.size.width)/8;
:) Will replace the numbers with #defines which make clear what their meaning is. 

Do you have an idea why I cannot use `button7.center.x` in this case? Before I used the flexible spaces (I did move the button directly to the desired position) this worked. I would prefer to avoid this magic calculation...

2021-01-06 09:45 UTC, wutschel commented on Kodi Remote.xcodeproj/project.pbxproj
> +		C788DDCE259F6D76006C90F1 /* button_view_list_toolbar@3x.png in Resources */ = {isa = PBXBuildFile; fileRef = C788DDCA259F6D76006C90F1 /* button_view_list_toolbar@3x.png */; };
Argh, I just looked at this and gave it a try. There seems to be quite some clean up needed as in the existing images there are obviously several images double defined (I get 300+ warnings). I agree to do this, but I would like to do this after this PR in a dedicated PR.

2021-01-06 09:50 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        return ([self.filteredListContent count]>0);
Done with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/104/commits/278a380856460cf15922b82186cc5d60c3167266. Will squash this later.

2021-01-06 09:52 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +//AB                             [bar layoutSubviews];
Agreed, will do a cleanup once this PR is ready. As I want to keep the searchbar and button rework in separate commits, I tend to fully remove all the button-related code (which I commented as a first step) and let the later button commit re-add the implementation.

2021-01-06 09:55 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        for (view in buttonsView.subviews) {
Done with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/104/commits/ef46f9ca5a8640119f2190a93958abb7a7e1de71. Will squash later.

2021-01-06 10:12 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    CGFloat x2 = (x1 - 7*button1.frame.size.width)/8;
Added #defines and further explanation for the calculation with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/104/commits/6241f22d021c6e69841e9047a5af91c50711f64a. I am still in favor of finding a more elegant way. Is it not possible to check the the position of a button when flexible spaces are used?

2021-01-06 10:15 UTC, kambala-decapitator commented on Kodi Remote.xcodeproj/project.pbxproj
> +		C788DDCE259F6D76006C90F1 /* button_view_list_toolbar@3x.png in Resources */ = {isa = PBXBuildFile; fileRef = C788DDCA259F6D76006C90F1 /* button_view_list_toolbar@3x.png */; };
thanks, that's fine

2021-01-06 10:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    CGFloat x2 = (x1 - 7*button1.frame.size.width)/8;
Do I understand correctly that UI hierarchy is the following: buttonX -> [subview of] buttonsView -> [custom view of] bar button item -> [child of] Toolbar?

`button7.center` is in coordinate system of its parent, i.e. `buttonsView`, while you want the coordinate in coordinate system of `buttonsView`'s parent. You'd want to convert between coordinate systems: `[buttonsView convertPoint:button7.center toView:buttonsView.superview].x`

2021-01-06 10:36 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    }
This is what works (and I admit it is more elegant):

```
- (void)searchForText:(NSString *)searchText
{
    // filter here
    [self.filteredListContent removeAllObjects];
    NSPredicate *pred = [NSPredicate predicateWithFormat:@"label CONTAINS[cd] %@", searchText];
    self.filteredListContent = [NSMutableArray arrayWithArray:[self.richResults filteredArrayUsingPredicate:pred]];
    numFilteredResults = (int)[self.filteredListContent count];
}
```

2021-01-06 10:55 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    CGFloat x2 = (x1 - 7*button1.frame.size.width)/8;
Great, with a minor change this works:

`[button7 convertPoint:button7.center toView:buttonsView.superview].x;`

2021-01-06 11:00 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    }
Done with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/104/commits/536ade50f5464facfa1f94b4282a275fbc9aa20b.

2021-01-06 19:33 UTC, wutschel commented
The force-pushed code has quite some rework done. New code provides -- except the introduction of a function for searchbar-setup -- all required changes and does not comment but removes code. When working on the latter I also now clearly separated searchbar changes from button changes (were mixed due to commenting button related parts in first commit).

2021-01-07 10:11 UTC, wutschel commented
- Removed residual comment
- Removed intermediate button rework (now directly implement the desired button solution)
- Removed obsolete UISearchBarLeftButton
- Rebased to master

2021-01-07 22:05 UTC, wutschel commented
- The search now works quite well for both iPhone and iPad types
- Removed deletion of search results when selecting from filtered list (was required before due to limitations)
- Handle iOS13 specific code, still support pre-iOS13
- Minor fix to searchbar color

This now needs more intense testing on older iOS and with Movie/TV data.

2021-01-10 16:50 UTC, kambala-decapitator requested changes
I've tested on XR 14.3, Air 2 14.3, 6+ 12.5 - looks good.

2021-01-10 16:50 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        }
can't you just write `[searchbar removeFromSuperview];` instead?

2021-01-10 16:50 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        }
1. `my` is never read => useless
2. can't you keep a reference to `UITableView` instead?

2021-01-10 16:50 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    [self viewWillLayoutSubviews];
not sure it's a good idea to call this method directly (and in the method below as well). If the point is to apply the above code, extract it to a function.

2021-01-10 16:50 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        [dataList endUpdates];
this doesn't feel right because it's identical to the code just below

2021-01-10 17:09 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    self.searchController.searchBar.delegate = (id)self;
Fixed with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/104/commits/adb9d909b54940a53bd2f91f92406deaf19b2fa3.

2021-01-10 17:09 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    self.searchController.searchResultsUpdater = (id)self;
Fixed with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/104/commits/adb9d909b54940a53bd2f91f92406deaf19b2fa3.

2021-01-10 17:12 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    UIImage *viewButtonImg = [UIImage imageNamed:@"button_view_list_toolbar.png"];
Fixed with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/104/commits/eb70ac79d07bdf05d4f8fc1f82f8655f44f55fe3.

2021-01-10 17:12 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    UIImage *sortButtonImg = [UIImage imageNamed:@"button_sort_bright.png"];
Fixed with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/104/commits/eb70ac79d07bdf05d4f8fc1f82f8655f44f55fe3.

2021-01-10 17:30 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        }
Thanks, simplified this with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/104/commits/2825bdcf861b6ff7a56783e82d539b8d127dbdc7.

2021-01-10 17:31 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        }
Thanks, forgot to remove the debug-variables and wasn´t seeing the easy solution. Simplified this with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/104/commits/2825bdcf861b6ff7a56783e82d539b8d127dbdc7.

2021-01-10 17:48 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    [self viewWillLayoutSubviews];
Done with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/104/commits/aab6ed69075635be406f7f6f44390d4ab4786bca. Thanks for nudging me on this, the code is less and cleaner now.

2021-01-10 17:52 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        [dataList endUpdates];
I was also wondering about this effect when doing the migration. I have a similar situation at line 281 of tbe same file:

```
if ([self doesShowSearchResults]){
        cell = [dataList cellForRowAtIndexPath:indexPath];
    }
    else{
        cell = [dataList cellForRowAtIndexPath:indexPath];
    }
```

For now I didn´t remove the additional/duplicate code. If everything works as expected, I will just delete the if/else.

2021-01-10 18:16 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        [dataList endUpdates];
I guess just remove the extra conditions/code

2021-01-10 18:57 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        [dataList endUpdates];
Ok, now cleaned up a lot of unneeded if/else structure and few duplicate code segments with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/104/commits/a13d39cfe53f107b6d454fbe89eae5fc601af832. This should be kept as a separate commit, as otherwise the initial search rework commit becomes hard to read.

2021-01-11 00:26 UTC, kambala-decapitator commented
you made a wrong rebase (see first commit), please fix

2021-01-11 00:31 UTC, kambala-decapitator requested changes
I got tired of copy-pasting the same code comment, please refactor duplicate code to a separate function

2021-01-11 00:31 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    UITableViewCell *cell = [dataList cellForRowAtIndexPath:indexPath];;
double semi-colon

2021-01-11 00:31 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
>          cell = [collectionView cellForItemAtIndexPath:indexPath];
please use if/else or ternary operator to avoid useless assignment when `enableCollectionView == YES`

2021-01-11 00:31 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
>          isTableView = FALSE;
- please use if/else or ternary operator to avoid useless assignment when `enableCollectionView == YES`
- prefer YES/NO over TRUE/FALSE

2021-01-11 00:31 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
>          cell = [collectionView cellForItemAtIndexPath:indexPath];
please use if/else or ternary operator to avoid useless assignment when `enableCollectionView == YES`

2021-01-11 06:09 UTC, wutschel commented on XBMC Remote/DetailViewController.m
>          cell = [collectionView cellForItemAtIndexPath:indexPath];
Done with last force-push.

2021-01-11 06:12 UTC, wutschel commented on XBMC Remote/DetailViewController.m
>          isTableView = FALSE;
Done with last force-push. 

General comment: Overall there are dozens of places where TRUE/FLASE is used in the whole code (not only in the parts I changed). Shall this be unified for the whole code in a dedicated PR?

2021-01-11 06:12 UTC, wutschel commented on XBMC Remote/DetailViewController.m
>          cell = [collectionView cellForItemAtIndexPath:indexPath];
Done with last force-push.

2021-01-11 06:12 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    UITableViewCell *cell = [dataList cellForRowAtIndexPath:indexPath];;
Done with last force-push.

2021-01-11 08:02 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
>          isTableView = FALSE;
no, it's enough to ensure only for the newly added code. General cleanup can be done later.

2021-01-11 11:14 UTC, kambala-decapitator commented
Looks pretty good now!

@wutschel do you consider this ready for a merge?

2021-01-11 16:23 UTC, wutschel commented
> @wutschel do you consider this ready for a merge?

Yes, let´s go for it. There are still a few issues with this, but the current master is unusable without this change. I can continue to work on bugfixes as the feedback comes from the Testflight users.

2021-01-11 16:30 UTC, merged