Fix for broken seek with Kodi 19+
xbmc/Official-Kodi-Remote-iOS pull request #105
Opened 2020-12-30 17:23 UTC by wutschel

Fixes Kodi issue https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/95

Details:
- With Kodi 15 an new syntax for Player.Seek was added
- With Kodi 19 the old syntax was removed
- This change checks for the Kodi server version and builds the support command parameter for seek

2020-12-30 17:26 UTC, wutschel commented
I am not too happy with the solution for the Seek-to-Percentage yet. Hopefully someone can find a more elegant way to build the parameter set. Would also be good, if someone could test this as well. On my setup (Kodi 17.6) the new implementation works.

2021-01-02 13:21 UTC, wutschel commented
@kambala-decapitator, could you review this change? I remember you were also mentioning we should fix this issue with Kodi 19.

2021-01-02 20:10 UTC, fuzzard commented
Ill try get a runtime test on v19 done today/tomorrow.

I think the approach you have put together is fine

2021-01-02 21:15 UTC, howie-f commented
really a cool thing something's going on here.. thanks a lot @wutschel 
i would do a runtime test, too - if i could or knew how to, but no jailbroken device and no macos, just using linux and windows, so i guess no chance...

there is another annoying issue that popped up inbetween, https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/96
posters are not showing since this commit https://github.com/xbmc/xbmc/pull/17127/commits/429284605f69a5156f96de9a12d657e830b30a73 but i fixed it for my personal branch by reverting :)
iirc @enen92 fixed the same poster issue for chorus2 here https://github.com/xbmc/chorus2/pull/392

so ofc. ....without any nudging.... this would be the icing on the cake and return the remote to a usable state without hacking the master tree of v19 ;)
is there a chance on the horizon?

2021-01-03 14:34 UTC, wutschel commented
In the meanwhile I could set up a Kodi 19.0 Beta2 test environment and can confirm the fix works for music and video playback, using the NowPlaying buttons and the Remote Control.

2021-01-05 07:11 UTC, fuzzard approved these changes

2021-01-05 11:25 UTC, kambala-decapitator requested changes

2021-01-05 11:25 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +            }
I strongly suggest to create a dedicated function that builds proper params because you're repeating yourself multiple times

2021-01-05 11:25 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +        [self SimpleAction:@"Player.Seek" params:dict3 reloadPlaylist:NO startProgressBar:YES];
- variable naming is really awful
- this code is repeated below
- it's quite difficult to understand the final result. Why not build the payload directly?

```objc
__auto_type params = @{
    @"playerid": @(playerID),
    @"value": @{@"percentage": @(ProgressSlider.value)},
};
[self SimpleAction:@"Player.Seek" params: params reloadPlaylist:NO startProgressBar:YES];
```

2021-01-05 12:37 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +            }
This was reworked in the 2nd commit. If accepted I will squash and force-push all to one single commit.

2021-01-05 12:38 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +        [self SimpleAction:@"Player.Seek" params:dict3 reloadPlaylist:NO startProgressBar:YES];
Are you ok with the solution in the 2nd commit?

2021-01-05 12:47 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +            }
Sorry, I don't see where **building params** is reworked: you have copy-paste code in all places

2021-01-05 12:49 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +        [self SimpleAction:@"Player.Seek" params:dict3 reloadPlaylist:NO startProgressBar:YES];
No. Like I wrote in my edit:

> Sorry, didn't check the second commit before writing comment. Dictionary literal is still more readable than using initializer.

I suggest to use my code (that uses dictionary literal) and place it in a separate function to avoid copy-paste.

2021-01-05 13:13 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +        [self SimpleAction:@"Player.Seek" params:dict3 reloadPlaylist:NO startProgressBar:YES];
Well, I kept the code similar to the other places in the same file, e.g.

`[self SimpleAction:@"Player.SetShuffle" params:[NSDictionary dictionaryWithObjectsAndKeys:[NSNumber numberWithInt:currentPlayerID], @"playerid", @"toggle", @"shuffle", nil] reloadPlaylist:YES startProgressBar:NO];`

You are asking to update the code into something like this, correct? I agree it is far better readable, just not in line with the other code sequences.

```
if ([AppDelegate instance].serverVersion < 15){
        __auto_type params = @{
            @"playerid": @(playerID),
            @"value": @(ProgressSlider.value),
        };
        [self SimpleAction:@"Player.Seek" params:params reloadPlaylist:NO startProgressBar:YES];
    } else
    {
        __auto_type params = @{
            @"playerid": @(playerID),
            @"value": @{@"percentage": @(ProgressSlider.value)},
        };
        [self SimpleAction:@"Player.Seek" params:params reloadPlaylist:NO startProgressBar:YES];
    }
```

2021-01-05 14:16 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +        [self SimpleAction:@"Player.Seek" params:dict3 reloadPlaylist:NO startProgressBar:YES];
Yes. But please extract this to a separate function that returns a dictionary without any temp variables, as you have this code twice.

Improving readability and comprehension is more important than matching existing style imo.

2021-01-05 15:05 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +        [self SimpleAction:@"Player.Seek" params:dict3 reloadPlaylist:NO startProgressBar:YES];
Here we go. I hope this is what you were asking for.

2021-01-05 15:52 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +        [self SimpleAction:@"Player.Seek" params:dict3 reloadPlaylist:NO startProgressBar:YES];
Yes, except one small part :)

> without any temp variables

I.e. return value from the function directly.

Also your second new commit should be squashed with the first one.

2021-01-05 16:05 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +        [self SimpleAction:@"Player.Seek" params:dict3 reloadPlaylist:NO startProgressBar:YES];
If you don´t mind I will squash all commits into a single one.

On the local variable: I am per default trying to avoid multiple returns. Is this something which is really bugging you?

2021-01-05 16:44 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +        [self SimpleAction:@"Player.Seek" params:dict3 reloadPlaylist:NO startProgressBar:YES];
I just thought of also moving the other changed seek commands into a function. 

```
+ (NSArray*)buildPlayerSeekStepParams:(NSString*)stepmode{
    NSArray *params = nil;
    if ([AppDelegate instance].serverVersion < 15){
        params = @[stepmode, @"value"];
    } else
    {
        params = @[ @{@"step": stepmode}, @"value"];
    }
    return params;
}
```

This way the other `Player.Seek` parameter builds reduce to 
`params = [Utilities buildPlayerSeekStepParams:@"smallforward"];` and 
`params = [Utilities buildPlayerSeekStepParams:@"smallbackward"];`

In this case I would declare and implement both `buildPlayerSeekStepParams` and `buildPlayerSeekPercentageParams` in Utilities.h/.m which seem to fit for such implementation.

2021-01-05 17:13 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +        [self SimpleAction:@"Player.Seek" params:dict3 reloadPlaylist:NO startProgressBar:YES];
Reworked, squashes and force-pushed latest and greatest. If you still want to have meremoving the local variables, I will do this.

2021-01-06 10:38 UTC, kambala-decapitator requested changes

2021-01-06 10:38 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    NSDictionary *params = @{};
either assign `nil` or don't assign anything at all (in ARC mode `nil` is assigned to objects implicitly)

2021-01-06 10:39 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +        [self SimpleAction:@"Player.Seek" params:dict3 reloadPlaylist:NO startProgressBar:YES];
- not insisting on removing local variable, although in this case I'd remove it :)
- this is fine, just see last minor point below

2021-01-06 11:06 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    NSDictionary *params = @{};
Done and force-pushed.

2021-01-06 11:10 UTC, kambala-decapitator approved these changes
LGTM

2021-01-06 11:11 UTC, merged