Feature: Blurred cover for iPad
xbmc/Official-Kodi-Remote-iOS pull request #1053
Opened 2024-04-28 13:39 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/1039.

This PR implements the "blurred cover" feature for iPad. If this feature is enabled (this is the app's default) and no cover is present, or if this feature is disabled, the background shows the fanart. In fullscreen mode the toolbar is made semi-transparent for an improved look.

Screenshots: https://ibb.co/7r9hYC1

## Summary for release notes

Feature: Blurred cover for iPad

2024-05-10 10:28 UTC, kambala-decapitator requested changes

2024-05-10 10:28 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +@synthesize toolbarBackground;
please drop all these ancient `@synthesize`, can be done in a separate PR

2024-05-10 10:28 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +        [[NSNotificationCenter defaultCenter] postNotificationName:@"IpadChangeBackgroundImage" object:coverImage userInfo:params];
better send `coverImage` in `userInfo`

2024-05-10 10:28 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +    fanartBackgroundImage = [[UIImageView alloc] initWithFrame:self.view.frame];
- the comment sounds quite obvious
- subviews should use `bounds` of superview, not `frame` (same for the others below)

2024-05-10 10:28 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +    UIVisualEffect *blurEffect = [UIBlurEffect effectWithStyle:UIBlurEffectStyleDark];
please swap these 2 lines - will be easier to read. Or you could also avoid `blurEffect` variable completely.

2024-05-10 10:28 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +        visualEffectView.alpha = 1;
- why using alpha instead of hidden?
- is there any performance drawback when visual effect is present but with alpha = 0?

2024-05-10 15:36 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +@synthesize toolbarBackground;
Ok, can do this in the coding style PR I am working on. What is the modern and right way to do this?

2024-05-10 15:39 UTC, wutschel commented on XBMC Remote/ViewControllerIPad.m
> +    fanartBackgroundImage = [[UIImageView alloc] initWithFrame:self.view.frame];
Well, all the comments -- also in the following blocks -- are quite obvious. I thought it is a good practice to do this. Shall I rather remove them all? 

Second, I shall then use `bounds` for the following subview as well, right?

2024-05-10 15:43 UTC, wutschel commented on XBMC Remote/ViewControllerIPad.m
> +    UIVisualEffect *blurEffect = [UIBlurEffect effectWithStyle:UIBlurEffectStyleDark];
Agreed, will remove `blurEffect` variable.

2024-05-10 16:01 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +        [[NSNotificationCenter defaultCenter] postNotificationName:@"IpadChangeBackgroundImage" object:coverImage userInfo:params];
Done, and looks more straight forward now.

2024-05-10 16:01 UTC, wutschel commented on XBMC Remote/ViewControllerIPad.m
> +        visualEffectView.alpha = 1;
Tested and works well. Will use `hidden`. Thanks for pointing me to it.

2024-05-11 07:21 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +@synthesize toolbarBackground;
compiler synthesises implicitly to an underscored property name. But it's better to use properties by default, direct ivar access should be limited only to specific cases (e.g. when you don't want KVO to trigger).

2024-05-11 07:24 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +    fanartBackgroundImage = [[UIImageView alloc] initWithFrame:self.view.frame];
- obvious comments aren't useful :)
```
// add 1 to i
++i;
```

- correct

2024-05-11 07:27 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +            @"cover": coverImage ?: [UIImage new],
not sure why you're setting `[UIImage new]` - you could just add `@"cover"` key conditionally

2024-05-11 08:02 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +@synthesize toolbarBackground;
ok, I will search a bit on how to do this properly and trust in your support :)

2024-05-11 08:04 UTC, wutschel commented on XBMC Remote/ViewControllerIPad.m
> +    fanartBackgroundImage = [[UIImageView alloc] initWithFrame:self.view.frame];
:)

Removed comments now.

2024-05-11 08:14 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +            @"cover": coverImage ?: [UIImage new],
I hope using `dictionaryWithObjectsAndKeys` is also fine for you.

2024-05-11 08:15 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +@synthesize toolbarBackground;
you'd simply use `self.toolbarBackground` instead of `toolbarBackground`

2024-05-11 08:17 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +            @"cover": coverImage ?: [UIImage new],
yes, also good

2024-05-11 08:17 UTC, kambala-decapitator approved these changes

2024-05-11 08:25 UTC, wutschel commented
Squashed and rebased to master.

2024-05-11 08:29 UTC, merged