Fix bottom padding for iPads without Home button
xbmc/Official-Kodi-Remote-iOS pull request #106
Opened 2021-01-02 13:08 UTC by wutschel

The newer iPads without Home button need some special treatment for the DetailViewController´s button toolbar and the StackViewController views. With this change both types of iPads (with and without Home button) will show the bar and views properly, including rotation.

2021-01-02 13:19 UTC, wutschel commented
@kambala-decapitator, could you take a look at this? This will make the newer iPads well usable.

2021-01-05 11:10 UTC, kambala-decapitator requested changes

2021-01-05 11:10 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            CGRect frame;
not clear why you're declaring a new variable

2021-01-05 11:10 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +        bottomPadding = window.safeAreaInsets.bottom;
why not reading insets directly from `self.view`?

2021-01-05 11:10 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +    if (bottomPadding > 0) {
I think it makes sense to move this inside `if (@available(iOS 11.0, *)) {`

2021-01-05 11:10 UTC, kambala-decapitator commented on XBMC Remote/iPad/StackScrollViewController.m
> +            bottomPadding = window.safeAreaInsets.bottom;
why not reading insets directly from `self.view`?

2021-01-05 11:28 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            CGRect frame;
True, will remove this.

2021-01-05 11:49 UTC, wutschel commented on XBMC Remote/ViewControllerIPad.m
> +        bottomPadding = window.safeAreaInsets.bottom;
I took the code snippet from other controllers where this was implemented the same way. Problem seems to be that reading the insets from `self.view` will result in 0 when called in `viewDidLoad()` where the variable `bottomPadding` will be needed (see [stackoverflow](https://stackoverflow.com/questions/47032855/safeareainsets-in-uiview-is-0-on-an-iphone-x)).

2021-01-05 11:50 UTC, wutschel commented on XBMC Remote/iPad/StackScrollViewController.m
> +            bottomPadding = window.safeAreaInsets.bottom;
Same as above (returns 0 in `viewDidLoad()`).

2021-01-05 11:53 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +        bottomPadding = window.safeAreaInsets.bottom;
oh yes, you're absolutely right. Have been working purely with constraints for a long time :)

2021-01-05 11:53 UTC, wutschel commented on XBMC Remote/iPad/StackScrollViewController.m
> +            bottomPadding = window.safeAreaInsets.bottom;
Same as above, returns 0 when called in `init()`.

2021-01-05 11:56 UTC, wutschel commented on XBMC Remote/ViewControllerIPad.m
> +    if (bottomPadding > 0) {
We could, but this would be inconsistent as we later use the variable `bottomPadding` in many other places without the condition (and I would like to keep it like this for readability). Otherwise we introduce a lot of conditions, even though the variable is cleanly set to 0.

2021-01-05 11:57 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +    if (bottomPadding > 0) {
valid point!

2021-01-05 12:19 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            CGRect frame;
Fixed, squashed and force pushed.

2021-01-06 11:13 UTC, kambala-decapitator approved these changes

2021-01-06 11:13 UTC, merged