Feature: Queue and Play a season via longpress menu
xbmc/Official-Kodi-Remote-iOS pull request #1107
Opened 2024-08-15 17:56 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/399.

This PR implements a longpress menu for seasons which allows to queue after current, queue and play a whole season.

## Summary for release notes

Feature: Queue and Play a season via longpress menu

2024-09-13 20:34 UTC, kambala-decapitator requested changes
some comments are obsolete as I was looking commit by commit

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        NSIndexPath *indexPath = [NSIndexPath indexPathForItem:0 inSection:section];
if you're working with UITableView, correct method is `indexPathForRow`

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    if (sender.state == UIGestureRecognizerStateBegan) {
early return please

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            NSString *title = [NSString stringWithFormat:@"%@", item[@"genre"]];
is `item[@"genre"]` not a string?

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            UIView *showfromview = nil;
why not camelCase?

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    if (processAllItemsInSection) {
just use -1 as "unavailable" and no need to use NSNumber then

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                else if (processAllItemsInSection) {
and here as well

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                    NSMutableArray *listedItems = [NSMutableArray new];
set capacity to countRows

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                    playlistItems = [NSMutableArray new];
set capacity to value.count

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                NSDictionary *playlistParams = [NSDictionary dictionaryWithObjectsAndKeys:
use dictionary literal

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    else if (processAllItemsInSection) {
and here

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        NSMutableArray *listedItems = [NSMutableArray new];
capacity

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            id singleItem = (NSMutableDictionary*)[self getItemFromIndexPath:indexPath];
why are you casting and setting to `id`?

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        playlistItems = [NSMutableArray new];
capacity

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    NSDictionary *playlistParams = [NSDictionary dictionaryWithObjectsAndKeys:
literal

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    else if (processAllItemsInSection) {
and here

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        NSMutableArray *listedItems = [NSMutableArray new];
capacity

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            id singleItem = (NSMutableDictionary*)[self getItemFromIndexPath:indexPath];
strange cast

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        playlistItems = [NSMutableArray new];
capacity

2024-09-13 20:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            if ([item[@"family"] isEqualToString:@"episodeid"]) {
will there be no actions otherwise? or these are additional ones?

2024-09-14 10:13 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        NSIndexPath *indexPath = [NSIndexPath indexPathForItem:0 inSection:section];
True, changed it.

2024-09-14 10:13 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    if (sender.state == UIGestureRecognizerStateBegan) {
Similar like in other review. Done like this everywhere in the code, let's stay consistent.

2024-09-14 10:15 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            NSString *title = [NSString stringWithFormat:@"%@", item[@"genre"]];
It should, but it is not guaranteed. I changed this to `[Utilities getStringFromItem:item[@"genre"]]`, which is  an even better solution.

2024-09-14 10:20 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            UIView *showfromview = nil;
copy-pasted (and tailored) and from another place. Changed both.

2024-09-14 10:27 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    if (processAllItemsInSection) {
Is using `NSNumber` here causing any trouble?

2024-09-14 10:58 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                    playlistItems = [NSMutableArray new];
Done

2024-09-14 10:59 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        playlistItems = [NSMutableArray new];
Are you, if do this only once and for the last commit which unifies the code and introduces `buildPlaylistItems`?

2024-09-14 12:28 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    if (processAllItemsInSection) {
doesn't give much value in this case. We can leave it as is, not insisting on changing.

2024-09-14 12:29 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        playlistItems = [NSMutableArray new];
> Are you, if do this only once and for the last commit which unifies the code and introduces `buildPlaylistItems`?

sure, that's fine

2024-09-14 12:56 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            id singleItem = (NSMutableDictionary*)[self getItemFromIndexPath:indexPath];
Changed this to directly use `NSDictionary`. Must have been a remnant from playing with this feature initially.

2024-09-14 12:56 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                NSDictionary *playlistParams = [NSDictionary dictionaryWithObjectsAndKeys:
Done. Also added a commit changing this at another place (AddQueue).

2024-09-14 12:56 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        playlistItems = [NSMutableArray new];
Done

2024-09-14 12:56 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    NSDictionary *playlistParams = [NSDictionary dictionaryWithObjectsAndKeys:
Done

2024-09-14 13:01 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            if ([item[@"family"] isEqualToString:@"episodeid"]) {
Nope, just not changed after initially re-using some existing code. Thanks for pointing me to this again.

2024-09-14 13:06 UTC, kambala-decapitator approved these changes

2024-09-14 13:37 UTC, wutschel commented
Nicely squashed and rebased.

2024-09-14 14:16 UTC, merged