Fix scaling for iPhones
xbmc/Official-Kodi-Remote-iOS pull request #112
Opened 2021-01-10 12:55 UTC by wutschel

This fixes issue https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/111.

Details already given in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/99#issuecomment-757415645:

> Still not checked for all screens and view modes. It is hard to see what exactly was calculated to get those hard coded numbers. In general the code on master tries to use different scaling factors for several items (e.g. thumbviews, the remote or the volume slider). There are three families of scaling factors which reflect the three different x-axis resolutions at the time when the last changes were done, the fourth one (e.g. iPhone 12) was not taken into account. As the factors are not 100% identical for each family (like 1.29, 1.294 and 1.31) I think there was some manual tweaking done in some places, possibly to handle the effect of separators.
Also, I doubt that all of the code is still active. In some places I could mess around with the scaling and the thumbviews and remote still looked fine.

This PR implement a centralized macro/define which calculates the transform/scaling factor from the current screen width. This factor is now applied instead of hard coded values. The macros should support future screen sizes as well.

Test were done on simulator with
- iPhone 12 Pro Max (width = 428)
- iPhone 11 Pro Max (width = 414)
- iPhone Xs (width = 375)
- iPod Touch (width = 320) and 
- iPad 8G (only to double check if regressions are seen for non-iPhone devices).

As I am mainly using Music it would be good to have some tests specifically with Movies and TV Shows.

2021-01-10 17:44 UTC, kambala-decapitator requested changes
Runtime test ok.

General code request: avoid using `float` (and `f` suffix in literals) when dealing with `CGFloat` values - on 64-bit devices (i.e. anything modern) it's resolved to `double`.

2021-01-10 17:44 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    CGFloat center_y = frame.origin.y + frame.size.height/2;
there're `CGRectGetMid...` functions ;)

2021-01-10 17:44 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        // All devices with width >= 414
I'd write it the other way around to have less comparisons: first check for `transform >= 1.29`, then for `transform > 1.0`

2021-01-10 17:44 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        [remoteControlView setFrame:CGRectMake(frame.origin.x, frame.origin.y, frame.size.width* 1.05, frame.size.height* 1.05)];
not clear what this magic multiplier means

2021-01-10 17:57 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        [remoteControlView setFrame:CGRectMake(frame.origin.x, frame.origin.y, frame.size.width* 1.05, frame.size.height* 1.05)];
It was there before, with a different value. This is just scaling the image a bit further to maximize the screen usage. If you do not apply this "hand tailored" magic number, there is more unused spaced around the remote image.

2021-01-10 18:01 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        // All devices with width >= 414
Good point, done with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/112/commits/fe4e56b5273e4a840d4391813a6060f0ac631854.

2021-01-10 18:15 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        [remoteControlView setFrame:CGRectMake(frame.origin.x, frame.origin.y, frame.size.width* 1.05, frame.size.height* 1.05)];
let's give it an understandable identifier then

2021-01-10 18:29 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        [remoteControlView setFrame:CGRectMake(frame.origin.x, frame.origin.y, frame.size.width* 1.05, frame.size.height* 1.05)];
Here we go: https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/112/commits/08114497235e9127e6676b3d9fce4f6ba049289c.

2021-01-10 18:35 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    CGFloat center_y = frame.origin.y + frame.size.height/2;
Nice :) -> https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/112/commits/9534a507798c9dea76578b635a38c6f646b1a8b0

2021-01-10 19:11 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    frame.origin.y = CGRectGetMidY(frame)*transform_y - frame.size.height/2;
at this point `frame` is already larger than the original, is it correct to get center after the transformation?

2021-01-10 19:46 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    frame.origin.y = CGRectGetMidY(frame)*transform_y - frame.size.height/2;
Sorry, I was moving too quick with this change. Fixed this with the latest force-push.

2021-01-11 16:35 UTC, kambala-decapitator commented
@wutschel 

> General code request: avoid using `float` (and `f` suffix in literals) when dealing with `CGFloat` values - on 64-bit devices (i.e. anything modern) it's resolved to `double`.

will you fix this in the PR or merge as is and you'll fix it globally in a separate PR?

2021-01-11 16:59 UTC, wutschel commented
> will you fix this in your new code in the PR or merge as is and you'll fix it globally in a separate PR?

I am not 100% sure I understand the change you ask for. How shall I avoid this case for example when scaling a CGFloat?

Example: 
```
float transform = 1.05f;
frame.size.height = frame.size.height * transform;
frame.size.width = frame.size.width * 1.10f;
```

Is the expectation to cast this back and forth like this?
```
float transform = 1.05f;
frame.size.height = (CGFloat)((int)frame.size.height * transform);
frame.size.width = (CGFloat)((int)frame.size.width * 1.10f);
```

In general I think such rework is worth a dedicated set of commits which can be done after all the relevant functional changes went in.

2021-01-11 17:05 UTC, kambala-decapitator commented
no, expectation is that you don't use `float` type unless necessary. Treat `CGFloat` as `double`:
```objc
CGFloat transform = 1.05;
frame.size.height = frame.size.height * transform;
frame.size.width = frame.size.width * 1.10;
```

2021-01-11 17:35 UTC, wutschel commented
Hope this is what you were searching for.

In fact, there are dozens of places where the current code uses `float` and `f` in combination with `CGFloat`. Especially in direct assignments and in lots of `CGRectMake`() calls.

2021-01-11 17:36 UTC, kambala-decapitator requested changes

2021-01-11 17:36 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
>      float transform = GET_TRANSFORM_X;
missed this one ;)

2021-01-11 17:37 UTC, kambala-decapitator commented
thanks!

> In fact, there are dozens of places where the current code uses `float` and `f` in combination with `CGFloat`. Especially in direct assignments and in lots of `CGRectMake`() calls.

yes, true, but let's not add even more such code :) This can be fixed in a separate cleanup PR.

2021-01-11 17:38 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
>      float transform = GET_TRANSFORM_X;
This is just used for multiplication with an `int`.

2021-01-11 17:48 UTC, wutschel commented
> yes, true, but let's not add even more such code :) This can be fixed in a separate cleanup PR.

Agreed.

2021-01-11 18:38 UTC, merged