Improvement: Update progress and recording indicators for Live TV and Radio
xbmc/Official-Kodi-Remote-iOS pull request #1220
Opened 2024-12-27 18:26 UTC by wutschel

## Description

This PR modernizes the way of visualizing a broadcast's progress and recording state. The current pie chart and its runtime label are hard to read. The recording icon shown in the middle of the pie chart is not recognizable well in channel list view. To improve this, a new class `ProgressBarView` is introduced, the formerly used `ProgressPieView` is removed.

#### Horizontal Progress Bar
The new visualization uses a horizontal progress bar, which is placed on the left side and uses the same width as the thumbnail or label under which it is placed. The progress bar has a dark gray background and uses Kodi blue to show the progress. 

#### Runtime and Recording State
Total runtime is located right aligned under the progress bar. The recording indicator is located in a reserved area left of the runtime.

#### EPG
In the EPG the highlighting of the current active broadcast is done by changing the cell background and letting the start time label use a bigger font size and label color.

#### Impression
Screenshots (left pair = new, right pair = old):
https://ibb.co/zmXZ1FY

## Summary for release notes

Improvement: Update progress and recording indicators for Live TV and Radio

2025-01-11 10:42 UTC, kambala-decapitator requested changes

2025-01-11 10:42 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    timerView.center = progressView.reservedArea.center;
using `center` of superview is usually incorrect

2025-01-11 10:42 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.h
> +#define ProgressBarView_h
objc headers don't need include guards. When creating new class, choose New Class rather than New Header.

2025-01-11 10:42 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +#import <Foundation/Foundation.h>
prefer modules: `@import Foundation;`

2025-01-11 10:42 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = CGRectMake(0, 0, 0, PROGRESSBAR_HEIGHT);
subview layout should be done in `- (void)layoutSubviews`, in user code you'd set view's frame directly

2025-01-11 10:42 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +    progressBar = [UIView new];
there's a real progress bar component, you know :) `UIProgressBar`

2025-01-11 15:27 UTC, wutschel commented on XBMC Remote/ProgressBarView.h
> +#define ProgressBarView_h
Ok, done and noted for next new class.

2025-01-11 16:10 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    timerView.center = progressView.reservedArea.center;
Hmm, interesting. In the code above the frames are still `CGRectZero`. So, placing the subview in parent's center does not have any effect. Later, the frames are set and the recording image is placed in the center of its parent automatically, I guess due the `autoresizingMask` in use. Should I just remove the assignment of center?

2025-01-11 16:22 UTC, wutschel commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = CGRectMake(0, 0, 0, PROGRESSBAR_HEIGHT);
Second nice learning from this PR review. 👍

2025-01-11 17:29 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +#import <Foundation/Foundation.h>
it's not really about consistency: it should be preferred to write new code in a better way.

I'd rather drop this include completely, as it doesn't really serve much purpose. If you want to write properly, the header must have `@import UIKit;` (because you inherit from a UIKit class) and also CoreGraphics must be imported there (because you use CG types that are not pointers). And UIKit already imports Foundation.

2025-01-11 17:30 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +    CGRect frame = self.frame;
iirc super must be called, please check in docs

2025-01-11 17:32 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    timerView.center = progressView.reservedArea.center;
yes, sounds right

2025-01-11 17:36 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    timerView.center = progressView.reservedArea.center;
btw to center in a superview, you could extend UIView with the following method (requires creating a **category**):
```objc
@implementation UIView (Positioning)
- (void)centerInSuperview {
  if (!self.superview) return;
  __auto_type superviewSize = self.superview.bounds.size;
  self.center = CGPointMake(size.width / 2, size.height / 2);
}
@end

// usage
UIView* someView; // could be any subclass
[someView centerInSuperview];
```

2025-01-11 17:57 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    timerView.center = progressView.reservedArea.center;
Got it, thanks.

2025-01-11 18:04 UTC, wutschel commented on XBMC Remote/ProgressBarView.m
> +#import <Foundation/Foundation.h>
Ok then. Is there a best practice where to place this, before or after other `#import` lines?

As I like to have consistency, should I attempt to do this for "our" (not the OpenSource parts) code as well as a part of a future coding styles PR?

2025-01-11 18:05 UTC, wutschel commented on XBMC Remote/ProgressBarView.m
> +    CGRect frame = self.frame;
Done, thanks for highlighting.

2025-01-11 18:47 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +#import <Foundation/Foundation.h>
I stick to the following rule: first import project's (actually target's) own imports, then import externals (other targets, 3rd parties) and import system modules last

2025-01-11 18:59 UTC, wutschel commented on XBMC Remote/ProgressBarView.m
> +#import <Foundation/Foundation.h>
Ok

2025-01-11 19:58 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +@import UIKit;
it should be in the header :)

2025-01-11 21:03 UTC, wutschel commented on XBMC Remote/ProgressBarView.m
> +@import UIKit;
Done

2025-01-12 06:43 UTC, kambala-decapitator approved these changes

2025-01-12 09:31 UTC, wutschel commented
Renamed new class to `BroadcastProgressView` to better match its purpose.

2025-01-12 10:02 UTC, kambala-decapitator approved these changes

2025-01-12 13:05 UTC, wutschel commented
Refactored this by introducing new class `ProgressBarView` which is then used by `BroadcastProgressView`. In a second step `ProgressBarView` can be used when rebasing and updating #1226. Does this look good?

2025-01-12 22:58 UTC, wutschel commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = CGRectMake(0, 0, 0, PROGRESSBAR_HEIGHT);
Need your help. Just understood that `layoutSubviews` is called after `cellForRowAtIndexPath`, which is where I already call `ProgressBarView`'s `setProgress` in some cases (broadcast of channels, or later for playlist items). Is the right way to handle this to add an ivar `progress` to `ProgressBarView` and let `layoutSubviews` also use it to draw the correct progress bar width?

2025-01-13 08:58 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                BOOL isRecording = [item[@"hastimer"] boolValue] || [item[@"isrecording"] boolValue];
please create a function instead of copy pasting

2025-01-13 08:59 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = CGRectMake(0, 0, 0, PROGRESSBAR_HEIGHT);
yes, progress property is the right way and then reading it in layoutSubviews

2025-01-13 09:00 UTC, kambala-decapitator commented
> Refactored this by introducing new class `ProgressBarView` which is then used by `BroadcastProgressView`. In a second step `ProgressBarView` can be used when rebasing and updating #1226. Does this look good?

sounds good

2025-01-13 11:04 UTC, wutschel commented
> > Refactored this by introducing new class `ProgressBarView` which is then used by `BroadcastProgressView`. In a second step `ProgressBarView` can be used when rebasing and updating #1226. Does this look good?
> 
> sounds good

It really paid off to not just do a minimal intrusive change as I started from, but re-implement some parts from scratch.

2025-01-13 11:33 UTC, kambala-decapitator commented on XBMC Remote/BroadcastProgressView.h
> +@interface BroadcastProgressView : UIView {
you could simply inherit from ProgressBarView

2025-01-13 11:43 UTC, wutschel commented on XBMC Remote/BroadcastProgressView.h
> +@interface BroadcastProgressView : UIView {
This screws up the layout. Must be connected to the layout methods and the changed hierarchy.

2025-01-14 07:05 UTC, kambala-decapitator commented on XBMC Remote/BroadcastProgressView.h
> +#import "ProgressBarView.h"
FYI since you only use pointer in header, it's better to use forward declaration `@class ProgressBarView;` and move include to the implementation file.

2025-01-14 07:10 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +    progress = newProgress;
Normally you'd perform work only if new value is different from the previous one, but in this case it's OK to ignore this approach

2025-01-14 07:13 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = frame;
Instead of doing it manually, you could simply call `[self setNeedsLayout]` to let the system know that you want to re-lay out your view

2025-01-14 08:58 UTC, wutschel commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = frame;
Understood. But to my understanding it would conflict with the way I plan to use it for the playlist progress bar:

```
- (void)setProgress:(CGFloat)progress {
    if (progressBarView.progress == 0 && progress > 0) {
        [UIView animateWithDuration:0.5
                         animations:^{
            progressBarView.progress = progress;
        }];
    }
    else {
        progressBarView.progress = progress;
    }
}
```

2025-01-14 08:59 UTC, wutschel commented on XBMC Remote/ProgressBarView.m
> +    progress = newProgress;
Ok, will keep it like this.

2025-01-14 09:03 UTC, wutschel commented on XBMC Remote/BroadcastProgressView.h
> +#import "ProgressBarView.h"
Done

2025-01-14 09:41 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = frame;
not sure how it conflicts. The code you posted would go into BroadcastProgressView, and the comment is about ProgressBarView.

2025-01-14 10:22 UTC, wutschel commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = frame;
Yes, this code goes into the caller's `setProgress` method. But if `progressBarView.progress` just triggers `setNeedsLayout` it does not animate the progress bar anymore. Also confirmed by testing it.

2025-01-14 11:29 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = frame;
oh yes, you're absolutely right. You could try inserting `layoutIfNeeded` call inside the animation block.

otherwise, just extract obtaining new bar width according to the percentage param into a function.

2025-01-14 14:52 UTC, wutschel commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = frame;
Why not keep it like it is? The above code sequence with the animation is quite straight forward. Is the main reason to avoid code duplication of `progress * CGRectGetWidth(self.frame)` in `setProgress` and `layoutSubviews`? This  (or the whole frame definition) could of course be moved into a helper method

2025-01-14 16:26 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = frame;
It's a more proper way to handle custom view updates. View has some state (which the view depends on of course) and you have a way to describe how view looks in any state, the rest is done by the system.

BTW that's basically how SwiftUI (or any other declarative ui framework) works. Although in UIKit we have to give hints that we want a re-render ASAP.

Not enforcing such solution, but I suggest that you try it at least.

2025-01-14 18:51 UTC, wutschel commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = frame;
> oh yes, you're absolutely right. You could try inserting `layoutIfNeeded` call inside the animation block.

This works (`layoutIfNeeded` in animation block and at the same time `setNeedsLayout` in `setProgress`). Will add another fixup commit to use `setNeedsLayout`. `layoutIfNeeded` will be added in https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1226.

2025-01-14 19:57 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = frame;
btw an improvement over your `setProgress:` API of `progressBarView` would be adding `animated` boolean parameter (similar to the system APIs) - this way you can hide these details including calling layoutIfNeeded / setNeedsLayout

2025-01-14 20:04 UTC, wutschel commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = frame;
Initially, I did something similar, but I dropped it as only used for the playlist progress bar.

2025-01-14 20:30 UTC, wutschel commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = frame;
Overall sounds like the code is good enough to go. Ok for you if I now squash all of the fixups to have proper commits?

2025-01-16 08:23 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = frame;
Could you point to the animation code? I don't think I see it in the total diff

2025-01-16 08:55 UTC, wutschel commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = frame;
This will only come with #1226 as part of a new class which handles the playlist progress bar. Looks like this:

```
- (void)setProgress:(CGFloat)progress {
    if (progressBarView.progress == 0 && progress > 0) {
        [UIView animateWithDuration:0.5
                         animations:^{
            progressBarView.progress = progress;
            [self layoutIfNeeded];
        }];
    }
    else {
        progressBarView.progress = progress;
    }
}
```

2025-01-16 09:16 UTC, kambala-decapitator commented on XBMC Remote/ProgressBarView.m
> +    progressBar.frame = frame;
ah, that's in the other PR, thanks a lot!

2025-01-16 09:16 UTC, merged