More code cleanup
xbmc/Official-Kodi-Remote-iOS pull request #124
Opened 2021-01-12 16:46 UTC by wutschel

Based on an ask from @kambala-decapitator I looked into the changes from his local branch [xcode11](https://github.com/kambala-decapitator/Official-Kodi-Remote-iOS/tree/xcode11) and brought those changes into a series of commits which were not yet merged to master as part of the latest updates.

Changes:
- Enable warning for overwriting deprecated functions
- Replace `didReceiveAuthenticationChallenge` with `willSendRequestForAuthenticationChallenge`
- Remove deprecated `viewDidUnload` and ensure all cleanups are moved to `dealloc`
- Remove deprecated `shouldAutorotateToInterfaceOrientation`
- Rework declarations of `supportedInterfaceOrientations`
- Remove pre-iOS 8 screen size retrieval

2021-01-13 10:15 UTC, kambala-decapitator requested changes
as part of this PR, please also review usage of `SYSTEM_VERSION_*` macros and remove everything that no longer makes sense (min version is 9.0 now).

I also suggest to replace it entirely with `NSProcessInfo.processInfo.operatingSystemVersion` checks.

2021-01-13 10:15 UTC, kambala-decapitator commented on XBMC Remote/AppInfoViewController.m
> +- (void)dealloc {
what's the point of this? All fields are `nil`'d automatically in `dealloc`. (same question to changes below)

2021-01-13 10:15 UTC, kambala-decapitator commented on XBMC Remote/PlayFileViewController.m
> +     return UIInterfaceOrientationMaskPortrait;
remove extra space

2021-01-13 19:14 UTC, wutschel commented on XBMC Remote/AppInfoViewController.m
> +- (void)dealloc {
Are you ok to let me do this with one commit on top of the other commits? This way I can easily remove also all the other assignments to `nil` in `dealloc`.

2021-01-13 19:40 UTC, wutschel commented
> as part of this PR, please also review usage of `SYSTEM_VERSION_*` macros and remove everything that no longer makes sense (min version is 9.0 now).
> 
> I also suggest to replace them entirely with `NSProcessInfo.processInfo.operatingSystemVersion` checks.

What about using `@available(iOS $VERSION, *)` instead, and removing the `SYSTEM_VERSION_*` macros?

2021-01-13 20:10 UTC, wutschel commented on XBMC Remote/AppInfoViewController.m
> +- (void)dealloc {
There are two checks for `LESS_THAN(X)` where I would replace with something like

```
if (@available(iOS 11.0, *)) {
    // nothing to do
}
else {
    assignment;
}
```

2021-01-13 20:10 UTC, wutschel commented on XBMC Remote/PlayFileViewController.m
> +     return UIInterfaceOrientationMaskPortrait;
Sure, will be done.

2021-01-13 20:27 UTC, kambala-decapitator commented on XBMC Remote/AppInfoViewController.m
> +- (void)dealloc {
yes please

2021-01-13 20:29 UTC, kambala-decapitator commented
`@available` makes API check (i.e. when you call a method that exists only in a higher version than the deployment one), it's not suitable for general OS version check IMO.

2021-01-13 20:34 UTC, wutschel commented on XBMC Remote/AppInfoViewController.m
> +- (void)dealloc {
Will do this with next update.

2021-01-13 21:19 UTC, wutschel commented
> `@available` makes API check (i.e. when you call a method that exists only in a higher version than the deployment one), it's not suitable for general OS version check IMO.

I searched and found in several sites (e.g. [stackoverflow](https://stackoverflow.max-everyday.com/2018/05/how-can-we-programmatically-detect-which-ios-version-is-device-running-on/)) that since XCode 9 `@available` will work. I tested on simulator and can confirm the runtime check of the iOS version works as intended.

2021-01-13 21:32 UTC, wutschel commented
Added the cleanup for `dealloc`, reworked the iOS version checks and rebased to master.

2021-01-14 07:58 UTC, kambala-decapitator commented
> > `@available` makes API check (i.e. when you call a method that exists only in a higher version than the deployment one), it's not suitable for general OS version check IMO.
> 
> I searched and found in several sites (e.g. [stackoverflow](https://stackoverflow.max-everyday.com/2018/05/how-can-we-programmatically-detect-which-ios-version-is-device-running-on/)) that since XCode 9 `@available` will work. I tested on simulator and can confirm the runtime check of the iOS version works as intended.

I know that it works, I just don't find it correct to use in a case when you simply want to check OS version. And in the "less" case it just looks ugly with empty `if` body.

2021-01-14 11:33 UTC, wutschel commented
> I know that it works, I just don't find it correct to use in a case when you simply want to check OS version. And in the "less" case it just looks ugly with empty `if` body.

Well, I personally found the consistent use of the `@available` macros quite nice, with the exception of the empty `if` bodies. I now undid all of this and only removed the obsolete version checks.

2021-01-15 18:40 UTC, kambala-decapitator commented
thanks!

2021-01-15 18:40 UTC, merged