Fix message position for iPhones in settings menu
xbmc/Official-Kodi-Remote-iOS pull request #126
Opened 2021-01-14 06:34 UTC by wutschel

Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/125.

Since 7a67e37 (set modal presentation style to fullscreen ...) messages are displayed at the wrong vertical position in the `SettingsValuesViewController`, e.g. when adding buttons manually. This PR uses `safeAreaInsets` to gather the correct offset for iPhones, and keeps using the former hardcoded value otherwise.

2021-01-15 20:55 UTC, kambala-decapitator requested changes

2021-01-15 20:55 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
> +        CGFloat deltaY = 44.0f;
don't use `f` suffix

2021-01-15 20:55 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
> +                deltaY += 20;
if `20` means status bar height, please use `CGRectGetHeight(UIApplication.sharedApplication.statusBarFrame)`

2021-01-15 20:56 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
> +        CGFloat deltaY = 44.0f;
btw what is `44`? Height of navigation bar?

2021-01-15 21:53 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
> +                deltaY += 20;
Your are right. In this case I can even remove the complete `if (@available ...) ... else ...` section and use `deltaY += CGRectGetHeight(UIApplication.sharedApplication.statusBarFrame);`

2021-01-15 22:08 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
> +        CGFloat deltaY = 44.0f;
It should be, but I `self.navigationController` is `nil`. What would be the correct solution to read the navigationbar´s height?

2021-01-16 08:34 UTC, wutschel commented
Removed the `float` suffix and simplified the code as suggested. Still not having a good solution to read the height of `navigationBar`.

2021-01-16 08:53 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
> +        CGFloat deltaY = 44.0f;
because in `init` it's too early, try getting the value in `viewDidLoad` or `viewDidLayoutSubviews`

2021-01-16 08:54 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
> +                deltaY += 20;
I think the best would actually be `CGRectGetMaxY(self.navigationcontroller.navigationBar.frame)` (merging with the above)

2021-01-16 09:24 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
> +                deltaY += 20;
Got it. I get the navigationController when used in `viewDidLayoutSubviews` (in `viewDidLoad` it is still `nil`). In this case I can move out the whole block which uses this height. Looks like this:

```
- (void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];
    CGFloat deltaY = CGRectGetMaxY(self.navigationController.navigationBar.frame);
    CGRect frame = [[UIScreen mainScreen ] bounds];
    if ([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPad){
        frame.size.width = STACKSCROLL_WIDTH;
        deltaY = 0;
    }
    
    messagesView = [[MessagesView alloc] initWithFrame:CGRectMake(0, 0, frame.size.width, deltaY + 42.0f) deltaY:deltaY deltaX:0];
    [self.view addSubview:messagesView];
}
```

There are so many magic numbers in the code ...

2021-01-16 09:31 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
> +                deltaY += 20;
See 19bbc64

2021-01-16 12:37 UTC, wutschel commented
When the latest open PRs should be accepted for merging I will look at the overall `CGFloat`/`float` mess. A good starting point will be code around calls of `CGRectMake` and `CGPointMake`.

2021-01-16 14:51 UTC, kambala-decapitator requested changes

2021-01-16 14:51 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
> +    [self.view addSubview:messagesView];
this is wrong: only set proper frame in this method, view should be created and added to the parent in `init`/`viewDidLoad`

2021-01-16 14:51 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
> +    CGFloat deltaY = CGRectGetMaxY(self.navigationController.navigationBar.frame);
why bother computing this for iPad if it's overwritten anyway?

2021-01-16 14:51 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
> +    CGRect frame = [[UIScreen mainScreen ] bounds];
please avoid extra spacing

2021-01-16 14:51 UTC, kambala-decapitator commented on XBMC Remote/RightMenuViewController.m
> +        self.peekLeftAmount = 0.0;
not sure why these changes are here: please add them to the float-fixing PR

2021-01-16 15:55 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +        self.peekLeftAmount = 0.0;
Will be removed with next update.

2021-01-16 15:59 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
> +    [self.view addSubview:messagesView];
I tried to find a good way to do this, and it is really frustrating as there is some logic inside the `initWithFrame:deltaY:deltaX` call which does not allow to easily set the correct frame afterwards. So, as I understand we cannot keep this like it is, I will go back to the old version which kept the magic "44.0". I really do not want to rewrite every tiny little thing just for this purpose.

2021-01-16 15:59 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
> +    CGFloat deltaY = CGRectGetMaxY(self.navigationController.navigationBar.frame);
see above comment, will roll this back

2021-01-16 16:00 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
> +    CGRect frame = [[UIScreen mainScreen ] bounds];
see above comment, will roll this back

2021-01-17 08:43 UTC, merged