Cleanup float
xbmc/Official-Kodi-Remote-iOS pull request #131
Opened 2021-01-17 18:58 UTC by wutschel

Major rework to use correct types instead of float.

- Covers `CGRectMake`, `CGPointMake`, `CGSizeMake`, `UIEdgeInstetsMake`, `minimumScaleFactor`, `cornerRadius`, `borderWidth`, `shadowRadius`, `alpha` and related variables and defines
- Use `NSTimeInterval` type variables and do not combine with `float` or `f` suffix
- Remove unused variable `storeBrightness`

2021-01-17 19:14 UTC, wutschel commented
@kambala-decapitator, thanks for merging the other PRs. Now I could prepare the `float`-rework. There are now only very few `float` or `f` suffixes left. The majority is related to `UIColor` definitions, which I want to resolve in a dedicated PR which will then also implement Dark Mode.

2021-01-23 13:21 UTC, kambala-decapitator requested changes
damn I made it

2021-01-23 13:21 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    cellGridHeight =  168;
please fix whitespace as well

2021-01-23 13:21 UTC, kambala-decapitator commented on XBMC Remote/HostViewController.m
> +- (void)AnimLabel:(UIView *)Lab AnimDuration:(NSTimeInterval)seconds Alpha:(CGFloat)alphavalue XPos:(int)X{
these animation methods look quite similar to those above, probably should be extracted to UIView category or some utility function

2021-01-23 13:21 UTC, kambala-decapitator commented on XBMC Remote/KenBurns/JBKenBurnsView.m
> +    CGFloat frameHeight   = isLandscape? self.frame.size.height : self.frame.size.width;
please add leading whitespace to `?` as well

2021-01-23 13:21 UTC, kambala-decapitator commented on XBMC Remote/KenBurns/JBKenBurnsView.m
> +    CGFloat rotation = (arc4random() % 9) / 100;
FYI `arc4random_uniform()` is preferred over `arc4random() % X`

2021-01-23 13:21 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +- (void)AnimTable:(UITableView *)tV AnimDuration:(NSTimeInterval)seconds Alpha:(CGFloat)alphavalue XPos:(int)X{
familiar animation again :)

2021-01-23 13:21 UTC, kambala-decapitator commented on XBMC Remote/PosterCell.m
> +        CGFloat labelHeight = (CGFloat)(frame.size.height * 0.19);
1. you've removed rounding down
2. actually I suggest to use rounding up instead

2021-01-23 13:21 UTC, kambala-decapitator commented on XBMC Remote/RightMenuViewController.m
> +        UIImageView *xbmc_logo = [[UIImageView alloc] initWithFrame:CGRectMake(self.view.bounds.size.width - 195, (int)((44/2) - (36/2)) - 2, 145, 36)];
I'm seeing this magical computation code for the second time ;)

2021-01-23 13:21 UTC, kambala-decapitator commented on XBMC Remote/SDWebImage/SDWebImageDownloaderOperation.m
> +                        CGContextDrawImage(bmContext, (CGRect){.origin.x = 0, .origin.y = 0, .size.width = self->width, .size.height = partialHeight}, partialImageRef);
please replace with `CGRectMake`

2021-01-23 13:21 UTC, kambala-decapitator commented on XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
>      if([[[UIDevice currentDevice] systemVersion]floatValue] >= 5){
we need to get rid of such useless things

2021-01-23 13:21 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
>      contextRect.size = [image size];
this is a good candidate for using `struct` initialiser :)

2021-01-23 13:21 UTC, kambala-decapitator commented on XBMC Remote/iPad/MenuViewController.m
> +            xbmc_logo. alpha = 0.25;
please fix whitespace as well

2021-01-23 13:21 UTC, kambala-decapitator commented on XBMC Remote/iPad/StackScrollViewController.m
> +    NSTimeInterval duration = [[[sender userInfo] valueForKey:@"duration"] floatValue];
1. use `doubleValue`
2. FYI generally `-valueForKey:` shouldn't be used to get dictionary value

2021-01-23 13:24 UTC, wutschel commented
> damn

:) Very much appreciated. Will walk through your comments now.

2021-01-23 14:33 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                                      CGFloat thumbBorder = isRetina ? 1.0/[[UIScreen mainScreen] scale] : 1.0;
Ok, what about `isRetinaHD`?

2021-01-23 14:56 UTC, wutschel commented on XBMC Remote/iPad/StackScrollViewController.m
> +    NSTimeInterval duration = [[[sender userInfo] valueForKey:@"duration"] floatValue];
Question: There are still several cases where `floatValue` is used. I understand the variable type is relevant for the output (= the variable type the value assigned to). Is this understanding correct?

2021-01-23 14:58 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        if (!cellMinimumLineSpacing) cellMinimumLineSpacing = 0;
Done with d4d0dd2.

2021-01-23 14:58 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                                      thumbImageContainer.layer.shadowOffset = CGSizeMake(0, 0);
Done with 1e3e046.

2021-01-23 14:59 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    cellGridHeight =  168;
Done with 1d8f4bc.

2021-01-23 14:59 UTC, wutschel commented on XBMC Remote/iPad/MenuViewController.m
> +            xbmc_logo. alpha = 0.25;
Done with 1d8f4bc.

2021-01-23 14:59 UTC, wutschel commented on XBMC Remote/Utilities.m
>      contextRect.size = [image size];
Done with abb8cee.

2021-01-23 15:00 UTC, wutschel commented on XBMC Remote/SDWebImage/SDWebImageDownloaderOperation.m
> +                        CGContextDrawImage(bmContext, (CGRect){.origin.x = 0, .origin.y = 0, .size.width = self->width, .size.height = partialHeight}, partialImageRef);
Done with dd2cc9b.

2021-01-23 15:04 UTC, wutschel commented on XBMC Remote/KenBurns/JBKenBurnsView.m
> +    CGFloat frameHeight   = isLandscape? self.frame.size.height : self.frame.size.width;
Done with 0555baf.

2021-01-23 15:06 UTC, wutschel commented on XBMC Remote/PosterCell.m
> +        CGFloat labelHeight = (CGFloat)(frame.size.height * 0.19);
Done with b794d5b.

2021-01-23 15:16 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +        UIImageView *xbmc_logo = [[UIImageView alloc] initWithFrame:CGRectMake(self.view.bounds.size.width - 195, (int)((44/2) - (36/2)) - 2, 145, 36)];
Oh, I see it even three times, with a minor deviation. Not sure if we really should change this until the magic numbers which are used are really clear (195, 193, 44, 36). Even though 44 and 36 I have good guesses ;)

2021-01-23 15:20 UTC, wutschel commented on XBMC Remote/KenBurns/JBKenBurnsView.m
> +    CGFloat rotation = (arc4random() % 9) / 100;
Done with ff72a45.

2021-01-23 15:21 UTC, wutschel commented on XBMC Remote/iPad/StackScrollViewController.m
> +    NSTimeInterval duration = [[[sender userInfo] valueForKey:@"duration"] floatValue];
For `NSTimeInterval` assignments done with 855e369.

2021-01-23 15:26 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +-(void)alphaImage:(UIImageView *)image AnimDuration:(NSTimeInterval)seconds Alpha:(CGFloat)alphavalue{
Agreed, but let us keep this out of this PR.

2021-01-23 15:27 UTC, wutschel commented on XBMC Remote/HostViewController.m
> +- (void)AnimLabel:(UIView *)Lab AnimDuration:(NSTimeInterval)seconds Alpha:(CGFloat)alphavalue XPos:(int)X{
Yes, same opinion here: separate PR.

2021-01-23 15:27 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +- (void)AnimTable:(UITableView *)tV AnimDuration:(NSTimeInterval)seconds Alpha:(CGFloat)alphavalue XPos:(int)X{
And again: separate PR.

2021-01-23 15:31 UTC, wutschel commented on XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
>      if([[[UIDevice currentDevice] systemVersion]floatValue] >= 5){
I have no idea what to do with this.

2021-01-23 15:52 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                                      CGFloat thumbBorder = isRetina ? 1.0/[[UIScreen mainScreen] scale] : 1.0;
looks pretty straightforward: just multiply size by `UIScreen.mainScreen.scale` and remove all conditions

2021-01-23 15:55 UTC, kambala-decapitator commented on XBMC Remote/PosterCell.m
> +        CGFloat labelHeight = (CGFloat)(frame.size.height * 0.19);
please use the rounding function instead of this poor man's solution

2021-01-23 15:56 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                                      CGFloat thumbBorder = isRetina ? 1.0/[[UIScreen mainScreen] scale] : 1.0;
Melts down to 

`return CGSizeMake(size.width * UIScreen.mainScreen.scale, size.height * UIScreen.mainScreen.scale);`

2021-01-23 15:57 UTC, kambala-decapitator commented on XBMC Remote/RightMenuViewController.m
> +        UIImageView *xbmc_logo = [[UIImageView alloc] initWithFrame:CGRectMake(self.view.bounds.size.width - 195, (int)((44/2) - (36/2)) - 2, 145, 36)];
at least extracting it to a separate function would be better, even better if you can figure out the explanation for such computation :)

2021-01-23 15:58 UTC, kambala-decapitator commented on XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
>      if([[[UIDevice currentDevice] systemVersion]floatValue] >= 5){
the condition means "if iOS version is >= 5", hope it's clear what needs to be done ;)

2021-01-23 16:00 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                                      CGFloat thumbBorder = isRetina ? 1.0/[[UIScreen mainScreen] scale] : 1.0;
Done with b1b299c.

2021-01-23 16:04 UTC, wutschel commented on XBMC Remote/PosterCell.m
> +        CGFloat labelHeight = (CGFloat)(frame.size.height * 0.19);
Done with de3e370.

I will have lots of fun squashing, and with rebasing to updated master ...

2021-01-23 16:05 UTC, wutschel commented on XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
>      if([[[UIDevice currentDevice] systemVersion]floatValue] >= 5){
Ah, now I got it. Thought you were commenting on `alphaGradientLocations`.

2021-01-23 16:08 UTC, kambala-decapitator commented on XBMC Remote/iPad/StackScrollViewController.m
> +    NSTimeInterval duration = [[[sender userInfo] valueForKey:@"duration"] floatValue];
> Question: There are still several cases where `floatValue` is used. I understand the variable type is relevant for the output (= the variable type the value assigned to). Is this understanding correct?

Yes, you're right, but in fact it depends on the floating-point value stored. `float` has simply less precision than `double`.

For example, if you simply feed `float` to formatting string, then you need to check how many digits after decimal point you want (for anything less than 7 `float` is ok).

In case of `resumePointPercentage` `float` is also fine because you always treat it as `float`.

Basically you need to review every case and decide whether `float` is sufficient or switch to `double`.

2021-01-23 16:11 UTC, wutschel commented on XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
>      if([[[UIDevice currentDevice] systemVersion]floatValue] >= 5){
Done with c4053b2.

2021-01-23 16:13 UTC, wutschel commented on XBMC Remote/iPad/StackScrollViewController.m
> +    NSTimeInterval duration = [[[sender userInfo] valueForKey:@"duration"] floatValue];
I was thinking of all the width/height definition which are still done in `AppDelegate.m`, and the read access to it.

2021-01-23 16:20 UTC, kambala-decapitator commented on XBMC Remote/iPad/StackScrollViewController.m
> +    NSTimeInterval duration = [[[sender userInfo] valueForKey:@"duration"] floatValue];
are you talking about https://github.com/xbmc/Official-Kodi-Remote-iOS/blob/master/XBMC%20Remote/AppDelegate.m#L95-L99 ?

2021-01-23 16:22 UTC, wutschel commented on XBMC Remote/iPad/StackScrollViewController.m
> +    NSTimeInterval duration = [[[sender userInfo] valueForKey:@"duration"] floatValue];
Yes, there is lots of code like this: 

```
float itemMovieWidthLargeIpad =158.0f;
...
[NSNumber numberWithFloat:itemMovieWidthLargeIpad], @"width",
```

2021-01-23 16:27 UTC, kambala-decapitator commented on XBMC Remote/iPad/StackScrollViewController.m
> +    NSTimeInterval duration = [[[sender userInfo] valueForKey:@"duration"] floatValue];
as long as those values are only wrapped in `NSNumber`, no need to change

2021-01-23 16:29 UTC, wutschel commented on XBMC Remote/iPad/StackScrollViewController.m
> +    NSTimeInterval duration = [[[sender userInfo] valueForKey:@"duration"] floatValue];
Also the `float` declarations shall be kept?

2021-01-23 16:30 UTC, kambala-decapitator commented on XBMC Remote/iPad/StackScrollViewController.m
> +    NSTimeInterval duration = [[[sender userInfo] valueForKey:@"duration"] floatValue];
yep

2021-01-23 16:31 UTC, wutschel commented on XBMC Remote/iPad/StackScrollViewController.m
> +    NSTimeInterval duration = [[[sender userInfo] valueForKey:@"duration"] floatValue];
Ok, resolved then.

2021-01-23 16:31 UTC, kambala-decapitator commented on XBMC Remote/iPad/StackScrollViewController.m
> +    NSTimeInterval duration = [[[sender userInfo] valueForKey:@"duration"] floatValue];
but you could change all those declarations to `NSNumber` directly if you wish, e.g.
```objc
__auto_type itemMovieWidthLargeIpad = @(158);
```

2021-01-23 16:37 UTC, kambala-decapitator commented
please solve the last point, resolve conflicts and LGTM

2021-01-23 17:02 UTC, kambala-decapitator commented on XBMC Remote/RightMenuViewController.m
> +        UIImageView *xbmc_logo = [[UIImageView alloc] initWithFrame:CGRectMake(self.view.bounds.size.width - 195, (int)((44/2) - (36/2)) - 2, 145, 36)];
this seems pending

2021-01-23 17:04 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +        UIImageView *xbmc_logo = [[UIImageView alloc] initWithFrame:CGRectMake(self.view.bounds.size.width - 195, (int)((44/2) - (36/2)) - 2, 145, 36)];
Yes, on it. Try to figure our what this really is about. Would great if you could check if there is anything missing for PR https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/139. From an end user point of view that´s having more impact.

2021-01-23 18:49 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +        UIImageView *xbmc_logo = [[UIImageView alloc] initWithFrame:CGRectMake(self.view.bounds.size.width - 195, (int)((44/2) - (36/2)) - 2, 145, 36)];
So, 18c109d does the trick. The logo is nearly invisible, but the calculation is now understood. If you´re ok with this, I will look into squashing some of the commits and rebasing.

2021-01-23 21:29 UTC, wutschel commented
Squashed and rebased to master.

2021-01-24 10:28 UTC, merged