Few fixes for issues reported from TestFlight builds
xbmc/Official-Kodi-Remote-iOS pull request #139
Opened 2021-01-19 21:13 UTC by wutschel

Details:
- Fix last item in playlist not fully shown
- Move up the tip in HostViewController to be fully readable

2021-01-22 15:35 UTC, kambala-decapitator requested changes

2021-01-22 15:35 UTC, kambala-decapitator commented on XBMC Remote/HostViewController.m
> +        if (([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPad) && UIInterfaceOrientationIsLandscape([[UIApplication sharedApplication] statusBarOrientation])) {
Does this support device rotation out of the box? (Don't remember if keyboard hides and appears again)

2021-01-22 15:35 UTC, kambala-decapitator commented on XBMC Remote/HostViewController.m
> +        tipView.frame = frame;
Don't you need to increase height respectively?

2021-01-22 15:35 UTC, kambala-decapitator commented on XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
> +    self.frame = frame;
A view shouldn't fiddle with its own frame because it's parent's responsibility. Is there a better solution?

Also height increase is missing.

2021-01-22 15:35 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +                                    [self SimpleAction:@"Player.Seek" params:[Utilities buildPlayerSeekPercentageParams:(int)[[item objectForKey:@"playlistid"] integerValue] percentage:resumePointLoc
- there's intValue method which would remove the necessity to cast 
- please use subscript access

2021-01-22 18:08 UTC, wutschel commented on XBMC Remote/HostViewController.m
> +        tipView.frame = frame;
No, there´s plenty of (free and unused) space above.

2021-01-22 18:14 UTC, wutschel commented on XBMC Remote/HostViewController.m
> +        if (([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPad) && UIInterfaceOrientationIsLandscape([[UIApplication sharedApplication] statusBarOrientation])) {
Keyboard hides when rotating. It works quite well, with one exception: If you start editing in Landscape mode and then rotate the iPad, the tipview does not come back until you touch the popup.

2021-01-22 18:25 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> +                                    [self SimpleAction:@"Player.Seek" params:[Utilities buildPlayerSeekPercentageParams:(int)[[item objectForKey:@"playlistid"] integerValue] percentage:resumePointLoc
Done. What you will not like is the 2nd change I applied: adding a `sleep(1)` before the `Player.Seek` command when resuming. As discussed in the forum thread the `Player.Seek` command is otherwise not executed -- at least on my test system with Kodi 19. Would be glad if you have a better idea...

2021-01-22 18:33 UTC, wutschel commented on XBMC Remote/SVPullToRefresh/UIScrollView+SVPullToRefresh.m
> +    self.frame = frame;
It is possible to simply call the following code from the parent:

```
frame = collectionView.pullToRefreshView.frame;
frame.origin.y = 0;
collectionView.pullToRefreshView.frame = frame;
```

As far as I can see there is no to do anything else. The PullToRefresh menu works as intended.

2021-01-23 11:47 UTC, kambala-decapitator requested changes

2021-01-23 11:47 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                                 NSDictionary *art = [nowPlayingInfo objectForKey:@"art"];
please use dictionary subscript and other "modern objc" features in all new code

2021-01-23 11:47 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                                 if ([art count] && [[art objectForKey:@"poster"] length]!=0) {
`count` check is useless actually, dictionary lookup is O(1)

2021-01-23 11:47 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +                                    sleep(1);
please use `+[NSThread sleepForTimeInterval:]` instead

2021-01-23 12:54 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> +                                    sleep(1);
Will do.

2021-01-23 12:59 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +                                 if ([art count] && [[art objectForKey:@"poster"] length]!=0) {
Will remove this.

2021-01-23 13:22 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +                                 NSDictionary *art = [nowPlayingInfo objectForKey:@"art"];
You are asking for something like this?

```
NSString *posterPath = (nowPlayingInfo[@"art"])[@"poster"];
if (posterPath != nil) {
    thumbnailPath = posterPath;
}
```

2021-01-23 13:53 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                                 art = [nowPlayingInfo objectForKey:@"art"];
seems that you can drop this line completely as basically you're assigning the same value

2021-01-23 13:57 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                                 NSDictionary *art = [nowPlayingInfo objectForKey:@"art"];
Yes. You can simplify it even further if string length check isn't needed:

```objc
NSDictionary *art = nowPlayingInfo[@"art"];
NSString *thumbnailPath = art[@"poster"] ?: nowPlayingInfo[@"thumbnail"];
```

Also there's no need to enclose subscript access in parentheses.

2021-01-23 13:59 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                           }
looks identical to the above

2021-01-23 14:11 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +                                 NSDictionary *art = [nowPlayingInfo objectForKey:@"art"];
Very nice. Will go for this. You should have nudged me on the same when I did the first commit regarding Kodi 19 & posters.

2021-01-23 14:19 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +                                 art = [nowPlayingInfo objectForKey:@"art"];
Yes, will remove it.

2021-01-23 14:20 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +                           }
Will rework this as for the other sequence.

2021-01-23 14:23 UTC, wutschel commented
Here we go 👍

2021-01-23 16:50 UTC, wutschel commented
Rebased against master. Anything more to change?

2021-01-23 17:07 UTC, merged

2021-01-24 10:22 UTC, howie-f commented on XBMC Remote/ShowInfoViewController.m
> +                                    [self SimpleAction:@"Player.Seek" params:[Utilities buildPlayerSeekPercentageParams:[[item objectForKey:@"playlistid"] intValue] percentage:resumePointLocal]];
@wutschel 
thanks, this is working. but you can obviously see on the screen it starts then seeks.
maybe you could give this a shot https://github.com/howie-f/Official-Kodi-Remote-iOS/commit/6169c8d6b777c870974dc5ad9150e00a41d38ad3
don't know if it works or even builds, but you get the idea. feel free to pick it or bin it.

2021-01-24 10:42 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> +                                    [self SimpleAction:@"Player.Seek" params:[Utilities buildPlayerSeekPercentageParams:[[item objectForKey:@"playlistid"] intValue] percentage:resumePointLocal]];
I am wondering, if the open/seek worked flawlessly with the old remote and older Kodi versions. I recently changed the way the Remote App seeks because an API change in Kodi 19. If I find time, I will look into you code.

2021-01-24 10:55 UTC, howie-f commented
> I am wondering, if the open/seek worked flawlessly with the old remote and older...

works with 18.9 and the old remote app.

your delay is working too, no need to hurry with my suggestion 😉