Implement Dark Mode support
xbmc/Official-Kodi-Remote-iOS pull request #140
Opened 2021-01-21 20:22 UTC by wutschel

This PR basically implements Dark Mode support and will fix some observations from test reports. Nevertheless this PR needs some testing (TestFlight?) to find menus and textfields not taken into account yet.

- Add new methods to allow setting system colors which support Dark Mode
- Use standard colors in case of iOS w/o Dark Mode support
- Use new system colors for main list/cell background d text colors

In addition this PR changes the used colors towards system red/green/blue/teal instead of homebrewn color definitions:

- Use system colors for red/green/blue/teal
- Use systemRed instead of Red

2021-01-22 13:34 UTC, kambala-decapitator requested changes

2021-01-22 13:34 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        return [UIColor colorWithRed:.682 green:.682 blue:.689 alpha:1.00];
instead of using comment + strange numbers, I suggest `174/255.0` approach (the same for all colours)

2021-01-22 13:34 UTC, kambala-decapitator commented on XBMC Remote/MoreItemsViewController.m
> +            }
I don't think it'd work correctly if you switch to Light mode when on this screen.

Also I find it not correct that in light mode you use variable icon and in dark - a fixed one.

2021-01-22 17:51 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        return [UIColor colorWithRed:.682 green:.682 blue:.689 alpha:1.00];
Done

2021-01-22 18:00 UTC, wutschel commented on XBMC Remote/MoreItemsViewController.m
> +            }
Yes, you need to re-enter from main menu to make the images reload. I just did not want to drop the dedicated "_black.png" images. In fact, it would a lot simpler to always use

`[iconImage setImage:[UIImage imageNamed:@"nocover_filemode.png"]];`

for each line. This would be also consistent with the filemode view and will look like this: [image](https://abload.de/img/simulatorscreenshot-ivgk86.png)

What´s your thought?

2021-01-22 22:20 UTC, wutschel commented on XBMC Remote/MoreItemsViewController.m
> +            }
Did this change with latest force-push. Looks good, is consistent and does not need a reload.

2021-01-23 07:51 UTC, wutschel commented
Updated the code to use e.g. `71/255.0` instead of a `float` representation. Use same folder image during Light and Dark Mode for the MoreItemsVC, and top updated a commit message.

2021-01-23 11:37 UTC, kambala-decapitator requested changes

2021-01-23 11:37 UTC, kambala-decapitator commented on XBMC Remote/MoreItemsViewController.m
> +        [iconImage setImage:[UIImage imageNamed:@"nocover_filemode.png"]];
why does this change belong to this commit?

2021-01-23 11:37 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        return [UIColor colorWithRed:174/255.0 green:174/255.0 blue:178/255.0 alpha:1.00];
sorry for not suggesting before: I think it'd be much more readable to create a macro like

    #define RGB(r, g, b) [UIColor colorWithRed:(r)/255.0 green:(g)/255.0 blue:(b)/255.0 alpha:1.0]

and just use it instead of the "long" version. (and/or RGBA macro, if needed)

2021-01-23 11:37 UTC, kambala-decapitator commented on XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
> +    _touchStatusView.backgroundColor = [Utilities getSystemRed:0.0];
not sure why care about color at all if alpha=0 means fully transparent. Besides, in `-setBackgroundVisibility:` method alpha is toggled for black color.

2021-01-23 12:20 UTC, wutschel commented on XBMC Remote/MoreItemsViewController.m
> +        [iconImage setImage:[UIImage imageNamed:@"nocover_filemode.png"]];
The images currently used are only available in black. They are not visible/recognizable when entering Dark Mode. I find it easiest to just use existing images, and this also unifies the look-and-feel.

2021-01-23 12:21 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        return [UIColor colorWithRed:174/255.0 green:174/255.0 blue:178/255.0 alpha:1.00];
Good idea, will do this for `RGBA` (alpha channel is not always 1).

2021-01-23 12:23 UTC, wutschel commented on XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
> +    _touchStatusView.backgroundColor = [Utilities getSystemRed:0.0];
I am simply not changing this to have a clear migration only from the former to the new calls, not mixing with further cleanup. In case of regressions it will be easier find the commit which causes problems.

2021-01-23 12:40 UTC, wutschel commented on XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
> +    _touchStatusView.backgroundColor = [Utilities getSystemRed:0.0];
Sorry, just checked the commit itself. In this case there is not much danger of a regression. :)
I will just set to black with alpha=0 as well, just for consistency.

2021-01-23 13:39 UTC, kambala-decapitator requested changes

2021-01-23 13:39 UTC, kambala-decapitator commented on XBMC Remote/MoreItemsViewController.m
> +        [iconImage setImage:[UIImage imageNamed:@"nocover_filemode.png"]];
I mean it deserves a dedicated commit as everything else is about colours :)

Also I remember you used some image for dark mode only initially. Would it be possible to have light and dark versions of the image? This way you could place both in a single asset within asset catalog and iOS would switch it automatically.

2021-01-23 13:44 UTC, wutschel commented on XBMC Remote/MoreItemsViewController.m
> +        [iconImage setImage:[UIImage imageNamed:@"nocover_filemode.png"]];
I can definitely pull out the change into a dedicated commit. 

Before I was using the images that are currently used always (they are black only) for Light Mode and used the blue'ish folder images only for Dark Mode. Now I changed it to use the blue'ish folder images for both Light and Dark Mode. And I really like it, as this follows the same visual scheme as for Genres and Folder view.

2021-01-23 13:49 UTC, kambala-decapitator commented on XBMC Remote/MoreItemsViewController.m
> +        [iconImage setImage:[UIImage imageNamed:@"nocover_filemode.png"]];
very well then :) Please just move the change to a separate commit and LGTM.

2021-01-23 13:59 UTC, wutschel commented
Here go :)

2021-01-23 15:43 UTC, merged