Replace deprecated UIAlertView with UIAlertController
xbmc/Official-Kodi-Remote-iOS pull request #148
Opened 2021-01-28 21:30 UTC by wutschel

Replace deprecated `UIAlertView` with `UIAlertController`

2021-01-30 14:36 UTC, kambala-decapitator commented
FYI I'm not going to add this to the upcoming update

2021-01-30 14:39 UTC, wutschel commented
I am fine with this. It will avoid risk for unwanted regressions, also I am still working on some of the other deprecated stuff like `UIActionSheet`. We can finalize this later.

2021-01-30 14:45 UTC, kambala-decapitator commented
please add UIActionSheet changes to this PR too

2021-02-06 17:01 UTC, wutschel commented
Now all traces of UIAlertView and UIActionSheet are gone.

2021-02-06 19:29 UTC, wutschel commented
Now also all traces of `UIPopoverController` are gone. Only very few "deprecated" warnings are left.

@kambala-decapitator, I am a bit lost in the deprecation warnings on `willAnimateRotation...`, `didRotateFrom...`, `willRotateTo...`, ` initWithRequest...` and `connectionWithRequest...`. You think you can take a look at this?

2021-02-06 20:29 UTC, kambala-decapitator commented
> @kambala-decapitator, I am a bit lost in the deprecation warnings on `willAnimateRotation...`, `didRotateFrom...`, `willRotateTo...`, ` initWithRequest...` and `connectionWithRequest...`. You think you can take a look at this?

hints in short if you'd like to explore:

- requests: `NSURLSession`
- rotation: `-viewWillTransitionToSize:withTransitionCoordinator:`

2021-02-16 11:23 UTC, wutschel commented
Rebased against master.

2021-02-18 19:08 UTC, wutschel commented
Rebased against master and added fix for longpress on filtered lists for iPad.

2021-02-21 21:15 UTC, wutschel commented
Rebased against master.

2021-03-14 05:49 UTC, kambala-decapitator commented
is this ready for review?

and what about [network calls and rotation](https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/148#issuecomment-774539045) btw?

2021-03-14 06:50 UTC, wutschel commented
> is this ready for review?

Yes, it is.

> and what about [network calls and rotation](https://github.com/xbmc/Official-Kodi-Remote-iOS/pullt/148#issuecomment-774539045) btw?

I wasn´t able to rework this yet. Let us keep it like it is for now.

2021-03-14 10:43 UTC, wutschel commented
Rebase against master, no other changes.

2021-03-19 06:57 UTC, wutschel commented
@kambala-decapitator, you had a chance to look at this one? I know it´s quite some code changes, but would be good close on this one as we otherwise get into too many merge conflicts over time.

2021-03-19 16:23 UTC, kambala-decapitator requested changes
I skipped couple of commits closer to the end because they're huge and not really readable, trust you :)

2021-03-19 16:23 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                // nothing to do
it's ok to skip such comment for ok/cancel buttons and just pass `nil` handler

2021-03-19 16:23 UTC, kambala-decapitator commented on XBMC Remote/WebViewController.m
> +        UIAlertController *alertView = [UIAlertController alertControllerWithTitle:NSLocalizedString(@"Error loading page", nil) message:nil preferredStyle:UIAlertControllerStyleAlert];
why did you remove error message?

2021-03-19 16:23 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    UIAlertController *alertView = [UIAlertController alertControllerWithTitle:title message:msg preferredStyle:UIAlertControllerStyleAlert];
I suggest to add a Cancel button as well, iirc there's an open issue about this

2021-03-19 16:23 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
> +            break;
useless statement

2021-03-19 16:23 UTC, kambala-decapitator commented on XBMC Remote/WebViewController.m
> +    UIPopoverPresentationController *popPresenter = [actionView popoverPresentationController];
you should check that it's not `nil` as the code below applies only to iPad

2021-03-19 16:23 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +    UIPopoverPresentationController *popPresenter = [actionView popoverPresentationController];
`nil` check

2021-03-19 16:23 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +        }
please put only title assignment inside if/else.

also just in case verify that completion is called on main thread.

2021-03-19 16:23 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        UIPopoverPresentationController *popPresenter = [actionView popoverPresentationController];
nil check. Got tired of repeating this, please check all code :)

2021-03-19 16:23 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        UIPopoverPresentationController *popPresenter = [actionView popoverPresentationController];
nil check

2021-03-19 16:23 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                    showfromctrl = ([self doesShowSearchResults]) ? self.searchController : self;
drop brackets

2021-03-19 16:25 UTC, kambala-decapitator commented
btw here's how to handle rotation: https://github.com/libsdl-org/SDL/blob/main/src/video/uikit/SDL_uikitviewcontroller.m#L336

2021-03-19 17:38 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
> +            break;
True, `break` is not reached in any case. Just kept it as I like to end `case` with `break`. Still removing the `break`?

2021-03-19 17:47 UTC, wutschel commented on XBMC Remote/WebViewController.m
> +    UIPopoverPresentationController *popPresenter = [actionView popoverPresentationController];
Just to make I got it right. You ask for the following (everywhere this segment occurs):

```
UIPopoverPresentationController *popPresenter = [actionView popoverPresentationController];
if (popPresenter != nil) {
    popPresenter.sourceView = bottomToolbar;
    popPresenter.sourceRect = bottomToolbar.bounds;
}
[self presentViewController:actionView animated:YES completion:nil];
```

2021-03-19 18:04 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    UIAlertController *alertView = [UIAlertController alertControllerWithTitle:title message:msg preferredStyle:UIAlertControllerStyleAlert];
Agreed. Just added this locally.

2021-03-19 18:05 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                    showfromctrl = ([self doesShowSearchResults]) ? self.searchController : self;
Agreed, did this locally.

2021-03-19 18:15 UTC, wutschel commented on XBMC Remote/WebViewController.m
> +        UIAlertController *alertView = [UIAlertController alertControllerWithTitle:NSLocalizedString(@"Error loading page", nil) message:nil preferredStyle:UIAlertControllerStyleAlert];
Ouch, this was not intended. Re-added this locally.

2021-03-19 18:24 UTC, wutschel commented on XBMC Remote/HostViewController.m
> +                NSURLSessionDataTask *connection = [session dataTaskWithURL:url];
Interesting. Just checked and I can completely comment or remove the whole section

```
//                NSString *serverJSON=[NSString stringWithFormat:@"http://%@:%@/jsonrpc", ipUI.text, portUI.text];
//                NSURL *url = [[NSURL alloc] initWithString:serverJSON];
//                NSURLSession *session = [NSURLSession sharedSession];
//                NSURLSessionDataTask *connection = [session dataTaskWithURL:url];
//                [connection resume];
```

Is this just pinging the Kodi server and does not expect a response? The code is called when using "Add host" and "Find" to find Kodi instances in the local network.

2021-03-19 18:49 UTC, kambala-decapitator commented on XBMC Remote/HostViewController.m
> +                NSURLSessionDataTask *connection = [session dataTaskWithURL:url];
Yes, if you need just to ping and don't care about response, then it's OK. 

But why would you want to remove it completely?

2021-03-19 18:50 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
> +            break;
Please remove

2021-03-19 18:50 UTC, kambala-decapitator commented on XBMC Remote/WebViewController.m
> +    UIPopoverPresentationController *popPresenter = [actionView popoverPresentationController];
Correct

2021-03-19 19:01 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
> +            break;
Ok, np.

2021-03-19 19:02 UTC, wutschel commented on XBMC Remote/HostViewController.m
> +                NSURLSessionDataTask *connection = [session dataTaskWithURL:url];
Will rename variables `pingSession` and `pingConnection`.

2021-03-19 19:14 UTC, wutschel commented on XBMC Remote/WebViewController.m
> +    UIPopoverPresentationController *popPresenter = [actionView popoverPresentationController];
Ok, applied for all relevant places where this was used. Will try to squash this into the commits.

2021-03-19 20:45 UTC, wutschel commented
Added the required updates, rebased to master and squashed where reasonable. I could even combine some more commits (e.g. all UIAlertView changes into one single commit and all UIActionSheet into one single commit).

2021-03-20 13:26 UTC, wutschel commented
> btw here's how to handle rotation: https://github.com/libsdl-org/SDL/blob/main/src/video/uikit/SDL_uikitviewcontroller.m#L336

Thanks, could resolve this now.

2021-03-28 10:01 UTC, merged