Feature: Enable sorting for PVR recordings/timers
xbmc/Official-Kodi-Remote-iOS pull request #168
Opened 2021-02-13 16:43 UTC by wutschel

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/134.

After a quite some journey through the code and many hints from the community here, here is the "sort for PVR recording/timer" feature. In fact, I was initially of the opinion that the Remote App does not sort itself and only display the item in the order coming from the JSON response. But this is not true. The App requests the items only once with a default sort method/order and in addition collects lots of metadata which can be configured to use for sorting. But: the selectable sorting methods are mingled together with the sort methods in the App -- the logic was a bit obscured.

For the PVR sort the App now sends a default sort request (sort by label, ascending). This is not sent in case the API does not support this yet. Independent (!) of this the UI now offers the sort options for Title, Channel, Date and Runtime -- meaning: this feature also works for older Kodi versions.

To avoid that the index is taking up to much space it is limited to 10 characters, which allows to display the full date in the format "YYY-MM-DD".

2021-02-14 17:20 UTC, howie-f commented on XBMC Remote/AppDelegate.m
> +                              @"label", @"method",
just a question out of couriosity. is initial sorting by label, desc correct? because personally i would think _date desc_ is more convinient. you'd see the latest recording on top.. am i missing something?

2021-02-14 17:45 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +                              @"label", @"method",
It looks like` "date", "ascending"`, was used before, at least for the setup I am using for testing (Kodi v19 with VU+ Add-On). I can of course configure the default to `"date", "descending"`. There is only 1 downside: You can never reach this state again w/o resetting the persistence again as the App´s sort options do not support this method. Using the default then will look different (no sections and index shown) than using the App´s sort by `"starttime"`. I´d rather keep it sorting by `"label"` as default and then let the user configure it.

2021-02-14 17:47 UTC, howie-f commented on XBMC Remote/AppDelegate.m
> +                              @"label", @"method",
sounds good, thanks

2021-02-16 11:22 UTC, wutschel commented
Rebased against master.

2021-02-16 16:54 UTC, kambala-decapitator commented
so is it a feature or a bugfix? Next release is fix-only.

2021-02-16 17:02 UTC, howie-f commented
i‘d say feature

2021-02-16 17:03 UTC, wutschel commented
Yes, feature. There was no sorting supported for PVR before.

2021-02-18 18:05 UTC, wutschel commented
Rebased against master.

2021-02-21 15:10 UTC, kambala-decapitator requested changes

2021-02-21 15:10 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +                            [NSMutableDictionary dictionaryWithObjectsAndKeys:
please use modern initialisers for array/dic, it's really difficult to read

2021-02-21 15:10 UTC, kambala-decapitator commented on XBMC Remote/en.lproj/Localizable.strings
> +"Runtime" = "Runtime";
maybe Duration would be better?

2021-02-21 15:10 UTC, kambala-decapitator commented on XBMC Remote/tcpJSONRPC.m
> +         if (error==nil && methodError==nil) {
please use `!` operator instead of comparing to `nil`

2021-02-21 15:10 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            }
you can remove objects unconditionally

2021-02-21 15:24 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            }
Thanks, wasn´t aware of this. Will change this with next update.

2021-02-21 15:28 UTC, wutschel commented on XBMC Remote/tcpJSONRPC.m
> +         if (error==nil && methodError==nil) {
Will be done with next update.

2021-02-21 15:30 UTC, wutschel commented on XBMC Remote/en.lproj/Localizable.strings
> +"Runtime" = "Runtime";
I chose this as we already have the same text in other places, but in capital letters ("RUNTIME" = "RUNTIME";).

2021-02-21 15:32 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +                            [NSMutableDictionary dictionaryWithObjectsAndKeys:
For me it is harder to maintain -- especially this place -- when moving to modern initializers as the whole AppDelegate.m is coded different. I agree to use modern style initializers for other places where I am adding code.

2021-02-21 15:39 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +                            [NSMutableDictionary dictionaryWithObjectsAndKeys:
this should be reformatted then ;) you can try automatic tool embedded in Xcode or clang-format for example.

2021-02-21 15:39 UTC, kambala-decapitator commented
see also input from @howie-f https://forum.kodi.tv/showthread.php?tid=359717&pid=3015333#pid3015333

2021-02-21 15:41 UTC, wutschel commented
> see also input from @howie-f https://forum.kodi.tv/showthread.php?tid=359717&pid=3015333#pid3015333

Already looking at this. :)

2021-02-21 15:42 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +                            [NSMutableDictionary dictionaryWithObjectsAndKeys:
Let´s put it on the todo list.

2021-02-21 18:19 UTC, wutschel commented
I took some time look into how the index view could be configured in a better (and consistent) way. Best solution from my point of view is to make use of already existing processing of index for other sort-methods. Now sort-by-date will only show sections by year (as done for sorting by "dateadded"), and sort-by-channel will only show the leading character as capital letter (as for sorting by name or artist). This even allowed to remove unneeded code I added in the former version of this PR.

Current look:
https://abload.de/img/simulatorscreenshot-iqijvh.png
https://abload.de/img/simulatorscreenshot-imckbd.png
https://abload.de/img/simulatorscreenshot-ihaj6z.png

As part of working on this, I figured some problem with the grid view index view. Will fix this in a separate PR.

2021-02-21 18:22 UTC, kambala-decapitator commented
code changes look good. If you don't plan to add anything else, let's wait for some feedback based on your SSs and LGTM.

2021-02-21 18:44 UTC, wutschel commented
> code changes look good. If you don't plan to add anything else, let's wait for some feedback based on your SSs and LGTM.

The change is complete from my side. Let´s hear the feedback on the screenshots.

2021-02-21 19:50 UTC, howie-f commented
i‘m perfectly fine with this, nice 👍

2021-02-21 20:20 UTC, merged