Rework NowPlaying and ShowInfoVC with enabled jewel case
xbmc/Official-Kodi-Remote-iOS pull request #172
Opened 2021-02-17 17:51 UTC by wutschel

Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/171.

- Fixes a regression of App version 1.6 and latest NowPlaying rework
- Fixes thumbview dimension not correct when image not in cache
- Calculates the thumbview frame size instead of hardcoding it
- Same method used for NowPlaying and ShowInfoVC
- Same method used for iPhone and iPad

2021-02-17 18:36 UTC, kambala-decapitator requested changes

2021-02-17 18:36 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    int jeweltype = 0;
1. avoid assigning useless values
2. I suggest to use enum instead of magic numbers

2021-02-17 18:36 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
>      if ([type isEqualToString:@"song"]){
"song" case is identical to the "else" one. What about merging them?

2021-02-17 18:36 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +        songDetailsView.center = jewelView.center;
what's the point of this? `center` is derived from `frame`, so this line does nothing.

2021-02-17 18:36 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +    int jeweltype = 0;
if value is assigned in all cases, don't assign it here

2021-02-17 18:36 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    if (type == 0) { /* CD */
1. use `enum`
2. use `switch`

2021-02-17 18:36 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    CGRect myfrm = jewelView.frame;
didn't want to comment on variables above, but are you trying to save a few bytes by giving not-so-easy-to-read names? :)

2021-02-17 18:57 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    if (type == 0) { /* CD */
Agreed, will be done with next update.

2021-02-17 18:59 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +        songDetailsView.center = jewelView.center;
Was a takeover from the former code, will be removed with next update.

2021-02-17 19:02 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    int jeweltype = 0;
1. No strong opinion on this on miy side, will remove the assignment.
2. Yep, will be done with next update.

2021-02-17 19:03 UTC, wutschel commented on XBMC Remote/NowPlaying.m
>      if ([type isEqualToString:@"song"]){
I prefer to keep this separated. This way the "song" condition is clearly visible and not only an implicit condition in the else-path.

2021-02-17 19:08 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> +    int jeweltype = 0;
I´d rather assign `jewelTypeUnknown` to it. Just in case.

2021-02-17 19:10 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    CGRect myfrm = jewelView.frame;
oh, I found "frm" as short form for "frame" quite ok. :)
I will change this to easier-to-read names, no problem with this.

2021-02-18 06:49 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
>      if ([type isEqualToString:@"song"]){
FYI you could've simply left a comment mentioning that it also covers song case. (not insisting on doing that)

2021-02-18 06:50 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +            break;
FYI `break` isn't needed after `return`

2021-02-18 06:51 UTC, merged

2021-02-18 07:37 UTC, howie-f commented
perfect, no more glitches on 14.4