Fix wrong index sorting for playcount
xbmc/Official-Kodi-Remote-iOS pull request #185
Opened 2021-02-25 20:33 UTC by wutschel

Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/184.

- Use localizedStandardCompare selector to sort
- Results in correct order 1, 2, 9, 12, 21 in instead of 1, 12, 2, 21, 9

2021-03-11 15:44 UTC, kambala-decapitator requested changes

2021-03-11 15:44 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    }
That's a not-so-easy to understand piece of code. If I understood it correctly, this should do the same:
```objc
NSMutableArray<NSString *> *sectionKeys = [self.sections.allKeys mutableCopy];
__auto_type sortDescriptor = [NSSortDescriptor sortDescriptorWithKey:nil ascending:sortAscending selector:@selector(localizedStandardCompare:)];
[sectionKeys sortUsingDescriptors:@[sortDescriptor]];
if (addUITableViewIndexSearch) {
    [sectionKeys insertObject:UITableViewIndexSearch atIndex:0];
    self.sections[UITableViewIndexSearch] = @[]; // not sure what's the point of setting a mutable array here
}
self.sectionArray = sectionKeys;
```

2021-03-11 18:47 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    }
Thanks for compressing the code. The following works as expected:

```
// first sort the index table ...
NSMutableArray<NSString*> *sectionKeys = [self.sections.allKeys mutableCopy];
NSSortDescriptor *sortDescriptor = [NSSortDescriptor sortDescriptorWithKey:nil ascending:sortAscending selector:@selector(localizedStandardCompare:)];
[sectionKeys sortUsingDescriptors:@[sortDescriptor]];
// ... then add the search item on top of the sorted list when needed
if (addUITableViewIndexSearch) {
    [sectionKeys insertObject:UITableViewIndexSearch atIndex:0];
    self.sections[UITableViewIndexSearch] = @[];
}
self.sectionArray = sectionKeys;
```

`sections` is mutable as otherwise `removeAllObjects` is not provided (called several times in the code).

2021-03-12 08:46 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    }
Added this with ba6ce31. If you´re ok with this, I can squash this into the first commit.

2021-03-12 11:29 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    }
I'm ok except one point: `self.sections[UITableViewIndexSearch] = @[];` - you said that mutable array is actually required, and here we use immutable one.

2021-03-12 11:38 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    }
Sorry, I got confused. I thought you were commenting on `sections` itself, which is of type `NSMutableDictionary*`. And: No, for the assignment we do not need a mutable array. All good.

2021-03-12 11:43 UTC, wutschel commented
Squashed and force-pushed.

2021-03-12 11:46 UTC, merged