Fix shuffle/repeat in overlays not working for iPads
xbmc/Official-Kodi-Remote-iOS pull request #186
Opened 2021-02-25 21:26 UTC by wutschel

Fixes issue reported in [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3017071#pid3017071).

Details:
- Instead of adding the overlay view to NowPlaying view as subview we only convert the desired center position

2021-03-11 15:58 UTC, kambala-decapitator requested changes

2021-03-11 15:58 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    songDetailsView.center = [jewelView convertPoint:jewelView.center toView:songDetailsView];
even if this code produces expected result by chance, it is incorrect: conversion method accepts point in local coordinate system of the caller, but `center` returns coordinates in parent's coordinate system (i.e. of superview).

2021-03-11 18:29 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    songDetailsView.center = [jewelView convertPoint:jewelView.center toView:songDetailsView];
But isn´t this what is required? `songDetailsView` is a subview of superview. So we need to move this to a position which is matching the superview-position of `jewelView` (which is part of `nowPlayingView`).

I was really working on this for a while before I found this to be the solution. What would you expect to be the correct call?

2021-03-12 11:48 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    songDetailsView.center = [jewelView convertPoint:jewelView.center toView:songDetailsView];
This would be correct for what you described:

    [jewelView.superview convertPoint:jewelView.center toView:songDetailsView]

2021-03-12 11:58 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    songDetailsView.center = [jewelView convertPoint:jewelView.center toView:songDetailsView];
Hmm, still disarranged then (small vertical and horizontal offset).

2021-03-12 12:02 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    songDetailsView.center = [jewelView convertPoint:jewelView.center toView:songDetailsView];
what is the view hierarchy that involves these views? are they siblings?

2021-03-12 12:25 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    songDetailsView.center = [jewelView convertPoint:jewelView.center toView:songDetailsView];
From what I see on iPhone they are both part of `NowPlayingView`. For iPad there is something different. Can you tell from this line in `ViewControllerIpad.m`?

`[self.view insertSubview:self.nowPlayingController.songDetailsView aboveSubview:rootView];`

2021-03-12 12:40 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    songDetailsView.center = [jewelView convertPoint:jewelView.center toView:songDetailsView];
This works as well: `[jewelView.superview convertPoint:jewelView.center toView:songDetailsView.superview];`

2021-03-12 14:03 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    songDetailsView.center = [jewelView convertPoint:jewelView.center toView:songDetailsView];
If 8e3767d is ok for you, I will squash and force-push.

2021-03-14 05:12 UTC, merged