Resize stackview
xbmc/Official-Kodi-Remote-iOS pull request #189
Opened 2021-02-28 11:48 UTC by wutschel

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/154.

Changes:
- Allow stack views width increased width on new iPads with higher resolution
- Scale up relevant content like TV Show banners and album/movie thumbs
- Bundled further removal of magic numbers
- Screenshots are linked in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/154

2021-03-14 05:37 UTC, kambala-decapitator requested changes
please also squash c20672d76ec17bc654556f6933f0adee086c294e

2021-03-14 05:37 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.h
> +#define STACKSCROLL_WIDTH (GET_MAINSCREEN_WIDTH - PAD_MENU_TABLE_WIDTH) //476 // 724
I'm pretty sure it's 468 ;)

also there're other values: new iPad Air, iPad 7Gen...

oh, I see subsequent commit undoes this. You should probably squash them or so for less confusion.

2021-03-14 07:06 UTC, wutschel commented on XBMC Remote/AppDelegate.h
> +#define STACKSCROLL_WIDTH (GET_MAINSCREEN_WIDTH - PAD_MENU_TABLE_WIDTH) //476 // 724
> please also squash [c20672d](https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/c20672d76ec17bc654556f6933f0adee086c294e)

Squashing with c07641c, right?

> 476 vs. 468

The code still shows the comment with the wrong number. I just kept it as this _was_ what was used all the time. But you´re right, it might be cofusing. I will remove the comment.
The problem is that 468 is the correct width for the stackview, but the App used 476 all the time, and the hardcoded thumbwidths are designed for this. This is why the rights side of the stackview was not fully visible.

2021-03-14 08:17 UTC, wutschel commented
Applied the required changes (squashed and removed confusing comment) and rebased to master.

2021-03-15 18:44 UTC, wutschel commented on XBMC Remote/AppDelegate.h
> +#define STACKSCROLL_WIDTH (GET_MAINSCREEN_WIDTH - PAD_MENU_TABLE_WIDTH) //476 // 724
All done with latest force-push.

2021-03-19 15:44 UTC, merged