Implement support for sort tokens
xbmc/Official-Kodi-Remote-iOS pull request #200
Opened 2021-03-20 16:30 UTC by wutschel

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/97

This PR implements support for sort tokens for the Remote App. When connecting to the Kodi server the App requests the server´s sort tokens and the server´s setting for "ignore articles when sorting" via the JSON API. As older versions of Kodi do not provide the sort tokens a default set (`"The"`, `"A"`, `"An"` and variants with extensions like `"The_"` and `"The."`) is defined.

2021-03-28 09:53 UTC, kambala-decapitator requested changes
can't say anything about the feature itself or runtime test though

2021-03-28 09:53 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    NSMutableString *c = [text mutableCopy];
give it a better name

2021-03-28 09:53 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    }
please use `for-in` instead, don't see any reason to use plain `for` here. You can also check for token count right in the beginning and avoid creating mutable string completely.

2021-03-28 09:53 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    NSMutableArray *copymutable = [[NSMutableArray alloc] init];
use `initWithCapacity:`

2021-03-28 09:53 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        NSDictionary *dict = @{@"sortby": sortby};
this temp variable can be avoided

2021-03-28 09:53 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    }
use `for-in`

2021-03-28 09:53 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    return [incomingRichArray sortedArrayUsingDescriptors:sortDescriptors];
```suggestion
    return [incomingRichArray sortedArrayUsingDescriptors:@[sortDescriptor]];
```

2021-03-28 09:53 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.h
> +@property (nonatomic, retain) NSArray *KodiSorttokens;
use `copy` instead

2021-03-28 09:53 UTC, kambala-decapitator commented on XBMC Remote/tcpJSONRPC.m
> +             [AppDelegate instance].KodiSorttokens = [methodResult[@"sorttokens"] copy];
no need to call `copy` when property is marked with `copy`

2021-03-28 12:43 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    NSMutableString *c = [text mutableCopy];
Done

2021-03-28 12:48 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    }
Done

2021-03-28 12:50 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        NSDictionary *dict = @{@"sortby": sortby};
Done

2021-03-28 12:57 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    }
Done

2021-03-28 12:59 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    return [incomingRichArray sortedArrayUsingDescriptors:sortDescriptors];
Fine for me, done.

2021-03-28 13:02 UTC, wutschel commented on XBMC Remote/AppDelegate.h
> +@property (nonatomic, retain) NSArray *KodiSorttokens;
Done

2021-03-28 13:02 UTC, wutschel commented on XBMC Remote/tcpJSONRPC.m
> +             [AppDelegate instance].KodiSorttokens = [methodResult[@"sorttokens"] copy];
Done

2021-03-28 13:07 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    NSMutableArray *copymutable = [[NSMutableArray alloc] init];
You mean like this as we know the final size?

`NSMutableArray *copymutable = [[NSMutableArray alloc] initWithCapacity:[incomingRichArray count]];`

2021-03-28 13:18 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    NSMutableArray *copymutable = [[NSMutableArray alloc] init];
Exactly

2021-03-28 13:23 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    NSMutableArray *copymutable = [[NSMutableArray alloc] init];
Consider it done.

2021-03-28 13:26 UTC, wutschel commented
Applied requested changes, tested and rebased.

2021-03-28 13:55 UTC, howie-f commented on XBMC Remote/tcpJSONRPC.m
> +    }];
please do not execute this call when the json api version doesn't support it, as you're querying JSONRPC.Version one call before. Sorttokens were introduced with version `9.5.0`. if your concern is this would lead to duplicate code for the array `@[@"The ", @"The.",...` can you define a `const` fallback array and use this?

2021-03-28 15:07 UTC, wutschel commented
Since the rebase I face a problem with the sorting of movies. The sort tokens are not applied always. I need to revise this whole thing. Sorry.

2021-03-29 07:30 UTC, wutschel commented on XBMC Remote/tcpJSONRPC.m
> +    }];
Done

2021-03-29 07:47 UTC, wutschel commented
The code is not that straight forward anymore, but I could generalize the approach and add a few very basic changes to configure the sorting. The reason for the late observation of the crash was that `"playcount"` is provided as `NSString` for music albums and `NSNumber` for movies. Also, for many menus the main variables for the sort method and order were set to `nil` which was used as part of the logic.

I am now setting all of the variables properly (even though `nil` is still allowed and observed for menus). There is preprocessing added for sort methods to fall back to `"label"`, if no key for the chosen method is part of the dictionary to be sorted. Another preprocessing ensures the sort selector is set to `@selector(localizedStandardCompare:)` only when sorting `NSString`. All sort token / sorting is done outside of other conditions and therefore now applied always, which finally enables this also for lists as they were requested via JSON from Kodi.

I guess this might have a performance impact (not experiencing this with my small database though) and definitely needs further testing.

2021-04-02 08:03 UTC, kambala-decapitator requested changes

2021-04-02 09:03 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    return [string copy];
Ok, your code avoids some unneeded assignments, if there are no sorttokens defined. Your comment on maybe leaving the loop after the first "hit" is interesting. I think it should. Just thinking of band names like "The The". So there could be exceptions where more than hits could happen with the current code.

2021-04-02 09:12 UTC, wutschel commented
Rebased to master and added the suggested changes (incl. leaving the loop after first found sort token). Did you have the chance to also test this?

2021-04-04 08:31 UTC, kambala-decapitator commented
> Did you have the chance to also test this?

nope.

let's make a TF build for testing.

2021-04-04 09:22 UTC, kambala-decapitator commented
FYI TF version was created before your last force push

2021-04-04 09:26 UTC, wutschel commented
> FYI TF version was created before your last force push

Ok, thanks for notifying me. I only rebased to master, so there is no difference in the implementation.

2021-04-04 12:08 UTC, heitbaum commented
Just tested after sync. Sort order still showing **The** after **Texas**

![D3E3EC7A-F76B-422B-8AAB-57A85D5B8EE8](https://user-images.githubusercontent.com/6086324/113508199-01080a00-9592-11eb-8c93-aced13eedf3d.png)
![73251867-CC2E-4CAC-A1BF-81DC7DEC9F9C](https://user-images.githubusercontent.com/6086324/113508207-07968180-9592-11eb-8dc0-c63ca3d6fa41.png)

2021-04-04 12:17 UTC, wutschel commented
> Just tested after sync. Sort order still showing **The** after **Texas**

Here it shows "The Naked Gun 2 1/2" after "Blade Runner" and before "Starship Troopers". Is the setting "Ignore articles when sorting" enabled? This is hidden well under "Kodi Settings" > "Media" > "General" > "Ignore articles when sorting".

2021-04-04 12:26 UTC, heitbaum commented
![7A139E65-DDF5-42FD-B92E-BD2409E137F7](https://user-images.githubusercontent.com/6086324/113508692-c18eed00-9594-11eb-9e5f-2f9cbc4e49db.jpeg)
Here are my settings. In movies on kodi it is sorted correctly.

2021-04-04 12:33 UTC, wutschel commented
> Here are my settings. In movies on kodi it is sorted correctly.
Looks just right. Which Kodi version is this?

2021-04-04 12:34 UTC, heitbaum commented
> > Here are my settings. In movies on kodi it is sorted correctly.
> 
> Looks just right. Which Kodi version is this?

19.0 / LE10b1

```
=== tested on ===
Generic.x86_64-devel-20210402102324-43848a2
Linux nuc11 5.10.27 #1 SMP Fri Apr 2 10:34:01 UTC 2021 x86_64 GNU/Linux
Starting Kodi (19.0 (19.0.0) Git:19.0-Matrix). Platform: Linux x86 64-bit
Using Release Kodi x64
Kodi compiled 2021-04-02 by GCC 10.2.0 for Linux x86 64-bit version 5.10.27 (330267)
Running on LibreELEC (heitbaum): devel-20210402102324-43848a2 10.0, kernel: Linux x86 64-bit version 5.10.27
FFmpeg version/source: 4.3.1-Kodi
Host CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 8 cores available
[    0.000000] DMI: Intel(R) Client Systems NUC11PAHi7/NUC11PABi7, BIOS PATGL357.0037.2021.0106.1527 01/06/2021
CRenderSystemGL::InitRenderSystem - Version: 4.6 (Core Profile) Mesa 21.1.0-devel, Major: 4, Minor: 6
GL_RENDERER = Mesa Intel(R) Xe Graphics (TGL GT2)
GL_VERSION = 4.6 (Core Profile) Mesa 21.1.0-devel
libva info: VA-API version 1.11.0
vainfo: VA-API version: 1.11 (libva 2.11.1)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.1.3 (43848a22aa)
```

2021-04-04 12:41 UTC, wutschel commented
And this is sorted by `title` (default), correct?

2021-04-04 12:57 UTC, howie-f commented
if i‘m running only the remote, no kodi instance up and connected (which means i see the cached movies list from the previous session).... and then change sort order ‚title asc/desc‘,
the sort tokens are not respected and i see the previous behavior.

once i boot up kodi and the remote reconnects the tokens are used correctly.

@heitbaum which resource.language are you using exactly?

2021-04-04 13:25 UTC, heitbaum commented
I have got the iPad to get it updated. IPhone - yet to have success.

Language is en_gb
`guisettings.xml:    <setting id="locale.language" default="true">resource.language.en_gb</setting> `

![8E0F2177-71A5-4EA0-AC60-601E3EAD7E9A](https://user-images.githubusercontent.com/6086324/113510083-39ace100-959c-11eb-9926-a66b40793406.jpeg)

2021-04-04 13:33 UTC, kambala-decapitator commented
just noticed fresh TF feedback from @heitbaum , I guess it's related to this PR:

> On sync - it fails The network connection was lost. METHOD VideoLibrary.GetMovies PARAMETERS {properties=(year,playcount,rating,thumbnail,genre,runtime,trailer,file,dateadded,art);sort={"available_methods"={label=(Title,Year,Rating,Duration,"Dateadded","Playcount");method=(label,year,rating,runtime,dateadded,playcount);};ignorearticle=0;method=label;order=ascending;};}

<img src="https://user-images.githubusercontent.com/1557784/113510334-06019500-9563-11eb-8d4c-ab9162aaec66.jpg" width="50%" />

2021-04-04 15:51 UTC, howie-f commented
i cannot prove it is not related to this pr, but refresh works fine on my iPad Air 2 (14.4.2) 🤔

2021-04-04 17:00 UTC, wutschel commented
Well, from Kodi server point of view this PR only adds the request for the sort tokens and the request for the ignore-article-setting. All the sort token processing is done in the App itself.

2021-04-04 22:31 UTC, heitbaum commented
Retested this morning. IPhone even after delete of Kodi Remote and recreate the host does not have the right sort order. It says it has synced - and date time reflects this.

note: all the data still is still there - even after an app delete (is it storing it in a persistent iCloud synced location in the phone?) the network, connection error is still there, not consistent though.

2021-04-04 23:13 UTC, wutschel commented
What you describe could come from an empty token list responded back from Kodi server. Only chance to further debug this is to make a build which has a debug output enabled to shows the parameter read from Kodi server. For my Kodi 20.0-ALPHA1 test system it looks like this: https://abload.de/img/simulatorscreenshot-irwkmj.png
I can provide a hardcoded commit for this.

2021-04-04 23:45 UTC, heitbaum commented
I’m heading out for the day - but why don’t I try and grab a tcpdump and look at the conversation.

2021-04-05 09:16 UTC, wutschel commented
Only hygiene and changes: Removed double semicolons and cherry pick comments.

2021-04-05 09:59 UTC, heitbaum commented
I have tried this evening on my iPhone ( it was working ... ¯\_(ツ)_/¯ ) 
I checked on the other iPhone here that had test flight - it was ok. I then added test flight to a 3rd phone - ok too... but as promised - here is the pcap output.

Here is the response from Matrix 19.0. 
`{"id":-1399671953,"jsonrpc":"2.0","result":{"sorttokens":["The ","The.","The_"]}} `

here is the full trace during initial connection.
```
        POST /jsonrpc HTTP/1.1
        Host: 192.168.42.63:8080
        Content-Type: application/json
        Accept-Encoding: gzip, deflate
        Connection: keep-alive
        Accept: */*
        User-Agent: DSJSONRPC/1.0
        Authorization: Basic 
        Content-Length: 123
        Accept-Language: en-au
        
        POST /jsonrpc HTTP/1.1
        Host: 192.168.42.63:8080
        Content-Type: application/json
        Accept-Encoding: gzip, deflate
        Connection: keep-alive
        Accept: */*
        User-Agent: DSJSONRPC/1.0
        Authorization: Basic 
        Content-Length: 60
        Accept-Language: en-au
        
        HTTP/1.1 200 OK
        Connection: Keep-Alive
        Content-Type: application/json
        Content-Length: 145
        Cache-Control: private, max-age=0, no-cache
        Accept-Ranges: none
        Date: Mon, 05 Apr 2021 09:38:43 GMT
        
        {"id":-1076997599,"jsonrpc":"2.0","result":{"name":"Kodi","version":{"major":19,"minor":0,"revision":"19.0-Matrix","tag":"stable"},"volume":100}} [|http]

        POST /jsonrpc HTTP/1.1
        Host: 192.168.42.63:8080
        Content-Type: application/json
        Accept-Encoding: gzip, deflate
        Connection: keep-alive
        Accept: */*
        User-Agent: DSJSONRPC/1.0
        Authorization: Basic 
        Content-Length: 123
        Accept-Language: en-au
        
        HTTP/1.1 200 OK
        Connection: Keep-Alive
        Content-Type: application/json
        Content-Length: 57
        Cache-Control: private, max-age=0, no-cache
        Accept-Ranges: none
        Date: Mon, 05 Apr 2021 09:38:43 GMT
                            
        {"id":-612635874,"jsonrpc":"2.0","result":{"value":true}} [|http]

        HTTP/1.1 200 OK
        Connection: Keep-Alive
        Content-Type: application/json
        Content-Length: 87
        Cache-Control: private, max-age=0, no-cache
        Accept-Ranges: none
        Date: Mon, 05 Apr 2021 09:38:43 GMT
        
        {"id":1514057847,"jsonrpc":"2.0","result":{"version":{"major":12,"minor":2,"patch":1}}} [|http]

--

        POST /jsonrpc HTTP/1.1
        Host: 192.168.42.63:8080
        Content-Type: application/json
        Accept-Encoding: gzip, deflate
        Connection: keep-alive
        Accept: */*
        User-Agent: DSJSONRPC/1.0
        Authorization: Basic 
        Content-Length: 110
        Accept-Language: en-au
        
        HTTP/1.1 200 OK
        Connection: Keep-Alive
        Content-Type: application/json
        Content-Length: 81
        Cache-Control: private, max-age=0, no-cache
        Accept-Ranges: none
        Date: Mon, 05 Apr 2021 09:38:43 GMT
        
        {"id":-1399671953,"jsonrpc":"2.0","result":{"sorttokens":["The ","The.","The_"]}} [|http]
```

2021-04-05 12:59 UTC, wutschel commented
@heitbaum, good to read this. Could this be related to the connection issues you saw yesterday?

2021-04-05 13:02 UTC, heitbaum commented
> @heitbaum, good to read this. Could this be related to the connection issues you saw yesterday?

Agree. I think going to have to chalk that up as transitory error, as all the testing this evening has been fine. 👍 PR tested as good by me 😀

2021-04-05 13:06 UTC, howie-f approved these changes
cool, i don‘t see issues as well

EDIT: also checked album, artists - views, genre for movies etc.. all good. 👍 hope i didn‘t something

2021-04-05 13:28 UTC, kambala-decapitator commented
@wutschel how to name this PR for testers? Is the one I wrote good?

> Sort tokens: "The", "A", "An" and variants

2021-04-05 13:35 UTC, wutschel commented
> @wutschel how to name this PR for testers? Is the one I wrote good?

I would go for `Feature: Ignore articles based on Kodi sort tokens (e.g. "The")` I can change the PR description to respect the new template.

Btw, we discussed this in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/97 that "A" and "An" should not be used as default sort tokens. Code checks also confirmed that only "The", "The." and "The_" are default. I added the other articles as the web interface definitely also applies "A" and "An" -- just checked this also against Kodi 17.6 and Kodi 20.0-ALPHA1. Is this an inconsistency between Kodi UI and the Web IF?

2021-04-05 14:21 UTC, howie-f commented
> Is this an inconsistency between Kodi UI and the Web IF?

WebIF decides on its own which sorttokens to use, as far as i can see. as v17.6 doesn't resolve the sorttokens json-request.
so yes, you can call it an inconsistency. `A` and `An` must be hardcoded somewhere in chorus2 i guess.
it's our own decision (or yours) what Official Remote should do

2021-04-05 14:43 UTC, kambala-decapitator commented
You could make the default tokens configurable via Remote settings and include all options by default

2021-04-05 14:55 UTC, wutschel commented
Now handles sort tokens also in fullscreen mode (reported in the forum). Rebased to master.

2021-04-05 17:29 UTC, kambala-decapitator commented
@wutsche please remove draft status when ready for merge

2021-04-05 21:40 UTC, wutschel commented
> @wutschel please remove draft status when ready for merge

I still feel this needs some more testing. Best would be to keep this out of the next release and merge it directly after.

2021-04-05 21:43 UTC, kambala-decapitator commented
> > @wutschel please remove draft status when ready for merge
> 
> I still feel this needs some more testing. Best would be to keep this out of the next release and merge it directly after.

I'm fine, let's do like that

2021-04-06 06:29 UTC, wutschel commented
Reduce default sort tokens to `"The"`, `"The_"` and `"The."` -- same as Kodi UI.

2021-04-06 13:19 UTC, kambala-decapitator commented
crash report by @heitbaum for build with this feature: 
[testflight_feedback.zip](https://github.com/xbmc/Official-Kodi-Remote-iOS/files/6264899/testflight_feedback.zip)

I think it could be introduced exactly in this PR as I don't see similar crashes in any other version.

2021-04-06 14:10 UTC, wutschel commented
> I think it could be introduced exactly in this PR as I don't see similar crashes in any other version.

Hard to say. We have similar -- but not same -- reports from 1.6.1. Searching the web for the crashlog did not help me too much. Could it be that this is what I am experiencing from time to time? The App (in simulator) freezes in the startup screen. On the iPhone I never realized this.

2021-04-06 14:24 UTC, heitbaum commented
> > I think it could be introduced exactly in this PR as I don't see similar crashes in any other version.
> 
> Hard to say. We have similar -- but not same -- reports from 1.6.1. Searching the web for the crashlog did not help me too much. Could it be that this is what I am experiencing from time to time? The App (in simulator) freezes in the startup screen. On the iPhone I never realized this.

Only happened once. I’ll keep an eye on it though.

2021-04-06 14:34 UTC, kambala-decapitator commented
> Could it be that this is what I am experiencing from time to time? The App (in simulator) freezes in the startup screen. 

might be. Next time you spot it, try pausing debugger immediately and inspecting the main thread.

2021-04-13 16:57 UTC, wutschel commented
Rebased to master.

2021-04-18 06:45 UTC, wutschel commented
Rebased to master.

2021-04-18 19:42 UTC, merged