Features and fixes around TV station logos
xbmc/Official-Kodi-Remote-iOS pull request #216
Opened 2021-04-03 10:08 UTC by wutschel

## Description

This PR resolves an issue report from a [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3027965#pid3027965).

1. Monochrome images were not properly analyzed for their average color / brightness causing an inadequate choice of background color. This PR reworks the calculation method.
2. For the TV station logos shown in the recording details the automatic choice of background color is now implemented.
3. The TV station logs for channel list, recording list and recording details now use same aspect ratios for improved UI consistency.

Screenshots:
https://abload.de/img/simulatorscreenshot-ia2k9f.png (monochrome before, recording + channel list)
https://abload.de/img/simulatorscreenshot-i53jr8.png (monochrome before, recording list + details)
https://abload.de/img/simulatorscreenshot-i96j2c.png (monochrome after, recording + channel list)
https://abload.de/img/simulatorscreenshot-ih3kp4.png (monochrome after, recording list + details)
https://abload.de/img/simulatorscreenshot-ibqjxp.png (RGBA after, recording + channel list)
https://abload.de/img/simulatorscreenshot-iehkbr.png (RGBA after, recording list + details)

## Summary for release notes

Bugfix: Correct handling of monochrome TV station logos with alpha channel
Feature: Choose background color of TV station logos for recording details
Feature: Align aspect ratio of TV station logos for channel list, recording list and recording details

2021-04-03 10:11 UTC, wutschel commented
@kambala-decapitator, should we do a test build before merging and ask for testing?

2021-04-04 08:26 UTC, kambala-decapitator requested changes
> @kambala-decapitator, should we do a test build before merging and ask for testing?

I don't find it necessary: can always be reverted later if needed

2021-04-04 08:26 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        if (stride == 4) {
better use `switch`

2021-04-04 08:26 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        if (stride == 4) {
`switch`

2021-04-04 08:41 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        if (stride == 4) {
done

2021-04-04 08:41 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        if (stride == 4) {
done

2021-04-04 08:42 UTC, wutschel commented
> I don't find it necessary: can always be reverted later if needed

Fair enough, then let´s go.

2021-04-04 08:46 UTC, merged