Enable shake recognition in NowPlaying controller
xbmc/Official-Kodi-Remote-iOS pull request #227
Opened 2021-04-04 19:40 UTC by wutschel

## Description

Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/223.

Make `NowPlaying` controller the first responder and move the `motionBegin` method there. Tested on iPhone Xs and iPad 5G simulator.

## Summary for release notes

Bugfix: Make shake gesture work again (allows to clear playlist)

2021-04-04 21:03 UTC, kambala-decapitator requested changes

2021-04-04 21:03 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +        [[NSNotificationCenter defaultCenter] postNotificationName: @"UIApplicationShakeNotification" object: nil];
iirc the same class responds to the notification, so I suggest to call respective method directly

2021-04-04 21:51 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +        [[NSNotificationCenter defaultCenter] postNotificationName: @"UIApplicationShakeNotification" object: nil];
True, done.

2021-04-05 13:33 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    [self becomeFirstResponder];
is this line required? shouldn't it work out of the box?

2021-04-05 13:41 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    [self becomeFirstResponder];
No, without this line it will not work. Can this have any side effects? In other controllers I see also `resignFirstResponder` called.

2021-04-05 13:49 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    [self becomeFirstResponder];
ok, no problem then.

`resignFirstResponder` is usually called to hide keyboard.

2021-04-05 14:47 UTC, merged