Fix runtime warnings
xbmc/Official-Kodi-Remote-iOS pull request #236
Opened 2021-04-08 12:05 UTC by wutschel

## Description

The App is throwing several runtime warning when started and while usage. This PR addresses 4 of them.

1. Instead of trying to load an UIImage from `filename = @""` we rather load the invisible `"blank.png"` (happens each start)
2. Method `selectIndex` in `HostManagementVC` should be called fro `viewDidLoad` (happens each start)
3. Do not try to load images from an empty URL path (e.g. happens when entering music genre menu)
4. Presenting actionsheet popups on iPad throw a warning. Presenting them from `self.view.window.rootViewController` fixes this, but I am not sure if this a good thing to do or we just ignore the warning...

## Summary for release notes

Maintenance: Avoid runtime warnings

2021-04-13 16:53 UTC, wutschel commented
Rebased to master.

2021-04-14 18:51 UTC, wutschel commented
Brought in one more case of loading @"blank.png" instead of causing runtime warnings when attempting to load an image named @"".

2021-04-18 08:42 UTC, wutschel commented
Rebased to master.

2021-04-18 20:39 UTC, wutschel commented
Rebased to master.

2021-04-30 13:17 UTC, kambala-decapitator requested changes
generally looks ok.

it'd really help if you post the warnings themselves.

action sheet: if it's still positioned correctly, then the change is fine.

2021-04-30 13:17 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        UIViewController *showfromctrl = nil;
camelCase is much easier to read ;)

2021-04-30 14:13 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        UIViewController *showfromctrl = nil;
I added a separate commit which changes the variable name at this place and also for the other location where the same variable was used.

I also updated the description which now has all the details on the warnings.

2021-04-30 14:28 UTC, kambala-decapitator commented
actually, `[self selectIndex:nil reloadData:YES];` in `viewDidLoad` makes no sense at all: at that point table has no data, so nothing to reload. Initial data loading occurs when table is displayed for the first time.

2021-04-30 14:36 UTC, wutschel commented
> actually, `[self selectIndex:nil reloadData:YES];` in `viewDidLoad` makes no sense at all: at that point table has no data, so nothing to reload. Initial data loading occurs when table is displayed for the first time.
> 
> In `viewWillAppear` it seems to make sense to reload the view next time you enter it. (can't say if that's really needed though)

Hmm, what do you suggest? Removing this change then?

2021-04-30 14:40 UTC, kambala-decapitator commented
yes, definitely drop. If you're really bothered with the warning, just add a flag to ignore the call the first time.

2021-05-01 08:46 UTC, wutschel commented
Rebased to master.

2021-05-01 10:12 UTC, merged