Implement new setting for TV logo background
xbmc/Official-Kodi-Remote-iOS pull request #238
Opened 2021-04-08 19:16 UTC by wutschel

## Description

Introduce a Kodi Remote App setting which allows the user to select the desired behavior. For performance reasons the setting is checked in `viewDidLoad` of `DetailVC` and `ShowInfoVC`. No restart of the App is needed after changing the setting. The user only needs to re-enter the Live TV menu.

Details:
- Allows to set automatic, dark, light and transparent
- Automatic = automatic detection (default)
- Dark = dark background
- Light = light background
- Transparent = transparent (as App version <=1.6.1)

Screenshot:
https://abload.de/img/bildschirmfoto2021-04x2j1m.png

## Summary for release notes

Feature: New setting to select TV logo background handling (auto, dark, light, transparent)

2021-04-12 19:22 UTC, kambala-decapitator requested changes
please also change encoding of `Root.strings` files to UTF-8

2021-04-12 19:22 UTC, kambala-decapitator commented on XBMC Remote/Utilities.h
> +    bgUnknown,
what's the point of this unused value?

2021-04-12 19:22 UTC, kambala-decapitator commented on XBMC Remote/Utilities.h
> +} eLogoBackgroundType;
types mustn't start with a lowercase letter: please drop the `e` prefix

2021-04-12 19:22 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        NSString *mode = [userDefaults objectForKey:@"logo_background"];
extract getting the setting to a variable, also replace `objectForKey`. (btw there's a dedicated `stringForKey:`)

2021-04-13 05:09 UTC, wutschel commented on XBMC Remote/Utilities.h
> +    bgUnknown,
I define these by default for all enums for error handling. In this case I am not using it as unknown settings are interpreted as "automatic". I do not have a strong opinion on this and can remove it.

2021-04-13 05:10 UTC, wutschel commented on XBMC Remote/Utilities.h
> +} eLogoBackgroundType;
I don't mind. In former times I always started enum types with "e" followed by a capital character. If this violates the coding style I will change it. I will then also change the other enums type definition I did (right above this one) in a seperate commit.

2021-04-13 05:22 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        NSString *mode = [userDefaults objectForKey:@"logo_background"];
This is what you are searching for?
```
NSString *mode = [userDefaults stringForKey:@"logo_background"];
    if ([mode length]){
```

2021-04-13 06:19 UTC, wutschel commented
> please also change encoding of `Root.strings` files to UTF-8 in a separate commit (before editing those files)

Not sure, if I am doing this the right way. If I am changing the type in XCode´s "Identity and Type" most files still show up as binary file and no diff can be seen. For some files it works already, e.g. the "sv" and "pl" language files. Viewing from the console the files which work have about half the size (about 1 kByte) as the other files (about 2 kByte).

2021-04-13 16:15 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        NSString *mode = [userDefaults objectForKey:@"logo_background"];
yes

2021-04-13 16:17 UTC, kambala-decapitator commented on XBMC Remote/Utilities.h
> +    bgUnknown,
please remove

2021-04-13 16:19 UTC, kambala-decapitator commented on XBMC Remote/Utilities.h
> +} eLogoBackgroundType;
having a type starting with a lowercase letter just doesn't feel right :)

2021-04-13 16:32 UTC, wutschel commented
Added requested changes and rebased to master.

2021-04-13 16:45 UTC, merged