Fixes around UI behavior while searching
xbmc/Official-Kodi-Remote-iOS pull request #242
Opened 2021-04-12 05:52 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/241.

1. Restore keyboard visibility
When coming back to a filtered list (e.g. filtering for music albums, then select one to go into the detail view, then go back) the App is never showing the keyboard and the search text field is not firstResponder anymore. This PR aligns the behavior with other iOS Apps: The keyboard visibility / editing mode is saved and restored when re-entering the menu.
2. Avoid misbehavior
When a filtered list is shown (e.g. filtering for music albums) and the user hits "Search" the keyboard becomes invisible and allows to touch the toolbar items. Hitting any of these buttons now leads to uncontrolled behavior which can only be fixed via re-entering the whole music menu. This PR avoids this situation by simply hiding the toolbar when the keyboard is made invisible (pressing "Search" button on the keyboard), and making it visible again when the search is ended (pressing "Cancel" button next to search text field). I chose this solution over ignoring touch of each toolbar item for its simplicity.

## Summary for release notes

Bugfix: Restore keyboard visibility while searching after selecting item from search list and returning back
Bugfix: Avoid misbehavior when selecting toolbar items during search list is presented

2021-04-13 16:56 UTC, wutschel commented
Rebased to master.

2021-04-17 17:37 UTC, kambala-decapitator requested changes

2021-04-17 17:37 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +}
maybe it'd be easier to just set to NO in didEndEditing?

2021-04-17 20:05 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +}
No, this does not work as `searchBarTextDidEndEditing` is called always when leaving the view. You would never see a situation with `showkeyboard == YES`.

2021-04-18 05:24 UTC, merged