Fix new XCode 12.5 cast warnings
xbmc/Official-Kodi-Remote-iOS pull request #276
Opened 2021-05-06 17:54 UTC by wutschel

## Description

With XCode 12.5 new compile warning show up. This PR fixes them.

## Summary for release notes

Maintenance: Fix compiler warnings introduced with XCode 12.5

2021-05-06 18:02 UTC, kambala-decapitator requested changes
a much better fix would be using `@(var)` ;)

2021-05-06 18:32 UTC, wutschel commented
> a much better fix would be using `@(var)` ;) but that's probably a task for the big cleanup "convert to modern objc syntax"

`@((NSInteger)connection)` instead of `[NSNumber numberWithInteger:(NSInteger)connection]` ?

2021-05-06 18:43 UTC, kambala-decapitator commented
no, simply `@(connection)`

2021-05-06 20:21 UTC, wutschel commented
> no, simply `@(connection)`

Doesn't compile for me.

2021-05-06 20:40 UTC, kambala-decapitator commented
ah, I see now. Existing code treats object as an integer (pointer). You'd rather use `NSValue` for that:
```objc
__auto_type connectionKey = [NSValue valueWithNonretainedObject:connection];
```

but I think this approach deserves a proper refactoring, using connections as keys doesn't look great.

2021-05-07 05:34 UTC, wutschel commented
> ah, I see now. Existing code treats object as an integer (pointer). You'd rather use `NSValue` for that:
> 
> ```objc
> __auto_type connectionKey = [NSValue valueWithNonretainedObject:connection];
> ```

Thanks, took your suggestion and updated the code.

> but I think this approach deserves a proper refactoring, using connections as keys doesn't look great.

Agreed, I was also wondering about this when I recognized it.

2021-05-07 09:51 UTC, kambala-decapitator requested changes
please also use dictionary subscript in the changed lines

2021-05-07 09:51 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    __auto_type  connectionKey = [NSValue valueWithNonretainedObject:connection];
```suggestion
    __auto_type connectionKey = [NSValue valueWithNonretainedObject:connection];
```

2021-05-07 16:11 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    __auto_type  connectionKey = [NSValue valueWithNonretainedObject:connection];
Done

2021-05-11 08:51 UTC, merged