Rework AppDelegate.m/.h
xbmc/Official-Kodi-Remote-iOS pull request #283
Opened 2021-05-11 17:36 UTC by wutschel

## Description

Long planned change to rework `AppDelegate.m` which holds the main configuration for JSON requests to Kodi server and the main menus. The rework will move to easier-to-read literals instead of initializers and will use common methods for repeated code sequences.

This should be observed in TF builds for a while. Making this a draft PR until we see the 1.7 Release showed no issues over a reasonable amount of time.

## Summary for release notes

Maintenance: Rework AppDelegate.m/.h

2021-05-16 16:02 UTC, wutschel commented
@kambala-decapitator, as the changes are anyhow too big to review partially, I will squash them into one commit once you´re ok with the last single commits I did (starting from b883386).

2021-05-29 08:13 UTC, wutschel commented
Squashed few commits (fixes which are now already merged to master) and rebased to master.

2021-06-09 19:01 UTC, wutschel commented
@kambala-decapitator, you see a possibility to look into this? Most of the other PRs should not be merged before this one.

2021-06-13 08:43 UTC, kambala-decapitator requested changes
oh man, that's really a task for an automatic tool like clang-format 😁 (iirc I already mentioned that) What do you think about integrating it and editing the whole codebase in a single PR/commit?

I can't comment on every single line of course, only outlined common patterns I noticed.

Btw which of the two PRs should be merged first?

2021-06-13 08:43 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +#define ITEM_MUSIC_PHONE_WIDTH 106.0f
don't see a reason to use float

2021-06-13 08:43 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +    NSDictionary* item = @{
in this case I'd suggest to drop the useless variable and return object directly

2021-06-13 08:43 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +            @{
please move the opening brace on the above line

2021-06-13 08:43 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +                @"width":               @(ITEM_MUSIC_PHONE_WIDTH),
I'd suggest not to use vertical alignment, just a single space is enough

2021-06-13 08:43 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +        animationStartX = @(STACKSCROLL_WIDTH);
```suggestion
        animationStartBottomScreen = @NO;
        animationStartX = @STACKSCROLL_WIDTH;
```
and the same for all other literals

2021-06-13 08:43 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +    mainMenu *menu_Music = [[mainMenu alloc] init];
```suggestion
    __auto_type menu_Music = [mainMenu new];
```

2021-06-13 08:43 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +            @"st_album", @"st_artist", @"st_genre", @"st_filemode", @"st_album_recently", @"st_songs_recently", @"st_album_top100", @"st_songs_top100", @"st_album_recently_played", @"st_songs_recentl
please put every value on a separate line

2021-06-13 08:43 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +            @[@"AudioLibrary.GetAlbums", @"method", @"AudioLibrary.GetAlbumDetails", @"extra_info_method"],
please put every value on a separate line

2021-06-13 08:43 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +- (NSDictionary*)setcolor:(void*)x r:(float)r g:(float)g b:(float)b {
1. what's the point of the unused `x` param?
2. use `double` instead (and drop `f` suffix from the calling code)

2021-06-13 08:43 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.h
> +#define NSLocStr(string) NSLocalizedString(string, nil)
please use a better name, e.g. `LOCALIZED_STR`

2021-06-13 08:50 UTC, wutschel commented
> oh man, that's really a task for an automatic tool like clang-format 😁 (iirc I already mentioned that) What do you think about integrating it and editing the whole codebase in a single PR/commit?

As far as I remember I tried this and couldn´t get this working. Let´s now move on with how it is.

> I can't comment on every single line of course, only outlined common patterns I noticed.

Yes, this is the feedback I need. I change wherever the pattern occurs.

> Btw which of the two PRs should be merged first?

Doesn´t matter, they can be merged independently.

2021-06-13 09:07 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +#define ITEM_MUSIC_PHONE_WIDTH 106.0f
Ok, will be done with next forced push.

2021-06-13 09:09 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +                @"width":               @(ITEM_MUSIC_PHONE_WIDTH),
I find this quite well readable, but would change it if you are concerned.

2021-06-13 09:13 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +- (NSDictionary*)setcolor:(void*)x r:(float)r g:(float)g b:(float)b {
`CGFloat` would also do?

2021-06-13 09:15 UTC, wutschel commented on XBMC Remote/AppDelegate.h
> +#define NSLocStr(string) NSLocalizedString(string, nil)
Done with next forced push.

2021-06-13 09:16 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +                @"width":               @(ITEM_MUSIC_PHONE_WIDTH),
the main point is: if at some point you add a new key which is quite long, it could break current structure and you'll have to re-align everything else to match it.

2021-06-13 09:17 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +- (NSDictionary*)setcolor:(void*)x r:(float)r g:(float)g b:(float)b {
I'd use `double` to avoid float->double conversions on 32-bit platforms (or vice versa on 64 bit)

2021-06-13 09:22 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +    mainMenu *menu_Music = [[mainMenu alloc] init];
I guess it is also desired to change other calls of `[mainMenu alloc] init]` with `[mainMenu new]`, e.g. when instantiating the submenus.

2021-06-13 09:31 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +                @"width":               @(ITEM_MUSIC_PHONE_WIDTH),
Ok, done with next forced push.

2021-06-13 09:34 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +    mainMenu *menu_Music = [[mainMenu alloc] init];
correct

2021-06-13 09:41 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +- (NSDictionary*)setcolor:(void*)x r:(float)r g:(float)g b:(float)b {
Ok, will change the method to `setColorRed:Green:Blue` using `double.`

2021-06-13 09:42 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +    mainMenu *menu_Music = [[mainMenu alloc] init];
Consider this done.

2021-06-13 09:50 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +    NSDictionary* item = @{
Ok, will do this this for _all_ functions which simply return a dictionary or array item.

2021-06-13 09:59 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +        animationStartX = @(STACKSCROLL_WIDTH);
Done.

2021-06-13 10:11 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +            @[@"AudioLibrary.GetAlbums", @"method", @"AudioLibrary.GetAlbumDetails", @"extra_info_method"],
At least we should keep the pairs of key (e.g. `"method"`) and object (`"AudiLibrary.GetAlbums"`) in one line. These should be dictionaries -- and they´re somewhere converted to this. I wanted to rework this as well, but faced too many hurdles and for now kept it like this.

2021-06-13 10:18 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +            @[@"AudioLibrary.GetAlbums", @"method", @"AudioLibrary.GetAlbumDetails", @"extra_info_method"],
fully agree

2021-06-13 10:25 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +            @[@"AudioLibrary.GetAlbums", @"method", @"AudioLibrary.GetAlbumDetails", @"extra_info_method"],
Consider this done.

2021-06-13 10:26 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +            @"st_album", @"st_artist", @"st_genre", @"st_filemode", @"st_album_recently", @"st_songs_recently", @"st_album_top100", @"st_songs_top100", @"st_album_recently_played", @"st_songs_recentl
You ask the same for each other array as well, e.g.

```
@"properties":
                    @[@"genre", @"year", @"duration", @"track", @"thumbnail", @"rating", @"playcount", @"artist", @"album", @"file"]
```

2021-06-13 10:27 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +            @{
Same for these kind of places, so always pulling the opening brace into the line where the key is used?

```
@"properties":
                    @[@"genre", @"year", @"duration", @"track", @"thumbnail", @"rating", @"playcount", @"artist", @"album", @"file"]
```

2021-06-13 10:46 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +            @"st_album", @"st_artist", @"st_genre", @"st_filemode", @"st_album_recently", @"st_songs_recently", @"st_album_top100", @"st_songs_top100", @"st_album_recently_played", @"st_songs_recentl
absolutely right :)

2021-06-13 10:47 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +            @{
yes.
```objc
@"properties": @[
  @"genre",
  ...
]
```

2021-06-13 10:51 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +            @{
Ok, will rework accordingly. Exception: one-liners like `@"properties": @[@"thumbnail"]`.

2021-06-13 11:40 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +            @"st_album", @"st_artist", @"st_genre", @"st_filemode", @"st_album_recently", @"st_songs_recently", @"st_album_top100", @"st_songs_top100", @"st_album_recently_played", @"st_songs_recentl
Done

2021-06-13 11:41 UTC, wutschel commented
All suggestions added, squashed all into 1 commit.

2021-06-13 13:50 UTC, merged