Extensive rework (coding style and refactoring)
xbmc/Official-Kodi-Remote-iOS pull request #286
Opened 2021-05-13 23:49 UTC by wutschel

## Description

This PR extensively reworks the code with respect to coding styles. In addition, it does refactoring in the area of processing Music/Movies/TVShows metadata to reduces code duplication

Details:
- Use literals instead of `objectAtIndex`, `objectForKey`, `numberWithBool`, `numberWithInt`, `numberWithFloat`, `arrayWithObjects`, `initWithObjects` and `setObject:forKey:`
- Use `YES`/`NO` instead of `TRUE`/`FALSE`
- Remove `==YES` and `==NO` conditions
- Unify usage of spaces and condition/loop braces
- Duplicate code moved to `Utilities`

## Summary for release notes

Maintenance: Coding styles and refactoring

2021-05-31 13:52 UTC, wutschel commented
Rebased to master.

2021-06-09 19:01 UTC, wutschel commented
@kambala-decapitator, you see a possibility to look into this? Most of the other PRs should not be merged before this one.

2021-06-09 19:04 UTC, wutschel commented
> yes, plan to do over the next days

I really appreciate this, I know this will take some time.

2021-06-13 09:14 UTC, kambala-decapitator requested changes
Generally looks good. As you understand, I didn't check every line closely :)

2 more general points:

1. remove `synchronize` call of `NSUserDefaults` - it's useless nowadays
2. the `indexKeyed` commit I'm not quite sure: iirc it's a special method of `NSObject` to allow some KVC stuff, please check manual to verify that nothing gets broken.

2021-06-13 09:14 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    }
Better use format string with appropriate specifier to add leading zero, it's `%02d` iirc (check `printf` manual)

2021-06-13 09:14 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    if ([text isEqualToString:@"(null)"]) {
why not compare `dict[key]` to `[NSNull null]` instead? (also in other methods)

2021-06-13 09:14 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +            path = dict[key];
probably add `break`?

2021-06-13 09:14 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    if (path != nil && ![path isEqualToString:@""] && ![path isEqualToString:@"(null)"]) {
```suggestion
    if (path.length > 0 && ![path isEqualToString:@"(null)"]) {
```

2021-06-13 09:14 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    if ([art count] && [art[@"poster"] length] != 0) {
drop `[art count]` check (also below)

2021-06-13 09:14 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    if ([art count] && [art[@"banner"] length] != 0 && useBanner) {
check the BOOL first (also below)

2021-06-13 11:52 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    if ([art count] && [art[@"banner"] length] != 0 && useBanner) {
Done

2021-06-13 11:52 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    if ([art count] && [art[@"poster"] length] != 0) {
Done

2021-06-13 11:54 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    if (path != nil && ![path isEqualToString:@""] && ![path isEqualToString:@"(null)"]) {
Looks good, agreed.

2021-06-13 12:01 UTC, wutschel commented on XBMC Remote/Utilities.m
> +            path = dict[key];
Agreed

2021-06-13 12:06 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +//        int playbackOriginY = [[formatter stringFromNumber:@(:(albumThumbHeight/2 - btnImage.size.height/2 + albumViewPadding))] intValue];
Oops.

2021-06-13 12:06 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +//        int playbackOriginX = [[formatter stringFromNumber:@((albumThumbHeight/2 - btnImage.size.width/2 + albumViewPadding))] intValue];
Yep, done.

2021-06-13 12:11 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    if ([text isEqualToString:@"(null)"]) {
Good idea. You mean like

```
else if (dict[key] == [NSNull null]) {
    text = empty;
}
else {
    text = [dict[key] length] == 0 ? empty : dict[key];
}
```

2021-06-13 12:32 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    }
True can be compressed to:

```
int secs = [seconds intValue];
int hour   = secs / 3600;
int minute = secs / 60 - hour * 60;
int second = secs - (hour * 3600 + minute * 60);
if (hour == 0) {
    result = [NSString stringWithFormat:@"%02d:%02d", minute, second];
}
else {
    result = [NSString stringWithFormat:@"%d:%02d:%02d", hour, minute, second];
}
```

2021-06-13 12:39 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    if ([text isEqualToString:@"(null)"]) {
Better like this:
```objc
NSString *text;
id value = dict[key];
if (value == [NSNull null]) {
    text = @""; // why not empty?
}
else if ([value isKindOfClass:[NSArray class]]) {
    text = [value count] > 0 ? [value componentsJoinedByString:@" / "] : empty;
}
else {
    text = [value length] > 0 ? value : empty;
}
return text;
```

2021-06-13 12:42 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    }
yes, just based on the current code `hour` should also be `%02d`

2021-06-13 12:44 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        currentValue = [NSString stringWithFormat:@"%ld", ((long)[[NSString stringWithFormat:@"%@", @([currentValue integerValue] / 15.0f)] integerValue] * 15) + 15 ];
This would simply become

`currentValue = [NSString stringWithFormat:@"%ld", ([currentValue integerValue] / 15) * 15 + 15];`

2021-06-13 12:50 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    }
Like this:
```
result = [NSString stringWithFormat:@"%02d:%02d", minute, second];
if (hour > 0) {
    result = [NSString stringWithFormat:@"%02d:%@", hour, result];
}
```

2021-06-13 12:53 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        currentValue = [NSString stringWithFormat:@"%ld", ((long)[[NSString stringWithFormat:@"%@", @([currentValue integerValue] / 15.0f)] integerValue] * 15) + 15 ];
looks good

2021-06-13 12:54 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    }
yep

2021-06-13 13:30 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    if ([text isEqualToString:@"(null)"]) {
Ok, included this with the last forced push (also for the other two places).

2021-06-13 13:31 UTC, wutschel commented
Updated as per review comments and squashed with the commits which did the initial changes.

2021-06-13 13:45 UTC, kambala-decapitator commented
what about this?

> 1. remove `synchronize` call of `NSUserDefaults` - it's useless nowadays
> 2. the `indexKeyed` commit I'm not quite sure: iirc it's a special method of `NSObject` to allow some KVC stuff, please check manual to verify that nothing gets broken.

2021-06-13 13:47 UTC, wutschel commented
> what about this?

Sorry, was only checking if all conversation were closed. Let me look into this now.

2021-06-13 14:07 UTC, wutschel commented
Rebase to master and removed occurances of `[NSUserDefaults synchronize]`.

> 2. the `indexKeyed` commit I'm not quite sure: iirc it's a special method of `NSObject` to allow some KVC stuff, please check manual to verify that nothing gets broken.

The `indexedKey` stuff is related to the way how the methods are defined in `AppDelegate.m`. As I wrote in the other PR I was trying to rework this and get rid of the `indexedKey` methods, but there is more to do before this would work. For now the code does the same as before, but doubled code is avoided.

2021-06-13 14:23 UTC, kambala-decapitator commented
thanks!

2) I thought it had something to do with https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/KeyValueCoding/SearchImplementation.html#//apple_ref/doc/uid/20000955-CJBBBFFA, but I was wrong.

LGTM.

2021-06-13 14:24 UTC, merged

2021-06-13 16:21 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    if ([text isEqualToString:@"(null)"]) {
Argh, this causes problems I was not seeing when quickly checking. When the key is not part of the dictionary `value = 0x0` and the condition `value == [NSNull null]` is not true. This results in "(null)" strings in the UI, e.g. when the TV station list does not have all data loaded.

It helps to change the condition to `(value == [NSNull null] || value == nil)`.

2021-06-13 16:25 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    if ([text isEqualToString:@"(null)"]) {
You're absolutely right, sorry for misleading you: I confused `NSNull` with `nil` :(

2021-06-13 16:29 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    if ([text isEqualToString:@"(null)"]) {
No worries. I can just change it to `value == nil` then, right?

2021-06-13 16:29 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    if ([text isEqualToString:@"(null)"]) {
yes, or `!value`

2021-06-13 16:33 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    if ([text isEqualToString:@"(null)"]) {
Went for `== nil `-> here we go: https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/327