Releases Notes for 1.7.1
xbmc/Official-Kodi-Remote-iOS pull request #301
Opened 2021-05-17 13:53 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/300.

## Summary for release notes

[not app] Release Notes 1.7.1

2021-05-19 13:00 UTC, kambala-decapitator commented
what do you think about adding some note regarding TF testing to release notes? That more users are aware of it.

2021-05-19 18:04 UTC, wutschel commented
> what do you think about adding some note regarding TF testing to release notes? That more users are aware of it.

Directly adding https://testflight.apple.com/join/VQkpfqDN? Or is the AppStore allowing to place a html link (<a href="https://testflight.apple.com/join/VQkpfqDN">Access to Beta-Software in TestFlight</a>.)

2021-05-20 08:22 UTC, kambala-decapitator commented
probably not the link itself as it's not clickable afaik, but rather some text mentioning TF and forums.

the only URL fields there are don't look suitable for TF link:
![Screenshot 2021-05-20 at 09 57 39](https://user-images.githubusercontent.com/1557784/118944976-b71a8e00-b95d-11eb-9a79-475f43708b7a.png)

2021-05-20 19:01 UTC, kambala-decapitator commented
> Ok, no hyperlink/html then. What about putting a footer like this:
> 
> > Beta-Testers are welcome to join us on TestFlight. Please follow us on https://forum.kodi.tv/forumdisplay.php?fid=193.

Yes, good idea! Please add to the PR.

> Btw, wouldn´t marketing URL be https://kodi.tv?

doesn't quite fit here I think:

> A URL with marketing information about your app. This URL will be visible on the App Store.

2021-05-20 19:08 UTC, wutschel commented
> Yes, good idea! Please add to the PR.

Done

> > Btw, wouldn´t marketing URL be https://kodi.tv?
> 
> doesn't quite fit here I think:
> 
> > A URL with marketing information about your app. This URL will be visible on the App Store.

I think this fits quite well. Following links from this page the remote App is listen. It somehow is the Kodi home, the App is a kind of spin-off from there.

2021-05-20 19:09 UTC, kambala-decapitator requested changes

2021-05-20 19:09 UTC, kambala-decapitator commented on fastlane/metadata/en-US/release_notes.txt
> +- Fix volume up/down button function for iPhone
please make it the first item

2021-05-20 19:09 UTC, kambala-decapitator commented on fastlane/metadata/en-US/release_notes.txt
> +Beta-Testers are welcome to join us on TestFlight. Please follow us on https://forum.kodi.tv/forumdisplay.php?fid=193.
```suggestion
Beta-testers are welcome to join TestFlight! Please follow us on https://forum.kodi.tv/forumdisplay.php?fid=193
```

2021-05-20 19:11 UTC, kambala-decapitator commented
> I think this fits quite well. Following links from this page the remote App is listen. It somehow is the Kodi home, the App is a kind of spin-off from there.

ok :) then please add the URL to `fastlane/metadata/en-US/marketing_url.txt`

2021-05-20 19:32 UTC, wutschel commented on fastlane/metadata/en-US/release_notes.txt
> +Beta-Testers are welcome to join us on TestFlight. Please follow us on https://forum.kodi.tv/forumdisplay.php?fid=193.
Done

2021-05-20 19:36 UTC, wutschel commented on fastlane/metadata/en-US/release_notes.txt
> +- Fix volume up/down button function for iPhone
Sorry, I don't understand your comment.

2021-05-20 20:36 UTC, wutschel commented on fastlane/metadata/en-US/release_notes.txt
> +- Fix volume up/down button function for iPhone
:) Done

2021-05-21 06:20 UTC, merged