Feature: Refresh of remote control screen buttons
xbmc/Official-Kodi-Remote-iOS pull request #312
Opened 2021-05-31 10:57 UTC by wutschel

## Description

This PR is an add-on to https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/311 and refreshes the icons/buttons of the remote control screen, as well as of the remote help screen. Screenshots can be found in #310.

## Summary for release notes

Feature: Refresh remote control screen buttons (aligned with Kodi 19)

2021-05-31 11:20 UTC, wutschel commented
I am adding this PR as work-in-progress to allow testing. It should be added only after the bigger code style and AppDelegate rework PRs to avoid problems rebasing those.

2021-06-13 19:44 UTC, wutschel commented
Rebased to master.

2021-06-21 18:56 UTC, wutschel commented
Rebased to master.

2021-06-25 13:54 UTC, kambala-decapitator requested changes
> Only keep remote images with 2x resolution

are you sure that's correct? We support iOS 9 which iPad 2 is capable of running, and it's non-retina.

2021-06-25 13:54 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +    CGFloat newWidth = remoteControlView.frame.size.width - ANCHORRIGHTPEEK;
please add underscores to the macro, it's quite difficult to read

2021-06-25 13:54 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +    CGFloat upperButtonLowerBorder = CGRectGetMaxY(((UIButton*)[self.view viewWithTag:6]).frame);
no need to cast to `UIButton`

2021-06-25 13:54 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +    frame = self.view.superview.frame;
using superview's `frame` (as opposed to `bounds`) in subview's calculations is generally incorrect. What are you trying to achieve here?

2021-06-25 13:54 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        [remoteControlView setFrame:CGRectMake(frame.origin.x, frame.origin.y, frame.size.width, frame.size.height)];
```suggestion
        remoteControlView.frame = frame;
```

2021-06-25 13:54 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        CGFloat scaleFactorVertical =  minViewHeight / remoteControlView.frame.size.height;
please use `CGRectGetHeight` for consistency

2021-06-25 13:54 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        CGFloat newHeight = remoteControlView.frame.size.height * transform;
`CGRectGet...`

2021-06-25 13:54 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        CGRect frame = CGRectMake(self.view.bounds.size.width - 256, self.view.bounds.size.height - TOOLBAR_ICON_SIZE - TOOLBAR_SPACING, TOOLBAR_ICON_SIZE, TOOLBAR_ICON_SIZE);
what is 256?

2021-06-25 13:54 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        frame.origin.x = frame.origin.x + TOOLBAR_PADDING;
FYI it's simpler to use `+=` operator:
```suggestion
        frame.origin.x += TOOLBAR_PADDING;
```

2021-06-25 13:54 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        frame.origin.x = frame.origin.x + TOOLBAR_PADDING;
+=

2021-06-25 13:54 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        frame.origin.x = frame.origin.x + TOOLBAR_PADDING;
+=

2021-06-25 19:34 UTC, wutschel commented
> are you sure that's correct? We support iOS 9 which iPad 2 is capable of running, and it's non-retina.

I was wondering if we really need the x1 images as there are also no 1x images for the gesture zone. Of course I can easily add the 1x images for remote help. Should I?

2021-06-25 19:38 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    CGFloat newWidth = remoteControlView.frame.size.width - ANCHORRIGHTPEEK;
You mean `ANCHORRIGHTPEEK`? If so, would you mind if I am doing this in a separate coding styles PR? This change touches several other files which are not connected to this PR.

2021-06-25 19:48 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    CGFloat upperButtonLowerBorder = CGRectGetMaxY(((UIButton*)[self.view viewWithTag:6]).frame);
Ok, will be done with next uodate.

2021-06-25 19:53 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        [remoteControlView setFrame:CGRectMake(frame.origin.x, frame.origin.y, frame.size.width, frame.size.height)];
Ok, will be part of next update.

2021-06-25 19:55 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        frame.origin.x = frame.origin.x + TOOLBAR_PADDING;
Ok, will do this the other 3 occasions as well.

2021-06-25 20:05 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        CGRect frame = CGRectMake(self.view.bounds.size.width - 256, self.view.bounds.size.height - TOOLBAR_ICON_SIZE - TOOLBAR_SPACING, TOOLBAR_ICON_SIZE, TOOLBAR_ICON_SIZE);
Argh, I already defined `TOOLBAR_START` for this. It also has the correct value, 256 was even a bit off. Will be part of next update.

2021-06-25 20:15 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        CGFloat scaleFactorVertical =  minViewHeight / remoteControlView.frame.size.height;
No problem, done with next update.

2021-06-25 20:15 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        CGFloat newHeight = remoteControlView.frame.size.height * transform;
No problem, done with next update.

2021-06-25 20:26 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +    CGFloat newWidth = remoteControlView.frame.size.width - ANCHORRIGHTPEEK;
sure that's ok

2021-06-25 20:27 UTC, kambala-decapitator commented
> > are you sure that's correct? We support iOS 9 which iPad 2 is capable of running, and it's non-retina.
> 
> I was wondering if we really need the x1 images as there are also no 1x images for the gesture zone. Of course I can easily add the 1x images for remote help. Should I?

yes please

2021-06-25 21:10 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    frame = self.view.superview.frame;
I wanted to draw the background image ("remote_temp") with same relative dimensions for this use case (embedded view) as for the standard remote view. This background image is at the same hierarchy level as the remote control view itself. 
The embedded view is drawn into a cell of a height of only 50 (see call of `[remoteControllerView setEmbeddedView]` in `RightMenuViewController.m`). The same dimensions I get when using `self.view.superview.frame` inside `setEmbeddedView`.

2021-06-25 21:24 UTC, wutschel commented
Rebased to master and updated regarding the review comments, except 

- `ANCHORRIGHTPEEK`: Will be done in separate PR
- Using superview's `frame` in `setEmbeddedView `: Still open

2021-06-26 07:09 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    frame = self.view.superview.frame;
I get the same desired behaviour if I remove

```
frame = self.view.superview.frame;
panFallbackImageView.frame = frame;
```

and set the frame after `setEmbeddedView` in `RightMenuViewController.m` like this:

```
[remoteControllerView setEmbeddedView];
remoteControllerView.panFallbackImageView.frame = cell.frame;
```

2021-06-26 10:19 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +    frame = self.view.superview.frame;
the latter looks much clearer, please use that

2021-06-26 10:24 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    frame = self.view.superview.frame;
Done.

2021-06-26 10:25 UTC, wutschel commented
Resolved last review comment regarding `setEmbeddedView`.

2021-06-26 10:36 UTC, merged