Read setting to show 1-movie-sets and ignore such sets when disabled
xbmc/Official-Kodi-Remote-iOS pull request #313
Opened 2021-05-31 11:09 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/308.

The App always shows **all** movie sets, independent of the Kodi server user setting to only show movie sets with >1 movie. This PR will enable the App to respect the Kodi server user setting. It will read `videolibrary.groupsingleitemsets` at connect, so in case you change the setting you need to re-connect once. If the user wants to ignore 1-movie sets, a post-processing is applied to remove the irrelevant movie sets from the list provided via the API.

## Summary for release notes

Feature: Respect setting to show/ignore 1-movie sets

2021-05-31 11:20 UTC, wutschel commented
I am adding this PR as work-in-progress to allow testing. It should be added only after the bigger code style and AppDelegate rework PRs to avoid problems rebasing those.

2021-06-13 18:02 UTC, wutschel commented
Rebased to master.

2021-06-20 09:28 UTC, kambala-decapitator requested changes

2021-06-20 09:28 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +         BOOL ignoreSingleMovieSets = (![AppDelegate instance].isGroupSingleItemSetsEnabled && [methodToCall isEqualToString:@"VideoLibrary.GetMovieSets"]);
please drop parentheses

2021-06-20 09:28 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                         __block NSMutableDictionary *newDict = [NSMutableDictionary dictionaryWithObjectsAndKeys:
`NSMutableDictionary *__block newDict = [@{...} mutableCopy];`

do you really need `__block` here? You aren't assigning new value inside the block to this variable.

2021-06-20 09:28 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                             NSDictionary *newParameter = @{@"setid": @([videoLibraryMovies[i][@"setid"] intValue])};
not clear why you're unwrapping `setid` and wrapping it again. Is it stored as a string in the original dictionary?

2021-06-20 09:28 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                             __block BOOL isLastItem = i == total-1;
`__block` isn't needed here

2021-06-20 09:51 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +         BOOL ignoreSingleMovieSets = (![AppDelegate instance].isGroupSingleItemSetsEnabled && [methodToCall isEqualToString:@"VideoLibrary.GetMovieSets"]);
Ok, will be part of update.

2021-06-20 09:53 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                         __block NSMutableDictionary *newDict = [NSMutableDictionary dictionaryWithObjectsAndKeys:
Thanks for pointing me to this. It is not needed anymore, and is left-over from first draft implementations. Will remove this with next update.

2021-06-20 09:53 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                             __block BOOL isLastItem = i == total-1;
Same here.

2021-06-20 09:57 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                             NSDictionary *newParameter = @{@"setid": @([videoLibraryMovies[i][@"setid"] intValue])};
No, the original dictionary also provides a number. I felt this is more robust. When I was working on the "ignore-articles"-PR I found different behaviour when providing some objects for music and movies. I can remove this though, if you would like to have this changed. You are looking for `NSDictionary *newParameter = @{@"setid": videoLibraryMovies[i][@"setid"]}`, correct?

2021-06-21 18:01 UTC, kambala-decapitator commented
seems you haven't updated the branch yet :)

2021-06-21 18:27 UTC, wutschel commented
> seems you haven't updated the branch yet :)

Yes, was waiting for your response on the unwrapping-topic. Updated now.

2021-06-22 06:52 UTC, merged