Feature: Make main menu configurable
xbmc/Official-Kodi-Remote-iOS pull request #315
Opened 2021-05-31 15:09 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/306.

Details:
- Each main menu entry can be switched on/off in Kodi App settings (default is ON for each)
- Added localized strings for English and German
- Minor refactoring when building the menu (iPad per default now also has NowPlaying)

## Summary for release notes

Feature: Make main menu configurable

2021-05-31 15:09 UTC, wutschel commented
I am adding this PR as work-in-progress to allow testing. It should be added only after the bigger code style and AppDelegate rework PRs to avoid problems rebasing those.

2021-06-14 16:55 UTC, wutschel commented
Rebased to master.

2021-06-21 19:05 UTC, wutschel commented
Rebased to master.

2021-06-25 13:59 UTC, kambala-decapitator requested changes
looks good, just one change to make

2021-06-25 13:59 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +-(BOOL)isMenuEntryEnabled:(NSUserDefaults*)userDefault menu:(NSString*)menuItem {
doesn't make much sense to pass `NSUserDefaults` singleton as parameter

2021-06-25 21:33 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +-(BOOL)isMenuEntryEnabled:(NSUserDefaults*)userDefault menu:(NSString*)menuItem {
Like this:

```
-(BOOL)isMenuEntryEnabled:(NSString*)menuItem {
    id menuEnabled = [[NSUserDefaults standardUserDefaults] objectForKey:menuItem];
    return (menuEnabled == nil || [menuEnabled boolValue]);
}
```

2021-06-26 09:59 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +-(BOOL)isMenuEntryEnabled:(NSUserDefaults*)userDefault menu:(NSString*)menuItem {
Decided to go with first option.

2021-06-26 09:59 UTC, wutschel commented
Rebased to master and updated following the review comment.

2021-06-26 10:21 UTC, merged