Feature: Implement favourites menu
xbmc/Official-Kodi-Remote-iOS pull request #316
Opened 2021-06-01 09:30 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/268.
Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/55.

This PR implements support for Kodi´s favourites. Details:
- Adding a main menu entry named "Favourites"
- Loading favourites from Kodi and display name and -- if available and loadable -- thumbs
- When selecting an item either play (`media` type), activate window on Kodi server (`window` type) or show an error (`unknown` type)

Remarks:
- Not possible to start showing favourite pictures as they are reported as `unknown` type 
- TV station logo background selection does not work as the API just reports channels as `media` type (like movies or music)
- Change is made on top of https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/283 for ease of changes to `AppDelegate.m`
- Needs to be aligned with the PRs related icon update coding style & refactoring and configurable main menu.

Screenshots:
https://abload.de/img/simulatorscreenshot-i7ekrd.png
https://abload.de/img/simulatorscreenshot-iz5k48.png
https://abload.de/img/simulatorscreenshot-iidj42.png

## Summary for release notes

Feature: Support Kodi favourites

2021-06-14 17:44 UTC, wutschel commented
Rebased to master.

2021-06-21 19:05 UTC, wutschel commented
Rebased to master.

2021-06-25 14:10 UTC, kambala-decapitator requested changes

2021-06-25 14:10 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +                @"row2": @"none",
is it possible to use `[NSNull null]` instead of `@"none"`?

2021-06-25 14:10 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +        menu_Favourites.family = 1;
what is 1?

2021-06-25 14:10 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            [messagesView showMessage:NSLocalizedString(@"Cannot do that", nil) timeout:2.0 color:[Utilities getSystemRed:0.95]];
I'd suggest to show `item` info in the dialog, at least the type

2021-06-25 14:10 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        if ([path rangeOfString:@"image://"].location == NSNotFound) {
probably `hasPrefix` method makes more sense here?

2021-06-25 14:10 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +            urlString = [NSString stringWithFormat:@"http://%@%@", serverURL, [path stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLPathAllowedCharacterSet]]];
don't you want to strip `image://` from the URL?

2021-06-25 21:48 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +        menu_Favourites.family = 1;
Oh, this is a magic number which is obviously used when determining which type the controller is that shall be loaded. 1 for `DetailViewController`, 2 for `NowPlaying`, 3 for `RemoteController` and 4 for `HostManagementViewController`. I was not bothering to change this.

2021-06-26 09:18 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +                @"row2": @"none",
Yes, this is possible. Will change this for the next update.

2021-06-26 09:28 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            [messagesView showMessage:NSLocalizedString(@"Cannot do that", nil) timeout:2.0 color:[Utilities getSystemRed:0.95]];
No problem, will be part of next update.

2021-06-26 09:33 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        if ([path rangeOfString:@"image://"].location == NSNotFound) {
Thanks, I will change this to `if (![path hasPrefix:@"image://"]) {`

2021-06-26 09:41 UTC, wutschel commented on XBMC Remote/Utilities.m
> +            urlString = [NSString stringWithFormat:@"http://%@%@", serverURL, [path stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLPathAllowedCharacterSet]]];
No, it seems this is needed to load the image which are in Kodi´s thumbnail path. If I remove this, the thumbs are not loaded anymore.

2021-06-26 09:42 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +        menu_Favourites.family = 1;
I could change this to use a enum in separate PR.

2021-06-26 10:02 UTC, wutschel commented
Rebased to master and reworked according to review comments. Changing `family` to enum can be done in separate PR.

2021-06-26 10:22 UTC, kambala-decapitator commented
> Changing `family` to enum can be done in separate PR.

sure, that's fine

2021-06-26 10:22 UTC, kambala-decapitator approved these changes

2021-06-26 10:58 UTC, wutschel commented
Resolved conflicts caused by making main menu configurable. Rebased to master and ready to go.

2021-06-26 11:01 UTC, merged