Hide non-used buttons in toolbar
xbmc/Official-Kodi-Remote-iOS pull request #319
Opened 2021-06-02 16:12 UTC by wutschel

## Description

Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/318.

Details:
- Fixes visible highlighting when touching un-used / non-loaded buttons (see screenshot in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/318)
- Reworked to modern objective c

## Summary for release notes

Bugfix: Hide non-loaded toolbar buttons

2021-06-13 17:39 UTC, wutschel commented
Rebased to master.

2021-06-20 09:35 UTC, kambala-decapitator requested changes

2021-06-20 09:35 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            CGRect frame = dataList.frame;
does it even compile? Afaik declarations are allowed only inside curly braces, i.e. `case 0: { ... }`.

2021-06-20 09:35 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    switch ([buttons count]) {
```suggestion
    switch (buttons.count) {
```

2021-06-20 09:35 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            selectedMoreTab = [[UIButton alloc] init];
```suggestion
            selectedMoreTab = [UIButton new];
```

2021-06-20 10:01 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            CGRect frame = dataList.frame;
Yes, it does not even throw a warning. I will move the declaration to the outside.

2021-06-20 10:02 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    switch ([buttons count]) {
Agreed, will come with next update.

2021-06-20 10:04 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            selectedMoreTab = [[UIButton alloc] init];
Agreed, will come with next update.

Btw, there are still 100+ occurances of `[bla alloc] init]` in the code. I can -- at a later point in time clean this up with a single commit.

2021-06-20 14:38 UTC, wutschel commented
Reworked as per review comments.

2021-06-21 18:02 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            CGRect frame = dataList.frame;
I'm surprised :) Might have something to do with C vs C++ though.

2021-06-21 18:03 UTC, merged