Feature: Make remote position configurable
xbmc/Official-Kodi-Remote-iOS pull request #344
Opened 2021-07-03 15:55 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/343.

Feedback from users is that -- especially on bigger screens -- the remote is not usable by 1 hand anymore. This PR adds a configuration to select the position of the remote in the window. It is possible to select top, mid and bottom positions.

## Summary for release notes

Feature: Make remote position configurable

2021-07-03 15:56 UTC, wutschel commented
Still marked as draft as I am not 100% satisfied with the safe area handling and the position calculation for newer iPhone.

2021-07-04 12:33 UTC, wutschel commented
With last push-force this works also for iPhone´s embedded view. Test on several devices to ensure the layout calculations are done right. 

Tested devices:
- iPodTouch 7th (iOS 14.5)
- iPhone 5s (iOS 11.4)
- iPhone 6s (iOS 11.4)
- iPhone Xs (iOS 14.5)
- iPad 5th (iOS 14.5)
- iPad Pro 7th 12.9" (iOS 14.5)

Open: Keep position after rotation on iPad.

2021-07-04 12:59 UTC, wutschel commented
Now rotation works.

Open: 
- Remove obsolete menu items from "user-defined-button" menu on iPhone (all functions are now available via remote screen toolbar)
- Remove non-used icons

2021-07-12 06:26 UTC, wutschel commented
Following screenshot shown the remote and custom button screen on iPhone with latest changes, and configured for showing the remote at bottom. I am thinking of also removing the "keyboard" line item as this is also not shown on the iPad custom screen. I kept it until now as the remote screen which is reachable via iPhone´s NowPlay screen is still showing this line item.

Screenshot: https://abload.de/img/bildschirmfoto2021-07qvk2l.png

Question: Are we losing any feature / use case when removing the line items like shown in the screen shot?

2021-07-12 14:44 UTC, kambala-decapitator commented
looks pretty neat in my opinion!

Does the new bottom bar look ok on the smallest device (iPhone 4S)?

> Question: Are we losing any feature / use case when removing the line items like shown in the screen shot?

you'd better ask the audience as I'm not a heavy remote user :) From a simple glance nothing gets lost.

@DakotaONeill what do you think?

2021-07-12 17:34 UTC, wutschel commented
> Does the new bottom bar look ok on the smallest device (iPhone 4S)?

I am not able to install the iPhone 4s simulator on my system. Seems it is requiring an older iOS as the oldest one which I can select in Xcode (iOS 11.4). But you right, I was testing with screen sizes with `height>=568`. Are you able to run a test?

2021-07-14 18:35 UTC, wutschel commented
> 2. Do not show the toolbar and keep supporting the functions/button on the custom button screen.

This was the easiest to implement. Last forced push has these changes.

In general I am not quite happy with the complex layout calculation and the special cases involved. I will try to look into supporting only top/bottom positions and use `UIViewAutoresizing` to align the remote view to top and bottom.

2021-07-15 18:22 UTC, wutschel commented
Huge rework to reduce the complexity. Now `UIViewAutoresizingFlexibleMargin` is used for the positioning and iPhone 4S should be supported properly. In consequence only the remote positions "top" and "bottom" are selectable.

2021-07-18 16:11 UTC, wutschel commented
Next bigger rework to also show a toolbar in the embedded remote view. As part of this rework
- a dedicated toolbar view is used which makes the layout easier
- the init-method has been updated to always initialize the remote view only once (before the layout was updated twice when entering the embedded view)
- the embedded only shows 4 buttons (as the 5th is not supported)

Screenshots (before and after):
https://abload.de/img/bildschirmfoto2021-07ljk96.png (iPhone Xs)
https://abload.de/img/bildschirmfoto2021-07p2je4.png (iPod Touch 7G)
https://abload.de/img/bildschirmfoto2021-07ehkzg.png (iPad 5G)

Remark 1: The "after" screenshots were made with the setting to move the remote screen to the bottom position. Of course it can still be positioned at the top -- still having the new toolbar.
Remark 2: For smaller devices (iPhone 4S) I cannot test. I took care of the small devices as far as I could, but it will be great if someone could provide screenshots.

2021-07-18 20:12 UTC, wutschel commented
It is even possible to add the volume slider to the remote screen for all screens with `height >= 568`. This looks a bit packed though: https://abload.de/img/simulatorscreenshot-icbjfn.png

2021-08-08 08:34 UTC, kambala-decapitator requested changes
may I ask you to split 37d12f5c74065301ef17b334c02e9501dd707ad8 into multiple? It contains a lot of separate changes and is quite difficult to review.

2021-08-08 08:34 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        }
you could also add for the future:

```objc
else {
  NSAssert(NO, @"new mode not handled");
}
```

2021-08-08 08:34 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    if (captureDeviceClass != nil) {
this check is no longer needed

2021-08-08 08:34 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        if ([device hasTorch] && [device hasFlash]) {
please use early return: if not this condition then return

2021-08-08 08:34 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +                [settings setFlashMode:AVCaptureFlashModeOn];
please use properties

2021-08-08 08:34 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +                NSLog(@"Unexpected class. Cannot set image for torch icon.");
use `NSAssert` instead

2021-08-08 08:34 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    if (captureDeviceClass != nil) {
remove the check

2021-08-08 08:34 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> ++ (BOOL)isTorchOn {
you could also return `nil` when device has no torch/flash, if that makes any sense for the calling code

2021-08-08 08:34 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        frame.origin.x = ((remoteControlView.frame.size.width - UIScreen.mainScreen.bounds.size.width) / 2);
please remove the outer brackets

2021-08-08 08:34 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +    if (showGesture) {
early return

2021-08-08 08:34 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +- (void)setGestureView {
please come up with a better method name

2021-08-08 08:34 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +    [remoteControlView setFrame:CGRectMake(0, offset, newWidth, newHeight)];
use property

2021-08-08 08:34 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +    CGRect frame = CGRectMake(CGRectGetMaxX(self.view.frame) - xMin - ToolbarStart, yMax - TOOLBAR_ICON_SIZE - TOOLBAR_FIXED_OFFSET, TOOLBAR_ICON_SIZE, TOOLBAR_ICON_SIZE);
are you sure that using `self.view.frame` is right? You're computing frames for subviews here.

oh, I see you removed this code in the next commit.

2021-08-08 08:34 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +- (void)createRemoteToolbar:(UIImage*)gestureButtonImg width:(CGFloat)width xMin:(CGFloat)xMin yMax:(CGFloat)yMax {
I'd rather use `UIStackView` to create a toolbar.

2021-08-08 08:34 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +    [settingButton setContentMode:UIViewContentModeRight];
please use properties where possible

2021-08-08 08:34 UTC, kambala-decapitator commented
> It is even possible to add the volume slider to the remote screen for all screens with `height >= 568`. This looks a bit packed though: https://abload.de/img/simulatorscreenshot-icbjfn.png

looks fine I'd say

2021-08-08 09:16 UTC, wutschel commented
> may I ask you to split [37d12f5](https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/37d12f5c74065301ef17b334c02e9501dd707ad8) into multiple? It contains a lot of separate changes and is quite difficult to review.

I am sorry, and in general I would have loved to do this. Because of massive refactoring in the course of implementing this feature, I couldn´t find a good way to squash certain changes. That´s why this ended up in one huge commit. Also, I lost my old backup branch when I needed to recreate my local repository. Only option would be to re-implement or split out changes manually now.

How important is this for you?

2021-08-08 10:54 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        }
Done

2021-08-08 10:55 UTC, wutschel commented on XBMC Remote/Utilities.m
> +                NSLog(@"Unexpected class. Cannot set image for torch icon.");
Done

2021-08-08 10:57 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        frame.origin.x = ((remoteControlView.frame.size.width - UIScreen.mainScreen.bounds.size.width) / 2);
Done

2021-08-08 10:59 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +- (void)setGestureView {
`setupGestureView` ? This is what it does.

2021-08-08 11:02 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    if (captureDeviceClass != nil) {
Removed

2021-08-08 11:02 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    if (captureDeviceClass != nil) {
Removed

2021-08-08 11:06 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        if ([device hasTorch] && [device hasFlash]) {
Done

2021-08-08 11:08 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    if (showGesture) {
Done

2021-08-08 11:12 UTC, wutschel commented on XBMC Remote/Utilities.m
> +                [settings setFlashMode:AVCaptureFlashModeOn];
Done, also applied this for `hasTorch` and `hasFlash`.

2021-08-08 11:18 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    [remoteControlView setFrame:CGRectMake(0, offset, newWidth, newHeight)];
Done. I have 100+ calls of `setFrame` in the code. I can change this with a coding style commit.

2021-08-08 11:24 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    [settingButton setContentMode:UIViewContentModeRight];
This is already removed. But there are several calls of `setContentMode` which I can replace with using the property directly. Will do this in a separate commit.

2021-08-08 17:19 UTC, wutschel commented on XBMC Remote/Utilities.m
> ++ (BOOL)isTorchOn {
I would like to keep it as it is, just returning plain `YES` or `NO`.

2021-08-08 17:23 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +- (void)createRemoteToolbar:(UIImage*)gestureButtonImg width:(CGFloat)width xMin:(CGFloat)xMin yMax:(CGFloat)yMax {
Is blocking to approve the PR? I can look into this later.

2021-08-08 19:27 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +- (void)setGestureView {
yep, that's better

2021-08-08 19:27 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +- (void)createRemoteToolbar:(UIImage*)gestureButtonImg width:(CGFloat)width xMin:(CGFloat)xMin yMax:(CGFloat)yMax {
not at all

2021-08-08 19:28 UTC, kambala-decapitator commented
ok, hoped it's straightforward :) will try to review as is.

2021-08-09 05:01 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +- (void)setGestureView {
Done

2021-08-09 05:14 UTC, wutschel commented
> > It is even possible to add the volume slider to the remote screen for all screens with `height >= 568`. This looks a bit packed though: https://abload.de/img/simulatorscreenshot-icbjfn.png
> 
> looks fine I'd say

Ok, will see if I can add this on top of this PR after all the fixups were made and squashed.

2021-08-14 10:00 UTC, kambala-decapitator requested changes
fixups are fine.

also reviewed that huge commit.

> Handle small iPhone displays (width < 576, e.g. iPhone 4S)

width or height?

2021-08-14 10:11 UTC, wutschel commented
> fixups are fine.

Good. Will do the other fixups and find a way to squash this.

> width or height?

height. Will fix the commit's description.

2021-08-14 10:35 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        shift = ((UIButton*)[self.view viewWithTag:21]).frame.size.height;
Done

2021-08-14 10:35 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        shift = 2.0 * ((UIButton*)[self.view viewWithTag:21]).frame.size.height;
Done

2021-08-14 10:37 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    [remoteControlView setFrame:CGRectMake(-1, offset, newWidth, newHeight)];
Already done in later commit.

2021-08-14 10:39 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +            [onoff setFrame:CGRectMake(0, (RIGHT_MENU_ITEM_HEIGHT - onoff.frame.size.height) / 2, onoff.frame.size.width, onoff.frame.size.height)];
Done

2021-08-14 10:42 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +        [toolbar setFrame:CGRectMake(0, 0, frame.size.width, TOOLBAR_HEIGHT)];
Done

2021-08-14 10:43 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        frame.size.width = frame.size.width * transform;
Done

2021-08-14 10:46 UTC, wutschel commented on XBMC Remote/RemoteController.m
>                         [(UIButton*)self.view viewWithTag:2],
You mean the tag IDs?

2021-08-14 10:48 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        quickHelpView.frame = frame;
Between the assignment of frame, to easier differentiate between different assignments? Like this:

```
remoteControlView.frame = frame;
        
frame.origin.y = 0;
quickHelpView.frame = frame;
        
frame = subsInfoLabel.frame;
```

2021-08-14 10:53 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        frame.size.width = CGRectGetWidth(remoteControlView.frame) * transform;
Good catch. I find the `*=` quite well readable. Moving this into a helper could be done, but might be less quickly readable.

2021-08-14 10:54 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        if (captureDeviceClass != nil) {
Yes, already removed with one of the earlier fixup commits.

2021-08-14 10:56 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
>                         [(UIButton*)self.view viewWithTag:2],
yep

2021-08-14 10:57 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        quickHelpView.frame = frame;
exactly

2021-08-14 10:59 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +
Done

2021-08-14 11:01 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +
Already removed later.

2021-08-14 11:02 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +        [title setFrame:CGRectMake(icon.frame.size.width + RIGHT_MENU_ICON_SPACING, (SERVER_INFO_HEIGHT - title.frame.size.height) / 2, tableView.frame.size.width - (icon.frame.size.width + 2 * RIGHT
Done

2021-08-14 11:05 UTC, wutschel reviewed
Test

2021-08-14 11:09 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +        return [[UIScreen mainScreen] bounds].size.height - [self getRemoteViewOffsetY];
Why not simply `UIScreen.mainScreen.bounds.size.height` and `CGRectGetHeight` instead? A fixup commit already did this.

2021-08-14 11:11 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +    CGFloat menuItemsHeight = UIScreen.mainScreen.bounds.size.height >= 568 ? 0 : 3 * RIGHT_MENU_ITEM_HEIGHT;
Yes. Should I create a helper function in `Utilities`?

2021-08-14 11:25 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +        NSMutableDictionary *itemDict = [NSMutableDictionary dictionaryWithObjectsAndKeys:
I double checked this. Mutable is not required, I also changed to literal in a fixup commit.

2021-08-14 11:25 UTC, kambala-decapitator commented on XBMC Remote/RightMenuViewController.m
> +    CGFloat menuItemsHeight = UIScreen.mainScreen.bounds.size.height >= 568 ? 0 : 3 * RIGHT_MENU_ITEM_HEIGHT;
yes please

2021-08-14 11:28 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    if (positionMode == remoteBottom && [self hasRemoteToolBar]) {
This is possible, let me do this once the other fixups are ok and I could squash them. Otherwise this get too nasty squash -- maybe it is already...

2021-08-14 11:28 UTC, kambala-decapitator commented on XBMC Remote/RightMenuViewController.m
> +        return [[UIScreen mainScreen] bounds].size.height - [self getRemoteViewOffsetY];
ok, let's leave like that

2021-08-14 11:28 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        quickHelpView.frame = frame;
Ok, will do after the other fixups are accepted and I could squash them.

2021-08-14 11:29 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +    if (positionMode == remoteBottom && [self hasRemoteToolBar]) {
sure

2021-08-14 11:30 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        quickHelpView.frame = frame;
CGPointZero change is done. The empty lines I will look at when the other fixups are accepted.

2021-08-14 11:32 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    if (@available(iOS 11.0, *)) {
Agreed, let me do this in another PR as this touches code all around. Will create an issue for this.

2021-08-14 11:40 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +    CGFloat menuItemsHeight = UIScreen.mainScreen.bounds.size.height >= 568 ? 0 : 3 * RIGHT_MENU_ITEM_HEIGHT;
Done

2021-08-14 12:15 UTC, wutschel commented on XBMC Remote/RemoteController.m
>                         [(UIButton*)self.view viewWithTag:2],
Done. Found 1 obsolete case-statement as an outcome. Reads much better now.

2021-08-14 12:34 UTC, wutschel commented
Most of the fixups and rework is added now. Only the requested empty lines and the possible refactoring of `if (positionMode == remoteBottom && [self hasRemoteToolBar]) {` is not done yet. I really need to see, if I can squash the fixups before I move one.

2021-08-14 13:28 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        quickHelpView.frame = frame;
sure no problem

2021-08-14 13:28 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        quickHelpView.frame = frame;
sure no problem

2021-08-14 13:29 UTC, kambala-decapitator commented
looks good, please proceed

2021-08-14 16:24 UTC, wutschel commented
Squashed all fixup commits -- except one change (the space correction stays separate) -- and rebased to master. Will now look into the last open review comments.

2021-08-14 17:15 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    if (positionMode == remoteBottom && [self hasRemoteToolBar]) {
Done

2021-08-14 17:20 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        quickHelpView.frame = frame;
Done

2021-08-14 17:21 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        quickHelpView.frame = frame;
Empty lines also done.

2021-08-14 17:25 UTC, wutschel commented
Added the refactoring around `(positionMode == remoteBottom && [self hasRemoteToolBar])` and added empty lines for the `= frame` occurances. If ok, I will try to squash especially the "empty line" changes into the older commits. If this is getting too difficult, I will just squash them into one single "empty lines" commit. I hope this is fine for you.

2021-08-14 18:27 UTC, kambala-decapitator commented
Yep, fine

2021-08-14 18:50 UTC, wutschel commented
I decided to just add the last fixups as two separate commits. Squashing them back into the former commits is too much work and not worth it.

2021-08-14 19:15 UTC, merged

2021-09-13 10:54 UTC, kambala-decapitator commented
feedback by @DakotaONeill 

> Hey OG poster who submitted request for movable screen. I’ll reply to your email at another time but wanted to send this here. Regardless of being at the top or bottom. The iPhone X and forward phones that have a virtual home button (the line at the bottom) is overlapping the toolbar you have shifted to the bottom. Everything else seems good though. Again will reply to email when I have a chance but figured this would be helpful in the meantime (on vacation).

<img src="https://user-images.githubusercontent.com/1557784/133071418-e147ac4f-2169-4319-bd00-7ee16f660349.jpg" width="20%" />

2021-09-13 17:03 UTC, wutschel commented
In fact, I did this for purpose. This way there is no space wasted and while testing I didn't find this problematic. As far as I remember I even found other Apps doing the same. But now I cannot find such anymore ... Change it, or leave it?

2021-09-13 17:07 UTC, kambala-decapitator commented
controls overlapping "safe area" is considered a bad UX, would be good to adjust

2021-09-13 18:03 UTC, wutschel commented
> controls overlapping "safe area" is considered a bad UX, would be good to adjust

Please see https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/390