Maintenance: Use #defines for UserInterfaceIdiom checks
xbmc/Official-Kodi-Remote-iOS pull request #345
Opened 2021-07-04 12:08 UTC by wutschel

## Description

Use `#define` for `UserInterfaceIdiom` checks as this is far easier to read while coding.

## Summary for release notes

Maintenance: Use #defines for UserInterfaceIdiom checks

2021-07-06 09:33 UTC, kambala-decapitator requested changes
looks good apart from minor style changes.

Suggestions for the future:

1. move convenience macros out of `AppDelegate.h` to a separate header and include it in a PCH
2. try using proper portrait/landscape checks instead of the status bar "hack"

2021-07-06 09:33 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.h
> +#define IS_IPAD ([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPad)
```suggestion
#define IS_IPHONE (UIDevice.currentDevice.userInterfaceIdiom == UIUserInterfaceIdiomPhone)
#define IS_IPAD (UIDevice.currentDevice.userInterfaceIdiom == UIUserInterfaceIdiomPad)
```

2021-07-06 09:33 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.h
> +#define IS_LANDSCAPE (UIInterfaceOrientationIsLandscape([[UIApplication sharedApplication] statusBarOrientation]))
```suggestion
#define IS_PORTRAIT UIInterfaceOrientationIsPortrait(UIApplication.sharedApplication.statusBarOrientation)
#define IS_LANDSCAPE UIInterfaceOrientationIsLandscape(UIApplication.sharedApplication.statusBarOrientation)
```

2021-07-06 18:25 UTC, wutschel commented on XBMC Remote/AppDelegate.h
> +#define IS_IPAD ([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPad)
:) I was thinking about this and even started working on changing it at many other places. Finally, this was too much of a change and I reverted everything. Will apply the changes for this case though.

2021-07-06 18:26 UTC, wutschel commented on XBMC Remote/AppDelegate.h
> +#define IS_LANDSCAPE (UIInterfaceOrientationIsLandscape([[UIApplication sharedApplication] statusBarOrientation]))
Same here.

2021-07-06 18:44 UTC, wutschel commented
> try using proper portrait/landscape checks instead of the status bar "hack"

Here we go. If ok, I will squash and push force.

2021-07-07 18:01 UTC, wutschel commented
> move convenience macros out of `AppDelegate.h` to a separate header and include it in a PCH

There is a PCH defined already, so I moved some defines into a new header and imported it from there.

2021-07-12 14:37 UTC, kambala-decapitator requested changes

2021-07-12 14:37 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.h
> +#define IS_LANDSCAPE (UIInterfaceOrientationIsLandscape(UIApplication.sharedApplication.statusBarOrientation))
```suggestion
#define IS_PORTRAIT UIInterfaceOrientationIsPortrait(UIApplication.sharedApplication.statusBarOrientation)
#define IS_LANDSCAPE UIInterfaceOrientationIsLandscape(UIApplication.sharedApplication.statusBarOrientation)
```

2021-07-12 14:37 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.h
> +#define IS_LANDSCAPE (UIDeviceOrientationIsLandscape(UIDevice.currentDevice.orientation))
checking device orientation for this is a bad solution. Device orientation is needed only to determine device orientation in 3D space, i.e. physical world.

By proper approach I meant something like comparing view's width to its height. Ideally, we should use the regular and compact traits. But that's definitely not for this PR.

2021-07-12 14:37 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.h
> +#define SYSTEM_VERSION_GET(v)                       ([UIDevice.currentDevice.systemVersion compare:v options:NSNumericSearch])
forget about `UIDevice.currentDevice.systemVersion`, use `NSProcessInfo`: either `operatingSystemVersion` property or `isOperatingSystemAtLeast...` method. These macros should also be removed.

2021-07-12 17:35 UTC, wutschel commented on XBMC Remote/AppDelegate.h
> +#define IS_LANDSCAPE (UIInterfaceOrientationIsLandscape(UIApplication.sharedApplication.statusBarOrientation))
Ok, will apply this change.

2021-07-12 17:36 UTC, wutschel commented on XBMC Remote/AppDelegate.h
> +#define IS_LANDSCAPE (UIDeviceOrientationIsLandscape(UIDevice.currentDevice.orientation))
Ok, will then go back to `UIInterfaceOrientationIsPortrait(UIApplication.sharedApplication.statusBarOrientation`.

2021-07-12 17:48 UTC, wutschel commented on XBMC Remote/AppDelegate.h
> +#define SYSTEM_VERSION_GET(v)                       ([UIDevice.currentDevice.systemVersion compare:v options:NSNumericSearch])
There is only call of `if (SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"11.0"))` left. At all other places simply `if (@available(iOS 11.0, *))` is used. Wouldn´t this work as well?

2021-08-04 10:39 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.h
> +#define SYSTEM_VERSION_GET(v)                       ([UIDevice.currentDevice.systemVersion compare:v options:NSNumericSearch])
`@available` does work, but I prefer to use it only for API checks, for simple runtime OS check I always use `NSProcessInfo`. Not insisting on changing :)

2021-08-04 10:40 UTC, merged