Bugfix: Resolve issues around playlist
xbmc/Official-Kodi-Remote-iOS pull request #348
Opened 2021-07-16 14:57 UTC by wutschel

## Description

This PR applies 3 main changes. 

- First change fixes an issue described in a [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3049725#pid3049725), which results in double `1x01` (or whatever season/episode is played) shown in the App's playlist when the playback was started via the Kodi UI. 
Screenshot: https://abload.de/img/a5137fe2-9c4b-4309-ap0k3p.jpeg

- Second change fixes missing or wrong thumbnails when calling the info screen via longpress on the playlist item.
Screenshots:
https://abload.de/img/simulatorscreenshot-i6iku0.png (before)
https://abload.de/img/simulatorscreenshot-i5lkam.png (after)
 
- Third change is renaming three main variables to match its content, which is not only Video based.

## Summary for release notes

Bugfix: Do not show double "1x01" in playlist for TVShow episodes
Bugfix: Show thumbnails for Movies/TVShows when calling info from playlist

2021-08-04 10:53 UTC, kambala-decapitator requested changes

2021-08-04 10:53 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> -    if (playerID == 0)
in this case `switch` is better

2021-08-04 10:53 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    if (storeSelection && storeSelection.row == indexPath.row) {
you could simply return the inverted condition (or even "open" the brackets):

    return !(storeSelection && storeSelection.row == indexPath.row);

but not insisting on this.

2021-08-04 17:54 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> -    if (playerID == 0)
Done in fixup commit.

2021-08-04 17:54 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    if (storeSelection && storeSelection.row == indexPath.row) {
Done in fixup commit.

2021-08-04 17:55 UTC, wutschel commented
Let me know if this is ok now. I will squash the changes then.

2021-08-05 17:15 UTC, kambala-decapitator approved these changes

2021-08-05 18:17 UTC, wutschel commented
Here we go.

2021-08-08 19:22 UTC, merged