Feature: rounded corners for thumbnails/images
xbmc/Official-Kodi-Remote-iOS pull request #351
Opened 2021-07-25 10:48 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/182.

This PR implements a new feature which allows the user to enable/disable rounded corners for thumbnails. The method to round the edges is using `bezierPathWithRoundedRect` which results in a smooth rounded edge, similar to iOS' "squircle". When enabled this gives the UI a fresher and modern look -- in my opinion. Per default the rounded corners are enabled.

Screenshots:
https://abload.de/img/simulatorscreenshot-i6rkkb.png
https://abload.de/img/simulatorscreenshot-i59jgm.png
https://abload.de/img/simulatorscreenshot-i60jba.png
https://abload.de/img/simulatorscreenshot-iukjk8.png
https://abload.de/img/simulatorscreenshot-i54j4n.png
https://abload.de/img/simulatorscreenshot-inkjuh.png
https://abload.de/img/simulatorscreenshot-i31krc.png
https://abload.de/img/simulatorscreenshot-ikwji3.png
https://abload.de/img/simulatorscreenshot-i7pkaq.png
https://abload.de/img/simulatorscreenshot-ie4jbe.png
https://abload.de/img/simulatorscreenshot-ikgjrb.png
https://abload.de/img/simulatorscreenshot-i6fkz0.png
https://abload.de/img/simulatorscreenshot-id3k2k.png
https://abload.de/img/simulatorscreenshot-ienjfw.png
https://abload.de/img/simulatorscreenshot-ijzkuw.png
https://abload.de/img/simulatorscreenshot-il3jsg.png
https://abload.de/img/simulatorscreenshot-iewj8a.png
https://abload.de/img/simulatorscreenshot-iknku0.png
https://abload.de/img/simulatorscreenshot-isgjmn.png
https://abload.de/img/simulatorscreenshot-imnj83.png
https://abload.de/img/simulatorscreenshot-itrk9b.png

## Summary for release notes

Feature: rounded corners for thumbnails/images

2021-07-25 10:49 UTC, wutschel commented
Keeping this draft for now as I am still not fully satisfied with the look of the covers in the list view.

2021-07-25 14:39 UTC, wutschel commented
Now with improved look & feel for list view, artists and actors.

Screenshots:
https://abload.de/img/simulatorscreenshot-i3ekhi.png
https://abload.de/img/simulatorscreenshot-ix9k5a.png
https://abload.de/img/simulatorscreenshot-i5kk64.png

2021-08-04 11:57 UTC, kambala-decapitator requested changes

2021-08-04 11:57 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    CALayer *imageLayer = [CALayer layer];
TBH I don't really like the approach with creating temporary layers. Isn't it possible to get away with simple clipping using `CGContext*` functions?

2021-08-04 11:57 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    imageLayer.borderWidth = 2 * 1.0 / UIScreen.mainScreen.scale;;
;;

2021-08-04 11:57 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    imageView.frame = CGRectMake(frame.origin.x + 0.5, frame.origin.x + 0.5, frame.size.width - 1.0, frame.size.height - 1.0);
use `CGRectInset`

2021-08-04 12:00 UTC, kambala-decapitator commented
if I understand correctly, in case when image adjustments aren't needed, you're doing a useless job of rendering a layer with image just to get exactly the same image as the input one

2021-08-04 18:23 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    imageLayer.borderWidth = 2 * 1.0 / UIScreen.mainScreen.scale;;
This fixed in a later commit. Acceptable?

2021-08-04 18:28 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    imageView.frame = CGRectMake(frame.origin.x + 0.5, frame.origin.x + 0.5, frame.size.width - 1.0, frame.size.height - 1.0);
Again learned something new, so `CGRectInset(frame, 0.5, 0.5)` does the same, right?

2021-08-04 18:52 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    CALayer *imageLayer = [CALayer layer];
Let me look into your suggestion. I was looking up this solution and wasn´t sure if there are easier ways to do this. Any help / hint is welcome.

2021-08-04 18:53 UTC, wutschel commented
> if I understand correctly, in case when image adjustments aren't needed, you're doing a useless job of rendering a layer with image just to get exactly the same image as the input one

Yes, pretty dumb. This can be reworked when I get an idea of how to do this using `CGContext*` as you suggest.

2021-08-05 17:18 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    imageLayer.borderWidth = 2 * 1.0 / UIScreen.mainScreen.scale;;
sure

2021-08-05 17:19 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    imageView.frame = CGRectMake(frame.origin.x + 0.5, frame.origin.x + 0.5, frame.size.width - 1.0, frame.size.height - 1.0);
correct

2021-08-05 17:21 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    CALayer *imageLayer = [CALayer layer];
I can't tell you the exact solution as I also don't know it. You need something like drawing with transparent color over the corners (or apply such mask). Please check available functions in `CoreGraphics` framework.

2021-08-05 18:40 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    CALayer *imageLayer = [CALayer layer];
Ok, will play around with this and see if I find a better solution. Will keep this PR as draft until then.

2021-08-07 10:41 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    CALayer *imageLayer = [CALayer layer];
Please check the latest forced push. Instead of having a single function which required the temporary layer I am now using one method to process `UIImage` using `CGContext` functions and another method to process `UIImageView`. Both methods are only called if the feature was enabled by user.

2021-08-08 08:01 UTC, kambala-decapitator requested changes
well done, looks much better now!

2021-08-08 08:01 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    imageLayer.cornerRadius = MAX(MIN(imageLayer.frame.size.width, imageLayer.frame.size.height) * 1.0 / 10.0, 8.0);
multiplying by 1.0

2021-08-08 08:22 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    CGFloat radius = MAX(MIN(image.size.width, image.size.height) * 1.0 / 10.0, 8.0);
Removed with fixup commit.

2021-08-08 08:23 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    imageLayer.cornerRadius = MAX(MIN(imageLayer.frame.size.width, imageLayer.frame.size.height) * 1.0 / 10.0, 8.0);
Removed with fixup commit.

2021-08-08 08:26 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    if (corner_preference == nil || [corner_preference boolValue]) {
Registering should be done in `AppDelegate.m `and the #define for the magic string in its header, right? I would like to  do this in a seperate commit and will then also replace the magic strings for other `userDefault` checks. Is this ok for you?

2021-08-08 08:36 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        CGContextSetLineWidth(context, 1.0 / UIScreen.mainScreen.scale);
Logic was to reduce the border width to the minimum (1 pixel, not 1 UI point). I can also use 0.5 here, which is a bit broader on my iPhone Xs and still looks ok. Benefit would be that the relation boarder to image is fixed then.

2021-08-08 08:37 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    if (corner_preference == nil || [corner_preference boolValue]) {
yes, sounds good.

> #define for the magic string in its header

if that string is used only in this file, then it can be put in the implementation file.

2021-08-08 08:45 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    UIGraphicsBeginImageContext(imageRect.size);
Is `UIGraphicsBeginImageContextWithOptions(image.size, NO, [[UIScreen mainScreen] scale])` what you are asking for?

2021-08-08 08:58 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        CGContextStrokePath(context);
Nice. The code reduces to

```
// Draw border with shape of path
path.lineWidth = 0.5;
[[UIColor blackColor] setStroke];
[path stroke];
```

2021-08-08 09:56 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    if (corner_preference == nil || [corner_preference boolValue]) {
Already started to work on a solution. Will close this conversation and raise an MR when I am ready.

2021-08-08 10:34 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        CGContextSetLineWidth(context, 1.0 / UIScreen.mainScreen.scale);
This is used in several places in the existing code as well. I compared the look and the borders look sleeker. If you are not objecting I tend to keep it like this (`1.0 / UIScreen.mainScreen.scale`).

2021-08-08 10:42 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    UIGraphicsBeginImageContext(imageRect.size);
`UIGraphicsBeginImageContextWithOptions(image.size, NO, UIScreen.mainScreen.scale)`, I guess ;)

2021-08-08 19:26 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        CGContextSetLineWidth(context, 1.0 / UIScreen.mainScreen.scale);
ok, let's keep

2021-08-08 19:26 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    UIGraphicsBeginImageContext(imageRect.size);
I'd rather pass `0` in third param

2021-08-09 04:55 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    UIGraphicsBeginImageContext(imageRect.size);
Ok, will provide 1 commit which is changing this for all three calls in `Utilities.m`.

2021-08-14 10:09 UTC, kambala-decapitator approved these changes

2021-08-14 13:00 UTC, wutschel commented
It is hard to squash all fixups in a good way. Is it ok for you, if the resulting commits are mainly squashed into 1 main implementation, followed by few add-on commits, like in https://github.com/wutschel/Official-Kodi-Remote-iOS/tree/look_4?

2021-08-14 13:22 UTC, kambala-decapitator commented
looks good to me

2021-08-14 15:24 UTC, wutschel commented
Here we go.

2021-08-14 15:39 UTC, merged

2021-08-14 20:18 UTC, kambala-decapitator commented
for some reason merging with Github iOS app didn't include the PR title in the merge message