Bugfix: Correct vertical position of volume control on iPad
xbmc/Official-Kodi-Remote-iOS pull request #352
Opened 2021-07-26 05:58 UTC by wutschel

## Description

This PR corrects the vertical position of the volume control elements for iPads.

<a href="https://abload.de/image.php?img=bildschirmfoto2021-07gljs0.png"><img src="https://abload.de/img/bildschirmfoto2021-07gljs0.png" /></a>

## Summary for release notes

Bugfix: Correct vertical position of volume control on iPad

2021-08-04 11:18 UTC, kambala-decapitator requested changes
a much clearer solution would be to apply the following to all views in question in a loop:

    aView.center = CGPointMake(aView.center.x, frame.size.height / 2); // or CGRectGetMidY(self.bounds)

2021-08-04 18:19 UTC, wutschel commented
Here we go. If ok for you, I will update the MR with the final solution.

2021-08-05 17:23 UTC, kambala-decapitator commented
you missed the **loop** point ;)

2021-08-05 18:28 UTC, wutschel commented
> you missed the **loop** point ;)

True, I really missed this :) Please check the updated code.

2021-08-08 07:41 UTC, kambala-decapitator approved these changes

2021-08-08 19:23 UTC, merged