Feature: Add volume slider to remote screen
xbmc/Official-Kodi-Remote-iOS pull request #363
Opened 2021-08-15 13:22 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/358.

Add volume slider to remote screen:
- When screen size allows (`height >= 568`) add the volume bar on top.
- Use `leftAnchor` to differentiate between embedded and full screen.
- Align both iPad/iPhone volume elements in vertical center of screen.

## Summary for release notes

Feature: Show volume slider on remote screen (not working for iPhone 4S)

2021-08-15 15:13 UTC, kambala-decapitator requested changes

2021-08-15 15:13 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +            frame.origin.y = frame.origin.y == 0 ? volumeSliderView.frame.size.height : frame.origin.y;
Use if to prevent useless assignment

2021-08-15 15:13 UTC, kambala-decapitator commented on XBMC Remote/VolumeSliderView.m
> +            subView.center = CGPointMake(subView.center.x, self.frame.size.height / 2);
1. self.subviews
2. Pre-compute y coordinate outside the loop (also CGRectGetHeight)

2021-08-15 15:25 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +            frame.origin.y = frame.origin.y == 0 ? volumeSliderView.frame.size.height : frame.origin.y;
Done

2021-08-15 15:25 UTC, wutschel commented on XBMC Remote/VolumeSliderView.m
> +            subView.center = CGPointMake(subView.center.x, self.frame.size.height / 2);
I hope I got the 2nd comment right.

2021-08-15 15:26 UTC, wutschel commented
I still still have a (minor) position glitch I would like to solve, and will keep this draft until I found a good solution.

2021-08-16 06:01 UTC, wutschel commented
> I still still have a (minor) position glitch I would like to solve, and will keep this draft until I found a good solution.

Solved now and added as first commit -- this change would also be correct without the changes to add the volume slider to the remote screen. I also tested with setting `hasRemoteToolBar` to `false` to simulate iPhone 4S screen size. This seems to work as expected. I am marking this as ready for review.

2021-08-17 17:15 UTC, kambala-decapitator requested changes
Everything else is fine

2021-08-17 17:15 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +    CGFloat shift = 0;
Looks useless as value is assigned in both cases

2021-08-17 17:15 UTC, kambala-decapitator commented on XBMC Remote/RightMenuViewController.m
> +    else if ([tableData[indexPath.row][@"label"] isEqualToString:@"VolumeControl"]) {
I strongly suggest to extract the left part into a variable

2021-08-17 17:23 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    CGFloat shift = 0;
True, made this change while commenting the whole block which hides/modes buttons. Will be removed with next forced push (not worth a fixup-commit).

2021-08-17 17:29 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +    else if ([tableData[indexPath.row][@"label"] isEqualToString:@"VolumeControl"]) {
Done

2021-08-17 17:34 UTC, wutschel commented
Last fixup provided.

2021-08-17 18:56 UTC, kambala-decapitator approved these changes

2021-08-17 19:04 UTC, wutschel commented
Here we go.

2021-08-17 19:18 UTC, merged