Bugfix: Fix rounded corners for some use cases
xbmc/Official-Kodi-Remote-iOS pull request #368
Opened 2021-08-18 19:17 UTC by wutschel

## Description

This PR fixes feedback from a [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3055353#pid3055353). The following topics are fixed:

1. Show rounded corners for recording details
<a href="https://abload.de/image.php?img=bildschirmfoto2021-08kfkmw.png"><img src="https://abload.de/img/bildschirmfoto2021-08kfkmw.png" /></a>

2. Show rounded corner for playlist thumbs (same as for thumbs in list view)
<a href="https://abload.de/image.php?img=bildschirmfoto2021-087bkmx.png"><img src="https://abload.de/img/bildschirmfoto2021-087bkmx.png" /></a>

3. Do not show border for TV logos in recording list
<a href="https://abload.de/image.php?img=bildschirmfoto2021-08xck5l.png"><img src="https://abload.de/img/bildschirmfoto2021-08xck5l.png" /></a>

## Summary for release notes

Bugfix: Fix rounded corners for some use cases

2021-08-18 21:17 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +    [self performSelectorOnMainThread:@selector(showImage:) withObject:image waitUntilDone:YES];
please replace both lines of this method with direct calls inside `dispatch_async(dispatch_get_main_queue(), ^{ ... })` (not sure if you actually need `_sync` for 1:1 correspondence to `waitUntilDone:YES`)

2021-08-18 21:17 UTC, kambala-decapitator commented
looks good, not sure if you're done though based on the forum discussion

2021-08-19 04:48 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> +    [self performSelectorOnMainThread:@selector(showImage:) withObject:image waitUntilDone:YES];
I changed this with one of the fixup commits.

2021-08-19 04:51 UTC, wutschel commented
> looks good, not sure if you're done though based on the forum discussion

This needs some testing of mine -- just found another issue which needed a fixup. I can do the testing later today, then we can bring it into a beta build and ask for further checks.

2021-08-19 18:01 UTC, kambala-decapitator commented
current state looks fine. Please let me know when PR is finished.

2021-08-19 20:15 UTC, wutschel commented
I found one more severe bug, also in current master: The thumb view size on iPad's fullscreen view is wrong when enabling "rounded corners". On top of my Kodi test system had a problem and lost the TV functionality. Need to get this back to work.

2021-08-20 07:30 UTC, wutschel commented
1. Got my Kodi test setup working again.
2. The issue can be reproduced when switching from grid view to fullscreen on Pad (e.g. movie list or album list). In this case the old smaller mask is still applied to the new bigger view. 
3. Above issue seems to connect to reuse cells/view via `dequeueReusableCellWithReuseIdentifier`. I do not have a clue why this behaving this strange yet ...

2021-08-20 08:24 UTC, kambala-decapitator commented
> Above issue seems to connect to reuse cells/view via `dequeueReusableCellWithReuseIdentifier`. I do not have a clue why this behaving this strange yet ...

if you use the same ID for cells in grid/fullscreen, then it makes sense. When switching between modes, you need to clear the rounded state I guess.

2021-08-20 20:43 UTC, wutschel commented
Should be working now. Finally this could be fixed by using the default auto resizing mask for the thumb.

2021-08-21 07:28 UTC, kambala-decapitator requested changes
after merging this I'll set version to 1.8 and submit it for review. If all goes fine and no negative feedback, will release in 2 weeks after returning from vacation.

2021-08-21 07:28 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
>  - (void)elaborateImage:(UIImage*)image {
this method is called on background thread which is makes no sense, please replace with direct calls

2021-08-21 07:28 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        cell.posterThumbnail.frame = CGRectMake(0, 0, cell.frame.size.width, cell.frame.size.height);
```suggestion
        cell.posterThumbnail.frame = cell.bounds;
```

2021-08-21 10:01 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
>  - (void)elaborateImage:(UIImage*)image {
Sorry, I am not clear on this comment.

2021-08-21 10:04 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
>  - (void)elaborateImage:(UIImage*)image {
check calls to `elaborateImage`

2021-08-21 10:06 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        cell.posterThumbnail.frame = CGRectMake(0, 0, cell.frame.size.width, cell.frame.size.height);
Done

2021-08-21 10:15 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
>  - (void)elaborateImage:(UIImage*)image {
Got it, thanks.

2021-08-21 10:16 UTC, wutschel commented
> after merging this I'll set version to 1.8 and submit it for review. If all goes fine and no negative feedback, will release in 2 weeks after returning from vacation.

Sounds good. As I am also out for two weeks we can let the beta version settle for this time and see, if there is anything else popping up.

2021-08-21 10:20 UTC, kambala-decapitator approved these changes

2021-08-21 10:27 UTC, wutschel commented
Squashed the fixups.

2021-08-21 10:28 UTC, merged