Feature: Implement automated rating request
xbmc/Official-Kodi-Remote-iOS pull request #420
Opened 2021-10-11 15:47 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/370.

This PR implements automated rating request for the AppStore. 

1st attempt: It will show the rating popup each 10th start/wakeup.

## Summary for release notes

Feature: Implement automated rating request

2021-11-20 11:06 UTC, wutschel commented
I added some logic which will save the current version in the key `"VersionUnderReview"` each time the version is updated. If the current version is different to the one under review, the counter will be reset to 0. If the version keeps same, the counter in key `"PlaybackAttempts"` is increased and each 50th time the review request will pop up. I am not 100% sure after how many attempts the popup shall appear. I am also thinking of adding a check for a certain amount of time to be passed before we ask again (e.g. 6 months or so). 

What are your thoughts?

2021-11-26 06:27 UTC, wutschel commented
@kambala-decapitator, do you see this is a good choice to trigger the reviews? And if so, should we add this for the next release already?

2021-11-26 13:50 UTC, kambala-decapitator requested changes

2021-11-26 13:50 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    id infoDict = NSBundle.mainBundle.infoDictionary;
why `id`? The type is known. Please either use `__auto_type` or `NSDictionary*`.

2021-11-26 13:50 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        if (count % 50 == 0) {
either code or comment is incorrect

2021-11-26 13:50 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        [[NSUserDefaults standardUserDefaults] setInteger:0 forKey:@"PlaybackAttempts"];
please don't use "magic" strings

2021-11-26 14:01 UTC, kambala-decapitator commented
> @kambala-decapitator, do you see this is a good choice to trigger the reviews? And if so, should we add this for the next release already?

let's do it!

2021-11-26 14:46 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    id infoDict = NSBundle.mainBundle.infoDictionary;
Will use NSDictionary.

2021-11-26 14:47 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        if (count % 50 == 0) {
Corrected the comment.

2021-11-26 14:51 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        [[NSUserDefaults standardUserDefaults] setInteger:0 forKey:@"PlaybackAttempts"];
Used defines now.

2021-11-28 07:00 UTC, kambala-decapitator approved these changes

2021-11-28 07:29 UTC, wutschel commented
Included one more fix (comment still referred to "50th launch/wakeup", but the trigger comes after "50th playback attempt"). Squashed all changes into one and updated the commit message.

2021-11-28 07:38 UTC, kambala-decapitator commented on XBMC Remote/Utilities.h
> ++ (void)showReviewController;
not sure why this method is public

2021-11-28 08:20 UTC, wutschel commented on XBMC Remote/Utilities.h
> ++ (void)showReviewController;
A remnant of the first implementations I did. I now removed it as part of the latest forced push.

2021-11-28 08:20 UTC, wutschel commented
Updated with last request for change.

2021-11-28 08:41 UTC, merged