Improvement: Rework handling of timers
xbmc/Official-Kodi-Remote-iOS pull request #476
Opened 2021-11-15 06:41 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/444.

This PR implements an separate lists for timer and timer rules. This is still work in progress, so I am keeping this as a draft until this settled.

Details:

- Enhance JSON API request to also receive `istimerule` property.
- Only do this for Kodi 19+ as the API response on recordings and timers are inconsistent before this version.
- Add a 5th toolbar icon to access the newly introduced timer rule list.
- Add new default thumb for timer rule
- Correct German translation (not all timers are scheduled recordings, some are reminders)

Screenshot:
<a href="https://abload.de/image.php?img=bildschirmfoto2021-11yckr9.png"><img src="https://abload.de/img/bildschirmfoto2021-11yckr9.png" /></a>

## Summary for release notes

Feature: Separate views for timers and timer rules
Improvement: Timer rules show summary, e.g. "Each day from 8:00 PM to 8:15 PM"
Bugfix: Correct German translation around timers

2021-11-15 06:42 UTC, wutschel commented
The next improvement will be to show icons to differentiate scheduled recordings from reminders.

2021-11-15 07:38 UTC, wutschel commented
@ksooo, I hope this way the implementation makes sense now.

2021-11-15 07:40 UTC, ksooo commented
> I hope this way the implementation makes sense now.

 Very nice, thanks a bunch.

2021-11-18 15:27 UTC, kambala-decapitator requested changes
also we can't merge this before #475 due to touching strings

2021-11-18 15:27 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +        @"st_timerrules"];
I think we have recently discussed this:
```suggestion
        @"st_timerrules",
    ];
```

2021-11-18 15:27 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +         BOOL ignoreTimerItems = [menuParam[@"label"] isEqualToString:LOCALIZED_STR(@"Timer rules")] && isTimerMethod;
a small note: if you swap conditions surrounding `&&`, it might give tiny speed increase due to short-circuiting

2021-11-18 15:27 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                                            [itemDict[i][@"isradio"] boolValue];
placing operator in the beginning of new line improves readability

2021-11-18 15:27 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                    NSString *minutesUnit = minutes > 1 ? LOCALIZED_STR(@"Mins.") : LOCALIZED_STR(@"Min");
that's a **very** wrong way to localize plurals. Apple already provides support for plurals localization, please read in the docs how to do it properly (keyword: stringsdict).

2021-11-18 15:27 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                }
please avoid copy-paste

2021-11-18 15:27 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                    NSDateFormatter *localFormatter = [NSDateFormatter new];
creating date formatter in `cellForRowAtIndexPath` each time doesn't sound like a great idea

2021-11-18 18:36 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +         BOOL ignoreTimerItems = [menuParam[@"label"] isEqualToString:LOCALIZED_STR(@"Timer rules")] && isTimerMethod;
Agreed.

2021-11-18 18:38 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                                            [itemDict[i][@"isradio"] boolValue];
This follows the code at many other places. Hope you do not insist on this.

2021-11-18 18:38 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                    NSString *minutesUnit = minutes > 1 ? LOCALIZED_STR(@"Mins.") : LOCALIZED_STR(@"Min");
Argh, I will look at this, but this is **very** old code.

2021-11-18 18:42 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                    NSDateFormatter *localFormatter = [NSDateFormatter new];
Agreed, I am working on this in a separate PR. Hope you are fine accepting this as the current (before this PR) implementation calls this same or even more often.

2021-11-18 18:48 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                }
Solved.

2021-11-18 18:50 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +        @"st_timerrules"];
I remember... I will only apply this for the cases you mention here. Doing this for all other places calls for a dedicated coding styles PR.

2021-11-18 19:23 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                    NSString *minutesUnit = minutes > 1 ? LOCALIZED_STR(@"Mins.") : LOCALIZED_STR(@"Min");
Similar solutions are used for 5 other and unrelated plurals as well. I am not completely sure yet on how to do this, this should go into a separate PR.

2021-11-18 19:56 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                                            [itemDict[i][@"isradio"] boolValue];
sure, no problem

2021-11-18 19:56 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                    NSString *minutesUnit = minutes > 1 ? LOCALIZED_STR(@"Mins.") : LOCALIZED_STR(@"Min");
separate PR sounds good

2021-11-18 19:57 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                    NSDateFormatter *localFormatter = [NSDateFormatter new];
yeah, noticed that too. Let's adjust in another PR.

2021-11-18 20:00 UTC, kambala-decapitator requested changes
all good except one tiny point :)

2021-11-18 20:06 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +- (NSString*)setTimerDefaultThumb:(BOOL)isReminder {
Well, I will choose a drastic approach and will name it `get...` :)

2021-11-18 20:15 UTC, kambala-decapitator approved these changes

2021-11-18 22:00 UTC, wutschel commented
Squashed the fixup commits. Will wait for the updated weblate PR now.

2021-11-20 12:44 UTC, kambala-decapitator commented
please fix conflicts

2021-11-20 12:47 UTC, wutschel commented
Rebased to master.

2021-11-20 14:14 UTC, merged