Feature: Server info
xbmc/Official-Kodi-Remote-iOS pull request #514
Opened 2021-12-04 09:35 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/389.

This PR implements a detailed server info, comparable to Kodi's System Info. The current state is shown in the screenshot below. More details can be shown, if this should be required. I am avoiding to add eye-candy like bars for memory consumption or the CPU load as I would need to parse Kodi's responses, and I am already seeing different string formats between my main test systems 17.6 and 19.3.

Screenshots (Kodi 19.3 on a VM):
<a href="https://abload.de/image.php?img=bildschirmfoto2021-121tk7s.png"><img src="https://abload.de/img/bildschirmfoto2021-121tk7s.png" /></a>

## Summary for release notes

Feature: Server info

2021-12-18 13:17 UTC, wutschel commented
@kambala-decapitator, you feel this is a useful feature?

2021-12-18 13:23 UTC, kambala-decapitator commented
looks good, wouldn’t hurt :)

Do you plan to add auto refresh?

2021-12-18 13:27 UTC, wutschel commented
> Do you plan to add auto refresh?

I didn't look into this, but I guess if this feature is added, I should  do so.

2021-12-18 15:44 UTC, wutschel commented
Added a timer to update the server info view. But I guess I overdid the invalidation of the timer. Does it make sense to  invalidate in both `viewWillDisappear` and `viewDidDisappear`?

2021-12-18 16:22 UTC, kambala-decapitator commented
> Added a timer to update the server info view. But I guess I overdid the invalidation of the timer. Does it make sense to  invalidate in both `viewWillDisappear` and `viewDidDisappear`?

It's sufficient to do only in one of them, usually "did" is fine (but might depend on the use case).

But invalidating it in dealloc makes no sense because it will never happen: timer holds a strong reference to its target essentially causing a retain cycle in your case.

2021-12-18 16:25 UTC, wutschel commented
> It's sufficient to do only in one of them, usually "did" is fine (but might depend on the use case).
> 
> But invalidating it in dealloc makes no sense because it will never happen: timer holds a strong reference to its target essentially causing a retain cycle in your case.

Perfect, applied the changes in a fixup commit.

2021-12-18 16:43 UTC, kambala-decapitator requested changes
Please use UITextView in readonly mode instead to make things easier ;)

2021-12-18 16:43 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +        [serverInfoTimer invalidate];
Seems you can invalidate it unconditionally?

2021-12-18 16:43 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +    [string2 addAttribute:NSForegroundColorAttributeName value:UIColor.whiteColor range:NSMakeRange(0, string2.length)];
Why not providing it in the attribute dictionary directly?

2021-12-18 16:43 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +    [serverInfoButton setBackgroundImage:[UIImage new] forState:UIControlStateSelected];
Not clear why this is needed

2021-12-18 16:48 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +        [serverInfoTimer invalidate];
True, will change this.

2021-12-18 17:06 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +    [string2 addAttribute:NSForegroundColorAttributeName value:UIColor.whiteColor range:NSMakeRange(0, string2.length)];
Like this?

```
NSDictionary *boldFontAttrib = @{
    NSFontAttributeName: [UIFont boldSystemFontOfSize:fontSize],
    NSForegroundColorAttributeName: UIColor.lightGrayColor
};
NSMutableAttributedString *string1 = [[NSMutableAttributedString alloc] initWithString:name attributes:boldFontAttrib];
```

2021-12-18 17:16 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +    [string2 addAttribute:NSForegroundColorAttributeName value:UIColor.whiteColor range:NSMakeRange(0, string2.length)];
Yes

2021-12-18 17:18 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +    [string2 addAttribute:NSForegroundColorAttributeName value:UIColor.whiteColor range:NSMakeRange(0, string2.length)];
Ok, done.

2021-12-18 17:24 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +    [serverInfoButton setBackgroundImage:[UIImage new] forState:UIControlStateSelected];
Oh, this came from copy-pasting the other button declarations in this controller. Obviously the others also do not need this clean-up as there is never a background set. Will add a fixup commit for the newly added button and another commit to remove the unneeded calls of setBackgroundImage.

2022-01-05 20:02 UTC, kambala-decapitator commented
new commits look fine.

> Please use UITextView in readonly mode instead to make things easier ;)

@wutschel will you do this?

2022-01-05 20:13 UTC, wutschel commented
> @wutschel will you do this?

Can you give me a hint what you are looking for?

2022-01-06 09:56 UTC, kambala-decapitator commented
> > @wutschel will you do this?
> 
> Can you give me a hint what you are looking for?

You're adding tons of labels onto scroll view. `UITextView` is exactly a "scrollable label".

2022-01-06 12:00 UTC, wutschel commented
Understood. I now tried to directly use `UITextView` and set the attributed string with all content. But I cannot get the string displayed, the view itself with the background color shows up. Any idea where to look at?

Btw, what works is to keep using `UIScrollView` and only add a single `UILabel` with all content to it.

2022-01-06 12:02 UTC, kambala-decapitator commented
> Understood. I now tried to directly use `UITextView` and set the attributed string with all content. But I cannot get the string displayed, the view itself with the background color shows up. Any idea where to look at?

sounds strange. Do you experience the same in a clean test project?

2022-01-06 12:09 UTC, wutschel commented
Hah, found it. I had added a loop which removes all subviews before adding the new ones. This also removed the text :) Works now. Will tweak a little and then provide a reworked version.

2022-01-06 12:21 UTC, wutschel commented
Here we go.

2022-01-06 13:25 UTC, kambala-decapitator requested changes
much better now!

2022-01-06 13:25 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +- (NSMutableAttributedString*)formatInfo:(NSString*)name text:(NSString*)text {
don't see a reason to return mutable object

2022-01-06 13:25 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +            NSMutableAttributedString *newLine = [[NSMutableAttributedString alloc] initWithString:@"\n"];
why is it mutable?

2022-01-06 13:25 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +            NSMutableAttributedString *infoString = [[NSMutableAttributedString alloc] initWithString:@""];
can be simplified to `[NSMutableAttributedString new]`

2022-01-06 13:32 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +- (NSMutableAttributedString*)formatInfo:(NSString*)name text:(NSString*)text {
Right.

2022-01-06 13:32 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +            NSMutableAttributedString *newLine = [[NSMutableAttributedString alloc] initWithString:@"\n"];
Copy pasted, removed this.

2022-01-06 13:32 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +            NSMutableAttributedString *infoString = [[NSMutableAttributedString alloc] initWithString:@""];
Right.

2022-01-06 13:33 UTC, wutschel commented
> much better now!

True, looks much cleaner now. Thanks for nudging ;)

2022-01-06 13:36 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +            NSAttributedString *newLine = [[NSMutableAttributedString alloc] initWithString:@"\n"];
```suggestion
            NSAttributedString *newLine = [[NSAttributedString alloc] initWithString:@"\n"];
```

2022-01-06 13:36 UTC, kambala-decapitator approved these changes

2022-01-06 13:38 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +            NSAttributedString *newLine = [[NSMutableAttributedString alloc] initWithString:@"\n"];
Thanks, will apply this in the update.

2022-01-06 13:42 UTC, wutschel commented
Squashed the fixup commits into a single commit.

2022-01-07 08:13 UTC, merged