Feature: Enable search in grid/wall view
xbmc/Official-Kodi-Remote-iOS pull request #519
Opened 2021-12-07 19:17 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/467.

This PR enables the search in grid/wall view (tested with albums, artists and movies):
- Search field usable as for list view
- Correct results are shown
- Longpressing or selecting an item processes the details of the correct item
- Show amount of found items in section header

Screenshots:
https://abload.de/img/simulatorscreenshot-iqrkga.png
https://abload.de/img/simulatorscreenshot-iajj2g.png
https://abload.de/img/simulatorscreenshot-i9tk5e.png

## Summary for release notes

Feature: Enable search in grid/wall view

2021-12-18 12:21 UTC, wutschel commented
Should be merged after #521.

2021-12-18 13:06 UTC, kambala-decapitator commented
Please fix conflicts

2021-12-18 13:17 UTC, wutschel commented
Rebased to master.

2022-01-07 08:51 UTC, kambala-decapitator requested changes

2022-01-07 08:51 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    NSDictionary *item = nil;
FYI under ARC `nil` is assigned to objects implicitly

2022-01-07 08:51 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        item = [self.sections objectForKey:self.sectionArray[indexPath.section]][indexPath.row];
I suggest to extract this into a separate function (or maybe even the whole if/else block)

2022-01-07 08:51 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        self.indexView.hidden = YES;
I don't find it a good place for this logic: should be done at the point where you toggle between search and normal view

2022-01-07 08:51 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        }
now it's time to start localizing plurals correctly ;)

2022-01-07 08:51 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        // will not  correctly show on top of the grid view.
please fix a couple of typos :)

2022-01-07 08:51 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    self.searchController = [[UISearchController alloc]initWithSearchResultsController:nil];
```suggestion
    self.searchController = [[UISearchController alloc] initWithSearchResultsController:nil];
```

2022-01-07 08:51 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> -    self.searchController.searchBar.backgroundColor = [Utilities getSystemGray6];
is it correct to remove these lines?

2022-01-07 08:51 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> -#pragma mark - ScrollView Delegate
I guess declaration of `UIScrollViewDelegate` conformance can be removed as well?

2022-01-07 08:51 UTC, kambala-decapitator commented on XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
> +            UIImageView *imageView = [[UIImageView alloc]initWithFrame:CGRectMake(0, 0, self.frame.size.width, 11)];
```suggestion
            UIImageView *imageView = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, self.frame.size.width, 11)];
```

2022-01-07 08:51 UTC, kambala-decapitator commented on XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
> +            [label addSubview:imageView];
```suggestion
            imageView.image = searchImage;

            [label addSubview:imageView];
```

2022-01-07 08:51 UTC, kambala-decapitator commented on XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
> +            // Use the same icon as iOS's index (magnifying glass with transparent circle)
I can suggest to use iOS system image on iOS 14+, you can find the list of system images in SF Symbols app

2022-01-07 09:36 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        }
Already created https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/479 for this whole thing. :)

2022-01-07 09:38 UTC, wutschel commented on XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
> +            // Use the same icon as iOS's index (magnifying glass with transparent circle)
I thought of the same, but dropped this as I wanted to have the same icons for all iOS versions. As long as we keep supporting older iOS version I would to keep it like this.

2022-01-07 09:42 UTC, kambala-decapitator commented on XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
> +            // Use the same icon as iOS's index (magnifying glass with transparent circle)
Personally I disagree on this, but not insisting on using system images

2022-01-07 10:53 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    NSDictionary *item = nil;
This is removed with a later commit.

2022-01-07 10:56 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        // will not  correctly show on top of the grid view.
Done

2022-01-07 11:04 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> -#pragma mark - ScrollView Delegate
Interesting. The delegate conformance was removed even before this commit about 9 years back (https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/0c53255b9f83f0f65b3800e32936c3cd9280bb15).

2022-01-07 11:05 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    self.searchController = [[UISearchController alloc]initWithSearchResultsController:nil];
Done.

2022-01-07 11:07 UTC, wutschel commented on XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
> +            UIImageView *imageView = [[UIImageView alloc]initWithFrame:CGRectMake(0, 0, self.frame.size.width, 11)];
Done.

2022-01-07 11:09 UTC, wutschel commented on XBMC Remote/BDKCollectionIndexView/BDKCollectionIndexView.m
> +            [label addSubview:imageView];
Done.

2022-01-07 11:17 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> -    self.searchController.searchBar.backgroundColor = [Utilities getSystemGray6];
Yes, these colors are set in `configureLibraryView`. The removed lines were obsolete.

2022-01-07 14:29 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        self.indexView.hidden = YES;
This took a while. You again hit the right spot. The visibility of the grid view's index was not handled well at all. I now reworked this. In addition i came across a few more issues with iPad's fullscreen view and found solutions (in 1 case a workaround which will do for now).

2022-01-07 14:35 UTC, kambala-decapitator requested changes

2022-01-07 14:35 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            [tmpArr replaceObjectAtIndex:0 withObject:[NSString stringWithUTF8String:"\xF0\x9F\x94\x8D"]];
what is this? Please use the UTF-8 string in code directly.

2022-01-07 15:00 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            [tmpArr replaceObjectAtIndex:0 withObject:[NSString stringWithUTF8String:"\xF0\x9F\x94\x8D"]];
This is the magnifying lens, see the updated commit.

2022-01-07 15:05 UTC, kambala-decapitator approved these changes

2022-01-07 16:06 UTC, wutschel commented
Squashed fixups and rebased to master.

2022-01-07 16:11 UTC, merged