Feature: Introduce Global Search
xbmc/Official-Kodi-Remote-iOS pull request #526
Opened 2021-12-15 06:59 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/418.

"Global Search" will load all Movies, TVShows, Music Videos, Artists (as configured in Kodi), Albums and Songs. Then a search can be applied (the screen shots show a search for "an") and items can be further processed from there. Selecting or long pressing an item will provide the same functionality as if the item would be processed from the standard menus -- e.g. processing a movie from the global search results will behave same as processing from the movie list directly.

This will have merge conflicts with other changes that are provided, and this needs further testing. Therefore I keep this as draft, but is already good to take a look at the implementation.

Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2021-12jrkb4.png"><img src="https://abload.de/img/bildschirmfoto2021-12jrkb4.png" /></a>

## Summary for release notes

Feature: Introduce Global Search

2021-12-19 12:17 UTC, wutschel commented
With the latest update the result lists cells can have different height to use the ideal thumb size and aspect ratio. 

Screenshot:
<a href="https://abload.de/image.php?img=simulatorscreenshot-iu2k26.png"><img src="https://abload.de/img/simulatorscreenshot-iu2k26.png" /></a>

2021-12-31 16:49 UTC, wutschel commented
This needs some more rework to also work with user-configured main menu (e.g. when hiding "Music").

2022-01-14 19:04 UTC, wutschel commented
> This needs some more rework to also work with user-configured main menu (e.g. when hiding "Music").

Works now. Code was rebased to latest master.

2022-01-21 19:27 UTC, wutschel commented
@kambala-decapitator, can you already take a look at this? I re-ordered the commits to ease up the reviews. Also this was rebased and has the changes to rename the `MenuItem` variable to `menuItem`.

2022-01-25 20:05 UTC, wutschel commented
Feedback from testers:
- Enable caching, loading can take quite a while.
- Why not show all albums of an artist (= also match album artist for an album)?
- Show the search bar right away, this is -- even by name -- a search menu.

2022-01-27 19:32 UTC, wutschel commented
Now with support for sorting. Screenshots: https://abload.de/img/bildschirmfoto2022-01vlk6u.png

2022-01-30 11:35 UTC, wutschel commented
Now also supports searching for artist and directors. You can find all albums, music videos and songs of a certain artist, or all movies by a certain director.

2022-02-02 15:14 UTC, kambala-decapitator requested changes
checked up to 90ac153f2c8ffeca6b5db90a033d679d0af3a958 so far

2022-02-02 15:14 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +NSMutableArray *mainMenuItems;
why using a global variable? You could simply use private property.

2022-02-02 16:58 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        [self.sections removeAllObjects];
Removed. This code snipped was moved to another method in a later change. I fixed it there.

2022-02-02 16:59 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    [self loadDetailedData:itemsAndTabs index:0 results:richData];
`loadDetailedData` is called recursively until the end-condition is met. Then `richData` is used.

2022-02-02 17:01 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    NSMutableArray *mutableProperties = [parameters[@"parameters"][@"properties"] mutableCopy];
Yes, it does. There is legacy code which alters the parameters. Not my preferred solution, but I cannot boil the ocean and rework it all.

2022-02-02 17:04 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                    if (((NSNull*)mainFields[@"itemid"] != [NSNull null])) {
Hmm, again legacy code. Overall there are about 40 occasions of `if (((NSNull*)bla != [NSNull null]))`. Should all be changed?

2022-02-02 17:11 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                    serverURL = [NSString stringWithFormat:@"%@:%@/vfs/", obj.serverIP, obj.serverPort];
This is later moved into a helper function:

```
- (NSString*)getServerURL {
    GlobalData *obj = [GlobalData getInstance];
    NSString *stringFormat = (AppDelegate.instance.serverVersion > 11) ? @"%@:%@/image/" : @"%@:%@/vfs/";
    return [NSString stringWithFormat:stringFormat, obj.serverIP, obj.serverPort];;
}
```

2022-02-02 17:16 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                                value = [NSString stringWithFormat:@"%@", itemDict[i][mainFields[@"row7"]]];
But you wouldn't mind to keep it like this, right? There are few dozens places where it is used like this and I would  to this consistent. Just in case I am searching for this pattern.

2022-02-02 17:18 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                            NSMutableDictionary *newDict = [NSMutableDictionary dictionaryWithObjectsAndKeys:
Oh yes. `nil` will sneak in. This is legacy stuff I do not want to touch (for now). I tried this a while back and failed due to the complexity of the whole logic behind.

2022-02-02 17:19 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    [self loadDetailedData:itemsAndTabs index:0 results:richData];
But it's not used in the top-level code. It's it intended to be like that?

2022-02-02 17:21 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                    if (((NSNull*)mainFields[@"itemid"] != [NSNull null])) {
If returned value is of type id, then cast is not needed

2022-02-02 17:21 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    [self loadDetailedData:itemsAndTabs index:0 results:richData];
Yes, this is correct and intended.

2022-02-02 17:22 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                                value = [NSString stringWithFormat:@"%@", itemDict[i][mainFields[@"row7"]]];
Sure, this was purely FYI :)

2022-02-02 17:23 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                    if (((NSNull*)mainFields[@"itemid"] != [NSNull null])) {
Would you be ok, if I make handle this in a separate coding styles commit? I will create an issue for this.

2022-02-02 17:29 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                        for (int i = 0; i < total; i++) {
Also an activity for an addtional coding style PR? There are few more places like this in the code.

2022-02-02 17:42 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                    if (((NSNull*)mainFields[@"itemid"] != [NSNull null])) {
Sure, that's fine

2022-02-02 18:09 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                        for (int i = 0; i < total; i++) {
Sounds good.

But the main point is that new code should be good from the start ;)

2022-02-02 18:16 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                            id row13obj = [mainFields[@"row13"] isEqualToString:@"options"] ? itemDict[i][mainFields[@"row13"]] == nil ? @"" : itemDict[i][mainFields[@"row13"]] : itemDict[i][mainFiel
If I should touch this (also legacy code), I would go for this:

```
id row13key = mainFields[@"row13"];
id row13obj = [row13key isEqualToString:@"options"] ? (item[row13key] == nil ? @"" : item[row13key]) : item[row13key];
```

2022-02-02 18:18 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                        for (int i = 0; i < total; i++) {
I understand your point. But most of what you ask me to change is just legacy code which I am just moving into methods to better organize the code. When I am writing fresh code I really try to follow whatever I learned. :)

2022-02-02 18:31 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    NSObject *row11 = item[mainFields[@"row11"]];
Done, also for the line below and code related to `row7` and `row7key`.

2022-02-02 18:40 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +NSMutableArray *mainMenuItems;
Interesting, I wasn't even looking at this. Just undid the former change as it became obsolete. I now made it a property and also removed the unneeded variable `hostRightMenuItems` below.

2022-02-03 14:47 UTC, kambala-decapitator approved these changes

2022-02-03 14:47 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    id row13obj = [row13key isEqualToString:@"options"] ? (item[row13key] == nil ? @"" : item[row13key]) : item[row13key];
you could use `item[row13key] ?: @""` here (and below) as well

2022-02-03 17:21 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        thumbSize.y = 53;
Removed it. I did this to see in the code which other types to handle.

2022-02-05 09:56 UTC, wutschel commented
Squashed, rebased and ready to go.

2022-02-07 08:55 UTC, merged