Improvements around playlist
xbmc/Official-Kodi-Remote-iOS pull request #533
Opened 2021-12-21 19:54 UTC by wutschel

## Description

Adresses an issue report in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3076638#pid3076638).

1. Choose correct default thumb for the Music and Video playlist.
2. Ignore playlist items which refer to files with a "`special://"` prefix. This happens when using skin intros (tested with _Aeon Tajo_)

## Summary for release notes

Bugfix: Show correct default thumb in movie/music playlists
Improvement: Ignore playlist items triggered by skin intros

2022-01-02 12:47 UTC, wutschel commented
Should be merged after https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/539 and needs a minor update to handle a third `playerID` which is introduced it.

2022-01-07 09:56 UTC, kambala-decapitator commented
FYI #539 has already been merged

2022-01-07 10:20 UTC, wutschel commented
Updated and rebased to master. Good for review.

2022-01-07 10:28 UTC, kambala-decapitator requested changes

2022-01-07 10:28 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    UIImage *defaultThumb = [UIImage imageNamed:@"nocover_filemode"];
makes more sense to assign this in `default`

2022-01-07 10:32 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    UIImage *defaultThumb = [UIImage imageNamed:@"nocover_filemode"];
Agreed, also will set a default for `cornerLabel.text`.

2022-01-07 10:36 UTC, kambala-decapitator approved these changes

2022-01-07 10:40 UTC, wutschel commented
Squashed and ready to go.

2022-01-07 10:41 UTC, merged