Rework main menu controllers
xbmc/Official-Kodi-Remote-iOS pull request #535
Opened 2021-12-22 07:29 UTC by wutschel

## Description

This PR reworks the controllers which implement the main menu and server connection status visualization for iPad and iPhone. The changes include:

- Refactoring to avoid code duplication in several places (shadows, connection status icons, menu item alpha, ...)
- Removing magic numbers
- iPad: Moving the connection status indicator from top of main menu to bottom right corner
- iPad: Rearrange the toolbar items (smaller Kodi icon, mute button moved left, more space around server button)
- iPad: Minor style update of left menu (improved visibility of vertical separator, remove horizontal separator)

Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2021-12xjjdh.png"><img src="https://abload.de/img/bildschirmfoto2021-12xjjdh.png" /></a>

## Summary for release notes

Improvement: Move iPad's connection status to bottom right corner
Improvement: Optimized arrangement of toolbar buttons
Maintenance: Avoid code duplication in several places

2021-12-23 19:55 UTC, wutschel commented
Based on a suggestion from the forum I added the label "Playlist" on top of iPad's playlist. This makes clear which purpose the empty view has if the playlist is empty. As the status bar was removed from the menu in this PR there is only very small loss of the playlist view height.

Screenshot: https://abload.de/img/bildschirmfoto2021-12g7j9e.png

2022-01-06 10:18 UTC, kambala-decapitator commented
please fix conflicts

2022-01-06 10:30 UTC, wutschel commented
Rebase to master.

2022-01-06 11:39 UTC, kambala-decapitator requested changes
on the shadow implementation: is it really required to use custom images? Can you implement standard shadow using `view.layer.shadow*` properties?

2022-01-06 11:39 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> ++ (void)addShadowsToView:(UIViewController*)controller viewFrame:(CGRect)frame {
1. method name says "...toView" but you actually pass a view controller
2. in second parameter you could as well pass the view itself and then just read its `frame` inside

2022-01-06 11:39 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +            [UIView commitAnimations];
1. please use block-based animation method
2. early "return": `if (!cell) continue;`
3. I think you can iterate only over `tableView.visibleCells` - with this `nil` check won't be needed at all

2022-01-06 11:39 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +        if (![extraTimer isValid]) {
you could also change to read property instead of calling method

2022-01-06 11:39 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +#define LINE_WIDTH 1
seems it's actually height?

2022-01-06 11:39 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +    frame.size.height = self.view.frame.size.height - YPOS - deltaY;
I think it's better not to flip sign of `YPOS` (less lines to touch) and change this line to `+ YPOS`

2022-01-06 16:13 UTC, wutschel commented on XBMC Remote/Utilities.m
> ++ (void)addShadowsToView:(UIViewController*)controller viewFrame:(CGRect)frame {
I changed the first parameter to `UIView`. The 2nd I would like to keep a different type as this is easier to read in the method itself.

2022-01-06 16:17 UTC, wutschel commented on XBMC Remote/ViewControllerIPad.m
> +        if (![extraTimer isValid]) {
I am adding a coding style change commit to replace `isValid` with the equivalent property in overall 3 locations.

2022-01-06 16:21 UTC, wutschel commented on XBMC Remote/ViewControllerIPad.m
> +#define LINE_WIDTH 1
In fact it is _thickness_. But as borders also use "width" I was not concerned too much. I have no strong opinion on this. Shall I still change to `LINE_HEIGHT`?

2022-01-06 16:34 UTC, wutschel commented on XBMC Remote/ViewControllerIPad.m
> +    frame.size.height = self.view.frame.size.height - YPOS - deltaY;
I find the layout calculation easier to read this way. `YPOS` and `deltaY` share the same sign and both reduce the frame's height. If you do not insist on changing it, I would like to keep it like this.

2022-01-06 17:03 UTC, wutschel commented on XBMC Remote/Utilities.m
> +            [UIView commitAnimations];
You are looking for the following implementation (not changing `viewWithTag`)?

```
+ (void)setStyleOfMenuItems:(UITableView*)tableView active:(BOOL)active {
    CGFloat alpha = active ? 1.0 : 0.3;
    for (UITableViewCell *cell in tableView.visibleCells) {
        if (cell != nil) {
            [UIView animateWithDuration:0.3
                             animations:^{
                                ((UIImageView*)[cell viewWithTag:1]).alpha = alpha;
                                ((UIImageView*)[cell viewWithTag:2]).alpha = alpha;
                                ((UIImageView*)[cell viewWithTag:3]).alpha = alpha;
                             }];
        }
    }
}
```

2022-01-06 17:06 UTC, wutschel commented on XBMC Remote/ViewControllerIPad.m
> +#define LINE_WIDTH 1
Nevermind, just did it.

2022-01-06 18:38 UTC, wutschel commented
> on the shadow implementation: is it really required to use custom images? Can you implement standard shadow using `view.layer.shadow*` properties?

Valid point. I just tried to find a good solution which works for iPad and iPhone. And I was not successful. Problem is the iPad where the shadows shall only be applied north, west and east. On the south side the toolbar shall be on top, more or less masking the shadow. Maybe I will find a better solution in future, but nothing which can be done as part of this PR.

2022-01-07 08:22 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +            [UIView commitAnimations];
yep.

- `if` check shouldn't be needed
- casting to `UIImageView` isn't needed
- you can also use `for` to loop through tags

2022-01-07 08:23 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +    frame.size.height = self.view.frame.size.height - YPOS - deltaY;
ok, let's leave as is

2022-01-07 08:26 UTC, kambala-decapitator commented
> > on the shadow implementation: is it really required to use custom images? Can you implement standard shadow using `view.layer.shadow*` properties?
> 
> Valid point. I just tried to find a good solution which works for iPad and iPhone. And I was not successful. Problem is the iPad where the shadows shall only be applied north, west and east. On the south side the toolbar shall be on top, more or less masking the shadow. Maybe I will find a better solution in future, but nothing which can be done as part of this PR.

it's possible to apply shadow to any sides you want, see e.g. https://www.hackingwithswift.com/articles/155/advanced-uiview-shadow-effects-using-shadowpath

Fully agree that it should be a separate PR.

2022-01-07 09:26 UTC, wutschel commented on XBMC Remote/Utilities.m
> +            [UIView commitAnimations];
I will remove the `if` check and keep the other stuff until the `viewWithTag` cleanup.

2022-01-07 09:30 UTC, wutschel commented
> it's possible to apply shadow to any sides you want
Saved the link for further investigation. But this looks similar to what I already tried yesterday.

Besides this the latest updates contain all discussed fixups.

2022-01-07 09:45 UTC, kambala-decapitator approved these changes

2022-01-07 10:09 UTC, wutschel commented
Squashed and rebased to master.

2022-01-07 10:11 UTC, merged