Maintenance: Rework playlist
xbmc/Official-Kodi-Remote-iOS pull request #539
Opened 2021-12-29 18:59 UTC by wutschel

## Description

This PR has several changes around `NowPlaying`, with a focus to the playlist's segment control and the song details.
- Use correct string `"Video"` in playlist's segment control (used `"Video "` before)
- Right-align `"Edit"` button in playlist's segment control
- Remove unneeded code, magic numbers and avoid code duplication

## Summary for release notes

Bugfix: Correct string "Video" in playlist's segment control
Improvement: Right-align "Edit" button in playlist's segment control
Maintenance: Remove unneeded code, magic numbers and avoid code duplication in NowPlaying

2022-01-06 12:19 UTC, kambala-decapitator requested changes

2022-01-06 12:19 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    if (selection) {
early return

2022-01-06 12:19 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +        UIImageView *coverView = (UIImageView*)[cell viewWithTag:4];
any chance to avoid tags?

2022-01-06 12:31 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +            playlistName = LOCALIZED_STR(@"Pictures ");
The string is (a few lines below) combined with another string to build localized message. The trailing space is part of the concept. Changing this will require to revisit all language strings. I would like to avoid this.

2022-01-06 12:34 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +                    (selectedPlayerID != -1 && playerID != selectedPlayerID)) {  // DA SISTEMARE SE AGGIUNGONO ITEM DALL'ESTERNO: FUTURA SEGNALAZIONE CON SOCKET!
I`d prefer to remove it. Fine for you?

2022-01-06 12:38 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    if (selection) {
Will do.

2022-01-06 12:42 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +        UIImageView *coverView = (UIImageView*)[cell viewWithTag:4];
Well, this is done all over the place in the existing code. I am not too happy about this. Maybe I'll do this separately one controller after the other. Imho such change would make this PR too heavy.

2022-01-06 12:51 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +#define PLAYERID_PICTURES 2
Just like this (would not require too many changes)?

```
typedef enum {
    PLAYERID_UNKNOWN = -1,
    PLAYERID_MUSIC = 0,
    PLAYERID_VIDEO = 1,
    PLAYERID_PICTURES = 2
} PlayerIDs;
```

2022-01-07 08:28 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +            playlistName = LOCALIZED_STR(@"Pictures ");
thanks for the explanation!

2022-01-07 08:28 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                    (selectedPlayerID != -1 && playerID != selectedPlayerID)) {  // DA SISTEMARE SE AGGIUNGONO ITEM DALL'ESTERNO: FUTURA SEGNALAZIONE CON SOCKET!
> I`d prefer to remove it. Fine for you?

yep

2022-01-07 08:28 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +#define PLAYERID_PICTURES 2
looks good. You could also assign value only to the first member.

2022-01-07 08:29 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +        UIImageView *coverView = (UIImageView*)[cell viewWithTag:4];
agree with a separate PR

2022-01-07 08:53 UTC, wutschel commented
Added the fixups. If ok, I will try to squash them and rebase to master.

2022-01-07 08:55 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    UIImageView *coverView = (UIImageView*)[cell viewWithTag:4];
casts not needed

2022-01-07 08:56 UTC, kambala-decapitator requested changes

2022-01-07 08:56 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    if (!selection) {
please also add early return to the method above (updatePlaylistProgressbar)

2022-01-07 08:58 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    UIImageView *coverView = (UIImageView*)[cell viewWithTag:4];
Let me handle this when revisiting the use of `viewWithTag`.

2022-01-07 09:00 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    if (!selection) {
Done

2022-01-07 09:01 UTC, kambala-decapitator approved these changes

2022-01-07 09:23 UTC, wutschel commented
Squashed and rebased to master.

2022-01-07 09:46 UTC, merged