Maintenance: Migrate from NSURLConnection to NSURLSession
xbmc/Official-Kodi-Remote-iOS pull request #542
Opened 2022-01-05 13:47 UTC by wutschel

## Description

This PR resolves some more deprecation warnings and simplifies especially the implementation of `DSJSONRPC`. It also adds `NSLog` messages for sent and received JSON commands for debug purposes. These are disabled by default and can be uncommented on demand.

## Summary for release notes

Maintenance: Migrate from NSURLConnection to NSURLSession

2022-01-05 13:51 UTC, wutschel commented
The changes are working from my first tests, and it gives a good feeling to finally got rid of the deprecated functions. Nevertheless I want to have more time to review and check some details of the implementation, especially in `SDWebImageDownloaderOperation`. I suspect potential issues with thread handling here. Therefore keeping this as draft for now. 

But a review of the changes in their current state is appreciated. :)

2022-01-07 09:37 UTC, kambala-decapitator requested changes
In general I don't find this PR correct.

1. instead of modifying `SDWebImage` I suggest to check if this library has been updated to `NSURLSession`. If not, then I'd rather replace it with a more modern alternative like AFNetworking (I remember it has image-related functionality) or Nuke or something similar (the choice is discussable).
2. you actually removed the main point of `didReceiveResponse` and `didReceiveData` delegate methods. They serve the purpose of "real time" data handling: initially you receive response telling how much data will follow, then `didReceiveData` may be called multiple times (for big payloads). If you feel that such functionality is no longer needed for Kodi API interaction, I'd suggest to refactor the task completion block to simplify data handling and avoid mimicking delegate methods. Otherwise, please use `NSURLSessionDataTaskDelegate` to implement the counterparts.

2022-01-07 09:37 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +        self.completionHandler = completionHandlerCopy;
you don't need to copy original object manually because your property does that internally

2022-01-07 09:37 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    NSURLSession *session = [NSURLSession sharedSession];
please use dedicated session object

2022-01-07 09:37 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> -#pragma mark - Runtime Method Invocation Handling
are you sure this code is no longer needed?

2022-01-07 09:37 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +//    NSString *JSONcommand = [[[NSString alloc] initWithData:postData encoding:NSUTF8StringEncoding] autorelease];
to make it even easier, I suggest to uncomment the code and surround it with macro, e.g. `DEBUG` (defined only in debug mode) or some custom one that would be on top of the file and commented by default.

But you could also use "arguments passed on launch" (basically `argv`) instead.

2022-01-07 09:37 UTC, kambala-decapitator commented on XBMC Remote/VolumeSliderView.m
> -        [self checkMuteServer];
seems you haven't added the call to appropriate place yet

2022-01-07 09:37 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> -    self._activeConnections = [NSMutableDictionary dictionary];
by removing this concurrent requests will be broken as you have only a single completion handler now

2022-01-07 09:37 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +- (void)willSendRequestForAuthenticationChallenge:(NSURLAuthenticationChallenge*)challenge {
to restore this functionality, you must implement data task delegate

2022-01-07 09:56 UTC, wutschel commented
Well, if this is going into the wrong direction, I'd rather close this one, take it as learning and start it over freshly. I guess you don't mind. :)

2022-01-07 09:58 UTC, closed without merging