Bugfix: Fix wrong navigation titles
xbmc/Official-Kodi-Remote-iOS pull request #552
Opened 2022-01-08 22:20 UTC by wutschel

## Description

Fixes a regression of https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/541 and improves the information shown in the navigation title.

The App uses the flag `enableSection` to determine whether a submenu's result list shall have sections or not.  This flag was also misused to decide, if a navigation title shall show the amount of results for a certain submenu -- e.g. "Albums (21)" -- or not. Since the latest changes to allow sections for more submenus this caused the problem of showing wrong navigation titles.

This PR reworks the logic to not misuse `enableSection` anymore and always show the applied filter and amount of results in the navigation title. This automatically brings additional value for several submenus. A required exception is the album view which must only show the album title and not the amount of tracks listed for this certain album.

Screenshots:
https://abload.de/img/bildschirmfoto2022-01v8jvm.png
https://abload.de/img/bildschirmfoto2022-01jzkic.png
https://abload.de/img/bildschirmfoto2022-01xljmw.png

As shown in the screenshots there are at least three more views where displaying the amount of results disturb the user experience in my opinion:
- Channel Guide
- Kodi Settings
- Files/Folders

Until I have clarity on how to deal with these views I keep this PR as draft.

## Summary for release notes

Bugfix: Fix wrong navigation titles
Improvement: Show filter and results details in navigation titles

2022-01-09 16:56 UTC, wutschel commented
I think I now found an overall solution I and other can live with for now. More changes / fine-tuning can be applied later, if needed.

Screenshots:
https://abload.de/img/bildschirmfoto2022-018hj03.png (iPad)
https://abload.de/img/bildschirmfoto2022-01a3jk2.png (iPhone)

2022-01-09 16:57 UTC, wutschel commented
@kambala-decapitator, I already added the block-based animation as I anticipated you will ask for this anyhow ;)

2022-01-10 13:07 UTC, kambala-decapitator requested changes
On 3347c029f5ee8d8aea7f671d197c804379df96a3: I think using `backBarButtonItem` would solve all the hassle.

2022-01-10 13:07 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        mainMenu *newMenuItem = [MenuItem.subItem copy];
FYI it's really difficult to read when type name starts with lowercase letter and, conversely, variable starts with an uppercase one.

2022-01-10 13:07 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        [UIView animateWithDuration:0.1
from the current implementation it seems that animations should run in parallel. I think your intention is to run the second animation after the first one? If yes, then you need to start it in the completion block of the first one.

2022-01-10 17:14 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +- (void)setScreenLabel:(NSString*)labelText withCheckButton:(BOOL)check checkParam:(BOOL)param {
`setFilternameLabel` is acceptable?

2022-01-10 17:18 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +- (void)setScreenLabel:(NSString*)labelText withCheckButton:(BOOL)check checkParam:(BOOL)param {
`setFilternameLabel:runFullscreenButtonCheck:forceHide:` is acceptable?

2022-01-10 17:22 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    if (IS_IPAD) {
Agreed.

2022-01-10 17:29 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        [UIView animateWithDuration:0.1
My intention was to keep the behaviour of the former code. Is the change correct then?

2022-01-10 17:35 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    NSString *labelText = [NSString stringWithFormat:@"%@ (%d)", parameters[@"label"], numResults];
My intention was to set `labelText` for the most likely condition outside of the if-condition. This way reading `parameters[@"label"]` is only executed once in most cases.
If I change the logic you will nearly always run the assignment twice -- 1x without `(%d)` and 1x with.

2022-01-10 19:57 UTC, wutschel commented
> On [3347c02](https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/3347c029f5ee8d8aea7f671d197c804379df96a3): I think using `backBarButtonItem` would solve all the hassle.

Maybe you help me a bit further. I now added
```
self.navigationItem.backBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"blib" style:UIBarButtonItemStylePlain target:nil action:nil];
self.navigationItem.backBarButtonItem.title = parameters[@"label"];
```
where `parameters[@"label"]` is the desired short form. But now the "back text" is always shown in full length and not reducing itself (first truncated, then reduced to "back", then reduced to "<") when the navigation label needs more space.

Screenhots (left = desired, right = using above`backBarButtonItem `):
<a href="https://abload.de/image.php?img=bildschirmfoto2022-01mikft.png"><img src="https://abload.de/img/bildschirmfoto2022-01mikft.png" /></a>

2022-01-10 20:18 UTC, wutschel commented
Using `self.navigationItem.backButtonTitle = parameters[@"label"]` works as intended. But this is only supported for iOS11 and higher. I could live with this and only allow the long label (incl. `"(%d)"`) for iOS11 and higher. For older iOS I can fall back to the short form for both the back and the navigation label. This I can avoid the nasty implementation in 3347c02 and get the desired result for iOS11 and higher.

2022-01-11 10:28 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                     animations:^{
if you don't put `animations:` on new line, then the block will be indented only with 4 spaces making it more readable

2022-01-11 10:36 UTC, kambala-decapitator commented
on the back button: full text is a bit unexpected. Can't give you the right solution straight out of my head as I haven't used this API for a while.

If `backButtonTitle` works as expected, let's use it: the amount of < 11 devices is quite low.

Btw now `parameters[@"label"]` is used quite a lot, I suggest to extract it into a variable.

2022-01-11 10:40 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        [UIView animateWithDuration:0.1
well, the former code with old-style animations works exactly the same: animations basically run in parallel.

2022-01-11 12:34 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                     animations:^{
Like this?

```
    // fade out
    [UIView animateWithDuration:0.3
                     animations:^{
        topNavigationLabel.alpha = 0;
        
    }];
    // update label
    topNavigationLabel.text = labelText;
    // fade in
    [UIView animateWithDuration:0.1
                     animations:^{
        topNavigationLabel.alpha = 1;
        if (check) {
            [self checkFullscreenButton:forceHide];
        }
    }];
```

2022-01-11 12:38 UTC, wutschel commented
> If `backButtonTitle` works as expected, let's use it: the amount of < 11 devices is quite low.

Same view here.

> Btw now `parameters[@"label"]` is used quite a lot, I suggest to extract it into a variable.

Reordering does the trick:
```
NSString *labelText = parameters[@"label"];
if (@available(iOS 11.0, *)) {     
    self.navigationItem.backButtonTitle = labelText;
    if (!albumView) {
        labelText = [NSString stringWithFormat:@"%@ (%d)", labelText, numResults];
    }
}
```

2022-01-11 14:28 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                     animations:^{
you got the indentation right, but next time you indent in Xcode, it will break it. Instead, write like this:

```objc
[UIView animateWithDuration:0.3 animations:^{
    topNavigationLabel.alpha = 0;
}];
```

2022-01-11 14:44 UTC, kambala-decapitator commented
you could also simplify appending a bit:

```objc
labelText = [labelText stringByAppendingFormat:@"(%d)", numResults];
```

2022-01-11 18:37 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                     animations:^{
Interesting seems to be connected to some settings then. Will do like you suggest.

2022-01-11 18:49 UTC, wutschel commented
Added the fixups.

2022-01-12 12:04 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        mainMenu *newMenuItem = [MenuItem.subItem copy];
that's something for a separate PR

2022-01-12 12:06 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        [UIView animateWithDuration:0.1
not sure why this is marked resolved? What was your original intention with animations?

2022-01-12 13:28 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        [UIView animateWithDuration:0.1
Well, this was not my code. I just wanted to make sure the behavior stays unchanged. You confirmed this as far as I understood. This is why I marked it resolved.

2022-01-12 13:45 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        [UIView animateWithDuration:0.1
right, sorry for misunderstanding!

do you confirm that animations still work correctly after changing the code to use the new style?

2022-01-12 18:59 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        [UIView animateWithDuration:0.1
I compared the behaviour old vs. new. The animation looks the same from what I can see.

2022-01-13 11:40 UTC, kambala-decapitator approved these changes

2022-01-13 16:35 UTC, wutschel commented
Squashed and rebased to master.

2022-01-14 09:04 UTC, merged