Feature: Playlist longpress details for music videos and recordings
xbmc/Official-Kodi-Remote-iOS pull request #563
Opened 2022-01-16 12:29 UTC by wutschel

## Description

This PR implements the longpress functionality for music videos and recordings in the playlist. This is consistent with the longpress functionality for music, movies and TV shows.

Remark: The new functionality for recordings will only work with Kodi 20.0 and later.

Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-01fzjpk.png"><img src="https://abload.de/img/bildschirmfoto2022-01fzjpk.png" /></a>

## Summary for release notes

Feature: Playlist longpress details for music videos and recordings

2022-01-16 12:32 UTC, wutschel commented
Needs to have https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/561 merged first, followed by replacing `"UIApplicationEnableVideoSection"` and "`UIApplicationEnableRecordingSection"`.

2022-01-16 21:25 UTC, wutschel commented
Updated and rebased to master.

2022-01-17 14:41 UTC, kambala-decapitator requested changes

2022-01-17 14:41 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.h
> +@property (nonatomic, retain) mainMenu *playlistMusicVideos;
use `strong` instead of `retain` in new code

2022-01-17 14:41 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    BOOL useIcon = [item[@"type"] isEqualToString:@"recording"] || [item[@"recordingid"] intValue];
please add `> 0` to improve readability (I guess negative values are impossible?), using `longLongValue` is also a good idea

2022-01-17 16:51 UTC, wutschel commented on XBMC Remote/AppDelegate.h
> +@property (nonatomic, retain) mainMenu *playlistMusicVideos;
Shall in general `retain` be replaced with `strong`? If so, I would like to change this consistently for the whole file.

2022-01-18 12:29 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.h
> +@property (nonatomic, retain) mainMenu *playlistMusicVideos;
yes, `strong` is preferred

2022-01-18 12:32 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    BOOL useIcon = [item[@"type"] isEqualToString:@"recording"] || [item[@"recordingid"] intValue];
it's about possible overflow of `int`: what if ID is greater than 32767?

Then you'd better change it everywhere in the app.

2022-01-18 12:36 UTC, wutschel commented on XBMC Remote/AppDelegate.h
> +@property (nonatomic, retain) mainMenu *playlistMusicVideos;
Is it recommended to do this for all properties? I could create 1 coding style PR which changes this in all files at once.

2022-01-18 12:38 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    BOOL useIcon = [item[@"type"] isEqualToString:@"recording"] || [item[@"recordingid"] intValue];
Isn't 'int' a 32 bit type? Otherwise I would have expected such overflows to have been reported for larger databases already.

2022-01-18 12:49 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.h
> +@property (nonatomic, retain) mainMenu *playlistMusicVideos;
only for those that are currently marked `retain`, would be a good code cleanup. But you could also review other properties and check if any of them need to be changed to `copy` or `assign` (or, conversely, to `strong`).

2022-01-18 12:50 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    BOOL useIcon = [item[@"type"] isEqualToString:@"recording"] || [item[@"recordingid"] intValue];
oh yes, indeed, should be 32-bit, sorry for the misleading info.

using `long` for IDs would be good for extremely large DBs anyway.

2022-01-18 18:31 UTC, wutschel commented on XBMC Remote/AppDelegate.h
> +@property (nonatomic, retain) mainMenu *playlistMusicVideos;
I added a commit to replace `retain` with `strong` for the whole app. Let me know, if this is correct this way.

2022-01-18 18:32 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    BOOL useIcon = [item[@"type"] isEqualToString:@"recording"] || [item[@"recordingid"] intValue];
Let me do this in a separate PR.

2022-01-19 12:28 UTC, kambala-decapitator approved these changes

2022-01-19 12:28 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSARCHelpers.h
> +#define DS_RETAIN(X)        [X strong];
this change is incorrect, but we don't use manual memory management anyway

2022-01-19 12:28 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    BOOL useIcon = [item[@"type"] isEqualToString:@"recording"] || [item[@"recordingid"] intValue];
sure, sounds good

2022-01-19 12:28 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.h
> +@property (nonatomic, retain) mainMenu *playlistMusicVideos;
yep, you did it right!

2022-01-19 12:57 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSARCHelpers.h
> +#define DS_RETAIN(X)        [X strong];
I will undo this one.

2022-01-19 17:16 UTC, wutschel commented
Ready to go.

2022-01-20 13:10 UTC, merged