Improvement:  Better usability of remote screen
xbmc/Official-Kodi-Remote-iOS pull request #577
Opened 2022-01-23 11:46 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/573.

This PR implemented some changes in the remote functionality:

iPad Remote Screen:
- Use `UIModalPresentationFormSheet` for the remote view on iPad:
- Remote view can be brought up from anywhere via a button in the iPad toolbar.
- Remote view on iPad does not dismiss the browser screen anymore, it is shown as overlay.
- Remote view is always shown in center.
- Remote view needs to have the volume slider as hitting the volume button in toolbar will dismiss the overlay.

iPhone Remote Screen:
- Remote Position can be toggled at runtime via new toolbar button.

Persistency:
- The gesture zone mode and remote position are now saved and restored.
- The app settings for the same were removed.

Screenshots:
https://abload.de/img/simulatorscreenshot-iy8ku5.png (iPad, overlay over browser)
https://abload.de/img/simulatorscreenshot-iofkk4.png (iPad, overlay over fullscreen)
https://abload.de/img/simulatorscreenshot-ic2kvy.png (iPad, overlay with volume bar)
https://abload.de/img/bildschirmfoto2022-0195jwi.png (iPhone, top/bottom toggle)

## Summary for release notes

Improvement: Remote screen on iPad does not dismiss browser screens
Improvement: Runtime change of remote top/bottom position on iPhone
Improvement: Restore remote modes instead of app settings configuration

2022-02-07 10:46 UTC, kambala-decapitator requested changes
also regarding 9590d3dff37f2af097793a998a0169a969512ce4: `stting` typo, don't see a reason to mention cherry-pick

2022-02-07 10:46 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        [NSKeyedArchiver archiveRootObject:modes toFile:path];
why not using user defaults?

2022-02-07 17:44 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        frame = remoteControlView.frame;
Good catch! In fact the former assignment and condition could be made much simpler.

2022-02-07 17:51 UTC, wutschel commented
> also regarding [9590d3d](https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/9590d3dff37f2af097793a998a0169a969512ce4): `stting` typo, don't see a reason to mention cherry-pick

Fixed.

2022-02-07 17:53 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        [self.presentationController.presentedView.gestureRecognizers[0] setEnabled:NO];
I didn't find any other way to handle this.

2022-02-07 18:11 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        [NSKeyedArchiver archiveRootObject:modes toFile:path];
You're asking the right question. With user defaults this is much less code and easier to read.

2022-02-08 08:49 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        [self.presentationController.presentedView.gestureRecognizers[0] setEnabled:NO];
I think it's related to the fact that modern OS uses `UIModalPresentationAutomatic` style by default when showing modal VCs, try setting `modalPresentationStyle` property to `UIModalPresentationFullScreen` instead (or a different one)

2022-02-08 09:03 UTC, kambala-decapitator requested changes

2022-02-08 09:03 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +    [userDefaults setObject:@(isGestureViewActive) forKey:@"GestureView"];
FYI there're dedicated `integerForKey` and `boolForKey` as well as respective setters.

Also, `GestureView` doesn't seem a good name for a boolean.

2022-02-08 12:24 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        [self.presentationController.presentedView.gestureRecognizers[0] setEnabled:NO];
I tried using `UIModalPresentationFullScreen` (and others). The current way definitely looks best. We should not change this.

2022-02-08 12:26 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    [userDefaults setObject:@(isGestureViewActive) forKey:@"GestureView"];
I will apply `integerForKey` and `boolForKey` in a dedicated PR. The key name I will change to `"GestureViewEnabled"`.

2022-02-08 12:40 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        [self.presentationController.presentedView.gestureRecognizers[0] setEnabled:NO];
ok, let's keep.

have you tested on pre-iOS 13? I feel it'd crash with array out-of-bounds. Using `gestureRecognizers.first` would be safer.

2022-02-08 12:52 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        [self.presentationController.presentedView.gestureRecognizers[0] setEnabled:NO];
> have you tested on pre-iOS 13? 

Just tested with iPad simulator using iOS 11.4 -> works. On iOS 11.4 it even works w/o this line. But on iOS 14.5 the line is required. Do we know by hard fro which iOS on this setting is needed?

> I feel it'd crash with array out-of-bounds. Using `gestureRecognizers.first` would be safer.

Changed to `gestureRecognizers.firstObject`.

2022-02-08 12:55 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        [self.presentationController.presentedView.gestureRecognizers[0] setEnabled:NO];
I believe it was introduced in iOS 13 and is directly related to UIModalPresentationAutomatic

2022-02-09 12:05 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        [self.presentationController.presentedView.gestureRecognizers[0] setEnabled:NO];
ok, let's keep without condition

2022-02-09 12:06 UTC, kambala-decapitator approved these changes

2022-02-09 18:51 UTC, wutschel commented
Squashed and rebased to master.

2022-02-09 20:27 UTC, merged