Feature: User selectable default view
xbmc/Official-Kodi-Remote-iOS pull request #578
Opened 2022-01-24 11:41 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/569.

This implements the possibility to let the user configure the view in which the App starts after the connection to Kodi was server established. The user can for example select the "Movies" or the "Remote" view for this. As default the App will still fall back to the "Main Menu" view -- as before this new feature. The same happens, if a view was selected which is not activated in the main menu configuration.

Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-0176jz1.png"><img src="https://abload.de/img/bildschirmfoto2022-0176jz1.png" /></a>

## Summary for release notes

Feature: User selectable default view

2022-01-30 00:33 UTC, wutschel commented
Feedback from TF tests:
- Default menu is not marked / selected in the main menu
- Already running (marked / selected) menus are not unmarked / unselected when the default gets activated
- So you might end up in e.g. Remote being up, but no entry or another  entry is marked / selected in the main menu

2022-02-07 11:18 UTC, kambala-decapitator requested changes
are you a polyglot now? :)

2022-02-07 11:18 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
have you tested case when not all cells fit on screen? In such case this method would return `nil`.

instead, better query the data source (not necessarily object conforming to `UITableViewDataSource`) itself that would return data regardless of the table being loaded / all cells being on screen.

2022-02-07 11:18 UTC, kambala-decapitator commented on XBMC Remote/Utilities.h
> ++ (void)enableDefaultController:(UIViewController<UITableViewDelegate>*)ctrl tableView:(UITableView*)tableView;
- better use `id<UITableViewDelegate>` type
- `ctrl` is a bad name

2022-02-07 17:22 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
No, I did not test this. Thanks for highlighting. A simple approach w/o too much changes would be this one:

```
// Search for the indexPath for the desired controller
for (int i = 0; i < [tableView numberOfRowsInSection:0]; ++i) {
    NSIndexPath *indexPath = [NSIndexPath indexPathForItem:i inSection:0];
```
Ok for you?

And btw: There is another loop using `indexPathsForVisibleRows` in the method above (formatting the text and icons). Isn't this the same problem?

2022-02-08 10:03 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
sorry, my initial reasoning was incorrect because I didn't notice that you use `indexPathsForVisibleRows`: obtaining a visible cell never returns `nil`. There was no need for this fixup.

But the main point is valid: you can't gain access to invisible cells using current approach. Your modified code also doesn't solve anything because you're still tied to `cellForRowAtIndexPath`: this method returns `nil` for invisible cells. That's why I'm suggesting to operate on the data source (model data) directly and not rely on UI at all.

2022-02-08 12:10 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
This is what you have in mind?

```
// Search for the index path for the desired controller
for (int row = 0; row < menuItems.count; ++row) {
    mainMenu *item = menuItems[row];
    if ([item.mainLabel isEqualToString:LOCALIZED_STR(label)]) {
        return [NSIndexPath indexPathForRow:row inSection:0];
    }
}
```

2022-02-08 13:16 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
yes, much better now!

even better would be using array's method `enumerateObjects...` ;)

2022-02-08 17:35 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
But that doesn't really improve the readability. You're ok with keeping this like I proposed?

2022-02-09 12:07 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
well, this method should be the preferred way when you need both object and its index. I'd rather use it.

2022-02-09 19:10 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
Not quite happy with the result, but please check the last fixup commit.

2022-02-09 19:48 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
oh right, you need to return an index path from there... Then `indexOfObjectPassingTest` would be a better choice.

2022-02-09 20:25 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
Sorry, but I find the result really hard to read

```
// Search for the index path of the desired controller
NSUInteger row = [menuItems indexOfObjectPassingTest:^BOOL(mainMenu *item, NSUInteger row, BOOL *stop) {
    return [item.mainLabel isEqualToString:LOCALIZED_STR(label)]; 
}];
    
NSIndexPath *indexPath = row == NSNotFound ? nil : [NSIndexPath indexPathForRow:row inSection:0];
    
return indexPath;
```

2022-02-09 20:26 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +        UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
looks quite natural to me :)

if you're really unsatisfied, let's keep the original version then.

2022-02-09 20:27 UTC, kambala-decapitator approved these changes

2022-02-09 20:27 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
Thanks

2022-02-09 20:39 UTC, wutschel commented
Squashed and rebased to master.

2022-02-09 20:46 UTC, kambala-decapitator commented
pls fix conflicts

2022-02-09 20:55 UTC, merged