Maintenance: Coding style changes
xbmc/Official-Kodi-Remote-iOS pull request #597
Opened 2022-02-10 19:10 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/589 and closes most topics addressed in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/570 (which needs more changes in `NowPlaying`). 

Following changes are done:
- Use `for (... in ...)` instead of `for (int = 0; ...)`
- Do not cast type `id` to `(NSNull*)`
- Use `NSUserDefaults` methods `boolForKey:`, `integerForKey:`, `setBool:forKey:` and `setInteger:forKey:`
- Use `longValue` when dealing with database IDs, window IDs and JSON IDs
- Use literals in some more cases
- Some new lines removed and added where appropriate

## Summary for release notes

Maintenance: Coding style changes

2022-02-15 16:38 UTC, kambala-decapitator requested changes

2022-02-15 16:38 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +    xbmcRemote.idleTimerDisabled = [userDefaults boolForKey:@"lockscreen_preference"];
please extract this piece into a dedicated function, could be a category for UIApplication for example

2022-02-15 16:38 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    BOOL diskcache_preference = [userDefaults boolForKey:@"diskcache_preference"];
this change is incorrect because when preference is missing (returns `nil`), you receive `NO`, while original code receives `YES`

2022-02-15 16:38 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +    BOOL showConnectionNotice = [userDefaults boolForKey:@"connection_info_preference"];
same mistake

2022-02-15 18:25 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    BOOL diskcache_preference = [userDefaults boolForKey:@"diskcache_preference"];
Yes, but wasn't this exactly why we introduced `registerDefaultsFromSettingsBundle`? This sets the default value at startup via `registerDefaults`.

2022-02-15 18:41 UTC, wutschel commented on XBMC Remote/NowPlaying.m
>                     if ([NSJSONSerialization isValidJSONObject:methodResult]) {
You mean `if ([NSJSONSerialization isValidJSONObject:methodResult])`? This is legacy code, I never questioned it. The same condition is checked in 11 more occasions in the code.

2022-02-15 18:56 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +    xbmcRemote.idleTimerDisabled = [userDefaults boolForKey:@"lockscreen_preference"];
Moved to `setIdleTimerFromUserDefaults`.

2022-02-15 19:25 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                    if ([item[@"playcount"] intValue] == 0) {
Agreed, looks quite elegant now:

```
filter = [NSPredicate predicateWithFormat:@"playcount.unsignedIntValue == 0"];
self.richResults = [[storeRichResults filteredArrayUsingPredicate:filter] mutableCopy];
```

2022-02-15 19:42 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        for (NSDictionary *item in self.richResults) {
Would look like this:

`float totalTime = [[self.richResults valueForKeyPath:@"@sum.runtime.unsignedIntValue"] floatValue];`

I personally find this harder to read than the old-style loop.

2022-02-15 20:00 UTC, wutschel commented on XBMC Remote/DetailViewController.m
>                               itemDict = dictVideoLibraryMovies[mainFields[@"typename"]][mainFields[@"fieldname"]];
Agreed.

2022-02-15 20:00 UTC, wutschel commented on XBMC Remote/DetailViewController.m
>                                  itemDict = dictVideoLibraryMovies[mainFields[@"typename"]][mainFields[@"fieldname"]];
Agreed.

2022-02-15 20:03 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +        lastServer = [userDefaults integerForKey:@"lastServer"];
I get a compiler warning, if I use `int` type for `lastServer`.

2022-02-15 20:11 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +                              @"position": @(sourceIndexPath.row)};
> please put braces on separate lines and add comma after the last element, like this:

I remember...

> P.S. variable name doesn't sound great :)

Legacy again. But as I somehow see it the same way, I am changing this. I just wanted to avoid to rewrite literally everything.

2022-02-16 06:30 UTC, wutschel commented on XBMC Remote/DetailViewController.m
>                                   [storeRichResults removeAllObjects];
Interesting. Triggered by your comment I figured I could simplify the code even further. See the commit on 1-movie-sets.

2022-02-16 06:58 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        for (NSDictionary *item in self.richResults) {
ok, let's not change then.

iirc you don't need to write `unsignedIntValue` explicitly, just `@sum.runtime` should be enough.

2022-02-16 07:27 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    BOOL diskcache_preference = [userDefaults boolForKey:@"diskcache_preference"];
thanks for reminding me! Then it's not an issue, of course.

2022-02-16 07:27 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +        lastServer = [userDefaults integerForKey:@"lastServer"];
I mean keep using `objectForKey`, but fetch long value from the object

2022-02-16 10:01 UTC, kambala-decapitator requested changes
regarding the 1-movie change I spotted the following:

- you're still comparing objects to find if it's the last one instead of using indexes
- RPC handler is actually incorrect regarding the last item. Since it's an async call, there're no guarantees that the request for the last item would finish after all the other ones. To handle this correctly, I suggest using dispatch group and handle the "is last item" logic in the `notify` block. You'd probably also want to synchronise access to the mutable array with serial queue or NSLock.

2022-02-16 17:17 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        for (NSDictionary *item in self.richResults) {
Thanks, will keep the code then.

2022-02-16 17:24 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +        lastServer = [userDefaults integerForKey:@"lastServer"];
Sorry, I am confused now. We were coming from `int bla = [[objectForKey] intValue]` (A). To avoid `objectForKey` I changed this to `long bla = [integerForKey]` (B) which uses consistent data types. Why should I now move to `long bla = [[objectForKey] longValue]` (C) which would just go back to the old way but changing the type for no reason. I would expect we either keep the very first implementation (A) or we keep the one proposed in this PR (B). I prefer B.

2022-02-16 17:30 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +    UIApplication.sharedApplication.idleTimerDisabled = [userDefaults boolForKey:@"lockscreen_preference"];
Agreed.

2022-02-16 17:34 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                filter = [NSPredicate predicateWithFormat:@"playcount.unsignedIntValue == 0"];
> writing unsignedIntValue explicitly shouldn't be needed

The object is either a `int`/`long` type or a `NSNumber`. And without `unsignedIntValue` the comparison did not work for `NSNumber`.

> you could even drop the `filter` variable and create the predicate in-place

Yes, but I prefer to have a line of code not exceeding my editor's width. You have a strong opinion on this?

2022-02-16 17:38 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +        NSString *actionRemove = @"Playlist.Remove";
Well, this is legacy code. But I guess it was done to keep the method and the params near to each other to oversee at one glance the complete JSON command.

2022-02-16 18:05 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +        lastServer = [userDefaults integerForKey:@"lastServer"];
ah, I see my mistake now. I thought this change belongs to "int-to-long" commit.

You changed variable to be `long`, but the new method returns `NSInteger`, not `long`. On 32-bit device the code would assign `int` value to `long variable, which is not an issue, but not quite correct I'd say. Basically you just need to declare the variable as `NSInteger` instead of `long`.

> I get a compiler warning, if I use `int` type for `lastServer`.

sure, because you're compiling for 64-bit.

2022-02-16 18:08 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +        lastServer = [userDefaults integerForKey:@"lastServer"];
Cool, now  it's clear.

2022-02-16 18:10 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +        NSString *actionRemove = @"Playlist.Remove";
ok, let's keep

2022-02-16 18:27 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                filter = [NSPredicate predicateWithFormat:@"playcount.unsignedIntValue == 0"];
> The object is either a `int`/`long` type or a `NSNumber`. And without `unsignedIntValue` the comparison did not work for `NSNumber`.

Sorry, I don't think I understand your reasoning about types. ObjC collections can hold **only** objects (i.e. NSNumber in this case), built-in C types like int are impossible.

Here's the simplest program proving otherwise:

```objc
#import <Foundation/Foundation.h>

int main()
{
  NSCAssert([@[@{@"q": @1}] filteredArrayUsingPredicate:[NSPredicate predicateWithFormat:@"q == 1"]].count == 1, @"");
  return 0;
}
```

> Yes, but I prefer to have a line of code not exceeding my editor's width. You have a strong opinion on this?

sure, no problem, was merely a suggestion :)

2022-02-16 19:20 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                filter = [NSPredicate predicateWithFormat:@"playcount.unsignedIntValue == 0"];
> Sorry, I don't think I understand your reasoning about types. ObjC collections can hold **only** objects (i.e. NSNumber in this case), built-in C types like int are impossible.

My fault. It is either a `NSString` (e.g. `@"1"` is used for album playcount) or a NSNumber (e.g. `(long)1` is used for movie playcount). For the `NSString` case `unsignedIntValue` is needed.

2022-02-16 19:28 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                filter = [NSPredicate predicateWithFormat:@"playcount.unsignedIntValue == 0"];
but string doesn't have `unsignedIntValue` method... Better use `longLongValue` then.

2022-02-16 19:43 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                filter = [NSPredicate predicateWithFormat:@"playcount.unsignedIntValue == 0"];
> but string doesn't have `unsignedIntValue` method... Better use `longLongValue` then.

Weird. Any idea why the command works then?

2022-02-16 21:10 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                filter = [NSPredicate predicateWithFormat:@"playcount.unsignedIntValue == 0"];
it works because you didn't encounter a string in your data set :) Take my above test code and modify it accordingly - you'll get runtime crash.

2022-02-17 05:30 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                filter = [NSPredicate predicateWithFormat:@"playcount.unsignedIntValue == 0"];
These types are complicated. Setting the object to `@"0"` works (becomes `NSTaggedPointerTyoe`), but, as you told, `@"Hello world"` crashes when I am using `.unsignedIntegerValue`.

2022-02-17 07:22 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                filter = [NSPredicate predicateWithFormat:@"playcount.unsignedIntValue == 0"];
> Another question: Wouldn't `intValue` be sufficient for the play count? I somehow cannot imagine anyone would play an item _that_ often.

probably you're right, although if library exists for decades... :)

2022-02-17 07:50 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                filter = [NSPredicate predicateWithFormat:@"playcount.unsignedIntValue == 0"];
> probably you're right, although if library exists for decades... :)

6.8 decades if the item's duration is 1 second and we play in a permanent loop. Should suffice :)

2022-02-17 15:19 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                filter = [NSPredicate predicateWithFormat:@"playcount.unsignedIntValue > 0"];
`intValue` as well

2022-02-17 18:29 UTC, wutschel commented
> regarding the 1-movie change I spotted the following:

Let me bounce off a simple idea with you.
1. In case we are at the last item a new key is set:
```
if (item == itemDict.lastObject) {
    newDict[@"isLastObject"] = @YES;
}
```
2. In the async call which checks for one or more movies in the movie set we read this key:
```
if ([newDict[@"isLastObject"] boolValue]) {
...
```
This way all information is carried inside `newDict`. And as for each new index a new instance of `newDict` is created newDict and the flag are not getting out of sync.

2022-02-18 06:43 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                             if (item == itemDict.firstObject) {
If this comparison is a real technical problem (`itemDict` or the order of the items is not changed), I would go back to `for (int i = 0; i < total; i++)`.

2022-02-18 07:52 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                             if (item == itemDict.firstObject) {
it's not a problem since it's a pointer comparison, but I would rather use index comparison instead :) We can leave as is.

btw why are you trying to avoid the `enumerate...` method at all costs? :)

2022-02-18 07:59 UTC, kambala-decapitator commented
@ 1-movie: I don't think I understand how your approach would solve the case when request for the last item finishes before request of some other item. The idea of that code is to update model items and UI as soon as all requests are done, and dispatch group exists exactly to detect the end of multiple async tasks.

2022-02-18 11:19 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                             if (item == itemDict.firstObject) {
> btw why are you trying to avoid the enumerate... method at all costs? :)

Just personal taste.

> We can leave as is.

Great, thanks.

2022-02-18 11:28 UTC, wutschel commented
> @ 1-movie: I don't think I understand how your approach would solve the case when request for the last item finishes before request of some other item. The idea of that code is to update model items and UI as soon as all requests are done, and dispatch group exists exactly to detect the end of multiple async tasks.

Well, it solves the problem that `isLastItem` is true even though the last item is not processed yet in the second/inner loop. Your point, if I got it right, is that in addition the _order_ of processing in the inner loop might be different (e.g. processing item N-1 before N). As this potential problem already exists in the master and also App version 1.9 I would prefer if this is not blocking this PR, and I create an issue for to handle it separately. In this case I would also drop the `@"isLastItem"` change and stick to the implementation "as is" in this PR.

2022-02-18 12:26 UTC, kambala-decapitator commented
> Well, it solves the problem that `isLastItem` is true even though the last item is not processed yet in the second/inner loop. Your point, if I got it right, is that in addition the _order_ of processing in the inner loop might be different (e.g. processing item N-1 before N). As this potential problem already exists in the master and also App version 1.9 I would prefer if this is not blocking this PR, and I create an issue for to handle it separately. In this case I would also drop the `@"isLastItem"` change and stick to the implementation "as is" in this PR.

Yes, you got it right. I fully agree with your conclusion.

The only thing that now bothers me is your simplification commit. We have few similarly named collections: storeRichResults, resultStoreArray and self.richResults. I'm having a hard time figuring out what means what to be able to evaluate your commit correctly, reading the huge method also doesn't quite help me. Could you explain the change? Ideally, rename variables to something more clear outlining their exact purpose (and refactor the method to smaller self-contained parts).

2022-02-18 18:25 UTC, wutschel commented
> The only thing that now bothers me is your simplification commit. We have few similarly named collections: storeRichResults, resultStoreArray and self.richResults. I'm having a hard time figuring out what means what to be able to evaluate your commit correctly, reading the huge method also doesn't quite help me. Could you explain the change? Ideally, rename variables to something more clear outlining their exact purpose (and refactor the method to smaller self-contained parts).

Yes, the legacy code is sometimes quite convoluted -- and `DetailViewController` is the most complex controller of all.

-----------
`self.richResults`:
This is the data which holds all unfiltered and ready-to-display data. The data is displayed when calling `indexAndDisplayData`. This data might be changed by filtering (see below).

`storeRichResults`:
This is an _unchanged_ copy of `self.richResults` which is used to apply filters like watched/unwatched. In this case `storeRichResults` is kept as backup of `self.richResults` as `self.richResults` itself is changed by the filtering and is finally what you see on the screen.

`resultStoreArray`:
Parameter of `retrieveData:` which either is `self.richResults` (see above) or `self.extraSectionRichResults` (only used for TH show seasons).

-----------

What the simplification commit does is:
- Write the resulting items directly to `resultStoreArray` (aka `self.richResults`). 
- When the loop finishes also save an unchanged copy into `storeRichResults`
- Follows the same order (first clean `resultStoreArray`, then write to `resultStoreArray`, then copy to `storeRichResults`)

Before, the code was writing first `storeRichResults` and at the end copied the result to `self.richResults`.

2022-02-20 12:19 UTC, kambala-decapitator approved these changes
thank you a lot! Now it's much clearer.

2022-02-20 15:12 UTC, wutschel commented
Squashed and rebased to master.

2022-02-21 07:20 UTC, merged