Bugfix: Special handling for old iOS
xbmc/Official-Kodi-Remote-iOS pull request #608
Opened 2022-02-19 17:19 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/607.

Since App version 1.9 the top bar item in the detail view were not shown under iOS 11 and earlier. This PR adds a special treatment for these old versions. In addition, it removes the possibility to enter a blocking state in the UI when selecting the so-called "extraButton" in detail view while in fullscreen mode.

## Summary for release notes

Bugfix: Fix missing top bar items in detail view for iOS 11 and earlier
Bugfix: Fix possible UI lock up in iPad fullscreen for iOS 13 and earlier

2022-02-19 17:28 UTC, wutschel commented
I am not proud of the 
```
if (@available(iOS 14.0, *)) {
    // Do nothing
}
else {
```
snippet. But this seemed the simplest solution which also later will be easy to find as all other iOS checks are done via `if (@available(iOS, *))`.

2022-02-19 17:33 UTC, kambala-decapitator commented
well, there's `-[NSProcessInfo operatingSystemVersion]` :)

2022-02-19 17:42 UTC, wutschel commented
> [NSProcessInfo operatingSystemVersion]

Did not want to let this become a blocking factor. Done.

2022-02-20 12:14 UTC, kambala-decapitator requested changes
would it make sense to replace `UIToolbar` with `UINavigationBar`? This way you won't have to compute width of the title.

2022-02-20 12:14 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +                [items removeObjectAtIndex:idx];
you can simply do `removeObject:`

2022-02-20 12:25 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> +                [items removeObjectAtIndex:idx];
True, that's better.

2022-02-20 13:03 UTC, wutschel commented
> would it make sense to replace `UIToolbar` with `UINavigationBar`? This way you won't have to compute width of the title.

I started to look into this, but this needs more work. Let's move this PR, if it is ok for you.

2022-02-21 07:21 UTC, kambala-decapitator commented
> > would it make sense to replace `UIToolbar` with `UINavigationBar`? This way you won't have to compute width of the title.
> 
> I started to look into this, but this needs more work. Let's move this PR, if it is ok for you.

sure, sounds good

2022-02-21 07:21 UTC, kambala-decapitator approved these changes

2022-02-21 11:15 UTC, wutschel commented
Squashed and rebased to master.

2022-02-21 15:28 UTC, merged