Maintenance: Prepare migration of NSKeyedArchiver methods and move to block-based animation
xbmc/Official-Kodi-Remote-iOS pull request #609
Opened 2022-02-20 16:32 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/599.

This PR has four main sections:
1. Prepare migration of `NSKeyedArchiver` methods
The method `unarchiveObjectWithFile` and `archiveRootObject:toFile:` are deprecated since iOS 11. This PR refactor reading/writing persistent data and already prepares the migration the newly introduced `unarchivedObjectOfClasses` and `archivedDataWithRootObject:requiringSecureCoding:error:`. 
2. Move duplicate animation related code to Utilities
This allowed to remove code duplication and unneeded code, as well as prepares for the next third step.
3. Migrate to block-based animation
All parameters and options were taken over into the block-based animation.
4. Optimizations and bugfixes around animation in `NowPlaying`
The code was refactored to remove unneeded variables. In addition, the animation for the transition between playlist and NowPlaying view was corrected (now properly sliding out and in). As a further optimization the "demo" animation for the playlist/NowPlaying toggle button is starting earlier. This always bugged me.

## Summary for release notes

Maintenance: Prepare migration of NSKeyedArchiver methods
Maintenance: Migrate to block-based animation
Bugfix: Fix flip in/out animation for playlist/NowPlaying view

2022-02-20 16:34 UTC, wutschel commented
@kambala-decapitator, I am keeping this as is for the review. There are multiple small commits which should make this PR easier to review. One this is done I propose to squash all commits of section 2 and section 3 into a single commit each.

2022-03-10 16:28 UTC, kambala-decapitator requested changes
I'd squash most of the animation commits into a single one: now you have utility methods for label / table / button / view, but all of these elements are views, don't see a reason to have dedicated methods that essentially do the same thing.

also it seems that in some places indentation broke.

2022-03-10 16:28 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +        self.nowPlayingController.itemDescription.scrollsToTop = NO;
this property is not animatable

2022-03-10 16:28 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        subsInfoLabel.alpha = 0;
you already have utility method to animate alpha, why not using it? there're also other places like this.

2022-03-10 16:28 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
>                           [UIView setAnimationTransition:anim forView:button cache:YES];
is this line removed in next commit?

2022-03-10 16:28 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> -                         [UIView setAnimationDelegate:self];
I don't see delegate method being removed / its logic being ported. Or is there no such method?

2022-03-10 19:32 UTC, wutschel commented on XBMC Remote/ViewControllerIPad.m
> +        self.nowPlayingController.itemDescription.scrollsToTop = NO;
Does it harm to keep `self.nowPlayingController.itemDescription.scrollsToTop = NO;` in the animation block? Or does it need to be moved out? Before this change it was also in the animated block.

2022-03-10 19:55 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> -                         [UIView setAnimationDelegate:self];
There is nothing like this. I guess this was just superfluous.

2022-03-10 19:56 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    NSData *archiveData;
Done

2022-03-10 19:58 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    }
Done

2022-03-10 20:04 UTC, wutschel commented on XBMC Remote/Utilities.m
> +        unarchived = [NSKeyedUnarchiver unarchivedObjectOfClasses:[NSSet setWithArray:objectClasses]
True, changed it.

2022-03-10 20:06 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +            [fileManager createDirectoryAtPath:self.libraryCachePath
Ok, removed the check -- also for the 2nd case.

2022-03-10 20:13 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +        self.dataFilePath = paths[0];
Agreed, done.

2022-03-10 20:16 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +        if (![fileManager fileExistsAtPath:self.epgCachePath]) {
But it also does not harm to keep this. If you don't mind, let us not change.

2022-03-10 20:22 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        subsInfoLabel.alpha = 0;
> I'd squash most of the animation commits into a single one

Yes, I wanted to squash 
1. [Use the block-based animation API] up to [Use the block-based animation API (7)]2. 
2. [Move AnimTable] up to [Remove alphaButton]

> now you have utility methods for label / table / button / view, but all of these elements are views, don't see a reason to have dedicated methods that essentially do the same thing.

Hmm, I didn't look into this yet. Let me see.

> also it seems that in some places indentation broke.

Well, especially `StackScrollViewController` has completely messed up indentations. Shall I just auto-indent this in a commit at the end?

2022-03-10 20:24 UTC, wutschel commented
> II'd squash most of the animation commits into a single one

Yes, I wanted to squash
1. [Use the block-based animation API] up to [Use the block-based animation API (7)]2.
2. [Move AnimTable] up to [Remove alphaButton]3. 

> now you have utility methods for label / table / button / view, but all of these elements are views, don't see a reason to have dedicated methods that essentially do the same thing.

Hmm, I didn't look into this yet. Let me see.

> also it seems that in some places indentation broke.

Well, especially `StackScrollViewController` has completely messed up indentations. Shall I just auto-indent this file in a commit at the end?

2022-03-10 20:25 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        subsInfoLabel.alpha = 0;
Is `UIViewAnimationOptionCurveEaseInOut` the default option?

2022-03-10 21:22 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        subsInfoLabel.alpha = 0;
It is `UIViewAnimationOptionCurveEaseInOut = 0 << 16`.

Nevertheless explicitly added `UIViewAnimationOptionCurveEaseInOut` as option the the helper methods.

2022-03-10 21:22 UTC, wutschel commented on XBMC Remote/ViewControllerIPad.m
> +        self.nowPlayingController.itemDescription.scrollsToTop = NO;
Done

2022-03-11 14:54 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +        if (![fileManager fileExistsAtPath:self.epgCachePath]) {
sure, I don't insist

2022-03-11 16:19 UTC, kambala-decapitator commented on XBMC Remote/ViewControllerIPad.m
> +        self.nowPlayingController.itemDescription.scrollsToTop = NO;
no harm here, I just prefer that animation block contains only animations to make things clearer

2022-03-11 16:20 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        subsInfoLabel.alpha = 0;
I was thinking about second method that accepts the curve parameter, will check your solution

2022-03-11 16:21 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
>                           [UIView setAnimationTransition:anim forView:button cache:YES];
thanks, was difficult to notice in that huge commit

2022-03-11 18:05 UTC, wutschel commented
Anything more I should work on? Or are we good and I can start to squash and rebase?

2022-03-11 19:04 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> -        button.hidden = hiddenValue;
- `hidden` isn't an animatable property
- you replaced `hidden` with `alpha` (which is animatable), is it intended?

2022-03-11 19:04 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> -            image.hidden = NO;
also hidden/alpha point

2022-03-11 19:08 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        subsInfoLabel.alpha = 0;
yeah, always this param is used, no need for a second method

2022-03-11 19:08 UTC, kambala-decapitator commented
squash: sounds good

indent: yes, let's do that

2022-03-11 19:16 UTC, wutschel commented on XBMC Remote/Utilities.m
> -        button.hidden = hiddenValue;
Yes, this was intended.

2022-03-11 19:21 UTC, wutschel commented on XBMC Remote/Utilities.m
> -            image.hidden = NO;
Yes, I was taking care if this. `alphaImage:` was only called in few places. The view handed over was either `fanartView` which never is hidden, or `jewelView` for which I added an explicit unhide before calling the unified method `alphaView:`. So, the `hidden = NO` is not required inside the helper method anymore.

2022-03-11 19:45 UTC, wutschel commented
Squashed and rebased. I skipped the auto-indent as I forgot I already have some work prepared in the background which conflicts with this. I will do this next time I am touching this file as part of a PR.

2022-03-12 10:19 UTC, kambala-decapitator approved these changes
just to double check: this is ready to be merged, isn't it?

2022-03-12 11:44 UTC, wutschel commented
> just to double check: this is ready to be merged, isn't it?

Yes, it is.

2022-03-12 11:47 UTC, merged

2022-03-20 05:27 UTC, kambala-decapitator commented
@wutschel have you seen this warning in the console?

> NSSecureCoding allowed classes list contains [NSObject class], which bypasses security by allowing any Objective-C class to be implicitly decoded. Consider reducing the scope of allowed classes during decoding by listing only the classes you expect to decode, or a more specific base class than NSObject.

2022-03-20 07:26 UTC, wutschel commented
> I guess it can be ignored since secure coding isn't used?

I have seen this yesterday for the first time. Not sure why it was not coming up before. Maybe it only showed after I removed the App.

I do not know what this can cause. I'd rather take a deeper look. In worst case I simply provide a PR which comments the new code for 1.10 to give time to deal this properly.

2022-03-20 07:37 UTC, kambala-decapitator commented
I think there's no issue, but please investigate shortly to be 100% sure