Bugfix: Fix invisible Kodi server settings
xbmc/Official-Kodi-Remote-iOS pull request #627
Opened 2022-03-15 06:58 UTC by wutschel

## Description

For the Kodi settings table there is a unique animation on iPhone. The animation slides in the table from bottom to top. For this we need to have a helper method which animates x and y origins.

## Summary for release notes

Bugfix: Fix invisible Kodi server settings

2022-03-16 12:26 UTC, kambala-decapitator requested changes

2022-03-16 12:26 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    [UIView beginAnimations:nil context:nil];
why old style?

2022-03-16 12:26 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    frame = view.frame;
```suggestion
    CGRect frame = view.frame;
```

2022-03-16 13:48 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    [UIView beginAnimations:nil context:nil];
Oh, that was because I searched for the error in the old code after bi-secting. Will change this.

2022-03-17 12:04 UTC, wutschel commented
Done and already squashed.

2022-03-17 12:06 UTC, merged