Bugfix: Fix getting MAC address
xbmc/Official-Kodi-Remote-iOS pull request #635
Opened 2022-03-18 19:08 UTC by wutschel

## Description

To get the MAC address we need to wait for the result of a ping which is done via `NSURLSessionDataTask`. For this we need to implement a delegate handler and use a dedicated `NSURLSession` instead of `sharedSession`.

This function broke already with 1.6.2 which was never reported as broken -- most like because mary either keep using the old setups or entered the MAC address manually.

## Summary for release notes

Bugfix: Fix getting MAC address

2022-03-18 19:08 UTC, wutschel commented
@kambala-decapitator, that's a really nasty one. Even though this was broken since >1 year.

2022-03-19 08:26 UTC, kambala-decapitator requested changes
I see zero reason to use delegate here, please use `dataTaskWithURL` method variation that accepts completion block. You can also continue using `sharedSession` with this approach.

Funny, I thought this feature broke because of new iOS :)

2022-03-19 08:57 UTC, wutschel commented
Thanks for pointing me towards this much leaner solution.

2022-03-19 09:01 UTC, merged

2022-03-19 19:39 UTC, wutschel commented
@kambala-decapitator, strange. The fix works in simulation, but not on the TF build. Any idea what could cause this?

2022-03-19 20:05 UTC, kambala-decapitator commented
could be some iOS limitation indeed

2022-03-19 20:15 UTC, wutschel commented
> could be some iOS limitation indeed

In this case we should remove this fix from the release notes.

2022-03-20 05:50 UTC, kambala-decapitator commented
> > could be some iOS limitation indeed
> 
> In this case we should remove this fix from the release notes.

I agree.

Didn't find any quick solution so far. Socket investigation needs to be made.

Maybe it'd work on older devices though :)