Rework RightMenuViewController
xbmc/Official-Kodi-Remote-iOS pull request #652
Opened 2022-03-25 22:03 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/644.

Resolves some auto-layout problems with moving button labels and transparencies. Now the button labels do not change their positions and the safe area stays colored correctly after coming back from Kodi settings menu.

In addition applies coding style changes:
- Use literals
- Unify spaces and new lines
- Remove commented code
- Remove obsolete variables
- ...     

## Summary for release notes

Bugfix: Fix moving button labels and transparency in custom button view

2022-07-09 08:00 UTC, wutschel commented
Rebased and ready for review.

2022-07-24 05:52 UTC, kambala-decapitator requested changes

2022-07-24 05:52 UTC, kambala-decapitator commented on XBMC Remote/RightMenuViewController.m
> +        NSNumber *hideLine = item[@"hideLineSeparator"] ?: @(NO);
```suggestion
        NSNumber *hideLine = item[@"hideLineSeparator"] ?: @NO;
```

2022-07-24 05:52 UTC, kambala-decapitator commented on XBMC Remote/RightMenuViewController.m
> +        NSNumber *showTop = item[@"revealViewTop"] ?: @(NO);
```suggestion
        NSNumber *showTop = item[@"revealViewTop"] ?: @NO;
```

2022-07-24 05:52 UTC, kambala-decapitator commented on XBMC Remote/RightMenuViewController.m
> +        fixedSpace2
is it guaranteed that all these variables are not `nil`? otherwise we might get a crash.

edit: I see further you remove this completely. The I suggest to drop this useless change :)

2022-07-24 06:38 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +        fixedSpace2
Done

2022-07-24 06:39 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +        NSNumber *hideLine = item[@"hideLineSeparator"] ?: @(NO);
Did this and also found few other places where this is now fixed.

2022-07-24 06:39 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +        NSNumber *showTop = item[@"revealViewTop"] ?: @(NO);
Same here.

2022-07-24 06:57 UTC, kambala-decapitator approved these changes

2022-07-24 07:55 UTC, wutschel commented
Squashed and ready to go.

2022-07-24 08:19 UTC, merged