Bugfix: Unwanted rotation after selecting item in iPad landscape fullscreen (iOS16 only)
xbmc/Official-Kodi-Remote-iOS pull request #752
Opened 2022-10-28 19:25 UTC by wutschel

## Description

Fixes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/745.

This PR redefines `supportedInterfaceOrientations` for iPad/iPhone via introducing `getSupportedOrientation` to return the desired supported orientation (portrait for iPhone and all for iPad).

## Summary for release notes

Bugfix: Unwanted rotation after selecting item in iPad landscape fullscreen (iOS16 only)

2022-10-28 19:25 UTC, wutschel commented
@kambala-decapitator, would like to have your opinion on this. To me it looks like the old code was even wrong.

2022-10-28 19:48 UTC, kambala-decapitator commented
if your goal is to set identical orientations for all screens of the app, there's a much easier way: just do it in Info.plist (or in target settings - General) and remove all custom code for that.

existing code seems incorrect indeed.

2022-10-28 20:10 UTC, wutschel commented
I cannot see the options to set different orientations for iPad/iPhone in the target settings anymore.

2022-10-28 20:33 UTC, kambala-decapitator commented
I see it's already more or less correct: https://github.com/xbmc/Official-Kodi-Remote-iOS/blob/edea678c8d0bc705b33b60bbdbb051cbfed2cacb/XBMC%20Remote/Kodi%20Remote-Info.plist#L70-83

are there screens on iPhone that can work in landscape? if not, then you could just throw away landscape settings in the iPhone field

2022-10-29 07:03 UTC, wutschel commented
Thanks, it's a lot simpler now.

2022-11-02 18:21 UTC, kambala-decapitator requested changes

2022-11-02 18:21 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> -    return UIInterfaceOrientationMaskAllButUpsideDown;
This screen allowed rotation to landscape on iPhone. Is it ok to remove?

2022-11-02 18:21 UTC, kambala-decapitator commented on XBMC Remote/CustomNavigationController.m
> +#import "Utilities.h"
please drop

2022-11-02 19:00 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> -    return UIInterfaceOrientationMaskAllButUpsideDown;
Yes, ok to remove.

2022-11-02 19:01 UTC, wutschel commented on XBMC Remote/CustomNavigationController.m
> +#import "Utilities.h"
Done

2022-11-03 07:32 UTC, merged