Bugfix: Do not dismiss remote when rotating iPad in fullscreen
xbmc/Official-Kodi-Remote-iOS pull request #772
Opened 2022-11-11 05:39 UTC by wutschel

## Description

Fixes a problem reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3117483#pid3117483).

The former solution also dismissed the remote popover. With this PR the dismissal is only applied to the action sheet when shown.

Remind: The action sheet is dismissed because the origin is not matching anymore as `FlowLayou`  changes with a rotation (different amount of columns and rows).

## Summary for release notes

Bugfix: Do not dismiss remote when rotating iPad in fullscreen

2022-11-12 11:34 UTC, kambala-decapitator requested changes

2022-11-12 11:34 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    if (IS_IPAD && stackscrollFullscreen && [actionView isViewLoaded]) {
I'd rather make `actionView` a weak variable or property - this way it'll be set to `nil` automatically after dismissal and won't eat extra memory, you'd also simply check for `actionView != nil`.

2022-11-12 12:35 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    if (IS_IPAD && stackscrollFullscreen && [actionView isViewLoaded]) {
Agreed.

2022-11-14 18:29 UTC, kambala-decapitator commented
Last feedback is still not fixed

2022-11-14 18:37 UTC, wutschel commented
> Last feedback is still not fixed

Sorry, but what did I miss?

2022-11-14 18:46 UTC, kambala-decapitator requested changes
Sorry, seems I forgot to "commit" my comment :)

2022-11-16 03:18 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    if (IS_IPAD && stackscrollFullscreen && [actionView isViewLoaded]) {
but now you changed it back to isViewLoaded :)

2022-11-16 03:20 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.h
> +@property (strong, nonatomic) UIAlertController *actionView;
> The main benefit of using weak is that the memory is free'd up, right?

yes, and weak var is automatically set to `nil` on release

> The assignment via a temporary variable is a bit unfamiliar for me.

you did it right!

>  am using a similar approach for checking popover visibility in three other places in ViewControlleriPad, so I'll keep using isViewLoaded.

ok, let's keep

2022-11-16 03:20 UTC, kambala-decapitator approved these changes

2022-11-16 05:19 UTC, wutschel commented on XBMC Remote/DetailViewController.h
> +@property (strong, nonatomic) UIAlertController *actionView;
> you did it right!

:) I am mainly worried I see this in a few months, start to clean up and directly assign it again.

2022-11-16 05:19 UTC, wutschel commented
Squashed and rebased to master.

2022-11-16 05:38 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.h
> +@property (strong, nonatomic) UIAlertController *actionView;
> :) I am mainly worried I see this in a few months, start to clean up and directly assign it again.

compiler should issue a warning in this case

2022-11-16 05:39 UTC, merged