Rework index
xbmc/Official-Kodi-Remote-iOS pull request #793
Opened 2022-11-23 05:39 UTC by wutschel

## Description

Use `BDKCollectionIndexView` for `UITableView` as well. This improves and unifies the overall index usability.
- Same position when switching between list/grid view
- Transparent overlay for TVShow banner view

In addition, fix the inset for grid view after jumping to top or to bottom via index and improve the readability on iPad via adding a small padding on the right side of the index.

## Summary for release notes

Bugfix: Correct inset for grid when jumping to top/bottom via index
Bugfix: Avoids issue with iOS16 index when minimizing App in iPhone
Improvement: Transparent index overlay for TVShow banners
Maintenance: Use same same index implementation for grid/list view

2022-11-23 05:40 UTC, wutschel commented
Needs a rebase after https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/791 was merged.

2022-12-03 18:48 UTC, wutschel commented
Rebased to master.

2022-12-04 10:59 UTC, kambala-decapitator requested changes

2022-12-04 10:59 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    self.indexView.hidden = self.indexView.indexTitles.count > 1 ? NO : YES;
```suggestion
   self.indexView.hidden = self.indexView.indexTitles.count <= 1;
```

2022-12-04 10:59 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            sectionNameLabel.text = [NSString stringWithFormat:@"%C%C", 0xD83D, 0xDD0D];
you can use unicode in code directly

2022-12-04 10:59 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                    NSDateFormatter *format = [NSDateFormatter new];
creating date formatter is expensive, please at least move it outside the loop. How often is this method called?

also, broken indentation.

2022-12-04 10:59 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        [detailView willRemoveSubview:self.indexView];
if in fact you want to remove `self.indexView`, then correct would be:
```suggestion
        [self.indexView removeFromSuperview];
```

2022-12-04 11:30 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    self.indexView.hidden = self.indexView.indexTitles.count > 1 ? NO : YES;
Agreed, done.

2022-12-04 11:40 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                    NSDateFormatter *format = [NSDateFormatter new];
Done. This is called only in the channel view per day. So it depends on how many days into the future the channel view has data. I would say typically between 7-14 days.

2022-12-04 12:03 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            sectionNameLabel.text = [NSString stringWithFormat:@"%C%C", 0xD83D, 0xDD0D];
Like this? 

`sectionNameLabel.text = @"🔍";`

2022-12-04 14:24 UTC, kambala-decapitator approved these changes

2022-12-04 17:08 UTC, wutschel commented
Squashed and rebased to master.

2022-12-04 19:03 UTC, merged