Migrate to NSURLSession
xbmc/Official-Kodi-Remote-iOS pull request #794
Opened 2022-11-26 09:10 UTC by wutschel

## Description

This PR migrates the App from the deprecated `NSURLConnection` to `NSURLSession`. This impacts both the basic JSON RPC connection to Kodi server as the web service to load images.

### Migration of `SDWebImageDownloaderOperation`

This is pretty straight forward and mainly replaces the delegate functions of `NSURLConnection` with the new ones for `NSURLSession`.

### Migration of `DSJSONRPC`

This change is more or less a rework of the implementation, removing lots of superfluous code and stripping this down to its core functionality which will improve maintainability.

### Reorder initial connection requests

The initial connect requests are now re-ordered to avoid JSON requests to read JSON API version and "ignore articles" feature before the basic connection to the server is established and verified.

## Summary for release notes

Maintenance: Migrate to NSURLSession from deprecated NSURLConnection

2022-11-26 10:16 UTC, wutschel commented
There is some performance improvement seen with this migration as well. This can be easily felt when performing pull-to-sync or entering views where data is loaded from server. 

Some numbers for synchronizing Global Search from my Kodi server:
- 1.4 s > 0.3 s Test Server Global Search (217 items)
- 7.0 s > 5.2 s Music Server Global Search (6631 items)

2022-12-04 10:38 UTC, kambala-decapitator requested changes

2022-12-04 10:38 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +        timer = [NSTimer scheduledTimerWithTimeInterval:timeout
not sure why you need this timer at all - request timeout can be configured directly

2022-12-04 10:38 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    self._activeConnection[@"methodName"] = methodName;
now we have a single connection - please created dedicated object properties instead

2022-12-04 10:38 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +        NSError *aError = [NSError errorWithDomain:RPC_DOMAIN code:DSJSONRPCNetworkError userInfo:[NSDictionary dictionaryWithObjectsAndKeys:[error localizedDescription], NSLocalizedDescriptionKey, n
makes sense to move error creation inside the `if`

2022-12-04 10:38 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.h
> +@interface DSJSONRPC : NSObject <NSURLSessionDelegate> {
you actually need NSURLSessionDataDelegate

2022-12-04 10:38 UTC, kambala-decapitator commented on XBMC Remote/SDWebImage/SDWebImageDownloaderOperation.h
> +@interface SDWebImageDownloaderOperation : NSOperation <SDWebImageOperation, NSURLSessionDelegate>
NSURLSessionDataDelegate

2022-12-04 10:38 UTC, kambala-decapitator commented on XBMC Remote/SDWebImage/SDWebImageDownloaderOperation.m
> +@property (strong, nonatomic) NSURLSessionDataTask *connection;
please name it `dataTask` or so

2022-12-04 10:38 UTC, kambala-decapitator commented on XBMC Remote/SDWebImage/SDWebImageDownloaderOperation.m
> +            if (self.options & SDWebImageDownloaderIgnoreCachedResponse && responseFromCached) {
```suggestion
            if ((self.options & SDWebImageDownloaderIgnoreCachedResponse) && responseFromCached) {
```

2022-12-04 10:38 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    NSURLSession *rpcSession = [NSURLSession sessionWithConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration]
you should actually save the created object, not create new one each time

2022-12-04 10:41 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +        timer = [NSTimer scheduledTimerWithTimeInterval:timeout
I tried to maintain the old methods. How can the timeout be configured?

2022-12-04 10:43 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +        NSError *aError = [NSError errorWithDomain:RPC_DOMAIN code:DSJSONRPCNetworkError userInfo:[NSDictionary dictionaryWithObjectsAndKeys:[error localizedDescription], NSLocalizedDescriptionKey, n
Ok, did the same for the other conditions as well.

2022-12-04 10:45 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.h
> +@interface DSJSONRPC : NSObject <NSURLSessionDelegate> {
Fixed.

2022-12-04 10:46 UTC, wutschel commented on XBMC Remote/SDWebImage/SDWebImageDownloaderOperation.h
> +@interface SDWebImageDownloaderOperation : NSOperation <SDWebImageOperation, NSURLSessionDelegate>
Fixed

2022-12-04 10:49 UTC, wutschel commented on XBMC Remote/SDWebImage/SDWebImageDownloaderOperation.m
> +@property (strong, nonatomic) NSURLSessionDataTask *connection;
Done

2022-12-04 10:50 UTC, wutschel commented on XBMC Remote/SDWebImage/SDWebImageDownloaderOperation.m
> +            if (self.options & SDWebImageDownloaderIgnoreCachedResponse && responseFromCached) {
Done

2022-12-04 11:00 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +        timer = [NSTimer scheduledTimerWithTimeInterval:timeout
create data task with `NSURLRequest` instead of plain `NSURL`

2022-12-04 11:02 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +        timer = [NSTimer scheduledTimerWithTimeInterval:timeout
oh, it's already like that. You have this line: `serviceRequest.timeoutInterval = 3600;`

2022-12-04 11:03 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    self._activeConnection[@"methodName"] = methodName;
Done

2022-12-04 11:08 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +        timer = [NSTimer scheduledTimerWithTimeInterval:timeout
Ok, thanks for helping to simplify this even further.

2022-12-04 11:12 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    NSURLSession *rpcSession = [NSURLSession sessionWithConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration]
Is this is an expensive operation? And would moving to `initWithServiceEndpoint` be sufficient?

2022-12-04 11:14 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    NSURLSession *rpcSession = [NSURLSession sessionWithConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration]
not aware of how expensive it is, but general recommendation is to reuse custom created session objects. Yes, creating it in some `init` is ok.

2022-12-04 11:20 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    NSURLSession *rpcSession = [NSURLSession sessionWithConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration]
Done

2022-12-04 11:32 UTC, kambala-decapitator requested changes

2022-12-04 11:32 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@property (nonatomic, DS_STRONG) DSJSONRPCCompletionHandler _callback;
```suggestion
@property (nonatomic, DS_STRONG) NSURL *serviceEndpoint;
@property (nonatomic, copy) NSDictionary *httpHeaders;
@property (nonatomic, DS_STRONG) NSMutableData *dataBuffer;
@property (nonatomic, copy) NSNumber *aID;
@property (nonatomic, copy) NSString *methodName;
@property (nonatomic, copy) DSJSONRPCCompletionHandler callback;
```

2022-12-04 11:32 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@synthesize _serviceEndpoint, _httpHeaders, _dataBuffer, _aID, _methodName, _callback;
```suggestion
```

2022-12-04 11:32 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    self._methodName = [methodName copy];
```suggestion
    self.callback = completionHandler;
    self.methodName = methodName;
```

2022-12-04 11:51 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@property (nonatomic, DS_STRONG) DSJSONRPCCompletionHandler _callback;
Done for property names and removal of spaces. But I'm not sure about replacing `DS_STRONG` with `copy`. Can you explain?

2022-12-04 11:53 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@synthesize _serviceEndpoint, _httpHeaders, _dataBuffer, _aID, _methodName, _callback;
If I am removing this the code does not compile anymore when calling `DS_RELEASE`. Not sure if this is ok, especially seeing this:

```
#ifdef __OBJC_GC__
#error Demiurgic JSON-RPC does not support Objective-C Garbage Collection
#endif
```

2022-12-04 13:50 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@synthesize _serviceEndpoint, _httpHeaders, _dataBuffer, _aID, _methodName, _callback;
Should be ok when using:
```
DS_RELEASE(self.serviceEndpoint)
DS_RELEASE(self.httpHeaders)
DS_RELEASE(self.rpcSession)
DS_RELEASE(self.dataBuffer)
DS_RELEASE(self.methodName)
DS_RELEASE(self.callback)
```

2022-12-04 13:51 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@synthesize _serviceEndpoint, _httpHeaders, _dataBuffer, _aID, _methodName, _callback;
In current reality that macro simply sets fields to nil which is basically a useless operation for dealloc as it does the same thing internally.
GC in objc is a very ancient thing that no longer exists.

2022-12-04 13:52 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    self._methodName = [methodName copy];
Sure.

2022-12-04 13:53 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@synthesize _serviceEndpoint, _httpHeaders, _dataBuffer, _aID, _methodName, _callback;
So, I just remove the whole `DS_RELEASE` in `dealloc`?

2022-12-04 13:54 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@property (nonatomic, DS_STRONG) DSJSONRPCCompletionHandler _callback;
In 99% of cases if a class implements NSCopying, then objects of this class should be copied when assigned to properties instead of being simply retained (strong does the latter).

2022-12-04 13:57 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@property (nonatomic, DS_STRONG) DSJSONRPCCompletionHandler _callback;
URL and dictionary can be copied => use copy.

Plain integer is good.

2022-12-04 13:57 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@synthesize _serviceEndpoint, _httpHeaders, _dataBuffer, _aID, _methodName, _callback;
Yep

2022-12-04 13:59 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@synthesize _serviceEndpoint, _httpHeaders, _dataBuffer, _aID, _methodName, _callback;
Done.

2022-12-04 13:59 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@property (nonatomic, DS_STRONG) DSJSONRPCCompletionHandler _callback;
> URL and dictionary can be copied => use copy.

Both `NSURL` and `NSURLSession`?

2022-12-04 14:06 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@synthesize _serviceEndpoint, _httpHeaders, _dataBuffer, _aID, _methodName, _callback;
Oh, should I remove the other `DS_RELEASE` calls as well?

2022-12-04 14:25 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@property (nonatomic, DS_STRONG) DSJSONRPCCompletionHandler _callback;
only NSURL. You can check in the header if NSCopying is implemented or not.

2022-12-04 14:25 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@synthesize _serviceEndpoint, _httpHeaders, _dataBuffer, _aID, _methodName, _callback;
yes please, you can also remove the macro definition itself

2022-12-04 14:59 UTC, kambala-decapitator commented
All good so far, only that session is marked as copy

2022-12-04 18:15 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@synthesize _serviceEndpoint, _httpHeaders, _dataBuffer, _aID, _methodName, _callback;
So, looked into this now. ARC was not set for DSJSONRPC, I changed this now and removed all macros.

2022-12-04 18:59 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +@synthesize _serviceEndpoint, _httpHeaders, _dataBuffer, _aID, _methodName, _callback;
> ARC was not set for DSJSONRPC, I changed this now and removed all macros.

Nice find! That's great.

2022-12-04 19:02 UTC, kambala-decapitator approved these changes

2022-12-04 19:37 UTC, wutschel commented
Squashed and rebased to master.

2022-12-04 20:06 UTC, merged