Rework NowPlaying
xbmc/Official-Kodi-Remote-iOS pull request #847
Opened 2023-01-29 18:24 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/719.

**Layout:**
The layout is updated by moving the cover up and having all text elements below. The text font (bold/normal, size, color) is changed to highlight the most important information.

**Content:**
`"year"` and `"director"` is shown as well as enrichment to the already available information.

**Refactoring:**
The code is refactored to ease up updating cover with and without having jewel case enabled: `thubmnailView` now always represents the cover and `jewelView` always the jewel case image. This allows to reduce code duplication and complexity.

**Animation:**
The flip animation when toggling between playlist and NowPlaying views is reworked to a single staged animation which looks a lot smoother than the former 2-staged implementation. The toggle-button animation on the right side of the toolbar is updated accordingly,

#727 must be merged first.

## Summary for release notes

Maintenance: Refactor handling of cover and jewel case views to reduce code duplication
Improvement: Easier to read NowPlaying key information
Improvement: Smoother animation when toggling playlist and NowPlaying
Improvement: Added year and director where applicable

2023-04-04 14:50 UTC, wutschel commented
https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/846 must go in first.

2023-04-29 08:15 UTC, kambala-decapitator requested changes

2023-04-29 08:15 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                                 itemDescription.text = description.length ? [NSString stringWithFormat:@"%@", description] : plot.length ? [NSString stringWithFormat:@"%@", plot] : @"";
```suggestion
                                 itemDescription.text = description.length ? description
                                     : (plot.length ? plot : @"");
```

2023-04-29 08:15 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    if (nowPlayingView.hidden && !demo) {
intended change?

2023-04-29 08:15 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                                         album = [NSString stringWithFormat:@"%@ - S%@E%@", showtitle, season, episode];
SxEx deserves a helper function

2023-04-29 08:24 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +                                 itemDescription.text = description.length ? [NSString stringWithFormat:@"%@", description] : plot.length ? [NSString stringWithFormat:@"%@", plot] : @"";
ok

2023-04-29 08:30 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    if (nowPlayingView.hidden && !demo) {
yes, intended.

2023-04-29 08:58 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +                                         album = [NSString stringWithFormat:@"%@ - S%@E%@", showtitle, season, episode];
ok and done

2023-04-29 13:04 UTC, kambala-decapitator approved these changes

2023-04-29 13:32 UTC, wutschel commented
Squashed and rebased to master.

2023-04-29 20:01 UTC, merged