Bugfix: Support new aspect ratios 1.00, 1.19 and 2.00
xbmc/Official-Kodi-Remote-iOS pull request #851
Opened 2023-02-06 22:06 UTC by wutschel

## Description

Solves an issue reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3138761#pid3138761).

Issue was caused by Kodi server introducing new aspect ratios and a mis-design in loading the aspect ratio images in the remote app. The new aspect ratio "2.00" resulted in loading the image for "2" (channels). To solve this, the image names for channels and aspect ratios now have prefixes. If the desired image cannot be loaded, the fallback to pure text is done (as before).

## Summary for release notes

Bugfix: Support new aspect ratios 1.00, 1.19 and 2.00

2023-02-07 21:16 UTC, wutschel commented
@kambala-decapitator, more changes than I wanted to, but this is worth being added to 1.12.1

2023-02-11 10:48 UTC, kambala-decapitator requested changes

2023-02-11 10:48 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    }
I think using a static dictionary would be better

2023-02-11 10:48 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +    }
also dictionary

2023-02-11 10:48 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +        aspect = @"2:0";
2:0? what is that? :) 2:1 probably?

2023-02-11 10:48 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                // Codec View uses "XBMC.GetInfoLabels" which might change asynchronously. Therefor check each time
```suggestion
                // Codec View uses "XBMC.GetInfoLabels" which might change asynchronously. Therefore check each time
```

2023-02-11 13:20 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    }
True, looks a lot better now.

2023-02-11 13:20 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +    }
True, looks a lot better now.

2023-02-11 13:20 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +        aspect = @"2:0";
:) Infinite wide screen format

Fixed.

2023-02-11 13:21 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +                // Codec View uses "XBMC.GetInfoLabels" which might change asynchronously. Therefor check each time
Fixed and already squashed.

2023-02-11 16:40 UTC, kambala-decapitator approved these changes

2023-02-11 17:35 UTC, wutschel commented
Squashed and rebase to master.

2023-02-11 17:37 UTC, merged