Improvement: Ignore BB and HTLM code for menu entries and descriptions
xbmc/Official-Kodi-Remote-iOS pull request #857
Opened 2023-02-26 14:54 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/369.

This PR will improve displaying content with BB or HTML code. It was reported by users that some plugins (e.g. youtube) and  most likely also the metadata of some service providers use BB or HTML code. As it is not reasonable to let the BB or HTML code control the layout (e.g. the text must keep readable in its context and for dark/light mode), the related code is stripped off and not used. For BB code most of the key words are stripped (`b, u, i, s, center, left, right, url, img, font, size, color`), for HTML simply all non-empty `<>`-brackets are stripped. The latter is _a lot_ faster than using the iOS internal solution via `NSHTMLTextDocumentType`.

Screenshots (youtube plugin main menu):
<a href="https://abload.de/image.php?img=bildschirmfoto2023-028jdjc.png"><img src="https://abload.de/img/bildschirmfoto2023-028jdjc.png" /></a>

## Summary for release notes

Improvement: Ingnore BB and HTLM code for menu entries and descriptions

2023-06-27 18:56 UTC, kambala-decapitator requested changes
sorry, I started implementing this using proper parsing (not just quick'n'dirty with regexes :) ) and writing a few unit tests, but never got to finish.

2023-06-27 18:56 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    textOut = [Utilities stripRegEx:@"\\[[\\s|/|b|u|i|s|center|left|right|url|img]+\\]" text:textOut];
this looks wrong. "Character classes" (stuff inside []) operate on character level and special placeholders. With the current implementation it will also match "tags" like `[|t/f]`. You'd rather want something like:

```
\\[/?(b|u|i|s|center|left|right|url|img)\\]
```

please adjust the next regex the same way.

2023-06-27 18:56 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        [Utilities stripBBandHTML:@"[color=blue]Hallo[/color]"];
gg

2023-06-27 18:56 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    //NSLog(@"%@ >> '%@'", text, textOut);
please drop

2023-06-27 18:56 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    textOut = [Utilities stripRegEx:@"\\[[\\s|/|font|size|color|url]+[^\\]]+\\]" text:textOut];
I'd also add explicit `=`

2023-06-27 21:18 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        [Utilities stripBBandHTML:@"[color=blue]Hallo[/color]"];
will of course be removed when we eve get this ready to go.

2023-06-27 21:19 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    textOut = [Utilities stripRegEx:@"\\[[\\s|/|b|u|i|s|center|left|right|url|img]+\\]" text:textOut];
no surprise your expression work better. Can you also propose the second one? I am lost...

2023-06-28 07:10 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    textOut = [Utilities stripRegEx:@"\\[[\\s|/|b|u|i|s|center|left|right|url|img]+\\]" text:textOut];
sure! although this is rather dirty as would also match `[/size=asd]`

```
\\[/?(font|size|color|url)(=[^]]+)?\\]
```

FYI there're convenient websites like https://regex101.com/

2023-06-28 07:12 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    textOut = [Utilities stripRegEx:@"\\[[\\s|/|b|u|i|s|center|left|right|url|img]+\\]" text:textOut];
btw not sure why you also check for spaces, are they allowed in bb tags?

2023-06-28 07:15 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    textOut = [Utilities stripRegEx:@"\\[[\\s|/|b|u|i|s|center|left|right|url|img]+\\]" text:textOut];
Thanks a million, I was not looking into this for a few months. Not easy to get into this again, if you're not regularly using it. Your expression of course works.

Updated with fixup commit.

2023-06-28 07:19 UTC, kambala-decapitator approved these changes

2023-06-28 07:30 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    textOut = [Utilities stripRegEx:@"\\[[\\s|/|b|u|i|s|center|left|right|url|img]+\\]" text:textOut];
> btw not sure why you also check for spaces, are they allowed in bb tags?

Not sure about this. From my experience with ID3 and other metadata tags I felt it is a good idea to handle malformatted tags as well.

2023-06-28 07:30 UTC, wutschel commented
Removed the debug code and rebased to master.

2023-06-28 07:33 UTC, merged

2023-06-28 07:33 UTC, kambala-decapitator commented
it's funny that "Summary for release notes" has typos unlike PR title, although text is the same. Do you re-type summary instead of copy-pasting it? :)

2023-06-28 07:36 UTC, wutschel commented
> it's funny that "Summary for release notes" has typos unlike PR title, although text is the same. Do you re-type summary instead of copy-pasting it? :)

For most PRs I do copy-paste. But sometimes I seem to fix typos afterwards without again copy-pasting. Sorry for that.

2023-06-28 07:45 UTC, kambala-decapitator commented
> > it's funny that "Summary for release notes" has typos unlike PR title, although text is the same. Do you re-type summary instead of copy-pasting it? :)
> 
> For most PRs I do copy-paste. But sometimes I seem to fix typos afterwards without again copy-pasting. Sorry for that.

please don't worry, all fine! When summary matches title, I simply go with the title, as it's added to the merge message automatically. Actually in such case you could simply leave the summary empty.