Improvement: Increase robustness against mal-formatted JSON API responses
xbmc/Official-Kodi-Remote-iOS pull request #878
Opened 2023-04-21 17:07 UTC by wutschel

## Description

Closes https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/877.

Check for `NSDictionary` type before processing further to increase robustness against mal-formatted JSON API responses as recently seen in Kodi 21.0-ALPHA nightly builds.

## Summary for release notes

Improvement: Increase robustness against mal-formatted JSON API responses

2023-04-22 07:02 UTC, wutschel commented
Changing to draft to go for a more common approach when working with the JSON API response.

2023-04-22 07:20 UTC, wutschel commented
For example: Does it makes to always check for `if ([NSJSONSerialization isValidJSONObject:methodResult]) {` on the JSON _response_? I understand this method returns, if an object can be serialized, but it was just _de_-serialized successfully. Instead, I am asking myself whether the checks should be done for the specific class the following code expects, e.g. `NSDictionary`.


In the current code there's a mixture of this used. I think it will be good to use similar condition logic when processing the JSON responses:
1. Check for `!error && !methodError`
2. Check for class type of `methodResult`
3. Process and check further class types where needed

@kambala-decapitator, can you share your point of view on this?

2023-04-22 19:52 UTC, kambala-decapitator commented
> it was just de-serialized successfully

then `isValidJSONObject` check definitely isn't needed.

if you expect e.g. dictionary and server might return null / string / array (i.e. anything that's not a dic), then class check is needed if you don't want to get a crash :). Normally server API should cover possible responses and it should be trusted, otherwise it's server (or docs) bug.

2023-07-09 04:52 UTC, kambala-decapitator requested changes
please also fix typo in commit message:

> Refactor building for index content
> Helper variable "BOOL found" can be set with **less** code.

2023-07-09 04:52 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    if (![NSJSONSerialization isValidJSONObject:methodCall]) {
not sure why you're doing it manually, it's already done below in case of decoding error

2023-07-09 04:52 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    id object = item[itemid];
please give better names to variables like `itemIDKey`, `itemID`

2023-07-09 04:52 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +        object = @([item[itemid] intValue]);
also better names are needed

2023-07-09 04:52 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                     // WORKAROUND due the lack of the artistid with Playlist.GetItems
```suggestion
                     // WORKAROUND due to the lack of the artistid with Playlist.GetItems
```

2023-07-09 04:52 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    if ([item isKindOfClass:[NSNumber class]] || [item isKindOfClass:[NSString class]]) {
```suggestion
    if ([item respondsToSelector:@selector(floatValue)])
```

2023-07-09 07:39 UTC, wutschel commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    if (![NSJSONSerialization isValidJSONObject:methodCall]) {
Ok, so just remove this whole thing and let run into the error when attempting to serialize?

2023-07-09 07:41 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +                     // WORKAROUND due the lack of the artistid with Playlist.GetItems
Found the same comment in two other places, aligned them as well.

2023-07-09 07:42 UTC, kambala-decapitator commented on XBMC Remote/dbowen-Demiurgic-JSON-RPC-168ecc9/DSJSONRPC.m
> +    if (![NSJSONSerialization isValidJSONObject:methodCall]) {
exactly

2023-07-09 07:42 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    if ([item isKindOfClass:[NSNumber class]] || [item isKindOfClass:[NSString class]]) {
Yep, that's better.

2023-07-09 09:16 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    id object = item[itemid];
Let's please keep this as is, there are some other places where a similar approach is used. I can rework this later, but have open PRs which otherwise will be a hassle to rebase.

2023-07-09 09:16 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +        object = @([item[itemid] intValue]);
Here as well.

2023-07-09 09:24 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    id object = item[itemid];
sure, no problem

2023-07-09 09:25 UTC, kambala-decapitator approved these changes

2023-07-09 10:34 UTC, wutschel commented
Squashed and rebased to master.

2023-07-09 10:36 UTC, merged