Maintenance: Refactoring in multiple areas
xbmc/Official-Kodi-Remote-iOS pull request #907
Opened 2023-06-04 14:47 UTC by wutschel

## Description

This PR collects multiple rework and refactoring, mainly focused to:
- Avoid code duplication
- Reduce magic numbers
- Remove obsolete definitions
- Remove not needed attempt to load from URL (in case any way falling back to pre-defined default thumbs)
- Correction of progress pie layout calculation (not visible as magic number resolved this before)

## Summary for release notes

Maintenance: Refactoring in multiple areas

2023-06-04 14:48 UTC, wutschel commented
https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/878 needs to get merged first.

2024-01-04 09:27 UTC, kambala-decapitator requested changes
you might also want to create NSString extension with `isEmpty` read-only property

2024-01-04 09:27 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                                     if (thumbnailPath.length) {
better keep the original order of conditional bodies

2024-01-04 09:27 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +                frame.size.width = frame.size.width - INDICATOR_SIZE - LABEL_PADDING;
but now that's 24

2024-01-04 09:27 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +    [self setSortButtonImage:sortAscDesc];
why did you move this statement lower?

2024-01-04 09:27 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            UIImageView *hasTimer = [[UIImageView alloc] initWithFrame:CGRectMake(progressView.frame.origin.x + pieSize / 2 - dotSize / 2, progressView.frame.origin.y + [progressView getPieRadius] +
```suggestion
            __auto_type hasTimerOrigin = progressView.frame.origin;
            hasTimerOrigin.x += pieSize / 2 - dotSize / 2;
            hasTimerOrigin.y += [progressView getPieRadius] + [progressView getLineWidth] - dotSize / 2;
            UIImageView *hasTimer = [[UIImageView alloc] initWithFrame:(CGRect){hasTimerOrigin, CGSizeMake(dotSize, dotSize)}];
```

2024-01-04 09:27 UTC, kambala-decapitator commented on XBMC Remote/HostViewController.m
> +    NSArray *allEntryMaskLabels = @[
seems you wanted to initialize the new ivar, but accidentally created a shadowing local variable

I suggest to create a function that returns the list of labels, no need to store it as ivar

2024-01-04 09:27 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +    for (int i = 0; i < numItems; i++) {
better use `[languageArray enumerate...]`

2024-01-04 09:27 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +            NSString *currentItemLanguage = itemDict[@"language"] != [NSNull null] ? itemDict[@"language"] : nil;
don't we already have a helper that returns nil when NSNull is encountered? IIRC this pattern is widely used in our project.

2024-01-04 09:27 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +            NSString *title = [NSString stringWithFormat:@"%@%@%@%@ (%d/%ld)", tickMark, language, name.length ? @" - " : @"", name, i + 1, (long)numItems];
after changing the loop, use `%lu` here

2024-01-04 09:27 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +    NSMutableArray *actionSheetTitles = [NSMutableArray array];
```suggestion
    NSMutableArray *actionSheetTitles = [NSMutableArray arrayWithCapacity:languageArray.count];
```

2024-01-04 09:27 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        NSString *language = @"?";
not clear why you need it here with such initial value. If I read the logic below right, you want LOCALIZED_STR(@"Unknown") as fallback

2024-01-04 14:33 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +                frame.size.width = frame.size.width - INDICATOR_SIZE - LABEL_PADDING;
yes, 22 was not correct.

2024-01-05 06:31 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +                                     if (thumbnailPath.length) {
Done

2024-01-05 06:35 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +    [self setSortButtonImage:sortAscDesc];
Just wanted to keep all processing related to `self.sectionArray `and `self.sectionArrayOpen` in a single block which is not disturbed by calling `setSortButtonImage`. No functional impact.

2024-01-05 06:45 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            UIImageView *hasTimer = [[UIImageView alloc] initWithFrame:CGRectMake(progressView.frame.origin.x + pieSize / 2 - dotSize / 2, progressView.frame.origin.y + [progressView getPieRadius] +
I like your proposal. Did the same for `isRecordingImageView` a few lines below.

2024-01-05 06:55 UTC, wutschel commented on XBMC Remote/HostViewController.m
> +    NSArray *allEntryMaskLabels = @[
Ouch, thanks & done.

2024-01-05 07:15 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +            NSString *currentItemLanguage = itemDict[@"language"] != [NSNull null] ? itemDict[@"language"] : nil;
You refer to `getStringFromItem`, right? 

Btw, just searched for checks against `[NSNull null]`. There are some more places where I can use the same method right away. I can add separate commit covering them all, instead of adding a fixup only for this occurrence. You're ok with this?

2024-01-05 07:35 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        NSString *language = @"?";
Hmm, the old code displayed `"?"` in case there was `[NSNull null]` given as language via `languageArray`. The rework keeps this. Let me rethink this, I see where you're coming from.

2024-01-05 07:36 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    NSMutableArray *actionSheetTitles = [NSMutableArray array];
Done (using `numItems`).

2024-01-05 07:36 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +            NSString *title = [NSString stringWithFormat:@"%@%@%@%@ (%d/%ld)", tickMark, language, name.length ? @" - " : @"", name, i + 1, (long)numItems];
Done

2024-01-05 07:37 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +    for (int i = 0; i < numItems; i++) {
Done

2024-01-05 11:42 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +            NSString *currentItemLanguage = itemDict[@"language"] != [NSNull null] ? itemDict[@"language"] : nil;
> You refer to `getStringFromItem`, right?
> 
> Btw, just searched for checks against `[NSNull null]`. There are some more places where I can use the same method right away. I can add separate commit covering them all, instead of adding a fixup only for this occurrence. You're ok with this?

yep, sounds good

2024-01-05 11:48 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            isRecordingImageOrigin.x += pieSize / 2 - dotSize / 2;
you could copy `hasTimerOrigin` and avoid setting the X coordinate (but then Y must reference `progressView.frame.origin.y`. Up to your liking.

2024-01-05 11:48 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            UIImageView *isRecordingImageView = [[UIImageView alloc] initWithFrame:(CGRect){isRecordingImageOrigin, CGSizeMake(dotSize, dotSize)}];
the size can be extracted to a variable as it's used twice

2024-01-05 11:48 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        NSString *language = @"?";
> Hmm, the old code displayed `"?"` in case there was `[NSNull null]` given as language via `languageArray`. The rework keeps this. Let me rethink this, I see where you're coming from.

such logic sounds kinda strange. What's the real difference for end user between `?` and `Unknown`?

2024-01-05 13:38 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +        NSString *language = @"?";
I can only imagine this was done for easier debugging based on user feedback. Not really sure. I will change this in a way that in this case also `Unknown` is shown -- fixup comes soon.

2024-01-05 13:50 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            UIImageView *isRecordingImageView = [[UIImageView alloc] initWithFrame:(CGRect){isRecordingImageOrigin, CGSizeMake(dotSize, dotSize)}];
Each case has different `dotSize`, `pieSize` and `progressView.frame.origin`.

What could be done is moving the whole block into a helper function (named something `createTimerRecordingImageView`), make `dotSize`, `pieSize` and `progressView` parameters and return the `UIImageView` as a result. But this will not improve the code readability from my point of view.

2024-01-05 13:50 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            isRecordingImageOrigin.x += pieSize / 2 - dotSize / 2;
See below.

2024-01-05 18:16 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +            NSString *currentItemLanguage = itemDict[@"language"] != [NSNull null] ? itemDict[@"language"] : nil;
Done

2024-01-06 06:57 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            UIImageView *isRecordingImageView = [[UIImageView alloc] initWithFrame:(CGRect){isRecordingImageOrigin, CGSizeMake(dotSize, dotSize)}];
> Each case has different `dotSize`, `pieSize` and `progressView.frame.origin`.

I mean the `CGSizeMake(dotSize, dotSize)}` part - it's repeated. Or actually the second case should use pieSize?

2024-01-06 06:58 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +            NSString *language = LOCALIZED_STR(@"Unknown");;
```suggestion
            NSString *language = LOCALIZED_STR(@"Unknown");
```

2024-01-06 06:59 UTC, kambala-decapitator commented on XBMC Remote/RemoteController.m
> +        if ([itemDict isKindOfClass:[NSDictionary class]]) {
please use early return

2024-01-06 07:58 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            UIImageView *isRecordingImageView = [[UIImageView alloc] initWithFrame:(CGRect){isRecordingImageOrigin, CGSizeMake(dotSize, dotSize)}];
No, this is correct. The first uses `dotSize = 12`, the second `dotSize = 6`.

2024-01-06 08:03 UTC, wutschel commented on XBMC Remote/RemoteController.m
> +            NSString *language = LOCALIZED_STR(@"Unknown");;
Done

2024-01-06 11:29 UTC, kambala-decapitator approved these changes

2024-01-06 12:01 UTC, wutschel commented
Squashed and rebased to master.

2024-01-06 12:11 UTC, merged