Improve setting the service discovery preference
xbmc/Official-Kodi-Remote-iOS pull request #928
Opened 2023-08-06 11:16 UTC by wutschel

## Description

With https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/923 the support to set a preference for the service discovery was added. As changing the preference was a but awkward (users needed to enter the app settings and then go back to the service discovery screen), this PR adds a UISegmentControl which allows to set the preference for the next 'Find Kodi' button press. This should improve the usability.

Screenshots: https://abload.de/img/bildschirmfoto2023-087sim7.png

## Summary for release notes

Improvement: Set the service discovery preference directly above 'Find Kodi'

2023-09-03 19:00 UTC, kambala-decapitator requested changes

2023-09-03 19:41 UTC, wutschel commented on XBMC Remote/HostViewController.m
> +        NSString *mode = index < segmentModes.count ? segmentModes[index] : @"ipv4";
Good suggestion. Done.

2023-09-04 08:24 UTC, kambala-decapitator approved these changes

2023-09-04 08:45 UTC, wutschel commented
Squashed and rebased to master. Now we need to wait until Weblate is fixed.

2023-10-21 08:14 UTC, merged