Rework configuration of SDWebImage
xbmc/Official-Kodi-Remote-iOS pull request #949
Opened 2023-11-10 16:58 UTC by wutschel

## Description

1. Limit in-memory cache size (1/4 of physical memory, but 256 MB max)
2. Only call `clearMemory` (= cleaning in-memory cache) in `applicationDidReceiveMemoryWarning`
3. Use `sd_setImageWithURL` instead of `queryDiskCacheForKey` which aligns this with all other places where images are loaded.
4. Set authorization for SWWebImage on connection success only.

## Summary for release notes

Rework configuration of SDWebImage

2023-11-10 20:22 UTC, wutschel commented
Local test of authorization changes look good, therefore marked it ready-for-review.

2023-12-10 11:35 UTC, kambala-decapitator commented
I guess you don't want to add this to 1.13.1?

2023-12-10 11:37 UTC, wutschel commented
> I guess you don't want to add this to 1.13.1?

Not required, we should not risk the release. ;)

2024-01-03 17:41 UTC, kambala-decapitator requested changes

2024-01-03 17:41 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +        NSInteger maxCost = MIN(memorySize / 4, 512 * 1024 * 1024) / 4;
not sure why you're also dividing by 4 in the end

2024-01-03 17:41 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                                         __weak NowPlaying *sf = self;
```suggestion
                                         __typeof__(self) __weak sf = self;
```
also usually such var is called `welf `or `weakSelf`

2024-01-03 17:41 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +    __block UIColor *newColor = nil;
why do you need this var outside of the completion block?

2024-01-03 17:41 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +                        if (image != nil) {
you should "strongify" the weak self var first and do nothing if it turns out to be `nil`

2024-01-03 17:41 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +                              [Utilities alphaView:sf.kenView AnimDuration:1.5 Alpha:0.2];
```suggestion
                              [strongSelf elabKenBurns:image];
                              [Utilities alphaView:strongSelf.kenView AnimDuration:1.5 Alpha:0.2];
```

2024-01-03 17:41 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    if ([note.name isEqualToString:@"XBMCServerConnectionSuccess"]) {
not sure what this check is for

2024-01-03 18:53 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +        NSInteger maxCost = MIN(memorySize / 4, 512 * 1024 * 1024) / 4;
`maxCost` does not refer to bytes but to pixels. As we use 32 bit pngs we need to divide by 4 (32 bit per pixel).

2024-01-03 19:04 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    if ([note.name isEqualToString:@"XBMCServerConnectionSuccess"]) {
`note.name` can be either `"XBMCServerConnectionSuccess"` or `"XBMCServerConnectionFailure"`. Credentials shall only be set on connection success. The old implementation just always did brute-force set the credentials, if available.

2024-01-03 19:22 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> +    __block UIColor *newColor = nil;
Nice one. This got missed during another rework (https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/c2b1bff8e14e19fe444e5c9e331efd5bff16bdff) in April 2021. Will change this.

2024-01-03 19:27 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +                                         __weak NowPlaying *sf = self;
Oh, I never touched this code, it is 11 years old. I just changed the indentation as a condition check was removed. Is it ok to just rename the var to `weakSelf`, or is the `__typeof__(self)` required as well?

2024-01-03 19:37 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> +                        if (image != nil) {
Sorry, I am not clear what you mean. Can you propose the code changes you have in mind?

2024-01-04 08:40 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +        NSInteger maxCost = MIN(memorySize / 4, 512 * 1024 * 1024) / 4;
please add respective comment and/or respective variable then

2024-01-04 08:41 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                                         __weak NowPlaying *sf = self;
> Oh, I never touched this code, it is 11 years old. I just changed the indentation as a condition check was removed. Is it ok to just rename the var to `weakSelf`, or is the `__typeof__(self)` required as well?

let's do the latter in a separate PR

2024-01-04 08:44 UTC, kambala-decapitator commented on XBMC Remote/ShowInfoViewController.m
> +                        if (image != nil) {
```suggestion
                        __auto_type strongSelf = sf;
                        if (!strongSelf) {
                            return;
                        }
                        // now use only strongSelf

                        if (image != nil) {
```

2024-01-04 08:47 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    if ([note.name isEqualToString:@"XBMCServerConnectionSuccess"]) {
normally such check should be done by the caller. But since you have this call in 2 places, let's keep as is.

2024-01-04 14:32 UTC, wutschel commented on XBMC Remote/ShowInfoViewController.m
> +                        if (image != nil) {
Thanks, done.

2024-01-04 14:42 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +        NSInteger maxCost = MIN(memorySize / 4, 512 * 1024 * 1024) / 4;
Btw, you think 512 MB is too excessive? My motivation behind this is that during testing this with simulator I could get into > 1 GB when loading `ShowInfoViewController` for many albums, movies and TV Shows. This is an effect of high resolution images kept in memory. Some users might have even set the max resolution to higher values, resulting in even more memory being consumed.

2024-01-05 11:37 UTC, kambala-decapitator commented on XBMC Remote/AppDelegate.m
> +        NSInteger maxCost = MIN(memorySize / 4, 512 * 1024 * 1024) / 4;
512 being 25% is fine I'd say

but if you have lots of high-res images, it's better to scale them to appropriate resolution after downloading to show in small cells

2024-01-05 11:39 UTC, kambala-decapitator approved these changes

2024-01-05 13:29 UTC, wutschel commented on XBMC Remote/AppDelegate.m
> +        NSInteger maxCost = MIN(memorySize / 4, 512 * 1024 * 1024) / 4;
> 512 being 25% is fine I'd say

Let's keep then.

> but if you have lots of high-res images, it's better to scale them to appropriate resolution after downloading to show in small cells

For most of the images this is done. They are scaled to the native resolution. Few images like the NowPlaying covers, the  ShowInfo covers are the fullscreen fanart images are not scaled. Usually these are provided in lower resolution than the native resolution of the iOS would be. But users can configure excess resolutions in Kodi itself, using e.g. 4K for fanart. This is most relevant for the in-memory caching as those image are kept uncompressed, not as png. For the storage png is used as far as I can see from the code. There the file sizes will be anyway smaller.

2024-01-05 13:35 UTC, wutschel commented
Squashed and rebased to master.

2024-01-06 06:53 UTC, merged

2024-01-07 19:41 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +                                         __weak NowPlaying *sf = self;
Just figured that I was not strongifying `waekSelf` inside the block. Shouldn't this be done in this case as well?

2024-01-08 09:39 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +                                         __weak NowPlaying *sf = self;
in this case it's not critical. The main idea of strongifying is to check if the weak object is still alive at the moment of calling the completion handler, as in 99% cases nothing needs to be done if it's nil. Here you have just a single statement that'd be noop in nil case.