Maintenance: Use standard notation when declaring weak self
xbmc/Official-Kodi-Remote-iOS pull request #969
Opened 2024-01-08 18:43 UTC by wutschel

## Description

As suggested in https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/949#discussion_r1440715340 this PR changes the declaration of a weak self to the standard notation:

`__weak __typeof(self) weakSelf = self;`

## Summary for release notes

Maintenance: Use standard notation when declaring weak self

2024-01-08 19:35 UTC, kambala-decapitator requested changes
`__weak __typeof(self)` is a popular but not quite correct way to write `__typeof__(self) __weak`

2024-01-08 20:11 UTC, wutschel commented
> `__weak __typeof(self)` is a popular but not quite correct way to write `__typeof__(self) __weak`

Ok, found many of this popular variant in the Open Source library SDWebImage which the Remote App uses. This also has a single use of `__weak __typeof__ (self)`. Would this be ok as well?

2024-01-08 20:29 UTC, kambala-decapitator commented
Changing it in the SDW is up to you (not necessary as it's a "vendored" dependency)

2024-01-08 20:33 UTC, wutschel commented
> Changing it in the SDW is up to you (not necessary as it's a "vendored" dependency)

I will not touch open source code for this. Sorry for the confusion. What I meant is: There is already the variant `__weak __typeof__ (self)` in use in SDW. Can I use the same in our code? Or do you insist on `__typeof__(self) __weak`? I am just of friend of not doing the same in too many different ways. Makes it easier, if I one searches in the code base.

2024-01-09 03:48 UTC, kambala-decapitator commented
Please use the "right" way that I posted

2024-01-09 06:08 UTC, wutschel commented
> Please use the "right" way that I posted

Done

2024-01-20 08:30 UTC, merged