Maintenance: Add LOCALIZED_STR_ARGS convenience macro
xbmc/Official-Kodi-Remote-iOS pull request #973
Opened 2024-01-21 09:00 UTC by wutschel

## Description

During the review of another PR it was suggest to introduce a new convenience macro `LOCALIZED_STR_ARGS` to handle localized strings with arguments/parameters. I felt this improves the code readability and did this.

While working on this I also reworked the copy-clipboard warning popup to use a common method for the creation of the message text.

## Summary for release notes

Maintenance: Add LOCALIZED_STR_ARGS convenience macro

2024-01-22 08:42 UTC, kambala-decapitator requested changes

2024-01-22 08:42 UTC, kambala-decapitator commented on XBMC Remote/ConvenienceMacros.h
> +#define LOCALIZED_STR_ARGS(string, args...) [NSString stringWithFormat:LOCALIZED_STR(string), args]
unfortunately, it's not as easy as that - it was only a pseudocode :) you'd need this:
```suggestion
#define LOCALIZED_STR_ARGS(string, ...) [NSString stringWithFormat:LOCALIZED_STR(string), __VA_ARGS__]
```

2024-01-22 08:42 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            sectionName = LOCALIZED_STR_ARGS(@"The %@s decade", sectionName);
`%@s` would look weird for translators I believe. This is why omitting comment param from NSLocalizedString is not always a good idea.

2024-01-22 08:42 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    // Convert disctionary to string and remove spaces and newlines
```suggestion
    // Convert dictionary to string and remove spaces and newlines
```

2024-01-22 08:42 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    NSString *message = LOCALIZED_STR_ARGS(@"METHOD\n%@\n\nPARAMETERS\n%@\n", method, parameterString);
does this really need to be localized?

2024-01-22 11:43 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    // Convert disctionary to string and remove spaces and newlines
Done

2024-01-22 11:50 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    NSString *message = LOCALIZED_STR_ARGS(@"METHOD\n%@\n\nPARAMETERS\n%@\n", method, parameterString);
I was asking this myself as it related to code itself, but didn't really bother about it too much. I can remove it. Shall I do this?

2024-01-22 14:47 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            sectionName = LOCALIZED_STR_ARGS(@"The %@s decade", sectionName);
It's important that translators see this comment on weblate.

@gaderade could you tell if weblate supports comments for strings?

2024-01-22 14:47 UTC, kambala-decapitator commented on XBMC Remote/Utilities.m
> +    NSString *message = LOCALIZED_STR_ARGS(@"METHOD\n%@\n\nPARAMETERS\n%@\n", method, parameterString);
Yes, let's do

2024-01-22 17:18 UTC, wutschel commented on XBMC Remote/Utilities.m
> +    NSString *message = LOCALIZED_STR_ARGS(@"METHOD\n%@\n\nPARAMETERS\n%@\n", method, parameterString);
Done. Funnily enough the translation does not even exist anymore since more than 2 years. Seems this was lost when Weblate PRs got introduced.

2024-01-22 17:22 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            sectionName = LOCALIZED_STR_ARGS(@"The %@s decade", sectionName);
Agreed, this would help in many places. I remember the German translation for "First aired on %@" where "%@" was assumed to be a TV station and not a date.

2024-01-23 06:09 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +            sectionName = LOCALIZED_STR_ARGS(@"The %@s decade", sectionName);
@gade01, is there a way to share a translation context via the the language files? I could add a comment after each string pair for the English reference file like:
`"Test" = "Test"; /* Context */`

2024-02-03 10:55 UTC, kambala-decapitator approved these changes

2024-02-03 12:16 UTC, wutschel commented
Squashed and rebased to master.

2024-02-03 12:25 UTC, merged

2024-02-13 17:52 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            sectionName = LOCALIZED_STR_ARGS(@"The %@s decade", sectionName);
@gade01 ping :)

2025-02-10 14:54 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +            sectionName = LOCALIZED_STR_ARGS(@"The %@s decade", sectionName);
@garbear maybe you could help us?