Maintenance: Replace magic numbers for tag/viewWithTag
xbmc/Official-Kodi-Remote-iOS pull request #974
Opened 2024-01-21 10:59 UTC by wutschel

## Description

As discussed earlier in several PR reviews it is desired to not use magic numbers, but at least defines when using `tag` or `viewWithTag`. This PR defines the tags locally per class. Only exception are a few defines which are shared across several classes and moved to `AppDelegate.h`. Most of the numbers are set in the related `xib` and it is important to keep them in sync.

## Summary for release notes

Maintenance: Replace magic numbers for tag/viewWithTag

2024-01-21 11:05 UTC, wutschel commented
I am not sure, if it could make sense to add a reference to the `xib` to the name, e.g. `XIB_NOWPLAYING...` to make clear where the numbers comes from and that they need to be kept in sync.

2024-02-03 10:51 UTC, kambala-decapitator requested changes
> I am not sure, if it could make sense to add a reference to the xib to the name, e.g. XIB_NOWPLAYING... to make clear where the numbers comes from and that they need to be kept in sync.

I agree, it's a very good idea!

2024-02-03 10:51 UTC, kambala-decapitator commented on XBMC Remote/RightMenuViewController.m
> +#define RIGHT_MENU_CELL_ICON 1
please separate tags with empty line

2024-02-03 10:51 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +#define HOST_MGMT_CELL_ICON 1
same

2024-02-03 10:51 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +        ((UIImageView*)[cell viewWithTag:HOST_MGMT_CELL_ICON]).image = [UIImage imageNamed:@"connection_off"];
FYI this can be simplified a bit to avoid extra parentheses (changing is up to you):

```objc
[(UIImageView*)[cell viewWithTag:HOST_MGMT_CELL_ICON] setImage:[UIImage imageNamed:@"connection_off"]];
```

2024-02-03 10:51 UTC, kambala-decapitator commented on XBMC Remote/NowPlaying.m
> +#define PLAYLIST_CELL_MAINTITLE 1
same

2024-02-03 10:51 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
>  		cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:tableCellIdentifier];
please fix indentation on this line

2024-02-03 10:51 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
> +        UILabel *sliderLabel = [[slider superview] viewWithTag:SETTINGS_CELL_SLIDER_LABEL];
reading tag from superview feels like a hack :) but this is out of scope of this PR

2024-02-03 10:51 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
>      if (newValue != storeSliderValue) {
FYI it's an incorrect way to compare floating-point numbers, you should something like

```objc
if (fabs(newValue - storeSliderValue) >= FLOAT_EPS)
```

2024-02-03 10:51 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +#define JSON_DATA_CELL_TITLE 1
same

2024-02-03 10:51 UTC, kambala-decapitator commented on XBMC Remote/HostViewController.m
> +#define PASSWORD_FIELD 12
same

2024-02-03 10:51 UTC, kambala-decapitator commented on XBMC Remote/HostViewController.m
> +    return (newLength > 2 && textField.tag >= FIRST_MAC_ADDRESS_FIELD && textField.tag <= LAST_MAC_ADDRESS_FIELD) ? NO : YES;
you could just return negation of the condition

2024-02-03 10:51 UTC, kambala-decapitator commented on XBMC Remote/SettingsValuesViewController.m
>      float newValue = newStep * [self.detailItem[@"step"] intValue];
can't comment on the proper line (a few lines higher), but you can simplify method declaration: replace
```
- (void)sliderAction:(id)sender {
    OBSlider *slider = (OBSlider*)sender;
```

with

```
- (void)sliderAction:(OBSlider *)slider {
```

2024-02-03 12:31 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +        ((UIImageView*)[cell viewWithTag:HOST_MGMT_CELL_ICON]).image = [UIImage imageNamed:@"connection_off"];
Understood, but I will keep it.

2024-02-03 12:35 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
>  		cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:tableCellIdentifier];
Done, fixed the lines above this one as well.

2024-02-03 12:36 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
> +        UILabel *sliderLabel = [[slider superview] viewWithTag:SETTINGS_CELL_SLIDER_LABEL];
ok

2024-02-03 12:39 UTC, wutschel commented on XBMC Remote/HostViewController.m
> +    return (newLength > 2 && textField.tag >= FIRST_MAC_ADDRESS_FIELD && textField.tag <= LAST_MAC_ADDRESS_FIELD) ? NO : YES;
Why not. I changed it.

2024-02-03 12:42 UTC, wutschel commented on XBMC Remote/SettingsValuesViewController.m
>      float newValue = newStep * [self.detailItem[@"step"] intValue];
Yep, done.

2024-02-03 13:49 UTC, wutschel commented on XBMC Remote/RightMenuViewController.m
> +#define RIGHT_MENU_CELL_ICON 1
Done

2024-02-03 13:49 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +#define HOST_MGMT_CELL_ICON 1
Done

2024-02-03 13:49 UTC, wutschel commented on XBMC Remote/NowPlaying.m
> +#define PLAYLIST_CELL_MAINTITLE 1
Done

2024-02-03 13:49 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +#define JSON_DATA_CELL_TITLE 1
Done

2024-02-03 13:50 UTC, wutschel commented on XBMC Remote/HostViewController.m
> +#define PASSWORD_FIELD 12
Done

2024-02-03 13:51 UTC, wutschel commented
All comment input take into account and pushed fixup commits. If ok, I will rename the define to reflect they are defined from XIB.

2024-02-03 13:51 UTC, kambala-decapitator approved these changes

2024-02-03 14:24 UTC, wutschel commented
Done, squashed and rebased.

2024-02-03 14:32 UTC, merged