Maintenance: Refactor parts of DetailViewController
xbmc/Official-Kodi-Remote-iOS pull request #984
Opened 2024-02-03 19:20 UTC by wutschel

## Description

This PR does a set of maintenance changes:
- Use ivar `selectedIndexPath` instead of misnamed global variable `selected`
- Remove unused method `handleLongPressSortButton`
- Reformat multi-condition check
- Refactor gathering of action sheet's source location inside `handleLongPress`

## Summary for release notes

Maintenance: Refactor parts of DetailViewController

2024-02-09 01:36 UTC, kambala-decapitator requested changes

2024-02-09 01:36 UTC, kambala-decapitator commented on XBMC Remote/DetailViewController.m
> +        UILongPressGestureRecognizer *activeRecognizer = enableCollectionView ? longPressGesture : lpgr;
`lpgr` really needs a better name: absolutely not clear how it's different from `longPressGesture`

2024-02-10 13:13 UTC, wutschel commented on XBMC Remote/DetailViewController.m
> +        UILongPressGestureRecognizer *activeRecognizer = enableCollectionView ? longPressGesture : lpgr;
I cleaned this up by using same long press gesture recognizer for both list and grid (aka collection) view. Also now creating this in code and not via xib.

2024-02-19 08:37 UTC, kambala-decapitator approved these changes

2024-02-19 08:37 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +    if (!longPressGesture) {
not sure how it can be not `nil` here (in viewDidLoad)

please also check if this condition makes sense in DetailViewController.m

2024-02-19 11:28 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +    if (!longPressGesture) {
Changed this for HostManagementVC. For DetailVC the solution is correct as `configureLibraryView` can be called multiple times and we only want to create the instance once.

2024-02-19 11:39 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +    if (!longPressGesture) {
> For DetailVC the solution is correct as `configureLibraryView` can be called multiple times and we only want to create the instance once.

but is the initial call done in viewDidLoad / is the gesture destroyed later? If yes, you could simply create it in viewDidLoad / disable the gesture instead of killing it

2024-02-19 16:44 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +    if (!longPressGesture) {
Right. In this case I would only remove `if (!longPressGesture) {` and always overwrite the old instance with a new one, which would automatically unload it and make any call of `removeGestureRecognizer` obsolete, correct?

2024-02-19 19:12 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +    if (!longPressGesture) {
no, seems that wouldn't be enough, as according to docs UIView holds a strong reference to a recogniser, hence you should explicitly remove it before destroying/recreating

2024-02-19 19:24 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +    if (!longPressGesture) {
Thanks for pointing me to the right direction. I now create the gesture in `viewDidLoad` only once, and the remove/add it as needed.

2024-02-20 06:35 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +    if (!longPressGesture) {
Just thinking over it again. Can I just add the same gesture to two views? Or will this cause problems? This would ease up the whole exercise as I then do not need to remove gestures when switching between list and grid view.

2024-02-20 06:38 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +    if (!longPressGesture) {
> Just thinking over it again. Can I just add the same gesture to two views? Or will this cause problems? This would ease up the whole exercise as I then do not need to remove gestures when switching between list and grid view.

I never tried such approach, please check if it'd work

2024-02-20 20:14 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +    if (!longPressGesture) {
Does **not** work.

I somehow still find this add/remove a bit off. I tend do go back to have two separate recognizers (1x for grid view, 1x for list view), create and set them in `viewDidLoad` and re-add the logic inside `handleLongPress` to figure out which one is currently active.

What are your thoughts?

2024-02-21 07:51 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +    if (!longPressGesture) {
that's fine for me.

a couple of remarks:
- gesture's action can accept parameter that has recogniser type, so you don't even need logic to determine which one is "active" and would just use the passed parameter
- please name the second recogniser "collection" instead of "grid"

2024-02-21 12:32 UTC, wutschel commented on XBMC Remote/HostManagementViewController.m
> +    if (!longPressGesture) {
Changed the name and proposed a change to use a parameter for the gesture action. Let me know, if this is what you had in mind. At least this is quite straight forward now.

2024-02-21 12:49 UTC, kambala-decapitator commented on XBMC Remote/HostManagementViewController.m
> +    if (!longPressGesture) {
yes, you did it absolutely correct. Good job!

2024-02-21 13:51 UTC, wutschel commented
Squashed and rebased to master

2024-02-21 13:53 UTC, merged